### ISSUE TITLE
Supporting Custom Fonts

### ISSUE THREAD

**Issue by rrandallcainc** [Khan/KaTeX#1010]
This may be a silly question, but I'm curious if Latex could support custom fonts.

In other words, let's say I wanted to use "Times new Roman". 

I'm guessing the font won't support all the characters necessary for something as extensive as Latex, but would it be able to support a subset and then fallback on the one's that it may be missing?

If so, what's required to test it out?
If not, why?

I'm a Latex newbie, so please excuse my newbieness.

**Comment by kevinbarabash** [comment]
@rrandallcainc it is possible, but the current workflow doesn't support it.  The mapping.pl assumes that the fonts are set up like standard TeX fonts as opposed to a regular TTF you might find somewhere else.

**Comment by RunasSudo** [comment]
Apologies for necro – this issue comes up when Googling "KaTeX custom fonts".

Since #1263 and #1269, it is now possible to use custom fonts on mainline KaTeX, with a little bit of work. I have a quick writeup/demo at https://yingtongli.me/blog/2022/09/24/katex-custom-fonts.html.
