### ISSUE TITLE
An idea for responsive display style equations

### ISSUE THREAD

**Issue by aterenin** [Khan/KaTeX#1012]
One of the difficulties with designing responsive math is that it is a priori unclear how to resize or break a user's equation if it is too wide to display on mobile devices.

I propose to handle this by allowing use of the TeX hyphenation macro `\-`. It would work as follows.

- A user may use the `\-` command once per line in a display style equation.
- If the equation is too large, everything after `\-`, is moved to the next line and right-aligned.

I'd be curious to hear thoughts. This won't cover every situation, but I think would cover most, and is better than having no responsive support at all. It could be added as a contrib module.

**Comment by edemaine** [comment]
I'd rather do something fully LaTeX compatible.  According to [this](https://tex.stackexchange.com/questions/4240/does-amsmath-provide-any-medium-to-auto-break-equations), there seem to be two main packages for automatic line breaking of equations:
* [breqn](https://ctan.org/pkg/breqn)
* [autobreak](https://www.ctan.org/pkg/autobreak)
The autobreak package sounds similar to your solution, in that you need to add explicit candidate line breaks.  But it does so with `\n`, a bit of a weird choice...  Maybe worth checking out breqn in more detail.

**Comment by aterenin** [comment]
I'm not familiar with either of those packages, but `autobreak` seems like it would work well. Its behavior is very much like the idea above, except that it treats newlines as break candidates, and requires breakable math to be wrapped in `\begin{autobreak}`. This seems like it would be a good addition in my view.

**Comment by edemaine** [comment]
I looked more closely at both and agree with your assessment. `autobreak` seems relatively clean in design (though I'm still a little confused how it interacts with arrays) and hopefully not too hard to implement. I'm a little surprised that there isn't a way to automatically wrap all display math in `\begin{autobreak}`, but this does give more control (especially as relates to arrays).
