### ISSUE TITLE
Better documentation and dev UX for snapshot testing

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#1013]
Talk about snapshot testing in CONTRIBUTING.md:
- how it works
- when to use it
- how to use

Add a `update-snapshots` command to `package.json` so that it's easy to update the snapshots when necessary.

**Comment by ylemkimon** [comment]
A link to `how it works` and `how to use` was added in #1146.

**Comment by edemaine** [comment]
@ylemkimon Lots of `npm` scripts are mentioned in CONTRIBUTING.md, but the screenshot ones aren't.  (Though the steps seem reasonably documented.)  Could you add a few explicit `npm run ...` lines?  (Ideally all `npm` scripts would be mentioned here...)

**Comment by ylemkimon** [comment]
@edemaine They're in the [`dockers/Screenshotter/README.md`](https://github.com/Khan/KaTeX/tree/master/dockers/Screenshotter), but it'll be nice to have a centralized place.
