### ISSUE TITLE
using the katex plugin from a web source?

### ISSUE THREAD

**Issue by pazz** [Khan/KaTeX#1014]
Hi, sorry this is a bit of a novice question and I couldn't find an IRC channel for reveal.js..

How would I use the katex plugin without a local checkout? I mean refering to the script source on the web? In your README you mention to use these lines.

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha2/katex.min.css" integrity="sha384-exe4Ak6B0EoJI0ogGxjJ8rn+RN3ftPnEQrGwX59KTCl5ybGzvHGKjhPKk/KC3abb" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha2/katex.min.js" integrity="sha384-OMvkZ24ANLwviZR2lVq8ujbE/bUO8IR1FdBrKLQBI14Gq5Xp/lksIccGkmKL8m+h" crossorigin="anonymous"></script>
```

I presume that this goes below the head section in the html document, yes?
Do I then need to initialize the plugin somewhere?
Just adding those lines to the head will not result in math content to be rendered..
Thanks for any pointers!

**Comment by edemaine** [comment]
Yes, those go within `<head>`. To then autorender math in your HTML, you'll want to also include the KaTeX autorender script and call it, as described in the autorender documentation. Let us know if you have trouble.

**Comment by pazz** [comment]
exactly what I was missing. Thanks a lot for your quick response!
