### ISSUE TITLE
`\hspace` adds an extra space outside the math in some environments

### ISSUE THREAD

**Issue by konn** [Khan/KaTeX#1026]
Using `\hspace` adds an extra space *outside*, right after the end of math.

Consider the following:

```html
<!doctype html>
<html>
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha2/katex.min.css" integrity="sha384-exe4Ak6B0EoJI0ogGxjJ8rn+RN3ftPnEQrGwX59KTCl5ybGzvHGKjhPKk/KC3abb" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha2/katex.min.js" integrity="sha384-OMvkZ24ANLwviZR2lVq8ujbE/bUO8IR1FdBrKLQBI14Gq5Xp/lksIccGkmKL8m+h" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha2/contrib/auto-render.min.js" integrity="sha384-cXpztMJlr2xFXyDSIfRWYSMVCXZ9HeGXvzyKTYrn03rsMAlOtIQVzjty5ULbaP8L" crossorigin="anonymous"></script>
</head>
<body>
  \(\mathop{\bigvee\hspace{-.75em}\bigvee} \emptyset\) denotes the contradiction.
  <script>
    renderMathInElement(document.body);
  </script>
</dody>
</html>
```

Then, Firefox renders it as expected:

<img width="263" alt="2017-12-19 23 43 11" src="https://user-images.githubusercontent.com/21860/34162267-737ffdb6-e516-11e7-86f3-6e0ba05eba17.png">

But in Safari, an extra space occurs right after the math:

<img width="244" alt="2017-12-19 23 42 13" src="https://user-images.githubusercontent.com/21860/34162282-84c36aea-e516-11e7-9f0d-0b105e5ee6d7.png">

Chrome also renders it similarly to Safari.

I confirmed this in `0.9.0-alpha2` and also in the current master.

**Comment by edemaine** [comment]
This is the same issue as #836. Unfortunately, we haven't been able to find a good fix yet. Let us know if you come up with some ideas...
