### ISSUE TITLE
\ddot\imath is too wide

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#1028]
`\ddot\imath` should render `ï` with the width of an `i`, not the width of the umlaut accent.  I think the fix would be to render the accent with style `width:0px`, but then we need to fix the horizontal offset to be half the width of the accent character.  So I believe this depends on #587 / #632 to add the width of characters (specifically the accent characters) to `fontMetricsData.js`.

**Comment by kevinbarabash** [comment]
Once #1030 gets merged I'll open a PR to add horizontal metrics.
