### ISSUE TITLE
test helpers

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#1031]
As discussed previously with @kevinbarabash, we should move the helper functions in `katex-spec.js` like `toParse`, `toNotParse`, and `toParseLike` into a common module shared by all test modules.

I'd also like to suggest a `toBuildLike` which compares the HTML outputs.  I think we do this in various places by manually calling `getBuilt` twice and comparing.

**Comment by kevinbarabash** [comment]
I really like the `toBuildLike` suggestion.
