### ISSUE TITLE
Use different width space characters for different size spaces in MathML

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#1036]
http://jkorpela.fi/chars/spaces.html contains a list of difference size spaces.  We'll want to figure out which map to `\,`, `\;`, `\:`, etc.

**Comment by edemaine** [comment]
Don't we already support those commands? We have CSS margin-left rules to implement them.

**Comment by kevinbarabash** [comment]
In #887 I add some code to handle `\,` (0.16667em):
```
 if (this.type === "mspace") {
    if (this.attributes.width === "0.16667em") {
        return "\u2006";
    } else {
        // TODO: Use other space characters for different widths.
        // https://github.com/Khan/KaTeX/issues/1036
        return " ";
     }
}
```
