### ISSUE TITLE
Nested Math with Non Default Text results in an Error

### ISSUE THREAD

**Issue by rrandallcainc** [Khan/KaTeX#1038]
Example: `\textsf{Hello $a+b$}` results in an error.

Expected result: `\textsf{Hello $a+b$}` should render the `a+b` with the default Math font.

**Comment by kevinbarabash** [comment]
@rrandallcainc it should use the default math style.  pdflatex renders the following:
<img width="453" alt="screen shot 2017-12-26 at 5 24 15 pm" src="https://user-images.githubusercontent.com/1044413/34366999-ba4cc9f4-ea61-11e7-9a1e-789b57922d59.png">

The error shows up on `master`, but not on the demo page.  The error is:
```
TypeError: undefined is not an object (evaluating 'fontMap[fontFamily].fontName')
```

**Comment by kevinbarabash** [comment]
I swapped out `\textbf` for `\textsf` in the screenshot above.

**Comment by rrandallcainc** [comment]
Okay. I see the issue. I can implement a fix, but I'd be curious if there's a better way. Ideally I'd like to reset all font options when entering math mode. Could you think of a place where that could be implemented?

**Comment by kevinbarabash** [comment]
@rrandallcainc you could probably add a `withMathMode` method to `Options` that resets everything.

**Comment by edemaine** [comment]
Nice find. Be sure to add a test for this too!

**Comment by rrandallcainc** [comment]
Just got back from a trip. I'll take a look at this soon.

**Comment by rrandallcainc** [comment]
@kevinbarabash Starting to look @ this now. Agreed that `withMathMode()` is probably the most elegant way to go.

Trying to think...where's the best entry point for when we enter math mode?

My first thought is around: https://github.com/Khan/KaTeX/blob/master/src/Parser.js#L486. I'm guessing I could leverage `this.settings.options.withMathMode()`. But would that be considered hacky?

**Comment by kevinbarabash** [comment]
@rrandallcainc maybe we could set a prop on the `styling` node that's created which could indicate to the HTML and MathML builders to call reset the fonts using `withMathMode()`.
