### ISSUE TITLE
fracline and sqrt line missing when fontsize change

### ISSUE THREAD

**Issue by nyiuang** [Khan/KaTeX#1039]
![image](https://user-images.githubusercontent.com/11516438/34369180-c80bc480-eaf4-11e7-9aab-5a5f1d3de23c.png)

version: 0.9.0-alpha2
OS: macOS10.12.6
browser: chrome
example: \dfrac{a}{ \sin A}=\dfrac{b}{ \sin B}=\dfrac{c}{ \sin C}

**Comment by kevinbarabash** [comment]
I don't even see the sqrt symbol.  @nyiuang can you link to a page with this and provide more details about what font size is causing the issue?  Please note that #1025 was merged recently and should fix the issue with the disappearing fraction lines.

**Comment by nyiuang** [comment]
sqrt line missing:
20px: 
![image](https://user-images.githubusercontent.com/11516438/34372827-4e2a9dda-eb12-11e7-8ccb-8267d89f1081.png)
21px: 
![image](https://user-images.githubusercontent.com/11516438/34372852-73ee4832-eb12-11e7-86a1-544cffeedb44.png)
22px:
![image](https://user-images.githubusercontent.com/11516438/34372857-82a8ec24-eb12-11e7-9b51-6c8aefeddd25.png)

examples: \because a-b=\sqrt{2}-1

I find that when the formula's top has some other elements, it may appear this problem, but when the formulas in one line, it doesn't.

**Comment by kevinbarabash** [comment]
I'm also running MacOS 10.12.6.  I wasn't able to reproduce the issue with either \dfrac or \sqrt in Chrome on `master`.

**Comment by kevinbarabash** [comment]
@nyiuang can you try again with v0.9.0-beta?

**Comment by kevinbarabash** [comment]
I'm going to close this for now.  @nyiuang please re-open if you experience this with v0.9.0-beta or any future releases.
