### ISSUE TITLE
File Uploads on iOS

### ISSUE THREAD

**Issue by reece8765** [Khan/KaTeX#1042]
File uploads on iOS do not work. When trying to upload files, nothing happens - though I'd raise this for you guys. Details: iOS 11, Web browser is Safari, also tried this on Google Chrome for iOS

**Comment by edemaine** [comment]
KaTeX does not offer implement any kind of upload support; it's just a rendering engine.  Perhaps this would be better posted in another forum, though without further context I'm not sure where to redirect you.  Where are you trying to upload files?

**Comment by reece8765** [comment]
Ah, I may be on the wrong page then, I'll go elsewhere, please ignore this issue
