### ISSUE TITLE
Unicode text characters in math mode

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#1046]
#992 added support for e.g. `é` in both math and text mode, mapping to `\acute{e}` and `\'e` respectively.   This felt natural to me... but I haven't been able to reproduce this behavior (specifically, the math-mode behavior) in LaTeX.  I'm compiling the following with `xelatex`, and only the text line is rendering:

```latex
\documentclass{article}
\usepackage{amsmath}
\usepackage{unicode-math}
\setmathfont{xits-math.otf}
\usepackage{xeCJK}
\begin{document}
é私はバナナです。

$é私はバナナです。$
\end{document}
````

I may be missing some packages though.  If this is really the state of XeLaTeX, should we remove support in KaTeX?  Alternatively, we could try to add support via the mythical `katex.sty`.

Related, I am wondering whether to add support for CJK in math mode, but rendering as text symbols.  This is how `\ae` works in LaTeX (with a warning), but doesn't seem to be how it works with CJK...

**Comment by kevinbarabash** [comment]
https://tex.stackexchange.com/questions/270154/utf-8-characters-in-math-mode describes a way to allow unicode chars in math mode, but it's definitely non-standard.

**Comment by rwbarton** [comment]
> Related, I am wondering whether to add support for CJK in math mode, but rendering as text symbols.

It sounds like this would be useful to some people, even if actual xelatex doesn't support it (I haven't tried).

**Comment by kevinbarabash** [comment]
I tried unicode characters in MathJax and it works there which is probably why so many people request this feature.

**Comment by kevinbarabash** [comment]
I think we could provide this functionality behind a switch.

**Comment by edemaine** [comment]
@kevinbarabash Nice idea. Perhaps `unicodeTextInMathMode`, where `false` means LaTeX compatible and `true` means MathJax compatible? Should the default be `false`? The differences from current master would be:
* When `unicodeTextInMathMode` is `true`, CJK and other similar languages get added support in math mode (as requested in #895).
* When `unicodeTextInMathMode` is `false`, `é` and other accented characters from `unicodeSymbols.js` would stop working in math mode. Note that this is a backwards incompatibility with some 0.9.0 alpha/betas, so we should try to resolve this before 0.9.0 final.

**Comment by kevinbarabash** [comment]
> we should try to resolve this before 0.9.0 final.

We can always go straight to 0.10.0-alpha.

**Comment by edemaine** [comment]
I drafted up a PR: #1117

**Comment by kevinbarabash** [comment]
> True, but it seems nicer if we don't release a non-alpha/beta version with new features which we then remove in the next version (even though it still satisfies semver).

Fair enough.  If we were doing this right we would freeze a version branch and then only accept bug fixes into that branch.  Or rather... keep merging everything on `master` and then we'd cherry-pick commits over to the 0.9.0 branch.  I'd want to review release.sh to make sure it would work from a non-`master` branch.
