### ISSUE TITLE
autorender README.md examples don't work.

### ISSUE THREAD

**Issue by keithpjolley** [Khan/KaTeX#1049]
```
<header>
...
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha2/contrib/auto-render.min.js" integrity="sha384-cXpztMJlr2xFXyDSIfRWYSMVCXZ9HeGXvzyKTYrn03rsMAlOtIQVzjty5ULbaP8L" crossorigin="anonymous">
</script>
</header>
```
gives a `ReferenceError: katex is not defined` error in the console.

In the `index.html` example file, which doesn't use the CDN, it also shows `<script src="/katex.js" type="text/javascript"></script>` which gave the hint of what's missing from README.md:
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha2/katex.min.css" integrity="sha384-exe4Ak6B0EoJI0ogGxjJ8rn+RN3ftPnEQrGwX59KTCl5ybGzvHGKjhPKk/KC3abb" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha2/katex.min.js" integrity="sha384-OMvkZ24ANLwviZR2lVq8ujbE/bUO8IR1FdBrKLQBI14Gq5Xp/lksIccGkmKL8m+h" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha2/contrib/auto-render.min.js" integrity="sha384-cXpztMJlr2xFXyDSIfRWYSMVCXZ9HeGXvzyKTYrn03rsMAlOtIQVzjty5ULbaP8L" crossorigin="anonymous">
</script>
```
I think adding this would make it easier for newbies such as myself to get auto-render working more quickly.
Thanks - Keith

**Comment by edemaine** [comment]
Good point! This does make it difficult to get started using KaTeX; I've definitely wanted a copy/pastable complete example for this purpose before myself. I've created #1050 as a first stab at this. Would you like to take a look and see if that would have helped you?

**Comment by keithpjolley** [comment]
Yes, that would do it. Everything but that little bit was "cut and paste" to get to work.
Thank you!
