### ISSUE TITLE
Error when trying to display formula with `\eqno`

### ISSUE THREAD

**Issue by nickkolok** [Khan/KaTeX#1055]
Greetings from Russia, comrads!

It is impossible to render any formula with `\eqno` command, e.g.
```
$$z'(x)+Q(x)z(x)=\lambda Dz(x), \eqno(3) $$
```
An error occures.
I understand that `\eqno` is a command which is rather useful in whole-LaTeX articles than in HTML, but sometimes I need to render formulas with it in HTML.

More generally, is there a way to define a custom tag?
```
\newcommand{\eqno}{~~~~}
```
(it would be enough for me).
More precisely: is #37 being solved?

**Comment by edemaine** [comment]
I believe `\eqno` is the TeX analog to LaTeX `\tag`, previously requested in #899. I've done some work on it, but it's not ready yet. If you have some feedback on the approaches listed there, I'd appreciate it.

Yes, you can define macros, as described in the README.  For example, you could specify `{"\\eqno": "~~~~"}`.

**Comment by nickkolok** [comment]
It helped, thanks!
