### ISSUE TITLE
`${\rm smth}$` doesn't work, `$\mathrm{smth}$` does

### ISSUE THREAD

**Issue by nickkolok** [Khan/KaTeX#1056]
Error:
```
${\rm psh\,}_{\lambda}(\mathbb C^n)$
```
OK:
```
$\mathrm{ psh\,}_{\lambda}(\mathbb C^n)$
```
Are there plans to support `\rm` ?

**Comment by edemaine** [comment]
Old-style font commands were added in version v0.8.0 (2017-08-11). Perhaps you're using an old version? Your example (without the $s) works fine on the test page on https://khan.github.io/KaTeX/

**Comment by nickkolok** [comment]
@edemaine, thanks, my version is really old (`0.7.1`).
