### ISSUE TITLE
underline rendering dependent on magnification with Chrome

### ISSUE THREAD

**Issue by samuelpmish** [Khan/KaTeX#1058]
Hi, I'm using KaTeX to render equations in a personal blog, and I'm noticing that at different magnifications, some symbols are being omitted. In particular, I was using \underline and \overline in one post, and saw that the base characters being underlined/overlined were rendering properly, but the lines themselves will disappear:

at 90%
<img width="696" alt="90" src="https://user-images.githubusercontent.com/16393433/34739606-ad22fa02-f531-11e7-826d-f50d36b0e1d3.png">

at 100%
<img width="741" alt="100" src="https://user-images.githubusercontent.com/16393433/34739622-b8e2d786-f531-11e7-906f-40510f73614a.png">

at 110%
<img width="833" alt="110" src="https://user-images.githubusercontent.com/16393433/34739621-b8ce2232-f531-11e7-95c9-b658a8f5a273.png">

at 125%
<img width="751" alt="125" src="https://user-images.githubusercontent.com/16393433/34739620-b8b6c588-f531-11e7-94e9-49a6f673adaf.png">

I've observed this behavior with chrome on an Ubuntu machine (without high dpi display) and a Mac (with high dpi display). I don't see the problem with Firefox.
 
Using v0.9.0-alpha2

**Comment by ronkok** [comment]
@samuelpmish, The current KaTeX master contains PR #1025, which upgrades not only frac-lines, but also underlines and overlines. We should have a release out soon that contains the new approach.

**Comment by samuelpmish** [comment]
Very cool, thanks for the info!
