### ISSUE TITLE
switch from browserify to webpack for building distribution files

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#1063]
Reasons:
- we already have a webpack.config.js with settings for the unminified distribution files
- webpack has cool plugins we can use to better optimize our code, e.g. https://webpack.js.org/plugins/module-concatenation-plugin/ to dedupe helper code that babel inserts, as discussed in #872.

**Comment by ylemkimon** [comment]
Is there any specific reason using make(Makefile) for build?

**Comment by kevinbarabash** [comment]
@ylemkimon the project started out using `make`.  We've transitioned some of the commands to `package.json`.  Not everyone has `make` installed on their computer so it would be nice to eventually transition everything to `package.json`.

**Comment by kevinbarabash** [comment]
So I looked at webpack.config.js a little more an it's not actually a valid webpack.config.js.  It specifies multiple configs but not in the way that webpack expects.  See https://github.com/webpack/webpack/tree/master/examples/multi-compiler.

**Comment by ylemkimon** [comment]
I'd like to work on this issue, if you don't mind.
