### ISSUE TITLE
\operatorname doesn't support all math functions

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#1079]
```
\operatorname{x\pi\frac{1}{2}}
``` 
is valid LaTeX, but KaTeX throws the following exception:
```
undefined is not an object (evaluating 'n.replace')
```

**Comment by leungbk** [comment]
With the current version of KaTeX, `\operatorname{x\pi\frac{1}{2}}` throws no errors for me besides the "no character metrics" error.

I noticed that `\operatorname{\sum}` doesn't work right now, though it is valid LaTeX. Setting `acceptUnicodeChar = true` for `\sum` in its `defineSymbol()` invocation at line 654 of `symbols.js`, and enforcing `math` mode (solely to accommodate `\sum` in this test case) in the `htmlBuilder` of `operatorname.js` allows `\operatorname{\sum}` to render. What is the reason for not setting `acceptUnicodeChar = true` by default?

**Comment by ronkok** [comment]
> What is the reason for not setting `acceptUnicodeChar = true` [on `\sum`] by default?

@leungbk, When we were implementing Unicode support, I included the big operators by writing them in the `defineFunction` section of file `ops.js`. I felt that this gave someone reading the code a more direct way to see the connection to operator symbol re-sizing, `\limits`, etc. 

It may be that we could do both that and also set the `acceptUnicodeChar` flag in `symbols.js`.

**Comment by kevinbarabash** [comment]
@ronkok #1461 closes this, right?

**Comment by ronkok** [comment]
Yes, I closes all the use cases that I can think of.
