### ISSUE TITLE
bounding box is wrong for \cancel groups

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#1080]
![strikethrough](https://user-images.githubusercontent.com/1044413/35199882-c294528c-fed2-11e7-85ae-0451a5f93c89.png)

I added
```
\usepackage{cancel}
\usepackage{ulem}
```
to test.tex in order to generate the image above.  The spacing around binary operators is better than it used to be.  It seems like the addition of the `\cancel` bar doesn't affect the bounding box of `\cancel` in the LaTeX rendering (green).  The bounding box of `\cancel` groups is essentially the same as the bounding box of the contents.  This is probably most noticeably in `{\cancel B}_1^2`.

**Comment by ronkok** [comment]
@kevinbarabash The `cancel` package documentation states that:

> By default, none of these commands affects the horizontal spacing, so they might over-
print  neighboring  parts  of  the  formula  (or  text).

I tried to accomplish that with CSS adjacency rules. It looks like I missed some of the possible combinations. I don't know if PR #1070 makes this easier or harder.

**Comment by kevinbarabash** [comment]
> I don't know if PR #1070 makes this easier or harder.

Hopefully easier.  🤞

**Comment by kevinbarabash** [comment]
I'm not sure why pdflatex rendered `\sout` as underlines.

**Comment by edemaine** [comment]
For reference, here's a texdiff on the #1295 branch.  I'm not convinced it's much better... but hopefully easier to fix?

![strikethrough](https://user-images.githubusercontent.com/2218736/39774128-f8f3858e-52c7-11e8-882d-32b472535294.png)

**Comment by kevinbarabash** [comment]
It's looks like there are two things going on:
- LaTeX's `\cancel`s are generally steeper, especially for single lowercase letters
- LaTeX has less spacing around the `\cancel`led element.
