### ISSUE TITLE
Fracline too thick in 0.9.0-beta

### ISSUE THREAD

**Issue by mossadal** [Khan/KaTeX#1084]
The 0.9.0-beta update seems to have solved the disappearing fracline problem in Chrome, but now the line is way too thick:

Firefox:

<img width="123" alt="firefox" src="https://user-images.githubusercontent.com/8174070/35272617-35d1fc86-0036-11e8-9f46-4faa3a6132fc.png">

Safari:

<img width="117" alt="safari" src="https://user-images.githubusercontent.com/8174070/35272649-54a0796c-0036-11e8-9746-1283f430912b.png">

Chrome:

<img width="111" alt="chrome" src="https://user-images.githubusercontent.com/8174070/35272687-6d72e074-0036-11e8-808b-b001b718b7a5.png">

All screenshots on Mac OS X 10.12.6

**Comment by kevinbarabash** [comment]
@mossadal are you using a retina or non-retina display?

**Comment by mossadal** [comment]
This is on a Macbook Pro with retina display.

**Comment by kevinbarabash** [comment]
<img width="765" alt="screen shot 2018-01-23 at 8 22 21 am" src="https://user-images.githubusercontent.com/1044413/35278016-b01b39f0-0016-11e8-95ef-9dfe3fe308ab.png">

This is what I'm seeing on `master` which is only a few commits ahead of `0.9.0-beta`.  The new commits shouldn't have any effect on fraction line output.  Not sure what's going on.  😕

**Comment by kevinbarabash** [comment]
@mossadal what font size are you rendering at?  FTR, that rendering above was on Safari at 16px.  I'm getting similar output from Chrome.  I'm also on 10.12.6.

**Comment by kevinbarabash** [comment]
I'll try reproducing using `0.9.0-beta` later this week.  Maybe something funky happened during while generating the release.

**Comment by mossadal** [comment]
Oh, it looks like something on my side. On a blank page with just the KaTeX js and css loaded, everything looks perfect. Trying to isolate where the conflict is.

**Comment by mossadal** [comment]
Very sorry, this was all my mistake. I accidently loaded the 0.90.alpha2 css in one place instead of the 0.90-beta css. Everything looks great now.
