### ISSUE TITLE
SVG-based functions like \sqrt don't render reliably inside other SVG images.

### ISSUE THREAD

**Issue by davidflanagan** [Khan/KaTeX#1088]
At Khan Academy we sometimes use KaTeX strings inside of SVG images. But now that \sqrt{} and \vec{} are themselves rendered as SVGs we've discovered a problem. Our SVG images set fill-opacity to 0, so when we try to render \sqrt{2} inside of one of these images, the square root sign is fully transparent and does not show up at all.

I've discussed this with @kevinbarabash. We're thinking that we should add some kind of `svg-reset` class name to the toplevel HTML element that we output. And then define this class to reset SVG css properties (like fill-opacity and stroke-width) to their default values.

The idea is that we don't want SVG glyphs to be distinguishable from glyphs actually rendered by a real font, so we shouldn't allow anything in the CSS environment to affect SVG glyphs if it would not also affect font glyphs. So presumably we should inherit the CSS color property, but not the SVG-specific CSS stroke property.

**Comment by davidflanagan** [comment]
It turns out that this is an issue even without the svg-inside-svg. We need to prevent our svg glyphs from inheriting styles that should not affect them:

<img width="958" alt="screen shot 2018-01-24 at 2 24 49 pm" src="https://user-images.githubusercontent.com/516914/35360423-81393aae-0112-11e8-90e3-7833a79d6f4d.png">

**Comment by ronkok** [comment]
I am fully in agreement with your proposed solution for styles.

Since the topic is nested SVGs, I wonder has anyone tried zooming them on Safari? Issue #883 revealed a problem.

**Comment by kevinbarabash** [comment]
Closing as #1089 has be merged.  @ronkok I tried zooming (in and out) on Safari and things seem fine now.
