### ISSUE TITLE
Non-portable use of String method `.includes`

### ISSUE THREAD

**Issue by ccorn** [Khan/KaTeX#1093]
KaTeX v0.9.0-beta chokes on `\mathbb{C}` (and `\mathbb{R}` so it's probably the macro), telling me "undefined not callable".
KaTeX v0.8.3 and v0.9.0-alpha2 render that without problems.
Found using `katex.renderToString` with Duktape.

**Comment by kevinbarabash** [comment]
Hmm... `\mathbb{C}` works in the test page on `master`, but that uses `katex.render`.  I wonder if there's a difference between that and `katex.renderToString`.

**Comment by kevinbarabash** [comment]
I tried `katex.renderToString("\\mathbb{C}")` on `master` and that works as well.

**Comment by kevinbarabash** [comment]
I checked `v0.9.0-beta` as well.  What's Duktape?  Could you post a more complete code example?

**Comment by ccorn** [comment]
Hmm, when I try it with less intervening Ruby layers, it works. Sorry, that's not your bug, even though it manifests at the Javascript execution level. Have to track it down myself.

**Comment by ccorn** [comment]
[Use of the string method `includes`](https://github.com/Khan/KaTeX/search?utf8=%E2%9C%93&q=is%3Afile+fontFamily.includes&type=) seems to be the culprit. Using the polyfill from [Mozilla's documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) makes the error go away.

**Comment by ccorn** [comment]
I'd propose to use `.indexOf(...) !== -1` instead, for compatibility.

**Comment by kevinbarabash** [comment]
Nice find!

**Comment by kevinbarabash** [comment]
We'll definitely want to fix this before the next release.

**Comment by kevinbarabash** [comment]
@ccorn if you have time, would definitely accept a PR to fix this.

**Comment by ccorn** [comment]
I'd like to do that, but I am not a Javascript expert, and I am not familiar with the build system around KaTeX. I can fork the repo, do a minimal `.indexOf` replacement, but then I would not know how to test that change. I could launch a PR and hope that some CI kicks in and that everything turns out well, but if not, then anyone familiar with KaTeX development should better take over. Also, compatibility issues such as this one are bound to happen again, and the preferred strategy might be different from fixing the instances as they are discovered.

**Comment by ccorn** [comment]
Hmm, there is a Makefile. Known territory. OK, I'll ssh into a server that has Node available, and then try and clone and mess around a bit.
