### ISSUE TITLE
lint against modern JavaScript construct we don't want to polyfill

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#1098]
Some polyfills are expensive, but we still want to maintain compatibility on older browsers so we should lint against those things we don't want to polyfilly, e.g. `.includes()` on strings.

Use https://github.com/kevinbarabash/eslint-plugin-luddite.

**Comment by ylemkimon** [comment]
What do you think about enabling `loose` option on babel preset? (Related to #850)

**Comment by kevinbarabash** [comment]
https://github.com/Khan/KaTeX/pull/1469 added a lint rule for this.
