### ISSUE TITLE
Make sandbox page easier to find

### ISSUE THREAD

**Issue by mbourne** [Khan/KaTeX#1109]
Each time I go to use the sandbox on this page: https://khan.github.io/KaTeX/, I can never remember where it is.

As we all do, I do a Google search with 'katex sandbox' (no quotes) and it offers up LaTeX ones, but when choosing "Katex" is still doesn't find it.

Then I do the usual "pecking"  around the various Github pages and go around in circles. Finally I saw the above link at the top of one of the pages, and voila - I finally found it. That process gets repeated every 6 months or so when I forget (again) where it is.

Suggestions:

1. On this page https://github.com/Khan/KaTeX, put under the text "KaTeX is a fast, easy-to-use JavaScript library" in the bullet list a link to https://khan.github.io/KaTeX/ with anchor text along the lines of "Try out KaTeX in the sandbox"

2. On the wiki page, https://github.com/khan/katex/wiki do the same thing

3. On the function support page https://khan.github.io/KaTeX/function-support.html, in the list of Links at the left, do the same thing.

4. On the actual page with the sandbox, use the word (or better, heading) "sandbox" somewhere near the top.

With all that in place, Google will know where the sandbox is, and will help users find it. Also, users will be able to find it easily from within the various KaTeX resources.

**Comment by ronkok** [comment]
@mbourne The next time that I update the [function support page](https://khan.github.io/KaTeX/function-support.html), I'll edit the first item under "Links" and change how it reads from "Home" to "Sandbox".

**Comment by ylemkimon** [comment]
I think the word `demo` is more familiar.

**Comment by ronkok** [comment]
Agreed. I'll use "Demo".

**Comment by ylemkimon** [comment]
The number 3 will be fixed by #1214.
