### ISSUE TITLE
Enforcing Squash Merging

### ISSUE THREAD

**Issue by rrandallcainc** [Khan/KaTeX#1113]
I'm wondering if enforcing squash merging would keep the master branch clean, while not burdening devs to squash themselves. I believe this is possible as part of the Merge Button settings.

![image](https://user-images.githubusercontent.com/16921005/35486545-5246af8c-043d-11e8-8b3b-03c47c7d8463.png)

Squashing is checked, while the other two options would remain unchecked. Thoughts?

**Comment by kevinbarabash** [comment]
I've made this change.  There are a few situations where rebase merging may be preferable, but this should simplify things.  I'm going to leave this open for a bit in case other people have concerns about this change.

**Comment by kevinbarabash** [comment]
Since no-one has commented on this, I'm going to assume it's not an issue.
