### ISSUE TITLE
Support for \mathring

### ISSUE THREAD

**Issue by akalin** [Khan/KaTeX#1124]
\mathring is a math mode accent defined in [amssymb](http://milde.users.sourceforge.net/LUCR/Math/mathpackages/amssymb-symbols.pdf).

It's basically the math mode equivalent of the text mode accent \r. I just needed it for a single letter (`$\mathring g$` for the round metric) so I tried to hack it up with `$\text{\r \textit{g}}$` but it doesn't look great:

<img width="27" alt="screen shot 2018-01-31 at 12 17 27 am" src="https://user-images.githubusercontent.com/425576/35607883-29ce6d20-061c-11e8-9d15-0865b595a2bb.png">

compared to

<img width="26" alt="screen shot 2018-01-31 at 12 19 52 am" src="https://user-images.githubusercontent.com/425576/35607966-934a6e20-061c-11e8-8398-7c9b1d2a9834.png">

I wonder if there's a better way to fake it?

**Comment by kevinbarabash** [comment]
@akalin once we fix #1099 your hack should work.

**Comment by edemaine** [comment]
Wow, thanks for the heads up about `\mathring`! Other than `\H`, it was bugging me that this accent was text-mode-only. I'm adding support for it now, and it renders correctly.

**Comment by edemaine** [comment]
@akalin Your non-hack version should work now, on the master branch.

**Comment by akalin** [comment]
Thank you!
