### ISSUE TITLE
Placement glitch for `cases`  

### ISSUE THREAD

**Issue by TyOverby** [Khan/KaTeX#1137]
`$\sum_{i=0}^{1,000,000,000} \begin{cases} i/2 + 2 & \text{if } i \% 2 = 0 \\\\ 0 & \text{otherwise} \end{cases}$`

produces the following image: 

<img width="313" alt="image" src="https://user-images.githubusercontent.com/573215/35751616-0e66f64e-080e-11e8-9c99-56a655344384.png">

```
OS: OSX 
Browser: Firefox 59.0b3 (64-bit)
KaTeX Version: 0.9.0-beta1
```

**Comment by ronkok** [comment]
@TyOverby What version of KaTeX is rendering that expression?

**Comment by ronkok** [comment]
Also, the "%" in your expression should be "\%".

**Comment by TyOverby** [comment]
@ronkok: I'm using the versions recommended on the readme:

```<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-beta1/katex.min.css" integrity="sha384-VEnyslhHLHiYPca9KFkBB3CMeslnM9CzwjxsEbZTeA21JBm7tdLwKoZmCt3cZTYD" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-beta1/katex.min.js" integrity="sha384-O4hpKqcplNCe+jLuBVEXC10Rn1QEqAmX98lKAIFBEDxZI0a+6Z2w2n8AEtQbR4CD" crossorigin="anonymous"></script>
```

**Comment by TyOverby** [comment]
@ronkok: thanks for the correction, turns out markdown thought that was an escape sequence, so I've quoted it.

**Comment by TyOverby** [comment]
This was my mistake.  I was overriding the fonts that KaTeX uses.
