### ISSUE TITLE
Include built files in the repository

### ISSUE THREAD

**Issue by jmeas** [Khan/KaTeX#114]
This will allow folks to take advantage of all of the perks that package managers provide.

If you're strictly using KaTeX on the server, then you won't run into this issue as you won't really need the built files. But when working on the client it's convenient to not have to worry about building the project, as you can just reference the built files directly.

For small projects [the manual installation process](https://github.com/Khan/KaTeX#usage) works fine, but the benefits of just being able to run `npm update` or [`bower update`](https://github.com/Khan/KaTeX/pull/112#discussion_r17942712) to get the latest versions for things (with the dependency tree sorted) quickly becomes relevant as a project's dependencies grow, especially as the project ages and its dependencies become out-of-date.

It might seem odd to include the built files, but a large number of popular libraries do it. Some examples are [Backbone](https://github.com/jashkenas/backbone/blob/master/backbone-min.js), [Marionette](https://github.com/marionettejs/backbone.marionette/blob/master/lib/backbone.marionette.min.js),  [Angular's proxy repository](https://github.com/angular/bower-angular), Ember's (unofficial?) [proxy library](https://github.com/components/ember), and [Bootstrap](https://github.com/twbs/bootstrap/tree/master/dist).

**Comment by tylerlong** [comment]
I have create a repository for the built files: https://github.com/tylerlong/katex-build

You can simply `bower install katex-build` and start using it!

Cheers!

**Comment by shime** [comment]
:+1:

**Comment by justinfagnani** [comment]
Any word here on including built files and a bower manifest? The first thing I went looking for when I found KaTeX was the bower dependency to use :)

**Comment by spicyj** [comment]
Let's do what jQuery does and tag releases with the dist files checked in but have those commits not be on master:

https://github.com/jquery/jquery/commit/4dec426aa2a6cbabb1b064319ba7c272d594a688

**Comment by samccone** [comment]
:+1: seems like a good plan to me @spicyj thanks for the resolution

**Comment by xymostech** [comment]
Woah, weird! That sounds fine to me. We can do this next release (which will hopefully be soon).

**Comment by samccone** [comment]
might be nice to backdate the releases with tags, if you need some help doing that more than willing

**Comment by spicyj** [comment]
We've already tagged the existing released; I'd rather not change those tags. We can do it going forward though.

**Comment by samccone** [comment]
yeah, i understand that, perhaps something like...	

`v0.1.1-build`

would be a nice middle ground, take for instance this usecase.

I have multiple apps that are on an older version of katex, I would love to drop the build step and just use the prebuilt version. If we add new tags for old releases I get that for free :smile: .

Otherwise I need to upgrade to the latest (across breaking releases)  (which sometimes is not an option for some apps due to the cost of an upgrade)

thoughts? 

Thanks for having this dialog with me, I appreciate your time.

**Comment by spicyj** [comment]
Yeah, the unfortunate thing is that bower versions have to match the tag names, so the bower version would be unclean in that case. Our breaking changes (just one, I think?) have been fairly minor and so hopefully it's not too much work to upgrade. (And it sounds like you've already got a working build setup so I'm not as concerned…)

**Comment by jakiestfu** [comment]
What is the status of this issue?

**Comment by spicyj** [comment]
Still waiting for the next release, when we'll commit the built files and publish a bower package.

**Comment by jakiestfu** [comment]
Thanks spiceh!

**Comment by tirsen** [comment]
It would be awesome if the NPM package could also include the CSS and font files. With webpack I can use NPM for almost everything except a few handful of packages, katex included.

**Comment by spicyj** [comment]
Definitely. I thought they were already but I guess not:

```
$ curl -s https://registry.npmjs.org/katex/-/katex-0.5.1.tgz | tar tvf -
-rw-r--r--  0 1000   10        756 Sep  1 19:44 package/package.json
-rw-r--r--  0 1000   10       3479 Sep  1 19:39 package/README.md
-rwxr-xr-x  0 1000   10        899 Jul 17  2015 package/cli.js
-rw-r--r--  0 1000   10       2196 Jul 17  2015 package/katex.js
-rw-r--r--  0 1000   10       1289 Jul 17  2015 package/LICENSE.txt
-rw-r--r--  0 1000   10       5653 Jul 17  2015 package/src/Lexer.js
-rw-r--r--  0 1000   10      51489 Sep  1 16:38 package/src/buildHTML.js
-rw-r--r--  0 1000   10      14888 Sep  1 16:38 package/src/buildMathML.js
-rw-r--r--  0 1000   10       1088 Sep  1 16:38 package/src/buildTree.js
-rw-r--r--  0 1000   10      14287 Sep  1 16:38 package/src/buildCommon.js
-rw-r--r--  0 1000   10       7223 Mar 12  2015 package/src/domTree.js
-rw-r--r--  0 1000   10       6318 Sep  1 16:38 package/src/environments.js
-rw-r--r--  0 1000   10       3930 Sep  1 16:38 package/src/fontMetrics.js
-rw-r--r--  0 1000   10     128060 Sep  1 16:38 package/src/fontMetricsData.js
-rw-r--r--  0 1000   10      19862 Sep  1 16:38 package/src/functions.js
-rw-r--r--  0 1000   10       3195 Feb 18  2015 package/src/Style.js
-rw-r--r--  0 1000   10       2693 Mar 12  2015 package/src/mathMLTree.js
-rw-r--r--  0 1000   10        783 Sep  1 19:39 package/src/Settings.js
-rw-r--r--  0 1000   10        444 Jul 17  2015 package/src/parseData.js
-rw-r--r--  0 1000   10      24524 Sep  1 19:39 package/src/Parser.js
-rw-r--r--  0 1000   10        377 Mar 10  2015 package/src/parseTree.js
-rw-r--r--  0 1000   10       1322 Feb  6  2015 package/src/ParseError.js
-rw-r--r--  0 1000   10      60176 Sep  1 16:38 package/src/symbols.js
-rw-r--r--  0 1000   10       4904 Sep  1 16:38 package/src/Options.js
-rw-r--r--  0 1000   10       2306 Jul 17  2015 package/src/utils.js
-rw-r--r--  0 1000   10      18861 Sep  1 16:38 package/src/delimiter.js
```

**Comment by spicyj** [comment]
Want to send a PR?

**Comment by gagern** [comment]
While the npm issues should be resolved by now, bower still has problems, as evidenced by #613. 

@xymostech wrote:
> We can do this [tagging with built files] next release (which will hopefully be soon).

Apparently this didn't happen for 0.7.0, although 0.6.0 got such a commit in b94fc6534d5c23f944906a52a592bee4e0090665. If this is really what we want, we could prepare a 0.7.1 to include this, and also have a commit on master in the release script to ensure we won't forget this next time around.

One problem I see with this approach is that I'd have intended for e.g. release 0.8.0 to have its breaking changes rolled back and the rest released as 0.7.x, and then 0.8.1 could simply be merged into the 0.7 branch to produce 0.7.(x+1). That kind of merging becomes a bit more difficult if we get conflicts in the built artifacts, so we might have to write the git identifiers as `0.8.1^` and similar, i.e. omit the very last commit before each tag. No show stopper, but worth remembering.

@kevinbarabash wrote:
> We might also want to consider having a separate repo for the built files. The Polymer project does this.

Not sure whether that's still an alternative to consider, but with CindyJS we do something like this: we have [one repository for the source code](https://github.com/CindyJS/CindyJS), and [another for the built artifacts](https://github.com/CindyJS/deploy). We use Travis to build artifacts [on release](https://github.com/CindyJS/CindyJS/blob/v0.8.3/.travis.yml#L19-L26), and those [get deployed](https://github.com/CindyJS/CindyJS/blob/v0.8.3/tools/travis-deploy.sh#L31-L57) to the second repository automatically, using a repo [deploy key](https://developer.github.com/guides/managing-deploy-keys/) with write permission that is stored as an [encrypted file](https://docs.travis-ci.com/user/encrypting-files). If any of this is of interest here, the approach we use could probably be adapted to KaTeX. We have no experience with CindyJS and Bower so far, though.

**Comment by gagern** [comment]
Seems I am to blame: The release script [used to add `dist`](https://github.com/Khan/KaTeX/blob/v0.7.0/release.sh#L36), but in 0ebbc256729e77ec40dbc7bf80eae1f0c7d02b07 for #546 I added that directory to `.gitignore` to keep the noise down. Perhaps we should remove that line from `.gitignore` before adding the content of the directory, or use `git add -f dist/* dist/*/*` or something like that.

**Comment by edemaine** [comment]
Why not use `.npmignore` different from `.gitignore`?  [NPM will use .npmignore instead of .gitignore if one is available.](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package)

**Comment by xymostech** [comment]
@edemaine That sounds like a good solution. Once someone fixes it, I can make a new release.

**Comment by gagern** [comment]
npm has nothing to do here. In fact in #546 I was careful to ensure that npm packaging worked all right. Didn't think of bower then, though.

**Comment by edemaine** [comment]
Oops, I see.  Bower pulls directly from Git...

**Comment by gagern** [comment]
Created #615 for automatically unignoring those files, among other things.
