### ISSUE TITLE
Expressions in Fractions Don't Contain Appropriate Spacing Data

### ISSUE THREAD

**Issue by rrandallcainc** [Khan/KaTeX#1147]
While working on: https://github.com/Khan/KaTeX/pull/251 I noticed that the domTree does not contain appropriate spacing data for expressions in fractions.

Example behaving correctly (non-nested expression): `a+b` will create a dom tree with following structure
<img width="609" alt="screen shot 2018-02-06 at 10 41 00 pm" src="https://user-images.githubusercontent.com/16921005/35897497-731a9bf2-0b8f-11e8-8225-669d72d46cb7.png">

Note that indexes 1/3 will contain data like "marginRight" which is then used to apply the appropriate margins when building the dom, or in my case, a canvas app.

Behaving incorrectly (nested expression): `\frac{a+b}{c}` which will create a dom tree with the following structure
<img width="552" alt="screen shot 2018-02-06 at 10 41 18 pm" src="https://user-images.githubusercontent.com/16921005/35897551-baf79862-0b8f-11e8-96d0-6fe54b576e81.png">

Note that the indexes found above, are now missing for this structure, which means marginRight is not available.

It appears that `marginRight` is applied during the building of the HTML for this scenario. If so, this would serve as a blocker an application attempting to use the `domTree` as an IR.

**Comment by kevinbarabash** [comment]
@rrandallcainc is the base style `\textstyle` or `\displaystyle`?

**Comment by rrandallcainc** [comment]
@kevinbarabash Doh! Didn't realize that KaTeX leverages the `displayMode: true` option in the demo page. I think this actually fixes another issue of mine as well... Going to double check, and then I'll close.

**Comment by rrandallcainc** [comment]
Confirmed this was indeed this issue. Thanks Kevin.

**Comment by kevinbarabash** [comment]
@rrandallcainc there's an open issue to add a toggle for `displayMode` to the test page, see #1035.
