### ISSUE TITLE
Supporting Arbitrary Font in Text Mode

### ISSUE THREAD

**Issue by rrandallcainc** [Khan/KaTeX#1148]
Is it possible to support an arbitrary font in text mode? I know Math mode is much more limited, but trying to see what's available for text.

Something along the lines of: https://tex.stackexchange.com/questions/67768/times-new-roman-font/67769

I don't think this is supported out of the box, but how would one approach this, if at all?

**Comment by ylemkimon** [comment]
I think we can provide font metrics data in similar manner to #1074.

https://github.com/Khan/KaTeX/pull/1074#issuecomment-362783568 by @kevinbarabash 
> I wonder if you had any thoughts about how we might allow plugins/extensions to add fonts and font metrics. I looking into generating Cyrillic fonts. If we add support for more scripts with fonts and metrics it would be nice to allow people to load only those which they think they might need.

**Comment by kevinbarabash** [comment]
There's a [Font Metrics API](https://github.com/w3c/css-houdini-drafts/tree/master/font-metrics-api) in the works, but it's quite a ways off.  That would definitely make this easier.
