### ISSUE TITLE
Thank you Khan development team

### ISSUE THREAD

**Issue by jaltekruse** [Khan/KaTeX#1150]
Hello Khan development team,

This isn't reporting an issue, I just wanted to take a moment to thank you for releasing all of your great open source projects for the benefit of the edtech community. Thanks to a number of your fantastic projects like Katex, KAS and Perseus, I was finally able to complete a passion project I had been wanting to build for a long time. It is an offline react application that allows recording step by step work and for teachers to review a class full of work, grouped by similar final answer.

If you would like to see the project, it is available here. The source for the site is released under the GPL and available on github.

http://freemathapp.org

From my own experience using Khan Academy, I've always found the scratchpad feature interesting, but hard to use without a graphics tablet. Would you have any interest in incorporating a multi-step equation editor like the one in the app to allow students to record digital work? It would also be possible to capture this and show it back to coaches so they could see how students are getting to incorrect answers.

**Comment by kevinbarabash** [comment]
@jaltekruse I too find the scratchpad hard to use with a mouse or a trackpad.  I had a look at the video on freemathapp.org.  I like the copy and modify workflow.  I'll pass this along to one of product managers.

**Comment by jaltekruse** [comment]
Hey @kevinbarabash,

I've had a few other project interested in incorporating this editor into their sites, so I'm planning on factoring it out of the larger Free Math project and putting it under a permissive license like Apache or MIT.

Did you ever hear anything back from your product team? I would be happy to make a contribution to Perseus to integrate it with your question viewer of there is interest.

**Comment by kevinbarabash** [comment]
@jaltekruse I shared it with the team.  Unfortunately our team is rather small given our ambitious mission and there are other higher priority things at the moment.  Unfortunately, we've moved Perseus into our closed source monorepo.

**Comment by jaltekruse** [comment]
Hey @kevinbarabash,

I understand, I know how hard managing open source projects can be.

I don't know if would consider letting me volunteer, but if you are making improvements to the Perseus components they likely would be useful to incorporate into Free Math.

I would be happy to do some of the more tedious work of occasionally publishing snapshots of Perseus and your other previously open source repos, even if you wouldn't have the resources to review external contributions and the code would just flow one direction.

**Comment by kevinbarabash** [comment]
It's not as simple as snapshotting Perseus, b/c now parts of Perseus are using files from other parts of the monorepo.

**Comment by jaltekruse** [comment]
@kevinbarabash,

I did assume that this was part of the motivation of having everything in a mono repo. I understand that it is likely a substantial amount of work, but it could still be beneficial to my project to have access to your continued improvements on these components.

I do have prior experience managing open source and closed source versions of a codebase. I was previously at Dremio, a company working on a big data processing system, including a complex web application component for configuring and managing data analysis. They release a community version that is Apache licensed and also sell a closed source enterprise edition. Splitting the two required refactoring in some cases, which took an non-trivial amount of time. As providing source code doesn't really impact your users decisions to use Khan, I understand this work doesn't directly serve your organizations core mission.

I would be willing to volunteer time to make this possible, but I understand it might involve making changes in the mono-repo to support this effort, which would require effort from your team to review. If you would consider mentioning the offer to your team for consideration I would appreciate it.

Thanks,
Jason
