### ISSUE TITLE
\boldsymbol removes spacing in expressions

### ISSUE THREAD

**Issue by rrandallcainc** [Khan/KaTeX#1154]
Rendering: `a\boldsymbol{+}c` will not contain spacing between the appropriate terms. 

<img width="571" alt="screen shot 2018-02-12 at 4 08 39 pm" src="https://user-images.githubusercontent.com/16921005/36119774-04771958-100f-11e8-8965-22bc90c2ad0f.png">

**Comment by kevinbarabash** [comment]
Well that's no good.  @rrandallcainc good find.

**Comment by RoyiAvital** [comment]
There is also more issue related to `\boldsymbol{}`.

Go to the [Demo Page](https://khan.github.io/KaTeX/).

Enter:

`{a}_{out} = {a}_{in} + \left( {y}_{out} - {y}_{in} \right) \boldsymbol{1}`

Rendering won't work.

**Comment by kevinbarabash** [comment]
@RoyiAvital the demo pages hasn't been updated, see https://github.com/Khan/KaTeX/issues/1171.

**Comment by RoyiAvital** [comment]
@kevinbarabash ,
It happens also with software based on KaTeX.
See - https://github.com/goessner/mdmath/issues/35#issuecomment-368304541.

**Comment by kevinbarabash** [comment]
@RoyiAvital what version of KaTeX is that project using?

**Comment by goessner** [comment]
@kevinbarabash ,

it should be `katex@0.8.3` with respect to `package.json`.

**Comment by edemaine** [comment]
I just posted over in https://github.com/goessner/mdmath/issues/35 but to repeat here: `\boldsymbol` got added in KaTeX v0.9.0-beta (also the recently released v0.9.0), so you just need to upgrade to add `\boldsymbol` support.
