### ISSUE TITLE
Is there a React / ES6 implementation?

### ISSUE THREAD

**Issue by sjorsvanheuveln** [Khan/KaTeX#1155]
Hi there,

I'm trying to set up KaTeX in react-16 using ES6. However I can't get it working. Also the react-katex repo is poorly maintained, so I'm currently kind of stuck. How to integrate katex rendering into react-16?

**Comment by kevinbarabash** [comment]
@sjorsvanheuveln does React 16 still support `dangerouslySetInnerHTML`?

**Comment by ylemkimon** [comment]
@kevinbarabash Yes

---
There is a react component that is developed and used by Khan Academy in [Khan/react-components/js/tex.jsx](https://github.com/Khan/react-components/blob/master/js/tex.jsx) ([Demo](http://khan.github.io/react-components/#tex)).

**Comment by kevinbarabash** [comment]
We should probably just add that to the README.md.

**Comment by kevinbarabash** [comment]
I didn't see anything particular wrong with https://github.com/talyssonoc/react-katex.  It hasn't been updated in a while, but it would only need updating if a person need access to recently added KaTeX options.  Although https://github.com/Khan/react-components/blob/master/js/tex.jsx has been updated recently it doesn't expose any of the new options either.

**Comment by sjorsvanheuveln** [comment]
@kevinbarabash I think `dangerouslySetInnerHTML` it is still supported, but that react-katex is giving me all kinds of problems. Maybe I have some conflicting packages or something, but that would be weird. I'll check that tex component, maybe that will solve all my problems. Thanks.

**Comment by sjorsvanheuveln** [comment]
How do I include this now? I have to use git submodules to install react-components? Can't I install through npm?

**Comment by kevinbarabash** [comment]
It looks like it's not handling the JSX.  You're babel config is probably excluding all files in node_modules.  You'll have to adjust the regex to all files in react-components to be transformed.

**Comment by sjorsvanheuveln** [comment]
Hmm, when I compare all the other NPM packages to this package I see that most of this is in JSX and all these other packages are JS only. This package seems to be an exception. Is this built in another fashion or something? Also I cannot just simply do this after installation:

`import { Tex } from 'react-components';`

It says the path is unresolved but the folder clearly exists in node_modules.

**Comment by kevinbarabash** [comment]
@sjorsvanheuveln that package is poorly constructed.  It doesn't defined a `main` entry point.  It really should have an `index.js` and multiple packages for each individual component if we wanted to get fancy.  Sorry about all of the issue with that package.

**Comment by sjorsvanheuveln** [comment]
No worries, is that on the planning though? Is it hard to make it like that?

**Comment by edemaine** [comment]
@sjorsvanheuveln None of the authors of that package are developers of KaTeX. I'd suggest posting an issue there, or someone could send in a PR...

**Comment by sjorsvanheuveln** [comment]
I did, but no response. Btw nice lectures on YT man! Learned some stuff from you.

**Comment by Jonnygwi** [comment]
@sjorsvanheuveln we have made react-latex and it works for us! Check it out https://github.com/zzish/react-latex

**Comment by sjorsvanheuveln** [comment]
@Jonnygwi How can I change the setup so that the css is already included in the package and doesn't need to be loaded externally?

**Comment by Jonnygwi** [comment]
@sjorsvanheuveln That is something we were thinking of adding to the project. At the moment you can either download the css or link to the cdn and include it into your template. You should not need to touch your webpack.

**Comment by edemaine** [comment]
If `react-latex` works well, we should probably link to it in the KaTeX README next to `ng-katex`.
