### ISSUE TITLE
Supporting \underline in Text Mode

### ISSUE THREAD

**Issue by rrandallcainc** [Khan/KaTeX#1158]
As a user I would expect `\text{\underline{hi}}` to work. Currently this works as expected in Math mode.

Actual Results: Error is thrown, and text is not rendered with an underline. 

Not sure if this is considered a bug, or just not yet implemented, but tagging as a bug for now.

**Comment by edemaine** [comment]
Agreed! I confirmed that this works in LaTeX. Fixed in #1159.
