### ISSUE TITLE
Katex fraction line inside iframe is not aligned properly

### ISSUE THREAD

**Issue by prabhatmuroor** [Khan/KaTeX#1163]
Katex is getting rendered properly in normal scenarios, but fraction lines are not aligned when rendered inside iframe.

![katex frac line](https://user-images.githubusercontent.com/32639057/36294557-8ac89fa4-1307-11e8-90de-91387a4dc7f8.PNG)

**Comment by ronkok** [comment]
@prabhatmuroor Which version of KaTeX are you using?

**Comment by kevinbarabash** [comment]
@prabhatmuroor is there a test page that you could link to with this issue?

**Comment by prabhatmuroor** [comment]
@kevinbarabash Unfortunately our site is not public yet. So I cannot give a link to try.
@ronkok I am using Katex 0.6.0

**Comment by edemaine** [comment]
Can you upgrade? 0.10.0 was just released, and  lot has changed since 0.6.0.

**Comment by kevinbarabash** [comment]
v0.9.0 was just released.

**Comment by kevinbarabash** [comment]
@prabhatmuroor can you check again with the latest version?
