### ISSUE TITLE
Don't run tests if only documentation changes have been made

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#1166]
It takes a while for tests to run and it would be nice if we could avoid running tests when we don't need to.

**Comment by ylemkimon** [comment]
What do you mean by tests: local tests or CI tests?

**Comment by kevinbarabash** [comment]
I was thinking on CI.  I usually don't run tests locally.

**Comment by kevinbarabash** [comment]
This isn't as important now that our tests run fast.
