### ISSUE TITLE
Fractional borders sometimes don’t appear.

### ISSUE THREAD

**Issue by mbostock** [Khan/KaTeX#1168]
I’ve noticed that sometimes the horizontal lines separating the numerator and denominator in frac expressions disappear (Chrome 64.0.3282.167, macOS 10.13.3, Retina display). For example:

![image](https://user-images.githubusercontent.com/230541/36347472-c73269ce-140c-11e8-8af5-60e2e1da129d.png)

This doesn’t always happen, even with the same input. For example, adding 0.5px to the margin-top above fixes the problem:

![image](https://user-images.githubusercontent.com/230541/36347488-eb540b28-140c-11e8-9cd8-32fac960cf35.png)

I traced this to the use of border-bottom-width: 0.04em as the style of the horizontal separator:

```html
<span class="" style="top: -3.23em;">
  <span class="pstrut" style="height: 3em;"></span>
  <span class="frac-line" style="border-bottom-width: 0.04em;"></span>
</span>
```

If border-bottom-width: 1px is used instead of 0.04em, then the line always appears at the desired thickness. Would you be willing to use px as units instead of em to fix this rendering problem in Chrome?

**Comment by kevinbarabash** [comment]
@mbostock https://github.com/Khan/KaTeX/pull/1143 may solve this.  I need to publish a new release though.

**Comment by kevinbarabash** [comment]
@mbostock v0.9.0 was released recently can you give it another try?

**Comment by mbostock** [comment]
0.9.0 fixes it for me! Thank you! 👍
