### ISSUE TITLE
0.9.0.zip has lots of unwanted stuff

### ISSUE THREAD

**Issue by mbourne** [Khan/KaTeX#1172]
katex.zip on the 0.9.0 release page is 2.5 to 3x the normal zipped size, and contains stuff such as:

FOLDERS
contrib
dist
dockers
...

FILES
.arcconfig
.arclint
.babelrc
...

This would be confusing for first-timers.

However, katex.tar.gz contains the usual needed files and folders.

**Comment by kevinbarabash** [comment]
@mbourne I checked the .zip file and it contains the same thing as the .tar.gz.  Can you paste the URL?

**Comment by edemaine** [comment]
This looks like the source ZIP as opposed to the distribution ZIP. Maybe you're comparing an old distribution ZIP to the new source ZIP?

**Comment by ronkok** [comment]
@mbourne, There are two links on the release page:
1. katex.zip
2. Source code (zip)

The one you want is katex.zip. The contents you describe are in Source code (zip).

**Comment by mbourne** [comment]
<blush> I was sure I grabbed katex.zip - my bad. :-(
