### ISSUE TITLE
Old Font Functions should switch to Text Mode

### ISSUE THREAD

**Issue by rrandallcainc** [Khan/KaTeX#1174]
When trying: `\sf{for $a < b$ and $c < d$.}` an error is thrown as `$` is used within math mode. When using the `\sf` and other old font functions, the mode should be switched to text.

**Comment by edemaine** [comment]
As you probably already figured out, `\sf` (and old font commands) don't switch to text mode in LaTeX.

**Comment by rrandallcainc** [comment]
Indeed I did haha.
