### ISSUE TITLE
Better Macro Docs

### ISSUE THREAD

**Issue by ry-randall** [Khan/KaTeX#1176]
I wasn't aware that the macro options could accept a function. This is awesome, and I think it would be cool to add it to the README.

**Comment by edemaine** [comment]
Oh, good point!  Sorry, that might have been me who added a feature without documentation...  It might also be good to clear up the confusion between the property name of the `macros` object and the name of the LaTeX macro, which is usually called a command in TeX parlance -- i.e., maybe change `\name` to `\command`.
