### ISSUE TITLE
Subscript/height issue within contenteditable

### ISSUE THREAD

**Issue by alexeymrkn** [Khan/KaTeX#1178]
The issue is very well seen on these pictures. I'm using the latest version of KaTeX, the issue is reproducible in Chrome and Opera on macOS as well as Chrome for Android. Haven't had a chance to test it on other platforms yet.

**Chrome**
<img src="https://user-images.githubusercontent.com/6084153/36646076-9aa69eb6-1a83-11e8-9ba4-31afd538fb93.jpg" width=350>

**Safari**
<img src="https://user-images.githubusercontent.com/6084153/36646051-4f031ebc-1a83-11e8-8838-5d4eb49c5724.jpg" width=350>

**Comment by ronkok** [comment]
I wonder if the KaTeX CSS is insufficiently isolated from external CSS.

@alexeymrkn Could you point to a test page where this occurs?

**Comment by alexeymrkn** [comment]
@ronkok this code is a part of a project that I maintain locally. After your request I've tried to reproduce the bug on a remote server (simplifying the code to ensure clearness) but failed to do so. It took me quite a time to realize that this bug appears only when inline math is rendered inside a `contenteditable` block. 

So here is a [jsFiddle playground](https://jsfiddle.net/91sc0vru/5/) demonstrating the issue.

**Comment by ronkok** [comment]
Among the  many clever steps in `makeVList`, it inserts a span with class `vlist` inside a span with class `vlist-r`, [here](https://github.com/Khan/KaTeX/blob/master/src/buildCommon.js#L560). The `vlist` span has no contents and it has a CSS rule of `display: table-cell;`. So it should render with the small height that the code defines for it.

Apparently Chrome will, in  `contenteditable` mode only, treat the cell as if it contains some text content, which then defines a `min-height` for the cell.  This can be evaded by placing yet another an empty span into the `vlist` span.

**Comment by kevinbarabash** [comment]
@ronkok thanks for investigating this.  I wish that we didn't have to content with `contenteditable`.  It's so poorly defined and each browser does its own thing. :\

**Comment by ronkok** [comment]
@alexeymrkn Thank you for determining that this problem takes place within a `contenteditable` div. That tip was the key to fixing the bug. A fix has now been merged into KaTeX master.

**Comment by alexeymrkn** [comment]
@ronkok It was my pleasure to make this nano contribution to this awesome project.
