### ISSUE TITLE
Markdown version of Function support html page

### ISSUE THREAD

**Issue by rahulpathakgit** [Khan/KaTeX#1181]
Hi,

Is it possible to get the markdown version of function support html page https://khan.github.io/KaTeX/function-support.html
I want to keep in my notes.

Regards
Rahul

**Comment by edemaine** [comment]
@ronkok can confirm, but that page was [written in HTML](https://github.com/Khan/KaTeX/blob/gh-pages/function-support.html), not Markdown.  So there is no Markdown version.  I'm not sure you could represent all the things on that page in Markdown...  But you could easily regex out all the `\(...\)` content and put it into your own Markdown file.

**Comment by rahulpathakgit** [comment]
Thanks Erik, I will surely try this.
Never got a change to thank you for A

**Comment by ronkok** [comment]
@rahulpathakgit, I've lately avoided maintaining both an HTML version and a Markdown version of that page. Later today or tomorrow, I'll try running a couple of RegEx scripts as @edemaine suggests. If all goes smoothly, I'll revive the [wiki page](https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX) version. If successful, the wiki page will be similar to the HTML version, but without the working examples.

**Comment by ronkok** [comment]
@rahulpathakgit, I've updated the [wiki page](https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX).  I'll probably revisit this sometime next week and add a table of contents.

**Comment by edemaine** [comment]
@ronkok Is this / can this be an automated process? I'd hate to double your maintenance work...

**Comment by ylemkimon** [comment]
Please note that the markdown version is now available in https://github.com/Khan/KaTeX/blob/master/docs/supported.md.
