### ISSUE TITLE
\not broken with new spacing code

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#1189]
0.9.0 seems to have introduced a bug in this simple example: `\not E`

0.9.0 renders as follows:
![image](https://user-images.githubusercontent.com/2218736/36811233-140437e6-1c9b-11e8-85fb-054231315fdf.png)
```html
<span class="katex-html" aria-hidden="true">
  <span class="strut" style="height:0.69444em;"></span>
  <span class="strut bottom" style="height:0.8888799999999999em;vertical-align:-0.19444em;"></span>
  <span class="base">
    <span class="mrel latin_fallback" style="position:absolute;padding-left:0.8em;"≯</span>
    <span class="mord rule" style="margin-right:0.2777777777777778em;"></span>
    <span class="mord mathit" style="margin-right:0.05764em;">E</span>
  </span>
</span>
```

0.9.0-alpha2 (as on the current demo site) renders correctly:
![image](https://user-images.githubusercontent.com/2218736/36811296-40ca1cb4-1c9b-11e8-883a-42ba809d01b5.png)

```html
<span class="katex-html" aria-hidden="true">
  <span class="strut" style="height:0.69444em;"></span>
  <span class="strut bottom" style="height:0.8888799999999999em;vertical-align:-0.19444em;"></span>
  <span class="base">
    <span class="mord mathit" style="padding-left:0.277771em;position:relative;">
      <span class="mainrm" style="position:absolute;right:0;"≯</span>
      <span class="mord mathit" style="margin-right:0.05764em;">E</span>
    </span>
  </span>
</span>
```

**Comment by kevinbarabash** [comment]
We should add a screenshot test case for this so we don't regress in the future.

**Comment by kevinbarabash** [comment]
@edemaine I forgot that we do have screenshot tests for this.  This bug seems to be Safari only.  Can you confirm what browser you're seeing this in?

**Comment by edemaine** [comment]
@kevinbarabash I just confirmed that the issue is present on Chrome 65.0.3325.181 for Windows on the current demo site (0.9.0).

**Comment by kevinbarabash** [comment]
Interesting.  It works fine for me in Chrome 66 on Mac.  In `makeFF` it looks like we're using the combining version and we're setting a negative left start bearing on the character which is probably what's causing the issue.

**Comment by kevinbarabash** [comment]
I've created https://github.com/KaTeX/katex-fonts/issues/44 to track fixing this.

**Comment by edemaine** [comment]
Just updated to 66.0.3359.117 and same issue.  Weird.  So maybe specific to Chrome for Windows?  And I assume you're seeing it on Safari too?

Anyway, we/you moved all the other accents over to noncombining characters to avoid Safari issues, so probably should do the same for `\not`...

**Comment by kevinbarabash** [comment]
I'm seeing the issue on Safari.

**Comment by edemaine** [comment]
Actually, I tried this on quicklatex, and maybe the new behavior is actually the correct one! (matching LaTeX)

![image](https://user-images.githubusercontent.com/2218736/39725408-a8c1c49e-5219-11e8-8d57-694a55f4a0e0.png)

**Comment by kevinbarabash** [comment]
@edemaine `\not=` is totally wrong.  It renders as `= /` in Safari so I think we still need a fix for this, as least for Safari.

**Comment by edemaine** [comment]
@riteme That is the intended behavior of `\not` -- it's how it works in LaTeX.  Here's a rendering from quicklatex.com:

![image](https://user-images.githubusercontent.com/2218736/42736797-f1e7c3de-8839-11e8-80a1-130583db24fe.png)

```latex
 
\begin{align*}
\not| \\
\nmid \\
\not\mid
\end{align*}
```

**Comment by riteme** [comment]
@edemaine That's strange... I have just switched to KaTeX from MathJax. It seems that MathJax simply translates `\not\mid` into `\nmid`.

**Comment by edemaine** [comment]
Thanks @riteme for the heads up. This does seem to be a difference between LaTeX and MathJax.  In these situations, we generally prefer to match LaTeX, in particular so that someone converting code from KaTeX to LaTeX will not have any surprises.
