### ISSUE TITLE
Inline \KaTeX is too wide in 0.9.0

### ISSUE THREAD

**Issue by mbostock** [Khan/KaTeX#1191]
From https://beta.observablehq.com/@mbostock/katex-0-9-0-spacing-bug:

![image](https://user-images.githubusercontent.com/230541/36815835-cf79f7c8-1c90-11e8-88ba-8a08d95f1fcf.png)

Here I’m using KaTeX to render its logo (`\KaTeX`). In 0.8.3, the resulting span was 56.28px wide. In 0.9.0, it’s 72.31px wide. It seems that 0.9.0 makes use of negative right margins, and unfortunately it seems that the negative right margins of descendants of the root span do not accumulate as expected, at least in Chrome and Safari. In Firefox the inline element has the expected width.

**Comment by edemaine** [comment]
Yes, this is a consequence of #836 and my rewrite of \KaTeX using macros (and negative spaces). :frowning: It would be great to fix the root problem, #836, but we've not yet found a solution. Let us know if you find something!

**Comment by edemaine** [comment]
#1194 should fix this!

**Comment by mbostock** [comment]
Thanks for fixing this bug! Any ETA on when a release that includes this fix? We’d love to update the version of KaTeX included in Observable’s standard library. Thank you all your work on this excellent library! ❤️

**Comment by kevinbarabash** [comment]
With all of the awesomeness that's been landing lately I was thinking I'd do a release sometime this weekend.
