### ISSUE TITLE
Position problems

### ISSUE THREAD

**Issue by ali-turan** [Khan/KaTeX#1196]
Hi, I have a few question : 

1- Integral sup and sub elements are not correctly positioned for my case. Or wide hat too close to its content. Is there an easy way to change positions? 

2- Is it possible to add new symbols by using unicode and svg path? If it is how can I do that?  

3- For example, I need double brackets (unicode: U+301A). How can I add it and how can I make it responsive to its content?

Thnx for your time.

**Comment by ylemkimon** [comment]
1. Could you post a screenshot?

**Comment by kevinbarabash** [comment]
@ali-turan could you open separate issues for these?

**Comment by edemaine** [comment]
I'm not sure we have an easy workflow for how to add symbols to fonts, though it's an area we've discussed.

Is there a LaTeX equivalent of double brackets that you're trying to achieve? If so, we'd probably consider it for the main KaTeX distribution.

**Comment by kevinbarabash** [comment]
@ali-turan 
1 - You might be able to tweak the CSS manually, but there isn't a easy way right now.  Having a screenshot though will help us determine if the spacing you're seeing is a bug or not.
2 - It isn't possible at the moment.  We do you use SVG for stretchy accents, but regular symbols are all rendered from fonts and changing that system to also all SVG would big a significant amount of work.  
3 - Adding specific glyphs from a package is definitely more doable.

@edemaine to answer your question there are two options:
- `\llbracket` and `\rrbracket` from the `stmaryrd` package
- `\textlbrackdbl` and `\textrbrackdbl` from the `textcomp` package

It might make sense to add these glyphs to our blackboard font file.

I found the answer in this awesome post https://tex.stackexchange.com/questions/81785/latex-code-for-white-square-brackets-and.  I love that it used dextexify to figure which packages the symbols were in.

**Comment by edemaine** [comment]
I added the double-bracket feature request as a separate issue: https://github.com/KaTeX/katex-fonts/issues/46

I'm going to close this issue for now, but feel free to provide more information and we can try to help.
