### ISSUE TITLE
\text accepts nested $...$ fragments but not \(...\)

### ISSUE THREAD

**Issue by akalin** [Khan/KaTeX#1212]
In LaTeX and MathJax, this works fine:
```
\[
  x = z \quad \text{because $x = y$ and \(y = z\)}
\]
```
KaTeX doesn't like the nested `\(...\)` fragment, though.

This is [documented](https://khan.github.io/KaTeX/function-support.html) and probably well-known, but I didn't find an issue on it.

This could probably be generalized to accepting only the delimiters passed in to `renderMathInElement` with `display: false`, but I don't know if the structure of the code makes that easy.

**Comment by edemaine** [comment]
Good idea!  We should definitely support nested `\(...\)`.  I originally added `$` support, and can try to do the same for `\(`.

I *don't* think we want to have any connection to `autorender` though. That's about getting from HTML into LaTeX.  Once in LaTeX, we should just support LaTeX syntax.

**Comment by akalin** [comment]
Ah, good point, forgot that they were separate! I agree.
