### ISSUE TITLE
Simple matrices are extraordinarily annoying to write

### ISSUE THREAD

**Issue by lpulley** [Khan/KaTeX#1219]
I take notes in KaTeX in StackEdit on my laptop. It works great for everything except matrices, which just seem unnecessarily complex. Is there a way to implement a simpler matrix format than `\begin{bmatrix}\end{bmatrix}`?

**Comment by edemaine** [comment]
I'm not sure what you're imagining for a simpler way.  I agree that it's tedious, but `&` between columns and `\\` between rows is about as simple as I can imagine.

Also, more generally, KaTeX won't support it unless LaTeX does.

**Comment by mbourne** [comment]
@lpulley You could consider ASCIIMath, which is a calculator-like input mode that makes entering matrices (and many other things) quite easy. For examples and a sandbox, see:
https://www.intmath.com/help/asciimath-input-katex-output.php

**Comment by kevinbarabash** [comment]
The goal of KaTeX is to provide an implementation of LaTeX for the web.  Providing alternative syntax for matrices is pretty far outside that goal.
