### ISSUE TITLE
support \widecheck

### ISSUE THREAD

**Issue by ylemkimon** [Khan/KaTeX#1221]
`\widecheck` is a wide `\check` and an upside-down `\widehat`, which is available in packages `mathabx` and `stix`.

**Comment by ylemkimon** [comment]
Related: #560

**Comment by ronkok** [comment]
I can do `\widecheck`. Not right away, though. Maybe in a couple of weeks.

`\wideparen` is a little more difficult. I may eventually get to it, but it is well down on my priority list.
