### ISSUE TITLE
Can not config both $$...$$ and $$\n...\n$$ as math delimiters

### ISSUE THREAD

**Issue by jiewuza** [Khan/KaTeX#1240]
When config `$$...$$` as inline math and `$$\n...\n$$` as display math,
```
$$ax^2$$
and then $$
ax^2
$$
```
the first line is not recognized, because the right `$$` is followed by `\n` and is treated as the left delimiter of display math.
See #1202

**Comment by kevinbarabash** [comment]
Closing as a duplicate.  I've posted a suggestion of how to work around the issue in #1202.
