### ISSUE TITLE
Sandbox/Demo/REPL for testing on local and the website

### ISSUE THREAD

**Issue by ylemkimon** [Khan/KaTeX#1244]
Currently, KaTeX has a demo at [GitHub pages](https://khan.github.io/KaTeX/), which provides very basic demo, and a local test page on `npm run`, where some options are configurable using URL parameters.

It'd be useful to have KaTeX sandbox/demo for _both_ local and the website with:
- GUI to configure KaTeX (#1225, #1193)
- ability to run previous versions or test a PR. (#1187, #1171, #1235)

There are many existing similar services and it'd be nice to adopt existing framework, but I can't seem to find a suitable one:
- [CodePen](https://codepen.io/pen/)
- [JSFiddle](https://jsfiddle.net/)
- [Babel REPL](http://babeljs.io/repl)
- [CodeSandbox](https://codesandbox.io/)
- [Ace Kitchen Sink](https://ace.c9.io/build/kitchen-sink.html)

**Comment by kevinbarabash** [comment]
We might want to look at revising our gh-pages to have multiple pages.  The current demo has both a small text input box and a small render output.  In another issue it was mentioned having a way to also change the settings.  I think a dropdown with specific examples would be nice too.
