### ISSUE TITLE
Hanging indent causes problems

### ISSUE THREAD

**Issue by mbourne** [Khan/KaTeX#125]
Hi

If the paragraph has this CSS:

.myIndent{text-indent:-1em;padding-left:1em}

Then KaTeX looks like this:

![image](https://cloud.githubusercontent.com/assets/7541940/4404636/74e97274-44b3-11e4-809e-de3363fde857.png)

This is how it looks without the indent applied:

![image](https://cloud.githubusercontent.com/assets/7541940/4404656/be08be88-44b3-11e4-9f12-c6948caa55df.png)

Seems to be the same on all browsers and OSs I've tried.

Regards
Murray

**Comment by ylemkimon** [comment]
Is this still an issue?

**Comment by mbourne** [comment]
No, I don't believe it's still an issue. `text-indent:0` is now in `.katex`, so all is good.
