### ISSUE TITLE
\mathnormal vs. \mathit

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#1250]
TeX has two "math italic" fonts with different italic corrections. Here's a comparison from quicklatex for `fff\mathnormal{fff)\mathit{fff)`:

![ql_f9de3eed425b22fbe468db5d6af6db20_l3](https://user-images.githubusercontent.com/2218736/38286911-df1887d8-3795-11e8-92f5-03e37f67f4d1.png)

KaTeX doesn't support `\mathnormal` but renders all italic text as if it is mathnormal. This is correct in the default, but is *not* how `\mathit` is supposed to work. 

This might be why we have two italic fonts (Main and Math) but I'm not sure. We should investigate how TeX does this. 

P.S. We might also look at what MathJax does, as it gets this right.

**Comment by ylemkimon** [comment]
The `\mathit` should use text italic fonts, `KaTeX-Main-Italic`.

**Comment by edemaine** [comment]
Agreed: `\mathit` should use text italic fonts but remain in math mode.  (I guess this doesn't explain Main vs. Math then.)

**Comment by edemaine** [comment]
In LaTeX, math and text fonts can be different. We don't support that yet in KaTeX; will we ever want to? If so, `\mathit` and `\textit` would then need to load different fonts...

**Comment by edemaine** [comment]
@kevinbarabash They aren't different by default, but you can `\usepackage{euler}` for example to use Euler math fonts, but keep text font the same (Computer Modern by default); or `\usepackage{crimson}` to use Crimson for the text font, but keep math font the same (Computer Modern by default). If we want to eventually support font changing like this, we might be careful when defining `\mathit` to behave like `\textit`.

**Comment by kevinbarabash** [comment]
Interesting.  It sounds like we need some sort of mapping to say which font either math fonts or text fonts are pointing to.  At least initially they'd point to the same font.

**Comment by ylemkimon** [comment]
math font | alphabet / greek | number / Greek
---------- | ----------------- | ---------------
(default) | wide spacing<br>(`Math-Italic`) | normal<br>(`Main-Regular`)
`\mathnormal` | wide spacing<br>(`Math-Italic`) | old-style / italic, wide spacing<br>(`Caligraphic` / `Math-Italic`)
`\mathit` | narrow spacing / ?<br>(`Main-Italic` / `Math-Italic`) | italic, narrow spacing<br>(`Main-Italic`)

**Comment by ylemkimon** [comment]
Related: #584

**Comment by rokyed** [comment]
@ylemkimon can you please add to options the old behaviour?

**Comment by ylemkimon** [comment]
@rokyed If you need `\mathnormal` behavior for `\mathit`, you can define a macro, `"\\mathit": "\\mathnormal"`.

**Comment by rokyed** [comment]
@ylemkimon I have latexes stored on the back-end, that I can't modify them anymore, adding mathit or mathnormal on them it's impossible since I'm front-end, my only fix was to revert the version to 0.9.0 which is not ideal. Also all our latex uses multiline and multiline with aligned signs and from what I tested, it's not ideal to write macros. My only solution would be to fork the repo and revert your solution in order to get back the old behaviour, but that's unrealistic. This behaviour was present on every piece of text before. Thanks.

**Comment by edemaine** [comment]
@rokyed You don't need to change your LaTeX at all.  You just need to call KaTeX with options that includes `{macros: {"\\mathit": "\\mathnormal"}}`.  See https://katex.org/docs/options.html

**Comment by rokyed** [comment]
@edemaine So, I need to apply by default on anything ```\mathit```  but that's not simple since all the latex is stored on the servers and it's not modifiable anymore and to make things even harder ```\begin{aligned} bla &= bla\\ bla &= 300blas\\ the 300 blas  &= boom\end{aligned}``` is something that occurs often. So the equations are not simple.

**Comment by edemaine** [comment]
@rokyed I still don't understand. Like I said, you don't need to change your LaTeX at all. If you're upgrading KaTeX, just change the calls to KaTeX at the same time.

If you have further questions, please open a fresh issue instead of appending to this old one.

**Comment by kevinbarabash** [comment]
@rokyed how are you calling `katex.render`?

**Comment by rokyed** [comment]
```javascript
return katex.renderToString(latex, options)
return katex.render(latex, element, options) // the element is usually a <div> empty by default.
```
nothing special

```javascript
let options = {
	unicodeTextInMathMode: true,
	// unicodes are not fully supported yet,
	// this is how we do 'round here
	macros: LATEX_MACROS,
}
```

**Comment by kevinbarabash** [comment]
Is `LATEX_MACROS` coming from the server?  Regardless of where it's coming from though, you should be able to do:
```
let options = {
	unicodeTextInMathMode: true,
	// unicodes are not fully supported yet,
	// this is how we do 'round here
	macros: Object.assign({}, LATEX_MACROS, {"\\mathit": "\\mathnormal"}),
};
```
