### ISSUE TITLE
\tt font blank has incorrect width

### ISSUE THREAD

**Issue by pzinn** [Khan/KaTeX#1255]
I switched from MathJax to katex in the hope of avoiding this very bug, but sadly am having the same problem: the space character of the \tt font (KaTeX_Typewriter) is not of the correct width.
```
\begin{array}{l}
\text{\tt x   y}\\
\text{\tt x123y}
\text{\tt x\ \ \ y}\\
\end{array}
```
\tt is supposed to be a fixed width font, yet neither the first nor the last line have the y at the same spot as the one in the middle...

**Comment by edemaine** [comment]
@pzinn Thanks for finding this bug! I dealt with this issue when implementing `\verb`, but didn't realize it still plagued `\texttt`.  You can use `\verb` as a workaround for now until we fix it.

**Comment by pzinn** [comment]
thanks for your quick response. yes, there are plenty of workarounds (just like there were in mathJax...) but none of them really work for the app I'm building. IMHO the only correct solution is to fix the font so that it's truly fixed width. I hope this is the option you'll choose.

**Comment by edemaine** [comment]
@pzinn Found the fix. PR https://github.com/KaTeX/katex-fonts/pull/41 should eventually solve this, once reviewed and brought into KaTeX.

**Comment by pzinn** [comment]
awesome thanks :)
