### ISSUE TITLE
[Bug] Unicode character ≪ gives parse error

### ISSUE THREAD

**Issue by Danmou** [Khan/KaTeX#1271]
The unicode character ≪ (U+226A) in KaTeX input currently gives a parse error, but it should be interpreted as `\ll`, just like ≫ (U+226B) is interpreted as `\gg`.

**Comment by Danmou** [comment]
Same problem with ⋘ (U+22D8)

**Comment by ronkok** [comment]
@Danmou,  Thanks for the note. I've just submitted PR #1273, which will fix this issue.

**Comment by literallyvoid** [comment]
Isn't this fixed? #1273 has been merged.

**Comment by ronkok** [comment]
@literallyvoid It's fixed in KaTeX `master` branch. It is not yet part of a KaTeX release.

**Comment by kevinbarabash** [comment]
I need to do a release.

**Comment by ronkok** [comment]
Fixed by #1273.
