### ISSUE TITLE
\underset and exponent

### ISSUE THREAD

**Issue by pzinn** [Khan/KaTeX#1275]
in KaTeX, 
```
\underset{*}{x}^2
```
results in the exponent 2 being right above x (instead of above to the right in LaTeX).
is that a known/expected behavior?

**Comment by kevinbarabash** [comment]
We must be assuming that any character inside `\underset` should be typeset using the limits structure.  Looks like a bug.  Thanks for reporting.

**Comment by ronkok** [comment]
@kevinbarabash I can confirm that `\underset` and `\overset` both use the limits structure. However, `\stackrel` is done differently and apparently in a more robust manner. I'll see if I can extend the `\stackrel` method to `\underset` and `\overset`.

**Comment by ronkok** [comment]
@pzinn I just turned in PR #1277, which will fix this issue.

**Comment by edemaine** [comment]
Fixed by #1277. Thanks for the report!
