### ISSUE TITLE
Why does makeGlue use .mord .rule instead of .mspace?

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#1289]
`makeGlue`, which is what `\hskip` uses to build a space in HTML, looks like this:

```js
const makeGlue = (measurement: Measurement, options: Options): DomSpan => {
    // Make an empty span for the rule
    const rule = makeSpan(["mord", "rule"], [], options);
    const size = calculateSize(measurement, options);
    rule.style.marginRight = `${size}em`;
    return rule;
};
```

Does anyone know why this space has classes `.mord .rule` instead of the more obvious `.mspace`?

For example, `buildHTML`'s `buildExpression` looks at the first class of groups to see whether it is `mspace`, to ignore spaces.  It seems like `\hskip`s ought to be treated as spaces, but they aren't currently?...

**Comment by kevinbarabash** [comment]
I'm pretty sure I originally wrote this function so it's fault.  Good catch.
