### ISSUE TITLE
Google group for KaTeX?

### ISSUE THREAD

**Issue by mbourne** [Khan/KaTeX#129]
I actually have a question, rather than an issue, but couldn't find anywhere to ask my question. Hence the   Google group suggestion. :-)

I'll ask my question here anyway and hope it's not annoying.

I'm looking for 2 signals:
1. When a particular math expression has finished processing.
2. When all the math on a page has finished processing.

Thank you!
Regards,
Murray

**Comment by spicyj** [comment]
Sounds like everything was resolved here – let me know if not and I'll reopen.
