### ISSUE TITLE
Migrate to travis-ci.com and enable GitHub Apps

### ISSUE THREAD

**Issue by ylemkimon** [Khan/KaTeX#1291]
On May 2nd, 2018 Travis CI announced that [open source projects will be joining private projects on `travis-ci.com`.](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/)

Repository on `travis-ci.com` supports GitHub Apps-based Integration, which provides a tighter integration with GitHub and finer control over repository and subscription ownership and permissions.

It also supports [Checks API](https://blog.github.com/2018-05-07-introducing-checks-api/), which was introduced on May 7th, 2018.

> Instead of pass/fail build statuses, your integrations can now report richer results, annotate code with detailed information, and kick off reruns—all within the GitHub user interface.
Build outputs are now accessible with the new “Checks” tab on pull requests. Inline annotations are simple to find, too. They’ll appear right alongside the relevant code in the pull request, so you can identify and address failing checks even faster.

Travis CI states that open source repositories will be migrated to travis-ci.com gradually, beginning at the end of Q2 2018. However, they also state that:
> Repositories may also be migrated without their build history immediately. Please contact support support@travis-ci.com and include “Repository Migration” somewhere in the subject line, and the name of the repository in your email.

I think, if our Travis build history is not important, we should request to migrate to `travis-ci.com` and enable GitHub Apps.

CC @kevinbarabash

**Comment by kevinbarabash** [comment]
@ylemkimon thanks for raising this issue.  I don't think our Travis build history is important.  I can email them.

**Comment by ylemkimon** [comment]
Closing this as we're moving to CircleCI.
