### ISSUE TITLE
Adding size functions in equations removes spacing

### ISSUE THREAD

**Issue by rrandallcainc** [Khan/KaTeX#1292]
Examples: `a {\small + } b` `a {\small = } b` `a {\small - } b`

Without Sizing:
<img width="816" alt="screen shot 2018-05-07 at 1 56 13 pm" src="https://user-images.githubusercontent.com/16921005/39716470-74c1cf9c-51fe-11e8-9bb6-547357aeceaa.png">

With Sizing:
<img width="779" alt="screen shot 2018-05-07 at 1 56 08 pm" src="https://user-images.githubusercontent.com/16921005/39716476-7bf77b54-51fe-11e8-9416-af2ac81c1b64.png">

**Edit:**

@edemaine has pointed out that this is a feature, not a bug. With that said, going to re-purpose this to a discussion around the following question:

What the best way to accomplish a smaller operator with LaTeX?

**Comment by edemaine** [comment]
@rrandallcainc Did you test against LaTeX? Because `a{-}b` is generally *supposed* to remove the spacing around `-` in LaTeX.

**Comment by rrandallcainc** [comment]
@edemaine Doh! Nice catch. I can close this issue. Curious, what's the best way to accomplish a smaller operator then with LaTeX?

**Comment by edemaine** [comment]
You need to remap the new symbol in `\mathbin` to get it to act like a binary operator again:

```latex
x\mathbin{\small +}y
```

Enjoy!
