### ISSUE TITLE
ParseError: KaTeX parse error: Expected 'EOF', got '\unsupported' at position 1: \̲u̲n̲s̲u̲p̲p̲o̲r̲t̲e̲d̲

### ISSUE THREAD

**Issue by BenjaminHoegh** [Khan/KaTeX#1293]
`ParseError: KaTeX parse error: Expected 'EOF', got '\unsupported' at position 1: \̲u̲n̲s̲u̲p̲p̲o̲r̲t̲e̲d̲`

Version: 0.9.0

**Comment by edemaine** [comment]
Could you clarify what your input is that generates this error?  It would appear to be `\unsupported`, but I'm guessing it was something else?

**Comment by BenjaminHoegh** [comment]
well it was just me there have made a typo.

A little question how to intergrade KaTeX into [Marked](https://github.com/markedjs/marked) ?

**Comment by edemaine** [comment]
@BenjaminHoegh I still don't understand what you're doing that is resulting in that error. Could you provide, for example, an example file, or an input to the demo site that causes the problem?

Regarding Marked, a quick google search gives https://www.npmjs.com/package/marked-katex which might be useful.

**Comment by edemaine** [comment]
It sounds like you resolved the issue, but if you're still having trouble, feel free to ask with more details.
