### ISSUE TITLE
Using Small Operators

### ISSUE THREAD

**Issue by rrandallcainc** [Khan/KaTeX#1294]
What's the best way to use a "smaller" operator with math equations? My first attempt was to do something like `a{\small -}b` but that removes the spacing. 

See:

<img width="779" alt="screen shot 2018-05-07 at 1 56 08 pm" src="https://user-images.githubusercontent.com/16921005/39716476-7bf77b54-51fe-11e8-9416-af2ac81c1b64.png">

Looking for alternative approaches that folks can think of.

**Comment by edemaine** [comment]
You need to rewrap the new symbol in `\mathbin` to get it to act like a binary operator again:

```latex
x\mathbin{\small +}y
```

**Comment by rrandallcainc** [comment]
@edemaine That worked perfectly. Thanks!
