### ISSUE TITLE
How do you get environments to work?

### ISSUE THREAD

**Issue by BenjaminHoegh** [Khan/KaTeX#1296]
how do you get Environments to work when using `renderMathInElement()`?

Example if I write this:
```
\begin{Bmatrix}
   a & b \\
   c & d
\end{Bmatrix}
```

I just end up with this in the browser:
`\begin{Bmatrix} a & b \\ c & d \end{Bmatrix}`

**Comment by edemaine** [comment]
That should work.  (It works on [the demo page](https://khan.github.io/KaTeX/), for example.)  We'd need a more complete example of the HTML/JavaScript to help you debug.  I doubt it's related to environments specifically, but rather just not calling `renderMathInElement()` correctly.  (Did you check the console?)

**Comment by ronkok** [comment]
@BenjaminHoegh , If you are not using the Auto-render extension, then the syntax you need is `katex.render`, not `renderMathInElement`

If you are using the Auto-render extension, then keep in mind that it always looks for math delimiters like `$$...$$` or `\[...\]`.  This is unlike LaTeX or MathJax, in which an environment is by itself enough to initiate math mode. The Auto-render extension needs the delimiters, even for environments.

**Comment by edemaine** [comment]
@BenjaminHoegh I'm not sure we can do that, as `\\` is valid LaTeX.  The underlying problem is that we don't yet support `\\`; see #171.  I'm reasonably hopeful that we'll be able to add support for `\\`, though, via #1287.
