### ISSUE TITLE
\underbrace vertical offset when subscript has depth

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#1303]
Correct behavior: `x=\underbrace{\frac{x}{y}}_h` (frac line is aligned with base line)

![image](https://user-images.githubusercontent.com/2218736/39878839-57e28588-5447-11e8-8803-1f8f6b13a399.png)

Incorrect behavior: `x=\underbrace{\frac{x}{y}}_g` (frac line is above base line)

![image](https://user-images.githubusercontent.com/2218736/39878865-63fb04a8-5447-11e8-838d-b273ae3cf89a.png)

@ronkok, any ideas why this might be happening?

**Comment by ronkok** [comment]
@edemaine  I'll look into it.
