### ISSUE TITLE
KaTeX Screenshotter Bot

### ISSUE THREAD

**Issue by ylemkimon** [Khan/KaTeX#1313]
GitHub [has introduced "Checks API"](https://blog.github.com/2018-05-07-introducing-checks-api/), which states:

> The Checks API allows you to build sophisticated tools for continuous integration (CI), linting, and acceptance testing on GitHub.

I've created a bot, based on `probot`(Node.js based), which posts a check run with CircleCI screenshotter results, as screenshotter is hard to run and CircleCI build artifacts are hard to access.

https://github.com/KaTeX/screenshotter-bot

- [x] Transfer the bot repo to KaTeX organization
- [x] Deploy the bot: [Glitch](https://glitch.com/)(free with restrictions), [Heroku](https://www.heroku.com/)(free plan with limitations), [Zeit Now](https://zeit.co/now)(free for open source)
- [x] Create a GitHub App and install on KaTeX repo

## Running
![running](https://user-images.githubusercontent.com/888148/39967625-cfbff4d2-56f9-11e8-86a1-095d375acaf6.png)

## Passed
![passed](https://user-images.githubusercontent.com/888148/39967619-be588ac4-56f9-11e8-80f5-de45b3bfeaff.png)

## Failed
![failed](https://user-images.githubusercontent.com/888148/39967621-c739afd8-56f9-11e8-9aaf-f04cff2078f3.png)

## Errored
![errored](https://user-images.githubusercontent.com/888148/39967623-cba7967a-56f9-11e8-9880-205946db1f1f.png)

**Comment by kevinbarabash** [comment]
This is awesome!  I love that diffs from failures show up right in the GitHub UI.

**Comment by kevinbarabash** [comment]
> Transfer the repo to KaTeX organization

Sorry I still haven't gotten around to this.  Knowing why this is necessary will me advocate transferring of the repo.

**Comment by ylemkimon** [comment]
@kevinbarabash I meant moving the bot repo(https://github.com/ylemkimon/screenshotter-bot) to the KaTeX organization. That way, it's easier to maintain, and other people can easily review and contribute to the code.

**Comment by ylemkimon** [comment]
@edemaine There is annotation feature in the `check`:

![](https://developer.github.com/assets/images/checks/checks_annotation.png)
![](https://developer.github.com/assets/images/check_run_annotations.png)

I think Travis CI or CircleCI will support exporting results to CI.

**Comment by ylemkimon** [comment]
I didn't know it was installed on the repo 😄 As it's running on my laptop, its uptime would be only when I'm debugging it or I forgot to turn off it after the debugging :)

**Comment by ylemkimon** [comment]
Blocked on https://github.com/ylemkimon/screenshotter-bot/issues/3 and https://github.com/ylemkimon/screenshotter-bot/issues/2.

**Comment by kevinbarabash** [comment]
Thanks for the update.

**Comment by ylemkimon** [comment]
The issues has been resolved and I think it's ready to be deployed. @kevinbarabash Can I transfer the bot repo's ownership to the KaTeX?

**Comment by kevinbarabash** [comment]
@ylemkimon go for it.  Thanks for setting this up.

**Comment by ylemkimon** [comment]
@kevinbarabash Done 😄 Please update the author/copyright information appropriately.

**Comment by kevinbarabash** [comment]
@ylemkimon just so that we're on the same page, you think we should change the copyright to
```
Khan Academy (c) 2018
```

**Comment by ylemkimon** [comment]
@kevinbarabash Yes, I'm willing to waive all my rights if necessary.

Also, it seems creating a GitHub app on the organization requires admin permission. Could you [create a GitHub app and deploy the bot](https://probot.github.io/docs/deployment/)? (I think we can go with [Zeit Now](https://zeit.co/now)).

**Comment by ylemkimon** [comment]
The bot is successfully deployed!

**Comment by ylemkimon** [comment]
I forgot to enable `Pull request` permission and event subscription, which is needed for PR from forked repo. I enabled them and re-authentication may be necessary.

**Comment by ylemkimon** [comment]
@kevinbarabash Thank you!
