### ISSUE TITLE
fcolorbox with transparent background

### ISSUE THREAD

**Issue by rrandallcainc** [Khan/KaTeX#1315]
I'd like to be able to use the fcolorbox, with a transparent background. Is it possible to do something like: `\fcolorbox{black}{none}{hi}`

**Comment by edemaine** [comment]
Yes, that works as-is.  Currently, colors are passed through directly to CSS, provided they match `/^(#[a-f0-9]{3}|#[a-f0-9]{6}|[a-z]+)$/i`, so `none` in particular works.

**Comment by rrandallcainc** [comment]
Thank you!
