### ISSUE TITLE
KaTeX run on WebView in mobile app

### ISSUE THREAD

**Issue by NhaPCS** [Khan/KaTeX#1317]
Hi, I have an app is using KaTeX run on WebView. 
On one screen, I have multi WebView, but sometimes, It's too heavy to load data on the WebView.
So can you create a version for WebView on mobile, it would be lighter and faster?

I am very thankful if you consider my problem. Thank you very much!

**Comment by ylemkimon** [comment]
I think KaTeX is light enough to run on mobile devices. Could you elaborate on `too heavy to load data`?

**Comment by NhaPCS** [comment]
It runs very well if I have a few of WebView on one screen. In my case, I need multi WebView on one screen. For example https://drive.google.com/file/d/14GlGuDZgYryBb3dL8Fa9uFlV9G2aq42Y/view?usp=sharing
It took about 2-4s delay to load data

**Comment by edemaine** [comment]
Right, I think what you need to do is figure out a way to load KaTeX only once, and share them among the various equations.  I routinely render hundreds to thousands of equations on mobile without trouble (in a single WebView).

**Comment by kevinbarabash** [comment]
Closing this as the suggested fixes should work.

**Comment by oustme** [comment]
Can we use KATEX to render math in a mobile app **when it is offline (without network connection)**? Has anyone tried this? Any guidelines will be helpful

**Comment by kevinbarabash** [comment]
If you have a copy of the .js/.css files in your app bundle you should be able to load them in a webview off-line.
