### ISSUE TITLE
CircleCI artifact access

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#1326]
When I look at a CircleCI run, I see this:

![image](https://user-images.githubusercontent.com/2218736/40238669-e1460a30-5a81-11e8-90af-c88ca880e4fb.png)

Notably, the [artifacts tab](https://circleci.com/docs/2.0/artifacts/) is missing.  Is there some way to make the generated artifacts readable by everyone? @ylemkimon 

This seems to also affect CircleCI runs triggered by my own PRs...

**Comment by ylemkimon** [comment]
It seems that you have to be logged in with a account to view the artifacts. Click top right button(<img src="https://user-images.githubusercontent.com/888148/40241080-0b8dd23c-5af5-11e8-9581-c81ae7bade53.png" height="20" width="20">) and click `Log out`, and log in with GitHub. Then you will see the organization name `Khan` upper left and be able to view artifacts.

**Comment by edemaine** [comment]
That did it, thanks!
