### ISSUE TITLE
Line breaks in macro-constructed relations

### ISSUE THREAD

**Issue by ronkok** [Khan/KaTeX#1333]
With the new line break code, line breaks sometimes occur between the symbols of a macro-constructed composite relation symbol. For example, `\coloneqq` should render roughly as ":=" and there should be no line break between the two characters. But I find that line breaks can sometimes occur there.

**Comment by ronkok** [comment]
Let me suggest a tactic to overcome this. Amend the macro and wrap a `mathrel` around the whole thing. Then add a `white-space: nowrap` rule to the CSS for `mrel`.

**Comment by edemaine** [comment]
Wrapping in a `\mathrel`, or even just {...} will suffice, as in LaTeX. Shouldn't need any additional CSS rules. We probably want to wrap in mathrel just to get the spacing right...

**Comment by ronkok** [comment]
@edemaine If you can find some way to land #1162, then I would be happy to take on these relations.

**Comment by ronkok** [comment]
Fixed. by #1372,
