### ISSUE TITLE
Support for custom delimiters in KaTeX

### ISSUE THREAD

**Issue by pariola** [Khan/KaTeX#1347]
I tried to use a custom delimiter `$$`, when I use this with automatic rendering this works but when I use renderToString I get a Parse error.

Thanks in anticipation

**Comment by edemaine** [comment]
`renderToString` expects to be given a math expression, so not wrapped by `$`s.  Could you give more context of how you're using it?

**Comment by pariola** [comment]
I'm using Preact and i'm trying to render a math equation gotten from a MongoDB so when i use `renderToString` it gives a Parse Error when i use the `$$`. Thanks for the info 👍

**Comment by pariola** [comment]
Thanks, i finally got it. I hooked up the auto-render on the `componentDidUpdate`'s hook of a component
