### ISSUE TITLE
\begin{pmatrix} after open { and close } \end{pmatrix}

### ISSUE THREAD

**Issue by balakrishnan1978** [Khan/KaTeX#1350]
Hi,

When we using **\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}** is working fine. But open "{" and close "}" brace is not working. Example **\begin{pmatrix} {1 & 2 \\ 3 & 4} \end{pmatrix}**.

**Comment by edemaine** [comment]
That example does not work in LaTeX either. `&` must appear at the top level group of an array/tabular environment.

**Comment by balakrishnan1978** [comment]
I agree will not work in LaTeX
