### ISSUE TITLE
Textdollar doesn't work

### ISSUE THREAD

**Issue by Danita** [Khan/KaTeX#1351]
Some functions from the [Function Support](https://khan.github.io/KaTeX/function-support.html) page don't work, such as `\textdollar` or `\textunderscore`. What am I doing wrong?

![captura](https://user-images.githubusercontent.com/754783/40494432-32805982-5f4b-11e8-8186-a1792ef533c5.PNG)

Using Katex 0.9.0.

**Comment by ronkok** [comment]
Yep. There are several entries that should get the `\text{…}` treatment. Thank you to @danita for pointing it out.

**Comment by ronkok** [comment]
Function support page is now updated to read as `\text{\textdollar}`. Closing this issue.
