### ISSUE TITLE
More NPM vulnerabilities

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#1355]
`npm audit` on the latest NPM is much more thorough than Github's (#1340).  I get:

```
[!] 399 vulnerabilities found [13870 packages audited]
    Severity: 379 Low | 8 Moderate | 11 High | 1 Critical
```

Most of them are on the build/testing side, so don't directly affect us, but we should probably comb through them and cleanup.

**Comment by kevinbarabash** [comment]
Good find.  Can you link to audit?

**Comment by ylemkimon** [comment]
@kevinbarabash What do you think about automating dependency management, like Greenkeeper? It automatically sends in PRs and open an issue if it breaks the tests.

**Comment by kevinbarabash** [comment]
@ylemkimon that sounds great!

**Comment by edemaine** [comment]
@kevinbarabash Here's a paste (5827 lines!): https://gist.github.com/edemaine/dd1c998483c7fc694584e33a69a2d7dc
You can get it by running `npm audit`.

#1337 will fix the webpack ones at the top, I imagine.

@ylemkimon Sounds awesome!

**Comment by kevinbarabash** [comment]
@edemaine I tried running `npm audit` locally but that doesn't seem to be a command in npm v5.6.0.  What version of `npm` are you running?

**Comment by ylemkimon** [comment]
@kevinbarabash It is introduced in `npm v6`.

With #1368 and #1374:
```
                       === npm audit security report ===

found 0 vulnerabilities
 in 42827 scanned packages
```
