### ISSUE TITLE
aligned environment issue

### ISSUE THREAD

**Issue by OnlineVagrant** [Khan/KaTeX#1364]
When aligning equations sometimes I require a bit of text before an equation. However if there are more than one line of text, the output looks bad as the sentences won't be left justified. Is there a way to achieve this in Katex?. Here is a nonsensical example of what I mean.

       $$\begin{aligned}
           \text{Since } x \text{ is an interger } \qquad   a&=b+c \\
           \text{ Hence} \qquad d+e&=f
       \end{aligned}
      $$
![sni](https://user-images.githubusercontent.com/39413259/40581613-afa48944-6133-11e8-8496-e0bcbf1a3353.JPG)

# Expected behaviour
![sni](https://user-images.githubusercontent.com/39413259/40581691-4e051ba2-6135-11e8-9318-ec83ff870e57.JPG)

**Comment by ronkok** [comment]
@OnlineVagrant The `aligned` environment can do this sort of thing. Think of the ampersands as being numbered 1, 2, 3. The odd numbered ampersands will be the alignment points. The even numbered ampersands are like a balloon that expands till enough space is created to enable the alignment.

![alignedat](https://user-images.githubusercontent.com/16403058/40581785-f96dc5fe-6115-11e8-9d5d-ddf4d5d73ad2.PNG)

**Comment by ronkok** [comment]
Correction. It's the `alignedat` environment, not `aligned`.

**Comment by OnlineVagrant** [comment]
Thank you. I saw that environment in the [Function support](https://khan.github.io/KaTeX/function-support.html#environments) but didn't think it could be used this way. Is there a Katex tutorial I can look at for the not so obvious things I may want to achieve?

**Comment by OnlineVagrant** [comment]
Thanks a lot.
