### ISSUE TITLE
Incorrect rendering of multiple - in \texttt

### ISSUE THREAD

**Issue by pzinn** [Khan/KaTeX#1367]
Try
```
\texttt{a---b}
```
In LaTeX the --- will appear as 3 individual "-". In KaTeX they will get merged into a single dash, which shouldn't happen for such a monospace font.

**Comment by edemaine** [comment]
Thanks for spotting. As a temporary work-around, `\verb|a---b|` should work correctly. We should be able to fix the `\texttt` behavior, though I forget how ligatures like this are processed in KaTeX.

**Comment by pzinn** [comment]
another workaround is to type `-{}-{}-{}`. this issue isn't a big deal, but
I thought I'd point out anyway.

**Comment by kevinbarabash** [comment]
Does this occur in any of the other `\textX` commands or is it just a `\texttt` thing?

**Comment by edemaine** [comment]
It's specific to `\texttt`.  Curiously, `\text{\tt --}` works fine.  I'm investigating.

**Comment by pzinn** [comment]
I think it's the normal behavior for other \textX.
