### ISSUE TITLE
Error on converting from text to HTML on server

### ISSUE THREAD

**Issue by kaushik1979** [Khan/KaTeX#138]
When I try converting the following tex to HTML on server, it throws the attached exception. Any ideas what am I doing wrong here?

`
var tex_val = 'x = {-b \pm \sqrt{b^2-4ac} \over 2a';
var html = katex.renderToString(tex_val);
`

Exception - 
`
I20140930-00:35:36.942(-4)? Exception in queued task: ParseError: KaTeX parse error: Expected '}', got '\over' at position 32: {b^2-4ac} \over̲ 2a}
I20140930-00:35:36.943(-4)?     at new h (packages/sashko:katex/katex.min.js:1)
I20140930-00:35:36.943(-4)?     at r.expect (packages/sashko:katex/katex.min.js:1)
I20140930-00:35:36.943(-4)?     at r.parseGroup (packages/sashko:katex/katex.min.js:1)
I20140930-00:35:36.943(-4)?     at r.parseFunction (packages/sashko:katex/katex.min.js:1)
I20140930-00:35:36.944(-4)?     at r.parseImplicitGroup (packages/sashko:katex/katex.min.js:1)
I20140930-00:35:36.944(-4)?     at r.parseAtom (packages/sashko:katex/katex.min.js:1)
I20140930-00:35:36.944(-4)?     at r.handleExpressionBody (packages/sashko:katex/katex.min.js:1)
I20140930-00:35:36.944(-4)?     at r.parseExpression (packages/sashko:katex/katex.min.js:1)
I20140930-00:35:36.944(-4)?     at r.parseInput (packages/sashko:katex/katex.min.js:1)
I20140930-00:35:36.945(-4)?     at r.parse (packages/sashko:katex/katex.min.js:1)
`

**Comment by kaushik1979** [comment]
Is there an update on my request? I will be really thankful if someone can help me get the latest KaTeX code to atmospere.meteor.com.

**Comment by spicyj** [comment]
We've done several KaTeX releases. You'll have to ask the maintainer of the Meteor plugin about the release schedule for that – looks like @stubailo?
