### ISSUE TITLE
No character metrics in 'Main-Regular' for certain unicode characters

### ISSUE THREAD

**Issue by InThisStyle10s6p** [Khan/KaTeX#1384]
Some unicode characters such as "\u2272" (\lesssim) and "\u2a7d" (\leqslant) are rendered in an inappropriate font, and trigger the warning that they do not have character metrics in Main-Regular. I notice that in symbols.js these characters are set not to be substituted, while their flipped counterparts \gtrsim and \geqslant are set to be substituted and are rendered in the correct font with no warnings. I am not sure if this is an error in symbols.js, or if this is an error in the font metrics.

I also get an "unrecognized Unicode character" warning for "\u2218" (\circ), but this is displayed in the correct font (and doesn't trigger the "no character metrics" warning).

**Comment by InThisStyle10s6p** [comment]
I see, thank you. I suppose I thought the Unicode equivalent of `leqslant` would have been supported since the equivalent of `geqslant` seemed to be. I do get that warning about strict mode.

I can always use the backslash commands for unsupported characters, certainly.

**Comment by edemaine** [comment]
@InThisStyle10s6p Agreed, this is likely just an oversight, but @ronkok is the expert.

**Comment by ronkok** [comment]
@InThisStyle10s6p Thanks for the note. You're right; these characters belong in KaTeX core. I'll write up a PR to do that. I see a couple more relations that I can pick up at the same time.

**Comment by ronkok** [comment]
Fixed via #1389.
