### ISSUE TITLE
\overline is not rendered correctly.

### ISSUE THREAD

**Issue by gkutiel** [Khan/KaTeX#1390]
Using katex version 0.10.0-alpha
`katex.render('\\overline{\\text{overline}}', span, {
            throwOnError: false
})`

results in a text without overline.

See [live result](https://tex.ninja/view/#%24%5Coverline%7B%5Ctext%7Boverline%7D%7D%24)

**Comment by ronkok** [comment]
@gkutiel That page is using `katex.js` from release 0.10.0-alpha, as you say, But it is using `katex.css` from release 0.9.0.  So the CSS rule for overline, fraction lines, etc is missing.

Get the CSS updated and you should be fine.

**Comment by ronkok** [comment]
Apparently the suggestion for a CSS upgrade worked. The OP's test page now renders `\overline` correctly. So I'm closing this issue.
