### ISSUE TITLE
Protect `gh-pages` branch

### ISSUE THREAD

**Issue by ylemkimon** [Khan/KaTeX#1412]
It is currently possible to delete or (force) push to the GitHub Pages branch(`gh-pages`), which may be prone to mistakes and attacks.

CC @kevinbarabash

**Comment by ronkok** [comment]
This is a good idea. @kevinbarabash left it unprotected at my request, so that I could update the function support page without a review in the same manner that I had previously updated wiki. 

But I have never done a non-reviewed push to that page, and the reviews have improved the document.

**Comment by kevinbarabash** [comment]
It's protected now.

**Comment by ylemkimon** [comment]
@kevinbarabash Thank you!
