### ISSUE TITLE
Does katex support the Unicode empty set symbol? 

### ISSUE THREAD

**Issue by OnlineVagrant** [Khan/KaTeX#1429]
When I paste in "∅" into my markdown editor(which uses katex release v0.9.0) instead of using \emptyset I get an error.

**Comment by ronkok** [comment]
@OnlineVagrant  KaTeX does not support Unicode character "∅", at least not at this time.

There are some Unicode symbols whose mappings are ambiguous and this is one of them. Should "∅" map to `\emptyset` or `\varnothing`? We're not sure, and we don't want to get it wrong, then have to do a breaking change later. So we have avoided this character, at least for now.

`\emptyset` and `\varnothing` both work, of course.

**Comment by OnlineVagrant** [comment]
Thank you for the reply.
