### ISSUE TITLE
Accessing baseline is not available

### ISSUE THREAD

**Issue by rrandallcainc** [Khan/KaTeX#1432]
Prior to `v0.10.0-beta` there was a class called "strut" which allowed users to access the "baseline" of the katex item. This was necessary when a user wanted to align two (or more) separate latex items side by side as if they were apart of the same item. Think of aligning a fraction or array next to `a^2`.

It appears that is no longer possible, or perhaps there is a new way I am not aware of. I believe the regression was part of: https://github.com/Khan/KaTeX/pull/1307/files

See the following image as an example of what it used to look like with two items side-by-side. The red represents the baseline/strut of the katex items.

<img width="251" alt="screen shot 2018-06-15 at 10 29 05 am" src="https://user-images.githubusercontent.com/16921005/41473358-10004b54-7087-11e8-9846-0721707e83be.png">

I would propose that the "strut" gets re-introduced with a more descriptive name (i.e. "baseline"). Curious on thoughts.

**Comment by edemaine** [comment]
You're right that `bottom` was removed by #1307.  I'm a little confused why you need it, though.  `$\frac{a}{b}$ $a^2$` renders via auto-render as

![image](https://user-images.githubusercontent.com/2218736/41476823-a18c9060-7090-11e8-88b7-f99142cfeca5.png)

Adjacent text renders correctly too.  In other words, the baseline of the KaTeX box is set correctly.  Or is there some other context where you're having trouble?

**Comment by rrandallcainc** [comment]
Think if you had two separate dom elements, each with a katex element inside. Then you wanted to align those elements vertically as if they were in one katex element. 

In other words:
const katexA = `\frac{a}{b}`
const katexB = `\frac{a^2}`

Then vertically position the two as if they were in one element. 

Hope that makes sense.

**Comment by edemaine** [comment]
@rrandallcainc Is there a reason you can't use `vertical-align: baseline`?

**Comment by rrandallcainc** [comment]
I'm working on a canvas renderer, so unfortunately I don't think that's possible. However, I looked at that PR again, and it looks like I can get the baseline distance with some simple math (strut + verticalAlign). Let me implement that, and I will close if that suffices.

**Comment by rrandallcainc** [comment]
@edemaine My above solution worked. Thank you for your quick responses!

**Comment by edemaine** [comment]
Cool! Glad it's still relatively easy to compute.  It makes sense -- the same information is there, just more compact.
