### ISSUE TITLE
Can't access height of KaTeX Expression via BuildTree

### ISSUE THREAD

**Issue by rrandallcainc** [Khan/KaTeX#1433]
I noticed that recently there are now multiple "strut" classes applied in KaTeX. Each one applied to a "group" of text. Previously there was one "root" strut class which contained the height of the KaTeX expression as a whole. 

I'm curious as to:
a) The motivation behind multiple strut classes, and potentially the relevant PR. 
b) If the height of the KaTeX expression is still easily accessible via the build tree.
c) If no to b, are there concerns with adding it back in?

**Here's a before screenshot of the KaTeX expression `a^2+b=c`:** 
<img width="813" alt="screen shot 2018-06-15 at 1 41 37 pm" src="https://user-images.githubusercontent.com/16921005/41482091-67c02d76-70a2-11e8-8cde-1235acebd690.png">

**Here's the after screenshot:**
<img width="943" alt="screen shot 2018-06-15 at 1 44 04 pm" src="https://user-images.githubusercontent.com/16921005/41482102-744ce156-70a2-11e8-8737-54199a7efc7e.png">

**Comment by ronkok** [comment]
@rrandallcainc, I can speak to motivation for two of the new struts. 

1. `\cfrac` adds a strut to ensure extra space in the numerator. This is done to emulate LaTeX, which does the same thing. PR #1392.
2. Another strut is now in the `mathrlap`, `mathllap` series. This one overcomes a rendering bug. These functions employ a span with `position: absolute` nested inside a span with `position: relative`. When elements taller than 1em are lapped, the strut ensures that the HTML bounding box is tall enough to contain the subject matter. PR #1251.

I haven't tried to access overall expression height, but I can see how that would be useful.

**Comment by rrandallcainc** [comment]
@ylemkimon That looks like the right place! What work do you think is involved to provide the height of the overall expression in the build tree?

**Comment by ylemkimon** [comment]
@rrandallcainc Have you tried `katex.__renderToDomTree`?

**Comment by rrandallcainc** [comment]
Alright, so I found a good solution to the problem.

After looking @ the tree structure again (via `katex.__renderToHTMLTree`), I noticed that there's height/depth properties on the root of the tree. I leveraged those, and was able to get all my tests to pass again. I like this solution as opposed to looking @ the strut class anyway. Seems more robust.

Thanks all for your help.

**Comment by edemaine** [comment]
Agreed, good solution. FYI, we use these height/depth values when laying out `\tag`s too.
