### ISSUE TITLE
How to change "G" in the formula used to compute the font size?

### ISSUE THREAD

**Issue by gvgramazio** [Khan/KaTeX#1438]
In your wiki, in the [units section](https://khan.github.io/KaTeX/function-support.html#units), it is written that

>G = 1.21 by default, because KaTeX font-size is normally 1.21 × the surrounding font size. This value can be over-ridden by the CSS of an HTML page. For example, on this page, G = 1.0.

Can you be more explicit in your wiki about how one is supposed to change this value?

**Comment by edemaine** [comment]
It's this CSS in `function-support.html` that changes it:
```css
.katex { font-size: 1em !important; }
```
Compare with the definition in `katex.less`:
```css
font: normal 1.21em KaTeX_Main, Times New Roman, serif;
```
@ronkok Perhaps we should add a note in function-support about how to change *G*.

**Comment by ronkok** [comment]
In the wiki page, I just added a link to https://github.com/Khan/KaTeX/wiki/Font-Options#user-content-font-size. So now that section of the wiki reads:

> G = 1.21 by default, because KaTeX font-size is normally 1.21 × the surrounding font size. This value [can be over-ridden](https://github.com/Khan/KaTeX/wiki/Font-Options#user-content-font-size) by the CSS of an HTML page.

 I'll put the same link into the next version of the HTML function support page.

**Comment by gvgramazio** [comment]
Thanks for the fast reply. After my post I noted that the instruction `.katex { font-size: 1em !important; }` was already posted in your [wiki about font options](https://github.com/Khan/KaTeX/wiki/Font-Options) but it seems that is outdated (the last update is on Jul 2, 2017) and has some broken links (like the ones to `font.less`). Also, it refer to build the project with `make` but there is no makefile so I don't know if I missed something or if it refers to an older version.

Ah, by the way, your suggestion works like a charm.

**Comment by edemaine** [comment]
Updated the broken links; thanks for mentioning those.

**Comment by johnm719** [comment]
I just got katex working by having pandoc do a conversion. I am very new to tex and markup languages. Below is a piece of the HTML file. I ended up putting a \footnotesize and a \normalsize at the beginning and end of every piece of math that katex renders. Is there a way to put a new G (size) in the header section here?

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>Noise Figure One And Two: Friis and IEEE</title>
  <style type="text/css">
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
    var mathElements = document.getElementsByClassName("math");
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") { katex.render(texText.data, mathElements[i], { displayMode: mathElements[i].classList.contains("display"), throwOnError: false } );
    }}});</script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css" />
  
</head>
<body>
<p>Noise factor <span class="math inline">\footnotesize F \normalsize</span> is defined two different noninterchangeable ways. <span class="math inline">\footnotesize F \normalsize</span> is the ratio of the input to output SNR of a 2-port device, or it is a non-linear transformation <span class="math inline">\footnotesize F=1+T_e/290^\circ K \normalsize</span> of an effective noise temperature ...</p>
<h2 id="overview">Overview</h2>
<p> ... noise-figure and noise-factor are related as,</p>
<p><span class="math display">\footnotesize \text{Noise Figure}=NF=10\text{ }{\log }_{10}\left(F\right)\text{ and,} \normalsize</span>
<span class="math display">\footnotesize \text{Noise Factor}=F=\frac{{10}^{NF}}{10}\text{.} \normalsize</span></p>

<h2 id="history-and-derivation-of-first-friis-definition">History and Derivation of First (Friis) Definition</h2>
<p>In 1942,  ....</p>
<h2 id="history-and-walk-through-of-second-ieee-definition">History and Walk Through Of Second (IEEE) Definition</h2>
<p>On June 11, 1959, the IRE published a standard [4] 
<h2 id="references">References</h2>
</body>
</html>

**Comment by edemaine** [comment]
@johnm719 See https://katex.org/docs/font.html for (the new location of) documentation about font size change. Start a new issue if you need any further help.

**Comment by kevinbarabash** [comment]
Have we discussed anywhere the possibility of changing `G` to be 1em by default?
