### ISSUE TITLE
\LaTeX{} spacing issue

### ISSUE THREAD

**Issue by samfearn** [Khan/KaTeX#1442]
Hi,

I'm having a problem with some horizontal spacing while using the \LaTeX{} macro in KaTeX. In case it turns out to be relevant, I'm using KaTeX with the kramdown parser in Jekyll. In my markdown file, I add `$$\LaTeX{}$$.`, as the double dollar is kramdowns in-line math block syntax, and a large space appears between the typeset latex and the full stop. Inspecting the html, I see a span with class `katex-html`, which contains a span with class `base`, which in turn contains a span with classes `mord` and `text`. The `.mord.text` span is the correct (expected) horizontal width, but the containing `base` span then includes a large horizontal space. 

<img width="193" alt="image" src="https://user-images.githubusercontent.com/2106074/41602496-de57eebe-73d2-11e8-8b16-d75d88fe87fa.png">

Any ideas as to what causes this spacing, or more importantly how to remove it?

**Comment by ronkok** [comment]
@samfearn We had a problem with negative spaces in Chrome. That was fixed by PR #1194. If you upgrade from KaTeX release 0.9.0, you should get relief from this problem. Current release is 0.10.0-beta.

**Comment by samfearn** [comment]
Perfect, that fixed it. Sorry, I hadn't realised I wasn't using the current version, turns out 0.9.0 was hard-coded into a config file. FWIW I was using Safari rather than Chrome, so I guess it was a webkit issue rather than Chrome specific?
