### ISSUE TITLE
Katex matrix rendering  error

### ISSUE THREAD

**Issue by yeshuanova** [Khan/KaTeX#1445]
I meet a problem as rendering matrix equation. For example, I use below tex script to render matrix equation

```tex
X=\begin{bmatrix} M_1 \\ \vdots \\ M_n \end{bmatrix}
```

The content in matrix block is aligned to error position

![katex](https://i.imgur.com/7Fd6ovc.png)

But, In MathJax, the rendering result is correct

![mathjax](https://i.imgur.com/emSU0nA.png)

#### Katex configuraiton

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/contrib/auto-render.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
<script>renderMathInElement(document.body);</script>
```

#### MathJax configuration

```html
<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML" async</script>
```

**Comment by mbourne** [comment]
@yeshuanova I tried your equation on the KaTeX demo (https://khan.github.io/KaTeX/) just now, and it works fine:

![image](https://user-images.githubusercontent.com/7541940/41776590-f6b0df90-765a-11e8-9a50-9d5b801a30b3.png)

It's using v0.10.0-beta. I suggest trying that out and see how it goes.

**Comment by edemaine** [comment]
Indeed, there must be something wrong with your configuration; even 0.9.0 should render that fine (though the behavior of `\vdots` changed in 0.10.0-beta to better match LaTeX).  Perhaps post or link to a complete example for us to diagnose.  And try turning off highlightjs to see if that's the issue?

**Comment by yeshuanova** [comment]
I try to use 0.10.0-beta to render same math equation, but it layout is also error status.

<img width="123" alt="katex_0 10 0-beta" src="https://user-images.githubusercontent.com/4150014/41811398-63aeed26-7741-11e8-9adc-661eb5cef1f1.png">

In my case, I generate a statics web site by [Hugo(v0.42.1)](https://gohugo.io/) and use [Mainroad](https://themes.gohugo.io/mainroad/) theme. This theme default using MathJax to render math equation, so I add Katex support to its [mathjax.html](https://github.com/Vimux/Mainroad/blob/master/layouts/partials/mathjax.html) template. The new content is

```html
{{ if and .IsPage (eq (.Param "mathjax") true) }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/contrib/auto-render.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
<script>renderMathInElement(document.body);</script>
{{ end }}
```

Then, I run `hugo server` preview web site and see this error situation. Other equation has no error but only the formatting of **matrix** is off.

Besides, I try to remove the `style.css` support from web site temporarily,   

- Remove `style.css`

<img width="360" alt="katex_pure_html" src="https://user-images.githubusercontent.com/4150014/41812062-2cbe1384-774e-11e8-91a9-07f865513e45.png">

- Mainroad theme using katex

<img width="360" alt="katex_theme_error" src="https://user-images.githubusercontent.com/4150014/41812063-330f1904-774e-11e8-8cd4-d83f314991c2.png">

Maybe the css style cause this layout error, but **MathJax** work OK. I don't know how to modify css configuration to fix this error. Can anybody give me some comments ?

**Comment by edemaine** [comment]
I"m a little confused between what you're calling input and output.  I tried [this HTML file](https://gist.github.com/yeshuanova/ef8108dd3bbd5bfd8ccafb56f1c66b63) you posted, and it loads and displays fine in my browser (Chrome on Windows).  Was this HTML an input or output of hugo?  I'm still worried that there's a step after this HTML file that messes things up, but I suppose it might also be a conflicting style file issue.

**Comment by ronkok** [comment]
@yeshuanova It's a CSS conflict. KaTeX matrices and arrays contain CSS classes to set justification on the array columns. In your example, the relevant KaTeX class rule is:

```
.col-align-c > .vlist-t {
    text-align: center;
}
```

The conflict occurs because the the Hugo Mainroad theme contain this CSS rule:
```
[class*="col-"] {
	float: left;
	margin-left: 2.5%;
	overflow: hidden;
}
```

That asterisk is a wild card, so Hugo is selecting any span with a class name that contains the string "col-". Then the "float-left" rule causes the rendering problem.

I think that if people use wild cards in their CSS, they ought to be careful not to override the CSS of others. We try to prefix all of our CSS rules with "katex ". Maybe in this case Hugo ought to select for "hugo-col-" instead of for every "col-" in the world.

**Comment by edemaine** [comment]
Long ago, @gagern suggested that we change all of our classes to start with `katex-` -- in this case, we'd change `.col-align-c` with `.katex-col-align-c`.  I believe that would fix this particular problem.  Perhaps we finally have motivation to switch?  I'll make this an issue for discussion: #1456.

**Comment by kevinbarabash** [comment]
Wow... I didn't even realize that `[class*="col-"]` was possible.  That's super powerful.

**Comment by yeshuanova** [comment]
@edemaine @ronkok Thanks yours answers for this problem. I am not familiar with CSS, so this case confused me. I replace all `col-` with `mr-col-` in Hugo Mainroad theme and now Katex rendering results is good !!

**Comment by ronkok** [comment]
It would be a good thing to open an issue at [Hugo](https://github.com/gohugoio/hugo). What they did there is not cool.

**Comment by yeshuanova** [comment]
@ronkok I think this is not Hugo's issue. Hugo just generate static web site by template of theme. Hugo's themes is provided by other developers. In this case, this problem is just CSS conflict between [Mainroad](https://github.com/Vimux/Mainroad) themes and Katex. (Mainroad is one of Hugo's theme, but Mainroad doesn't developed by Hugo's team.)

**Comment by ronkok** [comment]
@yeshuanova Thank you for the clarification. You're right, of course.

**Comment by edemaine** [comment]
Thanks @yeshuanova for pointing to the relevant repository; I was having trouble finding it.  I created https://github.com/Vimux/Mainroad/issues/60

**Comment by Vimux** [comment]
Mainroad owner here. I'm sorry for that weird bug. Mainroad doesn't use `col-*` rules at all. So I'll just delete this piece of code.

**Comment by edemaine** [comment]
@Vimux Thanks for the quick response! That was easier than I thought.
