### ISSUE TITLE
Support \operatorname

### ISSUE THREAD

**Issue by sophiebits** [Khan/KaTeX#145]
We should support this so you can do, e.g., `\operatorname{span}` (see #144). Its implementation is subtler than it may appear:

http://tex.stackexchange.com/a/84308/9

**Comment by gagern** [comment]
amsopn is the relevant package here, so `texdoc amsopn` will provide relevant implementation details. `\operatorname` builds on the more elementary `\qopname`.

```tex
\DeclareRobustCommand{\operatorname}{%
    \@ifstar{\qopname\newmcodes@ m}%
            {\qopname\newmcodes@ o}}%
```

> In the interior of the \mathop we need a null object (we choose a zero kern for minimum waste of main mem) in order to guard against the case where `#3` is a single letter; TEX will seize it and center it on the math axis if there is nothing else inside the `\mathop` atom.

```tex
\DeclareRobustCommand{\qopname}[3]{%
    \mathop{#1\kern\z@\operator@font#3}%
    \csname n#2limits@\endcsname}
```

This command `\qopname` is in turn used by many definitions, including the `\limsup` from #111. They tend to have `\relax` in place of `#1`. `#2` would either be `o` for `\nolimits@` which is `\nolimits` but eats any `\limits` that might follow, or it would be `m` for `\nmlimits@` which is `\displaylimits`, i.e. limits above and below in display mode, but to the right in inline mode.

If we can get our macro expansion to support this kind of command, we'd have access to a lot of built-in definitions with almost no additional work.

**Comment by gagern** [comment]
amsopn is the relevant package here, so `texdoc amsopn` will provide relevant implementation details. `\operatorname` builds on the more elementary `\qopname`.

```tex
\DeclareRobustCommand{\operatorname}{%
    \@ifstar{\qopname\newmcodes@ m}%
            {\qopname\newmcodes@ o}}%
```

> In the interior of the \mathop we need a null object (we choose a zero kern for minimum waste of main mem) in order to guard against the case where `#3` is a single letter; TEX will seize it and center it on the math axis if there is nothing else inside the `\mathop` atom.

```tex
\DeclareRobustCommand{\qopname}[3]{%
    \mathop{#1\kern\z@\operator@font#3}%
    \csname n#2limits@\endcsname}
```

This command `\qopname` is in turn used by many definitions, including the `\limsup` from #111. They tend to have `\relax` in place of `#1`. `#2` would either be `o` for `\nolimits@` which is `\nolimits` but eats any `\limits` that might follow, or it would be `m` for `\nmlimits@` which is `\displaylimits`, i.e. limits above and below in display mode, but to the right in inline mode.

If we can get our macro expansion to support this kind of command, we'd have access to a lot of built-in definitions with almost no additional work.

**Comment by ronkok** [comment]
I think the following code would work for `\operatorname`:
````
//////////////////////////////////////////////////////////////////////
// amsopn.dtx

//   \operatorname
// \mathop{#1\kern\z@\operator@font#3}\csname n#2limits@\endcsname}
defineMacro("\\operatorname", "\\mathop{\\text{#1}}\\nolimits");

//////////////////////////////////////////////////////////////////////
````

That macro gets the spacing correct; it avoids centering a single character; it deals with hyphens correctly.
![operatorname](https://user-images.githubusercontent.com/16403058/28554140-a584796a-70ac-11e7-8dd3-add9bf6209d5.PNG)

I'm not really up to creating any Screenshotter tests, but I think the code is ready if someone wants to take it on.

**Comment by ronkok** [comment]
@kevinbarabash, Do you think that this `\operatorname` macro needs Screenshotter tests? If not, then I could just submit the PR.

**Comment by edemaine** [comment]
I think a screenshot test would be useful in particular so it's easy to run `texcmp` to compare.  I'm particularly curious about the use of `\text` -- does `\operator@font` really switch to text mode, or just a roman font?  E.g., what happens to spaces or math-only operators inside `\operatorname`?  (Maybe `\text` should just be `\mathrm`.)

```latex
\def\operator@font{\mathgroup\symoperators}
```

**Comment by ronkok** [comment]
The purpose of the `\text` is to prevent a hyphen from turning into a minus. In other words, I'm using `\text` as a hack to replace `\newmcodes@`. If `\mathrm` were to replace `\text` the screenshot above would render as:
![badhyphen](https://user-images.githubusercontent.com/16403058/28584430-909c5192-7121-11e7-8d33-e7383767ebe0.PNG)

**Comment by edemaine** [comment]
Ah, I see, that makes sense.  What about spaces (do/should they appear in output?) and math-only commands (not sure KaTeX enforces those)?

**Comment by ronkok** [comment]
Well, there are math operators, such as **lim sup**, that do contain a space, so I suppose we want `\operatorname` to enable a space. I really hadn't thought much about math-only commands.

**Comment by spicyj** [comment]
lim sup should be lim\,sup if I remember correctly.

**Comment by ronkok** [comment]
Image from quicklatex.com for `\limsup x` 
![](http://quicklatex.com/cache3/fd//ql_0fa9c319d794fefaabfe93860598cbfd_l3.svg)

**Comment by edemaine** [comment]
What I meant was, "what does LaTeX do with spaces in `\operatorname`?"  Unfortunately, the answer is that `\operatorname` eats spaces, as if in math mode.  So it's not exactly `\text` mode, but partially...

It still might be worth defining `\operatorname` in the way you suggest, as a temporary solution, given that it works in most cases...

**Comment by ronkok** [comment]
I very much agree. This macro is meant to be a quick hack, done in time to be included in the next release. It can improved in several ways.

**Comment by ronkok** [comment]
Last evening, I wrote another version of `\operatorname`. It was a non-macro version written in `functions.js` that passed a string to `groupTypes.op`. That version had an improved MathML output and in that version, I could easily delete the spaces. But `groupTypes.op` will need some remedial work. When I pass a hyphen to it, it returns a minus, complete with operator spacing.

If I can't fix the hyphen problem quickly, is that other version still preferable to this macro?

**Comment by ronkok** [comment]
Okay, new option. This code eats spaces, and it has better MathML output than the macro version. Here's the output:
![newop](https://user-images.githubusercontent.com/16403058/28588936-f3ad8878-7130-11e7-93d4-f1b606872e9d.PNG)
from: `\( \operatorname{g}(z) + 5\operatorname{g}z + \operatorname{gam-ma}(z) + \operatorname{gam ma}(z) \)`

The code in `functions.js` is augmented by:
````
// \operatorname. No limits, not symbols.
defineFunction("\\operatorname", {
    numArgs: 1,
}, function (context, args) {
    const argArray = args[0].value;
    let opName = "\\";
    for (let i = 0; i < argArray.length; i++) {
        opName += argArray[i].value;
    }
    opName = opName.replace(/\\s/g, "");
    return {
        type: "op",
        limits: false,
        symbol: false,
        body: opName,
    };
});
````

In `buildHtml.groupTypes.op`, the line:
````
output.push(buildCommon.mathsym(group.value.body[i], group.mode));
````
is replaced by:
````
output.push(buildCommon.mathsym(group.value.body[i], "text"));
````

I don't do Screenshotter, but anyone is welcome to make this PR.

**Comment by kevinbarabash** [comment]
> I don't do Screenshotter, but anyone is welcome to make this PR.

This makes me sad.  I wish that Screenshotter wasn't a barrier to entry for contributors.  There appears to be a way to run multiple builds on travis with different environment variables.  travis-ci has a way to upload contents of a folder to S3 that I'm investigating.

https://docs.travis-ci.com/user/deployment/s3/

**Comment by kevinbarabash** [comment]
> I’m seeing open-source development for the first time and it seems as though the whole process may be held back because it doesn’t have a really good way to put those teams together.

It can definitely be slower than having a dedicated team of people who are being paid to work on a project.

> If you find a way to make Screenshotter easier, that’s great, but if you want to do something really brilliant, figure out a way to identify and build a team on demand.

My goals are definitely less lofty than figuring building an on demand team.  I'd like to make KaTeX easier to contribute to and hopefully I can generalize things I learn to other open source projects.

**Comment by ronkok** [comment]
@kevinbarabash I have prepared a PR to support `\operatorname`, but I am once again having trouble making a commit. I get the error message:
> Commit failed - exit code 1 received, with output: 'error: cannot spawn .git/hooks/pre-commit: No such file or directory'

I have tried:
* npm install
* npm update
* deleting the file `pre-commit` from the `hooks` folder.
* deleting all the files in the `hooks` folder.

Frustration waxes. Patience wanes. Any suggestions would be welcome.

**Comment by kevinbarabash** [comment]
@ronkok you can skip commit hooks by doing `git commit -n`.  If we can't figure out why this isn't working on windows we may just disable the hooks.  The various checks get run on travis-ci anyways.  The intent was to save when creating or updating a PR by running the checks locally first.  People can do this manually anyways.

I'm surprised that deleting `pre-commit` from the `hooks` folder didn't fix this though.

**Comment by edemaine** [comment]
`git commit -n` will fix short term.  Be sure to delete `pre-commit` from `.git/hooks` not `hooks`.

**Comment by ronkok** [comment]
Success. Thank you once more.

**Comment by janosh** [comment]
Having `operatorname` is great! Are there any plans to add support for `operatorname*` to enable proper limits in display mode?

**Comment by ronkok** [comment]
Yep. I'll turn in a PR sometime in the next few days.

**Comment by janosh** [comment]
Thank you very much! Looking forward to that!
