### ISSUE TITLE
Better MathML support in macros

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#1452]
We've generally moved toward adding features via macros when possible.  This is great because it's easier to add features, and is closer to how LaTeX does everything, so easier to guarantee compatibility.  But it often leads to messier MathML output, essentially because MathML is a bit more semantic than visual.  Two examples are #1400 and #974, though probably most macros should be reviewed on this point.

Here's a proposal for how to fix these, while still getting the macro benefits: add a **function** called `\htmlmathml` (or some other name) that takes two arguments.  The HTML builder for this node type calls the HTML builder on the first argument, while the MathML builder for this node type calls the MathML builder on the second argument.  So both arguments are LaTeX, and it gives you the ability to write the MathML "equivalent" of a fancy macro.  Some examples:

* `\notin` could be redefined to `\htmlmathml{...current definition...}{\mathop{∉}}` (for #1400)
* `\LaTeX` could be redefined to `\htmlmathml{...current definition...}{LaTeX}` (for #974)
* `\pmb` could be defined to `\htmlmathml{...how LaTeX does pmb...}{\mathbf{#1}}` (for #1418)

Originally I thought about how to do this via a macro, but I don't think that's really possible at that point, because macros need to have a single expansion.  Resolving this at function time seems like the right way.  Of course, it's still limited to producing MathML that can be produced by other existing functions, but I don't think we really want raw MathML (or any *ML) as arguments to LaTeX functions.

**Comment by kevinbarabash** [comment]
@edemaine how does this compare with other conditions for checking modes/styles/etc.?

**Comment by edemaine** [comment]
@kevinbarabash See #1454. The code was similar to (and even simpler than) `\mathchoice`.  But there are other challenges...
