### ISSUE TITLE
\newline and \\ dont not work on Gitlab.com

### ISSUE THREAD

**Issue by sw-tracker** [Khan/KaTeX#1460]
Hi,
I am using this on a project on GitLab and \newline does not work. I tried using \\ but it says "An error occurred while rendering KaTeX". How can I create a new line?
Thanks!

**Comment by edemaine** [comment]
Can you confirm which version of KaTeX you:re using? `katex.version` should tell you.

**Comment by sw-tracker** [comment]
How can I check which version https://gitlab.com is using?

**Comment by sw-tracker** [comment]
I am really sorry, I dont know where the JavaScript console in gitlab is. I created a new project in GitLab today, created a readme.md and started using KaTeX formulas in it.

**Comment by ronkok** [comment]
Well, I took a look at [this page](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/user/markdown.md#math). It calls KaTeX from [this static file](https://assets.gitlab-static.net/assets/webpack/vendors~katex.36f58d48.chunk.js). I couldn't get it to respond to `katex.version`.

So I did a couple of searches in the code. It contains `\not`, but it does not contain `\smash`, which means it is from release 0.8.3. The current release is 0.10.0-beta.

**Comment by edemaine** [comment]
@sw-tracker `\\` and `\newline` support was added in v0.10.0-alpha, so that's why it's not working.  Are you familiar with the Gitlab development process -- where to submit issues or pull requests?  If not, I can investigate.

**Comment by ylemkimon** [comment]
@edemaine It is possible submit a merge request, a GitLab equivalent of pull request, for GitLab community edition at https://gitlab.com/gitlab-org/gitlab-ce/merge_requests. The KaTeX version seems to be maintained at [`package.json`](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/package.json#L66).

**Comment by edemaine** [comment]
I created https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/20381

**Comment by kevinbarabash** [comment]
Now if only there was a way to get `KaTeX` support in GitHub.
