### ISSUE TITLE
It's normal in mathjax,but error in katex,why?

### ISSUE THREAD

**Issue by zuwensong** [Khan/KaTeX#1463]
this is mathjax tool:
[
![image](https://user-images.githubusercontent.com/18671875/42145909-b9cf743a-7df6-11e8-81ab-1ada20e84637.png)
](url)

this is katex tool:
![image](https://user-images.githubusercontent.com/18671875/42145932-d7232996-7df6-11e8-92ab-8a65a8216c0f.png)

the formula is:
\left\{ \begin{array}{*{35}{l}}   x+y\le 12,  \\   2x-y\ge 0,  \\   x-2y\le 0,  \end{array} \right.

How should I use KAtex to render this formula？

**Comment by edemaine** [comment]
KaTeX does not support the `*` notation in the array column specifier. See #269. This feature would be relatively easy to add, but for now, you can just use `\begin{array}{l} ` in your example.

**Comment by zuwensong** [comment]
thanks
