### ISSUE TITLE
Add `browserslist`

### ISSUE THREAD

**Issue by ylemkimon** [Khan/KaTeX#1466]
[browserslist](https://github.com/browserslist/browserslist) is used by many libraries to determine target browsers.

**Comment by kevinbarabash** [comment]
So we would define the browsers we want to support and then `browserslist` would then configure different tools we're using like babel, etc.?

**Comment by ylemkimon** [comment]
@kevinbarabash Yes, Babel (babel-preset-env), Autoprefixer (https://github.com/Khan/KaTeX/pull/1615#discussion_r210790077), and lint plugins (eslint-plugin-compat and stylelint-no-unsupported-browser-features) use the `browserslist`.

**Comment by ylemkimon** [comment]
What do you think about
```
ie >= 9
edge >= 15
chrome >= 45
and_chr >= 45
firefox >= 41
and_ff >= 41
safari >= 9
ios_saf >= 9
opera >= 32
and_uc >= 1
```
?
