### ISSUE TITLE
CSS files not published to npm

### ISSUE THREAD

**Issue by iamdanfox** [Khan/KaTeX#148]
I just tried to `require('katex')` but found that important files were missing as a result of these lines in `package.json`:

```
  "files": [
    "katex.js",
    "cli.js",
    "src/"
  ],
```

Currently, the recommended way to consume this library is by downloading a release.  Could we give the `require` approach feature parity by adding in the CSS files?

**Comment by fegemo** [comment]
hi! I've just run into the same need: to include css from a browserified context, using the npm repository. (Just FYI, I'm planning on including the css file using github.com/substack/insert-css)

Then I read #114 and saw the https://github.com/tylerlong/katex-build repo, which I'm going to use. But I'd just like to know if that is the way to go, since neither issues (#114 and #148) are closed.

Thanks for the great lib!!

**Comment by tarjei** [comment]
Hi, just a "me too!" here. I want to import the CSS from the package to be able to include it in my CSS build. Using the CSS from NPM could help me avoid version mismatches between the CSS and the JS.

**Comment by SummerWish** [comment]
+1 css file is missing

**Comment by newjam** [comment]
+1 I've been hoping this get's resolved for some time, without having to 1) introduce another package tool like bower or 2) manually installing the dependency.

**Comment by kevinbarabash** [comment]
We're planning to do a release soon.  From @xymostech's last comment it sounds like we should add the missing build files to the repo *and* then add them to "files" in package.json.  If anyone wants to create a pull request that does this that would be much appreciated.

**Comment by blink1073** [comment]
You don't necessarily have to include the files in the repo, since `make dist` is part of the prepublish script, this should be all you need: 

```diff
diff --git a/package.json b/package.json
index 24b6c69..8aef723 100644
--- a/package.json
+++ b/package.json
@@ -11,7 +11,8 @@
     "katex.js",
     "cli.js",
     "src/",
-    "dist/"
+    "dist/*.*"
+    "dist/**/*.*"
   ],
   "license": "MIT",
   "devDependencies": {
```

We are doing something similar in our project: https://github.com/phosphorjs/phosphor-core/blob/master/package.json

Would you accept this as a PR?

**Comment by blink1073** [comment]
Ah, this may not be necessary at all, it looks like the released version is missing the `dist/` part altogether.

**Comment by kevinbarabash** [comment]
This was fixed a while ago.
