### ISSUE TITLE
Document cli.js

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#1483]
There's no documentation for command-line interface `cli.js` in the README, but we should at least mention it.  At the same time, we should mention how to run it from a git clone, as described in https://github.com/Khan/KaTeX/issues/894#issuecomment-404758297

**Comment by ylemkimon** [comment]
`cli.js` arguments seem to be outdated:
https://github.com/Khan/KaTeX/blob/9783ac1466186504f823076c708c04473f8b6761/cli.js#L53-L59
