### ISSUE TITLE
use yarn instead of npm

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#1490]
`npm` has changed the format of package-lock.json between v5 and v6.  The yarn.lock format is intended to be stable so even if the organization of `node_modules` changes between versions, yarn.lock should remain unchanged.  Also, `yarn install` doesn't update its lock file whereas you have to pass `npm` the `--no-save` option if you want to prevent changes to `package-lock.json.  The downside of this change is that people will have to install yet another package manager.

**Comment by ylemkimon** [comment]
In #1484, `Docusaurus` recommends using yarn, too.
