### ISSUE TITLE
Refactor ParseNode to be plain objects

### ISSUE THREAD

**Issue by marcianx** [Khan/KaTeX#1492]
Original brainstorm in https://github.com/Khan/KaTeX/issues/892.

This will just change `class ParseNode<TYPE>` to `type ParseNode<TYPE> = ...` which would be a union of all possible `ParseNode` types. To avoid needing to do this all at once, will require some type indirection so that we don't refer to the Class version of `ParseNode` all over the place. If that doesn't end up working out, we might have to do an all-at-once style change.

**Comment by marcianx** [comment]
Yea...I think it might have to be done all at once to avoid getting into "this type is not compatible with that type" style errors which provide not additional insight and dramatically progress.

**Comment by kevinbarabash** [comment]
I wonder if we should introduce an `AtomNode` to encapsulate `bin`, `close`, `op` etc. but inside of something that looks like:
```
{|
   type: "atom",
   family: "bin" | "close" | "op" | ...,
   nucleus?: ParseNode,
   subscript?: ParseNode,
   superscript?: ParseNode,
|}
```
This makes our `ParseNode` type more regular and should make flattening `ParseNode`,  getting rid of `value`, easier (I assume this is what was meant by "plain objects").

**Comment by marcianx** [comment]
Oh yes, thanks for the reminder. That should be done first.

**Comment by kevinbarabash** [comment]
> And indeed, I mean plan objects.

Sorry, should've read the original post more carefully.  Changing `class ParseNode<TYPE>` to `type ParseNode<TYPE> = ...` seems pretty safe.

**Comment by marcianx** [comment]
@kevinbarabash It's worth noting that the `"atom"` refactor requires merging the various `src/functiosn/symbols*.js` into one.

**Comment by marcianx** [comment]
Actually, I can keep them in separate files and import them all into a new `symbol.js` that dispatches to these handlers.

**Comment by marcianx** [comment]
@kevinbarabash Before I go further (I've already gone pretty far, actually), do you think there should be separate "atom" types for "mathord", "textord", "op", and "spacing"?
Also, we don't have any HTML/MathML builder handlers for "accent-token" and "op-token". I'm not 100% certain (haven't done a deep audit) how precisely those are handled and whether we should do anything about separating them. Any insights would be appreciated.

**Comment by kevinbarabash** [comment]
I'm cool with either approach.  I don't think there should be any issues with `mathord`, `textord`, or `spacing`.  It seems like `op` (or should I say `op-token`) might be a little cumbersome.  Maybe leave that one out of the initial change.

**Comment by kevinbarabash** [comment]
🎉 Amazing stuff! 🎉
