### ISSUE TITLE
Improve NPM script design

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#1498]
I'm finding the split between the `build` and `dist` NPM scripts to be difficult to work with.  Recall the current definitions:

```js
    "build": "npm run prestart && rimraf build/* && webpack",
    "dist": "npm test && npm run build && npm run dist:copy && npm run dist:zip && npm run dist:dist",
    "dist:copy": "cd build && mkdirp katex && cp -r katex.js katex.min.js katex.css katex.min.css contrib fonts ../README.md katex",
    "dist:zip": "cd build && tar czf katex.tar.gz katex/ && zip -rq katex.zip katex/",
    "dist:dist": "rimraf dist/ && cp -r build/katex/ dist/"
```

In simpler terms:
* `build` makes the `build` subdirectory via webpack
* `dist` runs `test` (which takes a long time), `build`, and three other `dist` scripts:
* `dist:copy` copies the things in the `build` subdirectory into the `build/katex` subdirectory (I guess to flatten the directory structure? but it leaves the old copies!)
* `dist:dist` copies those same files into the `dist` subdirectory
* `dist:zip` makes a zip for the Github release

This is annoying because we also define `"main": "dist/katex.js"`.  So to `require("./")` (as in `cli.js` for example) to get the current code, we need to either
1. `npm run dist`, which takes a long time because of `npm test`, or
2. `npm run build && npm run dist:copy && npm run dist:dist`, which seems rather excessive.

I'd like to suggest that `npm run build` builds the files directly into `dist`, or at least does the equivalent by building into `build`, then copying to `dist` (ideally avoiding the second copy into build), and then deletes `build`.  Then the `dist` script should just be `npm test && npm run build && npm run dist:zip`.

@ylemkimon I think you are the last to tweak the NPM script design.

**Comment by ylemkimon** [comment]
`npm` scripts are messy and may contain redundant steps, as I directly translated the `Makefile`. I also agree having files at three place, `build`, `build/katex`, and 'dist`, is redundant.

I think we can change the build directory to `dist` and do not duplicate files:
https://github.com/Khan/KaTeX/blob/74fb394bb576b6d5096f0c275f8957d99d7cd0e8/webpack.common.js#L66
```js
    "build": "npm run prestart && rimraf dist/* && webpack && cp README.md dist",
    "dist": "npm test && npm run build && npm run dist:zip",
    "dist:zip": "cd dist && tar czf ../katex.tar.gz * && zip -rq ../katex.zip *", // make archives at the root
```

I think having built files at `build` makes more sense, but it would introduce breaking changes to codes directly using `./node_modules/katex/dist/katex.js` or CDN urls `https://cdn.jsdelivr.net/npm/katex@version/dist/katex.min.js`

This also would change archives(`katex.zip` and `katex.tar.gz`) structure, but I'm not sure there is anyone relying on this.
