### ISSUE TITLE
Support unicode in text

### ISSUE THREAD

**Issue by xymostech** [Khan/KaTeX#15]
e.g., "\text{µmol}"

**Comment by kevinb7** [comment]
In addition to supporting single glyphs for Greek letters we should also support as many characters from the latin-1 unicode block as possible.  

As suggested by @gagern in  https://github.com/Khan/KaTeX/issues/260 and by @spicyj in https://github.com/Khan/KaTeX/issues/65 we should use NFD to determine which unicode code points we can fake by composing glyphs, e.g. ```é``` becomes ```"\acute e"```.

Python has a handy built-in module called unicodedata that has function called ```decomposition``` which breaks code points into the base character and combining glyphs (if the decomposition exists).

https://docs.python.org/2/library/unicodedata.html#unicodedata.decomposition

**Comment by schovi** [comment]
Hi,
I am getting error `Unhandled rejection ParseError: KaTeX parse error: Unexpected character: 'ϵ' at position 2: x ̲ϵ R`

Should this pull request fix thi?

**Comment by gagern** [comment]
@schovi that's more like #243, since this one here is specifically about unicode in `\text`.

**Comment by kevinbarabash** [comment]
Apparently ß, æ, Æ, œ, Œ, ø, Ø exist in cmr10, see  http://www.math.union.edu/~dpvc/jsmath/symbols/cmr10.html.  So we should be able to support quite a few European languages without too much work.

**Comment by gagern** [comment]
We don't really have cmr10, do we? I don't see these symbols if I open the fonts (`KaTeX_Main-Regular.ttf` seems the most likely analogon to cmr10, but I looked at `KaTeX_Math-Regular.ttf` as well) in fontforge and set the encoding to glyph order. I doubt they are included.

By the way, what's the story behind the KaTeX fonts? Where did they originally come from, and can the process of creating them be used to port additional symbols from the TeX fonts? Or is this manual work for some font designer, and we should expect trouble if we try to extend the font while preserving the style of the glyphs?

**Comment by xymostech** [comment]
@gagern All of the fonts are generated using the pipline from the MathJax-dev repo. The mappings from LaTeX fonts to KaTeX fonts is here: https://github.com/Khan/MathJax-dev/blob/master/fonts/OTF/TeX/makeFF

So, the font files should never be manually modified, that repository should be modified and the fonts generated from there. There's an easy-ish way to generate the fonts from [this docker file](https://github.com/Khan/KaTeX/tree/master/dockers/MathJaxFonts).

**Comment by kevinbarabash** [comment]
After double checking the .ttfs, no we do not have have those glyphs.  It looks like it will be a little more work than I had originally envisioned.  I think if we fork https://github.com/mathjax/MathJax-dev and update `/blob/master/fonts/OTF/TeX/makeFF` to have the right entries we should be able to build the correct fonts using the docker file.

**Comment by xymostech** [comment]
@kevinbarabash we already have a fork (which I linked to)! Maybe you missed my comment.

**Comment by kevinbarabash** [comment]
@xymostech shame on me for not reading carefully.

**Comment by kevinbarabash** [comment]
I've started on this with https://github.com/Khan/KaTeX/pull/409 which adds support ßæœøÆŒØ.

**Comment by kevinbarabash** [comment]
I've added support for unicode Greek letters in math mode in https://github.com/Khan/KaTeX/pull/410.  Implementing support for `\text{}` will be more difficult b/c we have to find a find that doesn't have italicized glyphs for the lower case characters.

**Comment by kevinbarabash** [comment]
There's a package called `textgreek` which uses the default font `cbgreek`.  There might be some slight differences between the uppercase Greek glyphs from cmr10 being used for math, but there should be that much difference.  http://ctan.math.utah.edu/ctan/tex-archive/macros/latex/contrib/textgreek/textgreek.pdf contains renderings of all three styles of fonts.

I'm a little confused about the fonts though, the `textgreek` package declares the `\textgreekfontmap`  as:
```
\DeclareOption{cbgreek}{%
\renewcommand*{\textgreekfontmap}{%
  {eur/*/*}{U/eur/*/*}
  {phv/*/*}{U/psy/*/*}}}%
\DeclareOption{euler}{%
\renewcommand*{\textgreekfontmap}{%
  {phv/*/*}{U/psy/*/*}
  {*/bx/n}{U/eur/b/n}
  {*/b/n}{U/eur/b/n}
  {*/*/n}{U/eur/m/n}
  {*/*/it}{OML/*/*/*}}}%
\DeclareOption{artemisia}{%
\renewcommand*{\textgreekfontmap}{%
  {eur/*/*}{U/eur/*/*}
  {phv/*/*}{U/psy/*/*}
  {*/b/n}{LGR/artemisia/b/n}
  {*/bx/n}{LGR/artemisia/bx/n}
  {*/*/n}{LGR/artemisia/m/n}
  {*/b/it}{LGR/artemisia/b/it}
  {*/bx/it}{LGR/artemisia/bx/it}
  {*/*/it}{LGR/artemisia/m/it}
  {*/b/sl}{LGR/artemisia/b/sl}
  {*/bx/sl}{LGR/artemisia/bx/sl}
  {*/*/sl}{LGR/artemisia/m/sl}
  {*/*/sc}{LGR/artemisia/m/sc}
  {*/*/sco}{LGR/artemisia/m/sco}}}%
\newcommand*{\textgreekfontmap}{}%
```
Looking at this I would assume that all cbgreek font should start with `eur` or `psy`.  In search for cbgreek fonts on CTAN I found a `cbgreek` folder which contains fonts starting with the letter `g`, see https://www.ctan.org/tex-archive/fonts/greek/cbfonts/fonts/tfm/cbgreek.

**Comment by kevinbarabash** [comment]
http://www.cs.cmu.edu/afs/cs/misc/tex/common/teTeX-1.0/lib/texmf/fonts/source/public/cbgreek/cbgreek.txt contains details on the naming scheme used by the cbgreek fonts in CTAN.  We probably want grmn10.pdb which stands for greek, regular (slant), medium (weight), 10pt.

**Comment by kevinbarabash** [comment]
grmn1000.pdb
<img width="683" alt="screen shot 2015-12-05 at 4 44 56 pm" src="https://cloud.githubusercontent.com/assets/1044413/11611071/bbe10bce-9b6f-11e5-99fd-e208cae19fc8.png">

KaTeX_Main
<img width="637" alt="screen shot 2015-12-05 at 4 45 52 pm" src="https://cloud.githubusercontent.com/assets/1044413/11611070/bbdfde2a-9b6f-11e5-802e-84c0d1fc1d11.png">

**Comment by edemaine** [comment]
I believe we can safely close this old issue. We now support a lot of Unicode, especially in text mode. Any specific missing features should open a new issue.
