### ISSUE TITLE
Screenshotter doesn't run from its own directory

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#1501]
Since #1475, the screenshotter needs to be run from the repository's root directory (via `dockers/Screenshotter/screenshotter.sh`); running `screenshotter.sh` from within `dockers/Screenshotter` results in the following (path) error:

```
    Module build failed: Error: ENOENT: no such file or directory, open 'package.json'
        at Object.fs.openSync (fs.js:646:18)
        at Object.fs.readFileSync (fs.js:551:33)
        at Object.<anonymous> (/afs/csail.mit.edu/u/e/edemaine/Projects/KaTeX/node_modules/babel-plugin-version-inline/lib/index.js:27:39)
```

This might be considered a bug in https://github.com/gnandretta/babel-plugin-version-inline/blob/master/src/index.js#L3, but @ylemkimon suggests in https://github.com/Khan/KaTeX/pull/1496#issuecomment-406930265 that we should just change directories before running webpack.

**Comment by ylemkimon** [comment]
This is probably one of reasons why NPM scripts exist. One can only run them from the root.

**Comment by edemaine** [comment]
You can actually run them anywhere.  But then they magically run as if you were at the root. Very convenient!

**Comment by kevinbarabash** [comment]
TIL
