### ISSUE TITLE
Setup website `Deploy Preview` for the PR

### ISSUE THREAD

**Issue by ylemkimon** [Khan/KaTeX#1510]
netlify.com is a CI for websites, which provides a deploy preview:

> Deploy Preview: Deploy generated from a pull request or merge request, building the site as it would be if the proposed changes were merged. Deploy Previews are published to a URL which has the prefix `deploy-preview` followed by the identifier number of the pull request or merge request. For example, pull request #42 will automatically trigger a Deploy Preview at `deploy-preview-42--yoursitename.netlify.com`.

Websites using docusarus can be deployed using following configuration:

- Build command: `npm run build; cd website; npm install; npm run build;`
- Publish directory: `website/build/KaTeX`

CC @kevinbarabash

**Comment by kevinbarabash** [comment]
Being able to easily check documentation changes before merging would be awesome.

**Comment by kevinbarabash** [comment]
I have it deploying to https://katex.netlify.com/katex/.  I guess I have to set the `CONTEXT` variable to get it to deploy to `https://katex.netlify.com`.

**Comment by kevinbarabash** [comment]
The `CONTEXT` variable is supposed to be set automatically.  I'm going to try the `BASE_URL` environment variable instead.

**Comment by ylemkimon** [comment]
@kevinbarabash Please check the publish directory is `website/build/KaTeX`.

**Comment by kevinbarabash** [comment]
I set it to `website/build`... trying `website/build/KaTeX` now.

**Comment by kevinbarabash** [comment]
That did the trick.  https://katex.netlify.com

**Comment by kevinbarabash** [comment]
I've also turned on branch deploys so this should trigger a deploy next time someone creates a PR or updates one. 🤞

**Comment by kevinbarabash** [comment]
I've updated one of our open PRs.  There's now a netlify checking that shows up.  Clicking on the "details" link goes to the preview site.  In this case it's https://deploy-preview-1485--katex.netlify.com.

<img width="897" alt="screen shot 2018-07-29 at 3 16 52 pm" src="https://user-images.githubusercontent.com/1044413/43369822-77316848-9342-11e8-95a4-ea81e78df124.png">
