### ISSUE TITLE
Built docs should use relative paths

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#1525]
There are a few places where we assume that the docs will live inside `/KaTeX`.  This works when deploying to `khan.github.io` b/c the site lives in `khan.github.io/KaTeX`, but this won't work when deploying to netlify since we want `index.html` to live at `katex.netlify.com` instead of `katex.netlify.com/KaTeX`.

**Comment by edemaine** [comment]
Relatedly, I found it confusing that the docusaurus server run via `npm run start` would not respond to `http://localhost:3000/` (error message `Cannot GET /`), but rather required `http://localhost/KaTeX`.  I expected everything to live at the root level of the test server (which would require relative linking), but barring that, we should at least improve the error message.

**Comment by ylemkimon** [comment]
All urls are generated using `baseUrl` in `siteConfig.js`:
https://github.com/Khan/KaTeX/blob/edede0867dde7250d2aab07bb54312fe256f86f5/website/siteConfig.js#L25

**Comment by edemaine** [comment]
> Doesn't running npm start automatically open a browser with http://localhost:3000/KaTeX?

I'm running `npm start` via ssh into a Linux machine, and in that setting, it doesn't.  (Cool to hear that it does that when running locally though.)

**Comment by edemaine** [comment]
https://github.com/facebook/Docusaurus/issues/448 seems to be @kevinbarabash's original issue.

**Comment by ylemkimon** [comment]
One place where we have to use absolute paths is docs, e.g., in #1520:
> https://github.com/Khan/KaTeX/pull/1520/files#diff-4c5caa110a8eefbc2536f38bd144c8fcR5
```html
<link rel="stylesheet" href="/KaTeX/static/katex.min.css"/><!-- must use absolute path -->
```

I'm not sure how to make it work using the environment variable.

**Comment by edemaine** [comment]
Why does that path have to be absolute? Does `../static/katex.min.css` not work?

**Comment by ylemkimon** [comment]
@edemaine If versioning is enabled(#1521) or translations are enabled, the path may be nested one or two levels further.

**Comment by ylemkimon** [comment]
I've opened #1526.

**Comment by ylemkimon** [comment]
Closing as #1526 is merged and it's an upstream issue.
