### ISSUE TITLE
Support more arrows

### ISSUE THREAD

**Issue by mardukbp** [Khan/KaTeX#153]
`\Leftrightarrow`: It is commonly used for denoting *if and only if*. U+21D4 = '⇔'

`\Rightarrow`: It denotes an implication. U+21D2 = '⇒'

`\nRightarrow` : Does not imply. U+21CF = '⇏'

**Comment by kevinb7** [comment]
These have already been added.  See https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX for details.
