### ISSUE TITLE
CircleCI limit

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#1540]
Should I be concerned about this message?

> Your current usage represents 90% of your Khan Linux plan's limit. Please [upgrade](https://circleci.com/gh/organizations/Khan/settings#containers) in order to ensure no disruption in building.

**Comment by ylemkimon** [comment]
AFAIK, courtesy of CircleCI, they doesn't enforce usage limits (1500 build minutes) on OSS projects.

**Comment by kevinbarabash** [comment]
That's good to know.  I was concerned as well.

**Comment by ylemkimon** [comment]
The warning now exceeds 100%, but there is no problem building. Though another merit of moving to organization repo, as it can build independent from other Khan Academy projects using CircleCI, and vice versa.
