### ISSUE TITLE
请问支持将渲染成公式，转换为LaTeX吗？

### ISSUE THREAD

**Issue by wangchao117** [Khan/KaTeX#1543]
我现在想把渲染成功的公式，在编辑之后，再重新转换为LaTeX编码

**Comment by ylemkimon** [comment]
Duplicate of #454

**Comment by ylemkimon** [comment]
See above issue and `copy-tex` extension for how to get LaTeX source code from the KaTeX element. And if possible, please write the issue in English. Thank you!
