### ISSUE TITLE
Release 0.10.0

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#1544]
I was thinking with all of the changes to our docs that I should probably publish to gh-pages again.  Does anyone have any concerns about that?

**Comment by edemaine** [comment]
Sounds good to me.  There are more changes to come, but lots of good stuff already, so seems like a good time.

**Comment by ylemkimon** [comment]
It’d be best to get #1547 merged before.

**Comment by edemaine** [comment]
I'm now of the opinion that we shouldn't publish to gh-pages except when releasing...

**Comment by ylemkimon** [comment]
I've created a Version 0.11.0 milestone, consisting of mostly documentation tasks.

**Comment by edemaine** [comment]
@ylemkimon That is a nice list of documentation issues, and I'll try to help on them. (Let's self-assign issues that we're working on.) But I wonder if they're all necessary for 0.11.0.  We have an important bugfix (`\neq`) and rather large documentation changes in the ready, and I'd rather we release soon (@kevinbarabash said this weekend) and update as needed.

I added the new issue in #1428 which seems important for releasing, though @kevinbarabash (as admin) could still use the current version which directly publishes to `gh-pages`.

The rest seem like "nice to haves" but shouldn't necessarily block a new release; they could easily be added e.g. in "bug-fix" releases.  Or they could move to a 0.12.0 milestone.  (I may have also misinterpreted the list; maybe you had in mind that this weekend's release is 0.10.0 and these are for the next version?)  What do you and others think?

**Comment by ylemkimon** [comment]
@edemaine I was just listing issues that'd be nice to be resolved until the weekend (soft milestone, to-do list), as it's first time we're releasing new version with the website. They are not meant to block the release 😄

**Comment by ylemkimon** [comment]
BTW, the version number should be `0.10.0`, as last release is `0.10.0-beta`. My mistake.

**Comment by kevinbarabash** [comment]
I thought we were going to `0.11.0` b/c there was a breaking change that was going to be deployed.

**Comment by ylemkimon** [comment]
@kevinbarabash Semantic Versioning states:
> A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. 

But as people may be using `^0.10.0-beta`, I think `0.11.0` makes sense.

**Comment by kevinbarabash** [comment]
I didn't realize that.  Cool, let's go with 0.10.0 in that case.

**Comment by ylemkimon** [comment]
v0.10.0-rc is published! I think we should publish the stable version after we moved to the new domain.

**Comment by ylemkimon** [comment]
I'm thinking of releasing a final RC version, as we upgraded to Babel 7, preferably after latest three bugfix PRs get merged.

**Comment by edemaine** [comment]
The remaining one from this list is #1706. Personally, I think it would be okay if we release 0.10.0 sooner, and push such bug fixes to bug fix releases like 0.10.1, unless they are bugs that were introduced since the last version.

**Comment by edemaine** [comment]
There's something seriously wrong with the currently deployed website:

![image](https://user-images.githubusercontent.com/2218736/46907250-c56ab880-cedd-11e8-86bd-ec961864aabc.png)

Note the non-italic text in the arrays. I don't think the current master branch has this problem, but is worth checking. @ylemkimon do you know what's causing this? (Possibly related to `\mathnormal` font changes.)

**Comment by ylemkimon** [comment]
@edemaine It's because of outdated `katex.css`. It'll not affect the new versioned docs. I'll think of a way to fix it and send a PR.
