### ISSUE TITLE
\neq ligature vs line wrap

### ISSUE THREAD

**Issue by ccorn** [Khan/KaTeX#1546]
Using katex-0.10.0-beta.
When rendering some text with an inline formula `i\neq\frac{d}{2}`, the line got wrapped around where the symbol for `\neq` was supposed to be. Funnily, the `neq` symbol got split into / (at the end of the first line) and = (at the beginning of the following line):

![strange_neq](https://user-images.githubusercontent.com/25403527/43675943-01701cae-97d8-11e8-97f5-2680fb81b68a.png)

When rescaling (Ctrl+)  such that the lines get wrapped elsewhere, the correctly composed `\neq` symbol reappears. Which makes the issue look like a breaking ligature to me.

**Comment by ronkok** [comment]
@ccorn Thank you for the report. We'll fix it in the next release. For now, you can substitute `\mathrel{\neq}`.

Line wraps are still new to KaTeX and we have to get accustomed to using such wraps in the macros we write internally. Looking at the code, I see that `\ne`, `\nottin`, and some others also need such a wrap.

**Comment by ccorn** [comment]
Thanks @ronkok for looking into this. Yes, using `\mathrel` fixes the issue.
