### ISSUE TITLE
`\ne` renders abnormal after `\frac`

### ISSUE THREAD

**Issue by neilsustc** [Khan/KaTeX#1553]
```
R=\frac{1}{k}=\frac{(1+y'^2)^{\frac{3}{2}}}{|y''|}\quad(y''\ne0)

\frac{1}{2}(y''\ne0)
```

![image](https://user-images.githubusercontent.com/7588612/43703361-2cf0f156-998f-11e8-8de7-35d21f8a51be.png)

![image](https://user-images.githubusercontent.com/7588612/43703397-45c3e38c-998f-11e8-872d-e3a5f2a2775f.png)

**Comment by sthoch** [comment]
Also after matrices, `{a \atop b}` and aligned.

As a workaround, `\mathbin{\mathrlap{\,/}{=}}` doesn't have the issue.

**Comment by edemaine** [comment]
This bug is fixed on master, via PR #1497. I guess this is a reminder that we should do a release soon.

**Comment by kevinbarabash** [comment]
I'll do a publish this weekend.

**Comment by JettHu** [comment]
Also while the inequality sign appears at the end of a line.
