### ISSUE TITLE
Chaining \sqrt can be used to break sites

### ISSUE THREAD

**Issue by ctrlcctrlv** [Khan/KaTeX#158]
Consider the following:

```
\Huge \sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
```

Someone on my /b/ board just discovered this, it makes JS take up 100% CPU. I've had to emergency disable KaTeX.

**Comment by jschatz1** [comment]
We are thinking of using your library on our own large site. But are concerned about these security vulnerabilities. What is the status of these?

**Comment by kevinbarabash** [comment]
@jschatz1 no update.  You could count how many times `\sqrt` occurs in the input string, but this doesn't protect against other as of yet unknown vulnerabilities.  I think rendering to a string in a web worker's probably the way to go when dealing with possibly hostile input.

**Comment by kevinbarabash** [comment]
I tried the same `\sqrt` chain with MathJax and it renders it in a fraction of the time.

**Comment by xymostech** [comment]
@kevinbarabash do you mean MathJax renders it faster or KaTeX renders it faster? I find that MathJax renders a low-quality version quickly and then still pegs my CPU to 100% for a while while it renders the high quality version.

**Comment by kevinbarabash** [comment]
@xymostech I pasted the code from the original post into the demo on https://www.mathjax.org/ and it shows up quick and it seems to be the final render.  It's using MathJax's HTML renderer.

**Comment by xymostech** [comment]
I tested putting the giant expression in to the "ask a question" box on math.stackexchange.com/questions/ask, and it indeed also pegs my CPU and freezes the page (they use MathJax, for the record). They seem like a pretty high-profile site, so if they don't have protections against it, I wouldn't be tooo worried.

@kevinbarabash Wow, you're right! Much quicker there for me. Maybe it's a newer version of MathJax? It's speeding up! :)

**Comment by jschatz1** [comment]
@DouweM Anysite that allows user input that has to run something through JS would eventually get pegged. GH uses a checkbox list renderer that I am sure if you added a couple thousand markdown checkboxes you could get GH to crash. The question is _how many_ `sqrt`'s make it crash. If it's 5 that's a problem. If it's 9000 that's probably fine.

**Comment by ylemkimon** [comment]
It seems KaTeX rendering speed and performance have been greatly improved, and the nested `\sqrt`s render instantly. If this is still an issue, please reopen the issue. Thank you!

**Comment by kevinbarabash** [comment]
I tried it for myself just now and was pleasantly surprised.  There is probably still some number of `\sqrt`s that will cause issues, but any large amount of input will causes issues at some point so sanitizing user input is important.  That being said, I don't believe input sanitization is necessarily something KaTeX needs to solve.

**Comment by edemaine** [comment]
@kevinbarabash Welcome back!
