### ISSUE TITLE
Is there a way to pass "metadata" to render into HTML as classes?

### ISSUE THREAD

**Issue by nickgravelyn** [Khan/KaTeX#1582]
I'm working on an application that needs to render mathematical expressions, but we want the resulting equation elements to contain specific classes to enable interactivity around mouse hover and selection (both outside of the context of an input box).

Is there a way to feed data into KaTeX and have it add classes to the generated elements? Alternatively, would this be something that could be added and if so where would one start with attempting to add this into KaTeX?

**Comment by ronkok** [comment]
@nickgravelyn At the moment, the answer to your question is "no", but PR #1437 is pending. It needs a little work before it can be merged, but hopefully it will be available soon.

**Comment by nickgravelyn** [comment]
Wow that's great. Thanks. I'll keep an eye on that PR.
