### ISSUE TITLE
Use flow $ReadOnly and  for immutable objects

### ISSUE THREAD

**Issue by ylemkimon** [Khan/KaTeX#1617]
* freezed objects

https://github.com/Khan/KaTeX/pull/1469#discussion_r209471118 by @kevinbarabash 
> [W]e might also look at replacing `Object.freeze` with `flow`'s `$ReadOnly` and `$ReadOnlyArray` utility types.

* placeholder properties

https://github.com/Khan/KaTeX/pull/1471#issuecomment-404552143 by @kevinbarabash 
> If there are data structures, in this case `docFrag.classes`, that need to be read-only we should look to enforce that with flow.  It has `$ReadOnly` and `$ReadOnlyArray` generic types that help with this.

* parsed tree

https://github.com/Khan/KaTeX/pull/1470#issuecomment-404543789 by @kevinbarabash 
> [W]e might look into to ensure that structures aren't mutated by accident is to use flow to mark objects as read-only. See https://flow.org/en/docs/types/utilities/#toc-readonly for details.

**Comment by kevinbarabash** [comment]
@ylemkimon thanks creating an issue for this.
