### ISSUE TITLE
renderToString only renders inline (Can't use function '$' in math mode)

### ISSUE THREAD

**Issue by laclance** [Khan/KaTeX#1619]
Hi, how can i get renderToString function to not render inline? If I try add $$ and I get `Can't use function '$' in math mode`.

For example I want this 
![screen shot 2018-08-15 at 08 33 43](https://user-images.githubusercontent.com/10835285/44134630-fec7c47a-a065-11e8-926d-fd1c6fe9ecc7.png)
to look like this
![screen shot 2018-08-15 at 08 33 54](https://user-images.githubusercontent.com/10835285/44134632-0194dd82-a066-11e8-8feb-2f85aa82138a.png)

**Comment by ylemkimon** [comment]
You can pass options object as the last argument. Try
```js
katex.renderToString("\\sum_{n=1}^\\infty 2^{-n} = 1", {displayMode: true});
```

**Comment by laclance** [comment]
perfect, thank you very much.
