### ISSUE TITLE
Missing eot, ttf or woff files referenced by fonts.less

### ISSUE THREAD

**Issue by iamdanfox** [Khan/KaTeX#162]
In the [fonts directory](https://github.com/Khan/KaTeX/tree/master/static/fonts), only the `woff2` versions of KaTex_Greek are present.

However, the declaration `.font-face('Greek', bold, normal);` pulls in all versions of this font because [`fonts.less`](https://github.com/Khan/KaTeX/blob/master/static/fonts.less#L2) includes 

    @use-eot: true;
    @use-ttf: true;
    @use-woff: true;
    @use-woff2: true;

Admittedly, this is quite a minor problem (the stylesheet still works in most browsers) but it's upsetting webpack a little bit and seems quite easy to fix :)

**Comment by W4RH4WK** [comment]
just had a similar issue with pandoc using `--self-contained` removing the greek font entries solved the problem.

@iamdanfox commit looks good to me

**Comment by spicyj** [comment]
Fixed by #184.
