### ISSUE TITLE
Several 404s

### ISSUE THREAD

**Issue by mbourne** [Khan/KaTeX#1625]
I realise the documentation is in development, but there are several broken things currently published.

On this page: https://khan.github.io/KaTeX/, the comparison gif, https://khan.github.io/img/katex-comparison.gif returns 404.

On several of the inner pages, the "docs/en/" and favicon links are not working. For example:

https://khan.github.io/KaTeX/docs/api.html
	https://khan.github.io/KaTeX/https://khan.github.io/favicon.ico
	  \_____ error code: 404 (not found)
	https://khan.github.io/KaTeX/docs/en/node.html
	  \_____ error code: 404 (not found)
	https://khan.github.io/KaTeX/docs/en/api.html
	  \_____ error code: 404 (not found)
	https://khan.github.io/KaTeX/docs/en/options.html
	  \_____ error code: 404 (not found)
	https://khan.github.io/KaTeX/docs/en/support.html
	  \_____ error code: 404 (not found)

**Comment by ylemkimon** [comment]
The new website is deployed!

**Comment by mbourne** [comment]
Not a biggie, but may as well mention it. In the `/doc/` and `/en/` pages, this still gives 404:
&lt;link rel="shortcut icon" href="/KaTeX/https://khan.github.io/favicon.ico"/&gt;
