### ISSUE TITLE
`katex.renderToString` does not render spaces.

### ISSUE THREAD

**Issue by nijynot** [Khan/KaTeX#1626]
To reproduce, `console.log(katex.renderToString('45\space a'));`.
It returns
```
<span class="katex"><span class="katex-mathml">
<math><semantics><mrow><mn>45</mn><mi>s</mi><mi>p</mi><mi>a</mi><mi>c</mi><mi>e</mi><mi>a</mi></mrow><annotation encoding="application/x-tex">45space a</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8388800000000001em;vertical-align:-0.19444em;"></span><span class="mord">4</span><span class="mord">5</span><span class="mord mathit">s</span><span class="mord mathit">p</span><span class="mord mathit">a</span><span class="mord mathit">c</span><span class="mord mathit">e</span><span class="mord mathit">a</span></span></span>
</span>
```
which becomes "45spacea", and not "45 a".

On latest `katex` release `0.10.0-beta`.

**Comment by ccorn** [comment]
Not a bug. The [Escaping rule](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Escaping_characters) dictates such behavior. `\s` is not a special escape, so the backslash just robs the `s` from any special meaning (which it hasn't). The backslash gets absorbed in the process. Thus `katex.renderToString` is called with the argument `"45space a"`. Try `"45\\space a"` to get an actual backslash into the TeX math string.

**Comment by edemaine** [comment]
You can also try String.raw; see https://khan.github.io/KaTeX/docs/api.html#in-browser-rendering

**Comment by nijynot** [comment]
Got it. Thanks for pointing it out. :-)
