### ISSUE TITLE
Using KaTeX Fonts

### ISSUE THREAD

**Issue by ry-randall** [Khan/KaTeX#1627]
Is there any sort of licensing required if I wanted to use the KaTeX fonts in another project?

**Comment by ylemkimon** [comment]
The fonts source is licensed under [MIT License](https://github.com/KaTeX/katex-fonts/blob/master/LICENSE) and fonts (binary) are licensed under [SIL OFL 1.1](https://github.com/KaTeX/katex-fonts/blob/a09ea0bbe0c6a7dd18118207449654f929388eba/src/fonts/OTF/TeX/lib/Space.ttx#L132-L137).

**Comment by kevinbarabash** [comment]
Would it make sense to publish an `npm` package of fonts?

**Comment by ry-randall** [comment]
@kevinbarabash I would actually love that.

**Comment by kevinbarabash** [comment]
@ry-randall we'll probably be doing that as part of https://github.com/Khan/KaTeX/issues/1411.

**Comment by edemaine** [comment]
@ry-randall Presumably you can use the existing `katex` npm package for now?

**Comment by ry-randall** [comment]
@edemaine Yup, I can do that for now....not a problem. A trimmed down package with just the fonts would be nice in the future!

**Comment by ylemkimon** [comment]
Or you can use `Khan/katex-fonts`, e.g., `npm install Khan/katex-fonts#a09ea0bbe0c6a7dd18118207449654f929388eba`.
