### ISSUE TITLE
How to auto-render in react?

### ISSUE THREAD

**Issue by houx15** [Khan/KaTeX#1649]
In react, the doms may be refreshed, and the value may change.
But by using auto-render, I can only render once

**Comment by kevinbarabash** [comment]
If you're using React it's probably more appropriate to use one of the React components listed on https://khan.github.io/KaTeX/docs/libs.html#react.

**Comment by csbarnes** [comment]
@kevinbarabash I have a similar problem of needing to render katex inside a block of markdown text. Unfortunately both the react libraries don't cover this use case. I have a work around but it seems somewhat hacky...

@houx15 This is how I got auto-render to work with my app:

```js
import React from 'react';
import PropTypes from 'prop-types';

import Markdown from 'markdown-to-jsx';
import renderMathInElement from 'katex/dist/contrib/auto-render';

const MarkdownViewer = ({ content }) => {
  const ref = React.useRef(null);

  React.useEffect(() => {
    if (ref.current) {
      renderMathInElement(ref.current, {
        delimiters: [
          { left: '$$', right: '$$', display: true },
          { left: '\\[', right: '\\]', display: true },
          { left: '$', right: '$', display: false },
          { left: '\\(', right: '\\)', display: false },
        ],
      });
    }
  }, [ref.current]);

  return (
    <div ref={ref}>
      <Markdown>{content}</Markdown>
    </div>
  );
};

MarkdownViewer.propTypes = {
  content: PropTypes.string.isRequired,
};

MarkdownViewer.defaultProps = {};
```

**Comment by kevinbarabash** [comment]
@csbarnes KaTeX has a `renderToString` function, see https://katex.org/docs/api.html#server-side-rendering-or-rendering-to-a-string.  You could try to adapt some of the code from the auto-render extension to find all the math blocks within `content` and then use `renderToString` to replace them with the actual math.  I'm not sure if the `Markdown` component will mess things up though.

**Comment by kevinbarabash** [comment]
You might also want to check out https://levelup.gitconnected.com/adding-katex-and-markdown-in-react-7b70694004ef.

**Comment by csbarnes** [comment]
Thanks for the reply, I'll definitely look into it.
