### ISSUE TITLE
Production Build: Failed to minify the code

### ISSUE THREAD

**Issue by frogg** [Khan/KaTeX#1652]
I am using KaTeX in a react JS project.
On my computer running `yarn start` (`react-scripts start`) for running the debug build works fine.

But when I want to 'compile' it for the use in production I always get an error message from Katex:
`npm run build`:

```bash
yarn run v1.7.0
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/katex/dist/katex.mjs:5

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
```

This doesn't really make sense to me because obviously `katex.mjs` is already minified. Anyone has an idea how to fix this? Thanks!

**Comment by ylemkimon** [comment]
@frogg @dlrenz @RobZuazua @cocokiri We have published v0.10.0-rc.1, which hopefully fixes the issue. Please try it and let me know. I apologize for inconveniences.

**Comment by ylemkimon** [comment]
I'll do some kinds of post-mortem when I have time.

**Comment by frogg** [comment]
😱 wow 💯 thanks  🚀 a 🎉 lot 👏 that 💪 was 👍 quick! 🙌

I just ran `yarn build` successfully without any problems.

**Comment by kevinbarabash** [comment]
@frogg thanks for checking the new release and reporting back.
