### ISSUE TITLE
Fix \textcolor and \color to match what the color package does

### ISSUE THREAD

**Issue by jessebett** [Khan/KaTeX#1657]
I'm lost as to how I'm supposed to programmatically use custom colours. Especially since `\definecolor` is not supported.

To get around this I tried using `\newcommand` to define a new colour. 
`\newcommand{\myblue}[1]{\textcolor{#0074D9}{#1}}` but this is not valid because the `#` symbol needed for `textcolor` is parsed as an invalid number for the argument `#`. Any ideas on how to get around this?

Further, does `\newcommand` not make the command global? How do I have any new colours defined for the entire page?

**Comment by kevinbarabash** [comment]
I'm not sure if it's possible to work around this issue with `\newcommand`.  Since https://github.com/Khan/KaTeX/issues/750 is already requesting support for `\definecolor` I'm going to close this as a duplicate.

**Comment by kevinbarabash** [comment]
The `HTML` color model from https://en.wikibooks.org/wiki/LaTeX/Colors#Defining_new_colors shows that `\definecolor` using a hex color without the leading `#`.  It looks like `\color` and `\textcolor` require the user to specify the color model unless using a defined color so our current implementation of these commands appears to be incorrect.

**Comment by kevinbarabash** [comment]
`color` package reference: http://ctan.mirror.rafal.ca/macros/latex/required/graphics/color.pdf

**Comment by kevinbarabash** [comment]
I skimmed the PDF but it doesn't make mention of all of the color models listed on https://en.wikibooks.org/wiki/LaTeX/Colors.  I think it's fine to support more color models but it should be done in a way that's compatible with the `color` package.

**Comment by edemaine** [comment]
@jessebett You can fix the `#` issue as follows:

```latex
\newcommand{\myblue}[1]{\textcolor{##0074D9}{#1}}
```

(This is how `#`s get escaped in TeX macros.)

If you want a global definition, you can use `\gdef`:

```latex
\gdef\myblue#1{\textcolor{##0074D9}{#1}}
```

(Unfortunately, LaTeX has no global version of `\newcommand`.)

Both of these are generic advice about LaTeX not specific to KaTeX. Specific to KaTeX, there's another way to specify global macros: you can specify the macro in the `macros` option when calling KaTeX.

I agree that we should probably deprecate the `#` if it's not there in LaTeX. KaTeX's color support has always been HTML focused, and we should instead bring it into alignment with LaTeX.

**Comment by jessebett** [comment]
@edemaine your suggestion throws an error:

```
$$
\gdef\niceblue#1{\textcolor{##0074D9}{#1}}
\gdef\w{\niceblue{w}}
$$

$$
\w
$$
```

This throws error `KaTeX auto-render: Failed to parse `\w` with ParseError: "KaTeX parse error: Expected 'EOF', got '\w' at position 1: \̲w̲"`

**Comment by jessebett** [comment]
I believe it's autorender? It is rendered at the end with a call to
```
<div class="eq-grid">
  <div style="grid-row: 1; grid-column: 1; width: 40px;"></div>
  <div style="grid-row: 1; grid-column: 3;"><d-math>KL^E_D(X) ~~\leq~~ KL^E_D(X, Z)</d-math></div>
  <figcaption style="grid-row: 2; grid-column: 3; max-width:320px;">
    The KL divergence is a <b>upper-bound</b> on the errors of $p_D(X)$,
    optimizing the log-likelihood of the data.
  </figcaption>
</div>
```

**Comment by jessebett** [comment]
I believe it's autorender. It is rendered with  a call at the end to `renderMathInElement`

**Comment by edemaine** [comment]
@jessebett Could you link to a complete example of the HTML to diagnose?

**Comment by edemaine** [comment]
@ylemkimon The title of this issue is still open. Given that most of the thread was about other things, fine to move this to another issue. But we should do that.
