### ISSUE TITLE
Publish non-transpiled ECMAScript module as separate package

### ISSUE THREAD

**Issue by ylemkimon** [Khan/KaTeX#1659]
Currently, there is no field in `package.json` that can point to non-transpiled ESM, while supporting bundlers like webpack and Rollup or transpilers like Babel.

The best way to provide non-transpiled ESM seems to be providing it in the separate package, e.g., `katex-es`.

**Comment by kevinbarabash** [comment]
I'm pretty sure that Rollup can handle non-transpired ESM modules using https://github.com/rollup/rollup-plugin-node-resolve.

**Comment by ylemkimon** [comment]
@kevinbarabash But to use it in old environments with less ES6 support, it needs to be transpiled to ES5. However, by default, `babel-loader` (webpack) or `rollup-plugin-babel` (Rollup) doesn't transpile them.

**Comment by ry-randall** [comment]
AFAIK webpack recognizes the [module](https://webpack.js.org/guides/author-libraries/#final-steps) field (a [proposal](https://github.com/rollup/rollup/wiki/pkg.module)) in the package.json.

**Comment by ylemkimon** [comment]
Rather than publishing a new package, I think we can use `import katex from 'katex/dist/katex'`. I will make a documentation PR.
