### ISSUE TITLE
katex pre-release tarball/zip missing katex topdir level

### ISSUE THREAD

**Issue by ccorn** [Khan/KaTeX#1664]
Since `v0.10.0-rc`, the released `katex.tar.gz` and `katex.zip` no longer include the single `katex` topdir level. Which means that users using the previous layout now have to provide the `katex` subdir for themselves when extracting. Is this intended?
I was not aware of this, therefore did the usual

    cd assets
    tar xzf path/to/katex.tar.gz

and then had to use careful cleanup operations like

    tar tzf path/to/katex.tar.gz | while read f; do rm -f "$f"; done
    rmdir contrib fonts

Before re-issuing the corrected commands

    mkdir katex
    tar xzf path/to/katex.tar.gz -C katex

In my experience, most open-source projects use a single top-level directory. So if this change has been accidental, I'd like to see it reverted. If not, I'd like a prominent note in the changes list on the release page.

**Comment by edemaine** [comment]
This was a change in #1500 when we cleaned up our build scripts.  There we speculated that this change wouldn't be a big deal, but if it is important, I imagine we can fix it in one of those two ways.

**Comment by ccorn** [comment]
MacOS has commands `gnutar` (aliased to `tar`) and `bsdtar`. Even my old Darwin 9 version of gnutar (1.29) supports `--transform`. In particular, `--transform=s,^,katex/,` seems to do the trick.

**Comment by edemaine** [comment]
@ccorn Does that work with `tar` on MacOS? (`gnutar` doesn't work on Linux.)

**Comment by ccorn** [comment]
Upps, correction: The `gnutar` (and `tar`) version I gave was the MacPorts version. The built-in `/usr/bin/{gnu,}tar` (v1.15.1 on darwin9) does not support `--transform`, but newer OS versions might do; and there are always MacPorts, HomeBrew, Fink...

**Comment by ccorn** [comment]
Easiest might be a temporary rename without `cd`. Requires nothing special and also works with `zip`:

    "dist:zip": "(trap 'mv katex dist' EXIT; set -e; test ! -d katex; mv dist katex; tar czf katex.tar.gz katex; rm -f katex.zip; zip -rq katex.zip katex)"

**Comment by ccorn** [comment]
Easiest might be a temporary rename without `cd`.
Requires nothing special and also works with `zip`:

    "dist:zip": "(set -e; test ! -d katex; trap 'mv katex dist' EXIT; mv dist katex; tar czf katex.tar.gz katex; rm -f katex.zip; zip -rq katex.zip katex)"

**Comment by ylemkimon** [comment]
I've add a breaking changes section to https://github.com/Khan/KaTeX/releases/tag/v0.10.0-rc. How much do you think this will affect users? Are there tools depending on this behavior?

**Comment by ccorn** [comment]
As to the effects:
* Packagers will have to adapt their specfiles / Portfiles / recipes / howver they call them.
* Whoever has unpacked directly into an `assets` directory will have to clean up carefully and create an empty `katex` subdirectory before unpacking again.
  * If he happened to have another `README.md` in there: It's overwritten now. That's bad.
* Every user will be reminded of the rule not to make unwarranted assumptions about the contents of archives.

**Comment by ccorn** [comment]
Resolved by #1665.
