### ISSUE TITLE
Can KaTeX do anything with.. 

### ISSUE THREAD

**Issue by stewils76** [Khan/KaTeX#1672]
Sorry if this isn't the place for this suggestion but could katex do anything with this 
https://github.com/pyramation/LaTeX2JS/
To bring interactive graphs to katex? 
Thanks for your time. 
Feel free to ignore.

**Comment by kevinbarabash** [comment]
Currently LaTeX2JS uses MathJax.  If a person wanted to they could replace MathJax with KaTeX but some work would be involved.  You could submit a PR to LaTeX2JS and see if the maintainer accepts it.

**Comment by kevinbarabash** [comment]
@stewils76 we want to keep KaTeX focused on rendering math.  Feel free to incorporate it into other software to add math rendering to interactive graphs.

**Comment by edemaine** [comment]
@alihammad-gist As stated above, KaTeX is about rendering math, not plotting functions/graphs. KaTeX could be used to add math to plots, but that's not within scope of this project.
