### ISSUE TITLE
\begingroup messes up spacing

### ISSUE THREAD

**Issue by pzinn** [Khan/KaTeX#1679]
this is a standard issue in latex, see e.g.
https://tex.stackexchange.com/questions/85033/colored-symbols/85035#85035
try the following
```
\begin{gathered}
U \oplus V\\
U {\color{red}\oplus} V\\
U\begingroup\color{red}\oplus\endgroup V
\end{gathered}
```
in LaTeX vs KaTeX. in LaTeX the 2nd has wrong spacing, but the third line is okay; in KaTeX both 2nd and 3rd lines are incorrect.

**Comment by edemaine** [comment]
What's really going on here is that we don't properly implement `\begingroup ... \endgroup`. They apparently behave "transparently" in LaTeX, while we currently define them as equivalent to `\bgroup` and `\egroup`. 

See https://tex.stackexchange.com/questions/1930/when-should-one-use-begingroup-instead-of-bgroup although the TeXbook may be more informative.
