### ISSUE TITLE
Error: <path> attribute d: Expected path command, "M400000 80\u003C/br\u003EH435C64 80 …"

### ISSUE THREAD

**Issue by chenfengyanyu** [Khan/KaTeX#1696]
我的 katex 版本是 0.10.0-rc.1，这是升级之后抛出的异常。页面渲染的圆弧和向量也有问题，显示异常。please help me, thank you very much

**Comment by kevinbarabash** [comment]
From translate.google.com:
> My katex version is 0.10.0-rc.1, which is an exception thrown after the upgrade. There are also problems with the arc and vector rendered by the page, showing anomalies.

@chenfengyanyu thanks for the report.  Can you provide a link to a webpage that shows this error or reproduce the error on katex.org's demo page or in a jsfiddle or similar service?

**Comment by edemaine** [comment]
It looks like a newline in an SVG is somehow getting translated to a `<br>`. Are there newlines in our SVGs?

**Comment by ylemkimon** [comment]
@edemaine 
> Are there newlines in our SVGs?

Yes.

---

It seems the editor or framework you are using is converting newlines to `<br>` tag.

**Comment by edemaine** [comment]
I wonder if we should remove the newlines in (or otherwise minify) the SVGs when outputting them, to avoid this issue.

**Comment by ronkok** [comment]
I put newlines into the SVG paths just to get them to pass lint tests. How about adding `/* eslint-disable */` as necessary and removing the newlines? This would affect all of file `svgGeometry.js` and [one location](https://github.com/Khan/KaTeX/blob/master/src/delimiter.js#L389) in `delimiter.js`

**Comment by kevinbarabash** [comment]
From translate.google.com
> Sorry, after reading your comments, it is because I added the `</br>` tag to the katex string, which affects the parsing rendering of katex.
My approach is to remove the `</br>` tag before it is passed in. Thanks~

@chenfengyanyu cool.  I'm glad it's working for you now.
