### ISSUE TITLE
Local build issues

### ISSUE THREAD

**Issue by ronkok** [Khan/KaTeX#1704]
I find myself unable to create a local build. When I run `yarn install` and `yarn start`, I get:

```
yarn run v1.9.4
$ node check-node-version.js && yarn check && node src/unicodeMake.js
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
error "style-loader" is wrong version: expected "0.23.0", got "0.22.0"
error "istanbul-api#compare-versions" is wrong version: expected "3.3.1", got "3.3.0"
error Found 2 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And I get similar messages when I try `yarn build`.

Any suggestions would be welcome. I am running on Windows, if that makes any difference.

**Comment by edemaine** [comment]
Can you try `npm update -g yarn` to update yarn, then run `yarn` again?

**Comment by ronkok** [comment]
@edemaine I tried your suggestion. (Thanks for trying!) But I get the same results.  Would it help if I removed `package-lock.json`?

**Comment by edemaine** [comment]
@ronkok `yarn` doesn't use `package-lock.json`; it uses `yarn.lock`.  (You're not using `npm install` anymore are you? Probably `package-lock.json` is just leftover from pre-yarn times?)  I checked and the `style-loader` version is correct (0.23.0) in `yarn.lock` and `package.json` on master -- maybe check on your local copy too?  @ylemkimon Any ideas?

**Comment by edemaine** [comment]
@ronkok One other idea: try deleting the `node_packages` directory and running `yarn install` again.  A bit of a big hammer, but that should fix it.

**Comment by ronkok** [comment]
@edemaine Thanks! Your suggestion of deleting the `node_modules` directory worked.
