### ISSUE TITLE
How to export macro in rendering

### ISSUE THREAD

**Issue by hzhangxyz** [Khan/KaTeX#1722]
`katex.renderToString` have parameter `macros` to input some macros

is there some method to output macros defined in `katex.renderToString`'s input?

**Comment by edemaine** [comment]
Yes, macros defined via `\gdef` are output to the same `macros` object.  For example:
```js
let macros = {};
katex.renderToString("\\gdef\\foo{123}", {macros});
//macros.foo is now set
```
See https://katex.org/docs/options.html, in particular:
> *This object will be modified* if the LaTeX code defines its own macros via \gdef, which enables consecutive calls to KaTeX to share state.
