### ISSUE TITLE
Giving back

### ISSUE THREAD

**Issue by ry-randall** [Khan/KaTeX#1724]
Hi,

Just wanted to start off by saying thank you for all the hard work that has gone into this repo. It's obvious that you truly care.

In an effort to give back, I wanted to open source a canvas rendering implementation that I was working on. You can find it here: https://github.com/CurriculumAssociates/canvas-latex

It currently supports canvas libraries like: createjs and pixijs....I'd love to see a 3d rendering implementation. Perhaps AR math?

It is in its early stages, and I will be introducing a build process shortly. There are some unsupported features still, so feel free to contribute if you're interested! Also feel free to add other rendering implementations. I'll ensure it gets properly maintained.

Edit: Perhaps in the future we can consolidate with KaTeX. Maybe when the IR gets implemented.

**Comment by kevinbarabash** [comment]
This is super cool!  How did you deal with stretchy characters which are specified as SVG paths?  What about glyphs with no horizontal metrics?

**Comment by ry-randall** [comment]
For the short term, I'm using a library called canvg to convert svg -> canvas drawing commands.

For the longer term, I would like to leverage Path2D which is natively supported in browsers. Unfortunately, Edge doesn't support the addPath method. While there are pollyfills that exist, they don't work 100%. I noticed several breaking screenshots after attempting to go this route.

**Comment by kevinbarabash** [comment]
Path2D looks pretty cool.  That's too bad Edge doesn't support it.  It might be polyfillable though with a little bit of work.
