### ISSUE TITLE
the $\mathring{U}(x_0)$ does not work in VuePress

### ISSUE THREAD

**Issue by 330wuyanzu** [Khan/KaTeX#1725]
and I also tried \r,  \text, How I can fix it?

**Comment by kevinbarabash** [comment]
My guess is that VuePress needs to update to the latest version of KaTeX since `\mathring{U}(x_0)` works just fine on katex.org.

**Comment by 330wuyanzu** [comment]
> My guess is that VuePress needs to update to the latest version of KaTeX since `\mathring{U}(x_0)` works just fine on katex.org.

thanks

**Comment by 330wuyanzu** [comment]
> Yes, `\r` and `\mathring` are a relatively recent feature addition (0.9.0). You may be able to check what version you're using by typing `katex.version` in the Javascript console.

thanks
