### ISSUE TITLE
Lines are overlapping

### ISSUE THREAD

**Issue by OnlineVagrant** [Khan/KaTeX#1731]
Lines are overlapping when I try to make centred lines align at the  beginning.
![capture](https://user-images.githubusercontent.com/39413259/46253914-151c9f00-c45d-11e8-9c71-8d241b039a98.JPG)

**Comment by ylemkimon** [comment]
Could you give a full reproducible example?

**Comment by OnlineVagrant** [comment]
Never mind. I figured it out. :)
