### ISSUE TITLE
I am having trouble aligning equations. How do I do it correctly?

### ISSUE THREAD

**Issue by OnlineVagrant** [Khan/KaTeX#1732]
What I am trying to do
![1](https://user-images.githubusercontent.com/39413259/46297362-da0c8f80-c572-11e8-9251-f6857d6bdbfa.JPG)

What I have tried 

![2](https://user-images.githubusercontent.com/39413259/46297381-e1cc3400-c572-11e8-9c25-23dfadbb0076.JPG)
 
as well as 
![3](https://user-images.githubusercontent.com/39413259/46297391-e85aab80-c572-11e8-9e52-4a10847dd96c.JPG)

Code
```
 <div style="padding: 0.75em; border: 2px solid MediumSeaGreen; width: 600px;">

If $X ∼ B(n,p)$ then,
    
$$\begin{alignedat}{3}
        
    &P(X=x)={n \choose x}P^x(1-p)^{(n-x)}\\
    &E(X)=np\\
    &Var(X)=np(1-p)

\end{alignedat}$$

</div><br>
```

**Comment by ccorn** [comment]
There are a [lot of such threads on TeX.SE](https://tex.stackexchange.com/questions/408105) (which I'd recommend for such questions). Basically, use the `{aligned}` environment, and if you want to align at `=`, write `&=`. Every `&` in a row begins a new column and switches from right-alignment to left-alignment or vice versa.

**Comment by edemaine** [comment]
@OnlineVagrant The math part of the source code you gave works fine on the KaTeX demo page:

![image](https://user-images.githubusercontent.com/2218736/46353074-4944bb00-c629-11e8-88e1-a113c39baebb.png)

The fact that you're getting a line break in the middle of an aligned environment suggests that your not including or somehow changing the `display` of some KaTeX classes, from `inline-block` to `static`. In what context are you using KaTeX?

**Comment by OnlineVagrant** [comment]
@edemaine What do you mean by what Contest are you using? I'm using a software call bostnote that uses katex to renders maths

**Comment by kevinbarabash** [comment]
It sounds like there's maybe some issue with how bootsnote is setting up KaTeX.  @OnlineVagrant have you opened issue with them?

**Comment by OnlineVagrant** [comment]
No I have not. I thought it was a katex issue. Also, I wouldn't even know how to beginning explaining the problem.
