### ISSUE TITLE
katex render different mathjax, lack of escape symbols

### ISSUE THREAD

**Issue by yangjiaronga** [Khan/KaTeX#1735]
katex render different mathjax
source:  `\texttt{^ 3 1}`
mathjax render:
![image](https://user-images.githubusercontent.com/19570959/46545674-89da5800-c8f9-11e8-91fc-1b8739f6a519.png)
katex render:
![image](https://user-images.githubusercontent.com/19570959/46545709-a2e30900-c8f9-11e8-8ef1-2c8c66be4ecc.png)
but katex add an escape symbols render:
![image](https://user-images.githubusercontent.com/19570959/46545734-bc845080-c8f9-11e8-816f-525a386bc7aa.png)

**Comment by JZQT** [comment]
It looks like you can't smoothly migrate from MathJax to KaTex.

**Comment by JZQT** [comment]
Is that a bug?

**Comment by edemaine** [comment]
This is the same issue as #1676. Basically, KaTeX actually implements `\text` like LaTeX, whereas MathJax just treated as a kind of verbatim environment. I view this as a bug in MathJax, though I don't know whether it could be fixed. There are some workarounds discussed in #1676.
