### ISSUE TITLE
Missing spacing when using katex executable

### ISSUE THREAD

**Issue by raroni** [Khan/KaTeX#1738]
When I type in "a+b" in the demo textfield on katex.org and inspect the DOM I see the following spacing elements between "a and "+" and between "+" and "b".

    <span class="mspace" style="margin-right: 0.222222em;"></span>

The same happens if I use `node` and run a script with `var katex = require('katex'); katex.renderToString(...)`. The rendering looks fine.

However, if I do the exact same thing using the `katex` executable installed via `npm install -g katex` I get this:

    <span class="mspace" style="margin-right: 0em;"></span>

The spacing is missing and consequently it looks wrong in the browser. You can (presumably) reproduce the issue like this:

    npm install -g katex@0.10.0-rc.1
    echo "a+b" > test.tex
    katex -i test.tex -o test.html
    cat test.html

When I run the above and inspect the generated HTML I see `<span class="mspace" style="margin-right:0em;">` between each character. I would expect a margin of approximately 0.222em (like in the above shown above).

Am I doing something wrong? Anyway, thanks for a great library :-)

**Comment by edemaine** [comment]
I'm confused why this is happening, but I could reproduce it. Thanks for the report!

**Comment by edemaine** [comment]
FWIW, `yarn global add katex` behaves the same.  But from a Git master clone, `yarn; yarn build; echo a+b | node cli.js` works fine.  So maybe something to do with `bin` mechanism...

**Comment by edemaine** [comment]
OK, I found the problem: a bad (0) default for `maxSize`.  #1739 fixes the issue, and meanwhile you can use `katex -s 999` or similar.
