### ISSUE TITLE
\fcolorbox is not working

### ISSUE THREAD

**Issue by gpykhanna1** [Khan/KaTeX#1746]
Hello -- I downloaded your plugin into Wordpress and was playing around.  This is a great plug-in, but it looks like some of the features you say are supported in your document are not rendering.

For example, I typed in 
[latex] \fcolorbox{red}{aqua}{A} [/latex]

... and I got the "Formula Does not parse" error

**Comment by kevinbarabash** [comment]
The Wordpress plugin must be out of date since `\fcolorbox{red}{aqua}{A}` renders fine on `katex.org`.  We aren't responsible for this plugin so you'll have to find out who is and ask them to update it.

**Comment by gpykhanna1** [comment]
Yes -- you're correct.  It does render find on the site.  Would you happen to know who supports the Wordpress plug-in?  It would be great if it the releases for the plug-in were in sync with the improvements in the engine.

**Comment by edemaine** [comment]
I'd start here: https://wordpress.org/plugins/wp-katex/

**Comment by gpykhanna1** [comment]
Thank you - I posted this in the support forum for the plug-in.
