### ISSUE TITLE
Support for LaTeX proper and LaTeX CTAN packages

### ISSUE THREAD

**Issue by AaronNGray** [Khan/KaTeX#1749]
Suggesting this as a new major major step for KaTeX is to support TeX properly not just TeX '$$' math.

I need the ability to use CTAN packages :-

    https://ctan.org/

like Semantic :-

    https://ctan.org/pkg/semantic

My usecase: for doing inference rules for type theory documentation on my programming language within VuePress.

**Comment by kevinbarabash** [comment]
This would be very difficult to do.  I could see us support some common packages with the common `\usepackage` command sometime in the future but we'd be loading groups of commands that we've either defined as macros using commands supported by KaTeX or loading commands we've defined using `defineFunction` et al.

**Comment by ylemkimon** [comment]
Closing as won't fix. Please open new issue with specific package or command you'd need. Thank you!
