### ISSUE TITLE
some symbols like \times and \Omega not working in android app local html file.

### ISSUE THREAD

**Issue by satyendersaini56** [Khan/KaTeX#1756]
Its working fine in website (which is on server) but some symbols are not working in local html file in android app properly like \times  shows imes and \Omega shows Omega.

here is stackoverflow link

https://stackoverflow.com/questions/53009497/times-and-omega-not-working-in-mathjax-katex-in-local-html-file

**Comment by edemaine** [comment]
Can you post a KaTeX example? (I only see a MathJax example.)

In any case, it looks like you're not including the CSS files and thus not getting the required fonts. On desktop, tje browser might have a fallback font for these characters, but Android might not.

Alternatively, it could be an XSS issue with pages from localhost. Did you look at the logs from the browser? Also, which browser are you using?
