### ISSUE TITLE
Can I get the position information?

### ISSUE THREAD

**Issue by linwaytin** [Khan/KaTeX#1764]
Hello, I'm thinking how to make a WYSIWYG math editor based on KaTeX. I'm wondering if there is a way that I can get the position information after rendering.

For example, for an equation like $\frac{x^2}{x^2+y^2}$, can I get the position of the first "x" or the second "2" after rendering?  The API on the website looks very simple and I have no idea how to achieve this.

**Comment by kevinbarabash** [comment]
Please see #809 for discussion about using KaTeX as an editor.
