### ISSUE TITLE
\fcolorbox with math inside

### ISSUE THREAD

**Issue by basilgass** [Khan/KaTeX#1766]
Hi !
(this is my first issue - hope I'm doing it correctly)

I'm using this code to highlights some part of an equation:

    \fcolorbox{#007bff}{white}{16x^2}

But it seems to not working. If I remove the "power 2", e.g.

    \fcolorbox{#007bff}{white}{16x}

it is then working. Am I doing something wrong ? Is this a limitation ?

Thanks!

**Comment by edemaine** [comment]
In LaTeX and KaTeX, `\fcolorbox` renders its third argument as text.  You need to switch back to math mode:
```latex
\fcolorbox{#007bff}{white}{$16x^2$}
```
![image](https://user-images.githubusercontent.com/2218736/47722896-c4e65780-dc29-11e8-8c1d-2aebb1c1b0fd.png)

**Comment by edemaine** [comment]
Yes, this behavior matches LaTeX. It is implicit in the "Supported Functions" documentation in that the letter A appears upright and not italic. But I agree that is quite subtle, and we could perhaps make it more explicit. For example, we could make the example text include a space character. @ronkok, thoughts?

**Comment by ronkok** [comment]
Yes, "Supported Functions" has always been a page that shows examples but doesn't explain them. It covers a lot of material that way, but it falls short as a tutorial. I think @edemaine's  suggestion is a good one. We'll change the example into one that contains math. Maybe `\colorbox{aqua}{$16 x^2$}`. 

There are probably other TeX boxes on that page and on the "Support Table" page that would benefit from similar treatment. I'll look into it.

I've long had the urge to augment that page with some links to explanations of TeX behavior. For instance, in the delimiter section, the page could show a <img src="https://user-images.githubusercontent.com/16403058/47855192-1e24c700-dda1-11e8-98e4-ec17db5d26fe.PNG" width="24" alt="question"> button which links to, say, [here](https://en.wikibooks.org/wiki/LaTeX/Mathematics#Automatic_sizing). Any thoughts on the links-to-explanations idea?

**Comment by edemaine** [comment]
Links to relevant LaTeX documentation seems like a neat idea. For example, for features that come from a specific LaTeX package, we could link to that package documentation on CTAN. The wikibook is a reasonable other source. Nice idea!

**Comment by qcho** [comment]
Had the exact same issue.
It seems  the change proposed by @ronkok never reached the documentation. Sending a PR.

**Comment by ronkok** [comment]
Fixed via PR #2288.
