### ISSUE TITLE
wrong color render

### ISSUE THREAD

**Issue by licstar** [Khan/KaTeX#1769]
`\frac{\color{red}{1}2}{3}`

I think "2" should be black. However, it's red

**Comment by edemaine** [comment]
This matches LaTeX behavior. In LaTeX, you need to write
```
\frac(\textcolor{red}{1}2}{3}
```
If you want `\color` to work like `\textcolor`, there is an option specifically to maks that happen; see the option documentation. (MathJax has the opposite default: it incorrectly defines `\color` to work like `\textcolor` unless you include the Color package.)
