### ISSUE TITLE
Feature request: HTML inside mathematics

### ISSUE THREAD

**Issue by jabacchetta** [Khan/KaTeX#1774]
[jqMath](https://mathscribe.com/author/jqmath.html) allows for things like text inputs as part of a fraction (where a user can fill in the inputs). An example of this can be seen on the site (search for `\html`).

As far as I know, this isn't possible with KaTeX, but would love to see the feature added.

**Comment by edemaine** [comment]
I believe this is the same request as #1596. Also related to #1771 if you'd care to comment.

**Comment by ylemkimon** [comment]
Duplicate of #1596
