### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by 0a-** [Khan/KaTeX#179]
This TypeError was thrown when I use `katex.render` in a `for in` loop like this:

```javascript
var dom = document.getElementsByClassName('math'); 
for(key in dom){ 
   var math = dom[key].innerHTML; katex.render(math, dom[key]); 
} 
```

However, all the maths are rendered nicely. Nothing really goes wrong. It is just that a TypeError is thrown.

**Comment by spicyj** [comment]
Can you provide a complete stack trace?

**Comment by 0a-** [comment]
Sure, gimme a minute. I was using the minified version from CDN

**Comment by kevinb7** [comment]
be careful with using for-in loops.  getElementsByClassName does returns

**Comment by kevinb7** [comment]
In this case the ```for-in``` loop will include keys: ```length```, ```item```, and ```namedItem``` whose values aren't ```HTMLElements```.  These additional properties show up at the end because numbered keys come first "alphabetically" which is why all of the math renders properly.

**Comment by 0a-** [comment]
Nice catch. I just saw that too. That is why _innerLex was throwing the error.
