### ISSUE TITLE
Make other kinds of overlines work

### ISSUE THREAD

**Issue by xymostech** [Khan/KaTeX#18]
Now, `\overline` works, but things like `\overleftrightarrow` don't.

**Comment by gagern** [comment]
I guess `\widetilde`, `\widehat` and so on will be more difficult. At the moment, we have no information as to the width of the characters. We have only the heights, and all the horizontal alignment is taken care of by the browser. Which means we can make a line as wide as a box, and have that box be a bit shorter than some other box, but choosing the most suitable size for a big tilde or hat would require more knowledge about how wide the box in question actually is.

**Comment by kevinbarabash** [comment]
This is fixed in [v0.8.0](https://github.com/Khan/KaTeX/releases/tag/v0.8.0).
