### ISSUE TITLE
\begin{aligned} not supported

### ISSUE THREAD

**Issue by keithphw** [Khan/KaTeX#182]
KaTex doesn't appear to support \begin{aligned}.
Here is a test case:
http://jsfiddle.net/keithphw/2449ehuv/3/

By the way, thank you for making a great library. I currently use MathJax but am quite dissatisfied with its speed, how it only works on the client, and how it re-flows the page. I would like to use katex however I make extensive use of \begin{aligned} which khatex doesn't support. I wish to use katex on my student page here:
www.fightfinance.com
Cheers,
Keith

**Comment by xymostech** [comment]
This is correct, this is currently documented in #61. This is definitely on the radar, Khan Academy also uses a lot of `\begin{align}` (similar to `\begin{aligned}`); when I have time to work on KaTeX I'll definitely be working on this.

**Comment by kynan** [comment]
Why has this been closed?

**Comment by spicyj** [comment]
It's a duplicate of #61.
