### ISSUE TITLE
lots more symbols

### ISSUE THREAD

**Issue by drdozer** [Khan/KaTeX#185]
I've been using KaTeX through gitter, but have found that many symbols I use are not yet defined. I regularly use many of the relational symbols described here: 

http://www.artofproblemsolving.com/Wiki/index.php/LaTeX:Symbols

For example, the curved and square subset/superset relations aren't defined.

If this is easy to add, I'd be happy to work on it.

**Comment by abejfehr** [comment]
I saw that this issue hadn't yet been replied to, and thought I'd mention that those symbols seem to be present in PR #151

**Comment by spicyj** [comment]
These should have all been added in #126 and d61a04c80d14577212e3e98e83ff2da0c7a70907. We're planning to cut a new release soon with these updates.
