### ISSUE TITLE
adding a `supported` function

### ISSUE THREAD

**Issue by episodeyang** [Khan/KaTeX#186]
Hi,

I am trying to use KaTeX as the primary rendering library while using MathJax as a fallback, just like Kahn academy's main website.

Is there a function that I can use to test if a string is supported by KaTeX? It would be very nice to have this function included in the library!

Cheers,
Ge

**Comment by xymostech** [comment]
In general, no. I'm not sure this would be possible either, as things like `\sqrt{3}` are currently supported, but `\sqrt[3]{3}` are not, so it's not clear whether `\sqrt` would count as supported or not.

However, KaTeX will throw an exception if it encounters something that it doesn't understand, so you could try something like:

```javascript
function isSupported(expression) {
    try {
        katex.renderToString(expression);
        return true;
    } catch (e) {
        if (e.__proto__ == katex.ParseError.prototype) {
            return false;
        } else {
            throw e;
        }
    }
}
```

Does that work for you? Note that you need a full expression, not just a function, so `isSupported("\\sqrt")` will return `false`, but `isSupported("\\sqrt{3}")` will return `true`.

**Comment by episodeyang** [comment]
Since the renderToString is basically doing the rendering, wouldn't it be faster if I just use KaTeX's `render` function as the default, and catch the exception to backup with mathjax? 

How quickly does KaTeX throw the exception?

Cheers

**Comment by spicyj** [comment]
> Since the renderToString is basically doing the rendering, wouldn't it be faster if I just use KaTeX's `render` function as the default, and catch the exception to backup with mathjax?

Yes, this is exactly what we do at Khan Academy. KaTeX should be plenty fast enough for you to run it and test first.

**Comment by episodeyang** [comment]
is there any speed difference between the `render` function and the
`renderToString` function?

**Comment by spicyj** [comment]
If you count the cost of setting `.innerHTML` after calling renderToString, they're pretty similar. Probably `render` is faster in modern browsers and `renderToString` is faster in IE8. If you're not actually rendering to the DOM, renderToString will be faster since it won't touch the DOM at all.

**Comment by episodeyang** [comment]
Thanks. I will run some benchmarks.
