### ISSUE TITLE
I can use the matrix notation

### ISSUE THREAD

**Issue by aldajo92** [Khan/KaTeX#187]
Well I'm trying to use the matriz notation, but I found that it have errors for identify the following latex code:

The \emph{characteristic polynomial} $\chi(\lambda)$ of the
$3 \times 3$~matrix
\[ \left( \begin{array}{ccc}
a & b & c \\
d & e & f \\
g & h & i \end{array} \right)\] 
is given by the formula
\[ \chi(\lambda) = \left| \begin{array}{ccc}
\lambda - a & -b & -c \\
-d & \lambda - e & -f \\
-g & -h & \lambda - i \end{array} \right|.\] 

This is an example that I found in the web.

**Comment by episodeyang** [comment]
Environments are not yet supported. You can refer to these issues: #68 #47 #43
