### ISSUE TITLE
katex.render fails in Firefox

### ISSUE THREAD

**Issue by kosek** [Khan/KaTeX#188]
In Firefox (I tried versions 33 and 35) katex.render() will lead to the following error on console:

TypeError: this._input is undefined
	
...prototype._innerLex=function(e,t,i){var a=this._input.slice(e);var s;if(i){s=a.m...

I was using latest stable release 0.1.1.

**Comment by spicyj** [comment]
That's the error you get if you pass `undefined` as the input string. See also #179.

**Comment by kosek** [comment]
Yes, sorry for false alarm. Now I realized I have used innerText instead of textContent for pulling TeX math for rendering from the element content. My bad.

Might be adding sample code for iterating over all equations stored in <span class="math"> and rendering them into README.md would be of help for seasonal JS developers.
