### ISSUE TITLE
Add font styles like \mathrm, \mathcal, etc.

### ISSUE THREAD

**Issue by xymostech** [Khan/KaTeX#19]

**Comment by delip** [comment]
@xymostech can you look into the PR submitted by @kevinb7? Please let us know if you need help.

**Comment by kevinb7** [comment]
Implemented in https://github.com/Khan/KaTeX/pull/290, https://github.com/Khan/KaTeX/pull/291, and https://github.com/Khan/KaTeX/pull/292.

**Comment by delip** [comment]
Just awesome!
