### ISSUE TITLE
Add support for \implies and \iff

### ISSUE THREAD

**Issue by spicyj** [Khan/KaTeX#190]
These are tricky because they should have space around them (`\;` on either side). We should probably implement these as some sort of internal macro, which can maybe be a precursor to #37.

**Comment by ericaxu** [comment]
It would be awesome to have this!

**Comment by edemaine** [comment]
Just bumped into lack of `\implies`.  This should be easy once #605 gets merged.

**Comment by gagern** [comment]
Ideal candidate for that, yes. Looking at the definition in `amsmath.sty` I read

```tex
\newcommand{\implies}{\DOTSB\;\Longrightarrow\;}
\renewcommand{\iff}{\DOTSB\;\Longleftrightarrow\;}
```

So these should have some interaction with #599, too. Would be nice to see the combination of all these features work together as intended. A definition without `\DOTSB` might go into master shortly after #605 while #599 waits for a follow-up implementing JavaScript-written macros with look-ahead capability.

**Comment by edemaine** [comment]
Sounds good.  Alternatively, we could include `\DOTSB` in the macro definition, and also include a macro definition for `\DOTSB` that maps to the empty string.  (Technically, AMS defines `\DOTSB` to `\relax`.  I suppose you could add that layer of indirection too.)  That *should* set the stage for support in #599 (which currently already looks for `\DOTSB` as well as `\implies` and `\iff`, FWIW, but not yet in the macro expansion stage).

**Comment by kevinbarabash** [comment]
So `\DOTSB` is equivalent to `\relax` and `\relax` is used to prevent a command with optional params from "eating" the `\;`.  Is that correct?

**Comment by edemaine** [comment]
Yes, I think so.

**Comment by gagern** [comment]
`\relax` is a non-expandable command, not a macro, so we probably should add support for that in `functions.js`. I'm not sure how a “do nothing” would best be represented in the parse tree, though.

**Comment by ronkok** [comment]
As mentioned earlier on this thread, these functions are now ripe to be implemented. The code:

```
defineMacro("\\iff", "\\mathrel{\\;\\Longleftrightarrow\\;}");
defineMacro("\\implies", "\\mathrel{\\;\\Longrightarrow\\;}");
defineMacro("\\impliedby", "\\mathrel{\\;\\Longleftarrow\\;}");
```

… would pick up three functions at once. They can be modified later to be dots-aware.

**Comment by edemaine** [comment]
@ronkok Great!  I can turn this into a PR if you'd like.

**Comment by ronkok** [comment]
That works for me. I tried it myself this morning and GitHub defeated me again.

**Comment by edemaine** [comment]
PR: #697

**Comment by astoilkov** [comment]
Any plans for making 0.7.2 release soon?
