### ISSUE TITLE
Demo to use this library on Android.

### ISSUE THREAD

**Issue by iAviatorJose** [Khan/KaTeX#194]
Is there any project demonstrating the use of these library for Android.

**Comment by PeterBocan** [comment]
It's a library for websites, not Android as a platform. If you can write website-based application then go for it, if not, I'm sorry.

**Comment by spicyj** [comment]
Khan Academy uses KaTeX, which you can try on an Android phone. Example:

https://www.khanacademy.org/math/integral-calculus/indefinite-definite-integrals/fundamental-theorem-of-calculus/e/the-fundamental-theorem-of-calculus

There's no special support for Android in particular.

**Comment by iAviatorJose** [comment]
ok thanks

**Comment by judemanutd** [comment]
Created a library [ KatexView ](https://github.com/judemanutd/KatexView) that would allow you to handle this in android.

**Comment by kevinbarabash** [comment]
@judemanutd would you be interesting in adding a link to this to https://github.com/KaTeX/KaTeX/blob/master/docs/libs.md?

**Comment by judemanutd** [comment]
> @judemanutd would you be interesting in adding a link to this to https://github.com/KaTeX/KaTeX/blob/master/docs/libs.md?

@kevinbarabash created a pull request [ 1943 ](https://github.com/KaTeX/KaTeX/pull/1943)
