### ISSUE TITLE
rules in .katex-mathml should not be !important

### ISSUE THREAD

**Issue by fred-wang** [Khan/KaTeX#197]
For some reason, the rules in .katex-mathml are !important:

https://github.com/Khan/KaTeX/commit/aaeab1200c73f633af607d94ba95dca9b22a4d66#diff-03326d64354534b6fb69a723fb333018R30

this means that someone  who wants to override them to use the native MathML rendering instead, will need to do that with Javascript instead of a pure CSS solution :-(

**Comment by xymostech** [comment]
You're right! I don't know why they're marked like that, I copied them from another website. I'll change that.
