### ISSUE TITLE
contenteditable integration

### ISSUE THREAD

**Issue by tarjei** [Khan/KaTeX#199]
Hi, have you guys integrated KaTeX with a contenteditable element? I'm looking both for implementation details but also for good ideas on interaction design.

Regards,
Tarjei

**Comment by kevinb7** [comment]
I'm not quite sure how this would work as the presentation looks quite different from the LaTeX source.  Maybe when the user clicks on the KaTeX rendering you could hide the rendering and display a contenteditable element containing the source and then when the user clicks outside you could do the reverse and update the rendering.  It might be nice to do this if the user hits enter, but you'd have to capture that event youreself.

**Comment by spicyj** [comment]
We don't have any plans for this in KaTeX right now. You can look into other libraries like MathQuill: http://mathquill.com/.

**Comment by tarjei** [comment]
Hmm, mathquill has a very nice UI solution - thanks! 

I'm going to try to emulate that using katex and react. Any tips on how to get the blinking cursor inserted in the right place will be well recived :)
