### ISSUE TITLE
Add support for % comments

### ISSUE THREAD

**Issue by xymostech** [Khan/KaTeX#20]

**Comment by alexirpan** [comment]
Poking this. It turns out the kramdown engine turns `0 < 1` into

    % <![CDATA[
    0 < 1 %]]> 

The intention is that it gets wrapped to properly escape the < sign, and the wrapping gets commented out in the rendering.

kramdown is the main markdown engine for Github Pages, so this is a barrier for setting up KaTeX on blogs hosted there.

**Comment by spicyj** [comment]
That's clever. CDATA isn't even valid in HTML5 though (only SVG and MathML): https://html.spec.whatwg.org/#cdata-sections.

**Comment by meygerjos** [comment]
Kramdown has [a workaround](https://github.com/gettalong/kramdown/issues/292#issuecomment-257770946) now.  But KaTeX should still fix this.

**Comment by kevinbarabash** [comment]
I was thinking of pre-processing the input to remove the comments, but we probably don't want to do that b/c then an error reporting would have the wrong position information.

**Comment by edemaine** [comment]
Can't this be done in the Lexer?  Just add comment pattern to the regex, but don't return upon a comment match.

**Comment by kevinbarabash** [comment]
I think `%[^\n]*\n` should do the trick.

**Comment by xsznix** [comment]
Perhaps `%[^\n]*(?:\n|$)` so that it allows comments at the end of the expression?

**Comment by sophiebits** [comment]
`%.*?\n?` is also equivalent to @xsznix's in case you need more ways to do this.

My "mrrh?" comment was ambivalence about the correct answer. I'm not sure it makes sense to allow it at the end of an expression – since you can't do `$x%y$` in TeX without a newline. Maybe it does.

**Comment by kevinbarabash** [comment]
So `pdflatex` throw an error in that situation which means that people copy TeX code into KaTeX won't be include code with comments like that.  Things might go wrong copy/pasting a KaTeX string back into a .tex file, but users will have to modify the string anyways by add `$`.  If we support comments a person should be able to type `a^2 + b^2 = c^2 %% Pythagoras' theorem` into a text input and have that work without having to add a newline at the end of it before they pass it to `katex`.  My vote would be to allow comments without a newline at the end of the string.

**Comment by sophiebits** [comment]
The fact that this exists feels like a small argument in favor of not supporting ending comments:

https://github.com/Khan/KaTeX/blob/a358c5a94c86a13bd3381334c9ad4ca23cd57781/dockers/texcmp/texcmp.js#L62

**Comment by kevinbarabash** [comment]
We could change that to
```
let tex = "$" + itm.tex + "\n$"
```
😛

**Comment by sophiebits** [comment]
Yes, but only if you're expecting this behavior! The fact that it isn't that already indicates that you wouldn't. Someone else might equally try to build a web writing interface that accepts KaTeX and turns into a full TeX document later and be bitten by this.

**Comment by kevinbarabash** [comment]
We could have an option to allow comments without newlines, but have the default be strict LaTeX compliance.

**Comment by sophiebits** [comment]
In Perseus (or auto-render), I also wouldn't want typing `$x%y$` to render a mathy x. It's confusing

What's the value in allowing comments without newlines? If you really want to do that you can always just tack on a newline to the input expression when calling KaTeX.

**Comment by edemaine** [comment]
IMHO, if `$x%y$` causes `x%y` to get passed into KaTeX, then that's a mistake: that second `$` shouldn't be considered a terminator when it's hidden by the comment.  Of course, that *is* how it works now with auto-render, but in my opinion that's a bug in auto-render.

I guess I can't imagine a setting where `x%y` really makes sense as input to KaTeX, so I'd be OK with requiring a `\n` at the end of the comment regex.

**Comment by kevinbarabash** [comment]
I'm okay with that too.  The best justification I could come up with is that it would all writing comments in our test app, but that isn't much of a justification.  Our test app should be modified to use a `<textarea>` instead so that it's easy to test comments locally.

**Comment by xsznix** [comment]
Yeah, it sounds like allowing a comment to end a math expression would not be expected behavior. I rescind my suggestion.

**Comment by kevinbarabash** [comment]
I'm going to give this a shot.

**Comment by kevinbarabash** [comment]
<img width="1072" alt="screen shot 2017-09-15 at 12 32 45 am" src="https://user-images.githubusercontent.com/1044413/30466678-7590315c-99ad-11e7-83b0-6ddc7b21f265.png">

**Comment by edemaine** [comment]
@kevinbarabash `<textarea>` would be very handy when testing arrays and such, thanks!

You should test spacing behavior:
```latex
\text{hello% comment
world}
```
should parse like `\text{helloworld}`, but not like
```latex
\text{hello% comment

world}
```
