### ISSUE TITLE
KaTeX doen't render (Chrome)

### ISSUE THREAD

**Issue by brunetto** [Khan/KaTeX#200]
Hi!
I added 

```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.2.0/katex.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.2.0/katex.min.js"></script>
```

to a js presentation, but it does not render even the simplest equation. 
Am I missing something?

Note: the same presentation looks perfect with MathJax.

Thanks

**Comment by xymostech** [comment]
Are you running `katex.render` on your mathy elements? KaTeX doesn't (yet) automatically render all of the math on the page, so you have to manually call it.

**Comment by brunetto** [comment]
Ooops, I didn't. Is there a guide to follow? 
So it's not possible to include it in a markdown parser.. Do I have to write the page from scratch to use it?

**Comment by xymostech** [comment]
It is definitely possible to use KaTeX with a markdown library, (we do so at KA), but there isn't really a guide, yet. If you look at the README, there's a short description of the `katex.render` API, which you would probably use. What markdown library are you using?

**Comment by xymostech** [comment]
This should be solved by using the [auto-render extension](https://github.com/Khan/KaTeX/tree/master/contrib/auto-render).
