### ISSUE TITLE
MathML for primes (') is wrong

### ISSUE THREAD

**Issue by NSoiffer** [Khan/KaTeX#204]
On the [definite integral page](https://www.khanacademy.org/math/integral-calculus/indefinite-definite-integrals/definite_integrals/e/evaluating-definite-integrals), the encoding of `F'` is not quite right -- while the MathML properly uses `<msub>` for the prime, the prime character is in a `<mi>` but should instead be in `<mo>` as it is an operator. The MathML for the entire expr is:

``` html
<math><semantics>
  <mrow><mstyle displaystyle="true" scriptlevel="0">
     <msup>
        <mi>F</mi>
        <mrow> <mi mathvariant="normal">′</mi> </mrow>
     </msup>
     <mo>(</mo>
     ...
     </mstyle></mrow>
<annotation encoding="application/x-tex">\displaystyle F'(x) =  f(x)\,</annotation>
</semantics></math>
```

Although using `<mo>` for the prime char isn't mentioned in chapter 3 of the MathML spec, there is an example of it in [chapter 7](http://www.w3.org/Math/draft-spec/chapter7.html#chars.pseudo-scripts).

**Comment by kevinb7** [comment]
@NSoiffer what tex code are you using to generate this MathML?

**Comment by kevinb7** [comment]
For reference MathJax renders the prime in ```F'``` as:
```
<msup>
    <mi>F</mi>
    <mo>&#x2033;</mo>
</msup>
```
and ```F^\prime``` as:
```
<msup>
    <mi>F</mi>
    <mi class="MJX-variant" mathvariant="normal">&#x2032;<!-- ′ --></mi>
</msup>
```
