### ISSUE TITLE
Add support for \begin \end environments

### ISSUE THREAD

**Issue by rymohr** [Khan/KaTeX#206]
Found a couple related issues and just wanted to add a central one to tie everything together:

- align support https://github.com/Khan/KaTeX/issues/61
- array support https://github.com/Khan/KaTeX/issues/47
- matrix support https://github.com/Khan/KaTeX/issues/43

**Comment by PeterBocan** [comment]
Is there somebody working on it?

**Comment by rymohr** [comment]
Not that I know of, though @kevinb7 and @xymostech have given it some thought:
https://github.com/Khan/KaTeX/issues/43#issuecomment-55658982
https://github.com/Khan/KaTeX/issues/61#issuecomment-57091390

**Comment by gagern** [comment]
Can we close this, now that #246 has been merged?

**Comment by kevinb7** [comment]
I think we can close this because the infrastructure for ```\begin``` and ```\end```.  We'll leave the other issues open that deal with specific environments.
