### ISSUE TITLE
\overline is present but not \underline

### ISSUE THREAD

**Issue by abejfehr** [Khan/KaTeX#209]
I may be missing something here, but isn't `\underline` part of LaTeX by default? Or was this omitted strategically?

**Comment by xymostech** [comment]
You are correct, we have `\overline` but not `\underline`. Not a strategic move or anything, we just haven't added it yet.

**Comment by pepperblue** [comment]
`\underline` would be very useful. For us it's the only thing left to be able to completely switch from MathJax to KaTex

**Comment by mici-** [comment]
Do you have an ETA on this?

**Comment by kevinbarabash** [comment]
@mici- no ETA.  I think this one would should be pretty easy though because overline is already in place.   Maybe someone can put together a PR for this.

**Comment by ericaxu** [comment]
Any update on this?

**Comment by ericaxu** [comment]
@spicyj THANKS!
