### ISSUE TITLE
Trimming off the first and the last 2 characters

### ISSUE THREAD

**Issue by PeterBocan** [Khan/KaTeX#210]
Guys, I've tried the 0.2.0 version and something has broken up, at least for me:
```html
<div class="math">  f(x) = \int_{-\infty}^\infty F(x) dx  </div>
<div class="math"> f(x) = \int_{-\infty}^\infty F(x) dx </div>
<div class="math">f(x) = \int_{-\infty}^\infty F(x) dx</div>
```

![A trimmed equation](http://s22.postimg.org/86tra81m9/Screenshot_2015_03_25_23_24_01.png)

I'm not sure if this is a "feature" or bug, but it's strange.

**Comment by spicyj** [comment]
That's weird. How are you calling katex.process?

**Comment by spicyj** [comment]
(Does http://khan.github.io/KaTeX/ work okay for you?)

**Comment by PeterBocan** [comment]
Yup, it's okay, my fault. There was a little issue with javascript. You can close this.
