### ISSUE TITLE
Support MathML input

### ISSUE THREAD

**Issue by jonathankroll** [Khan/KaTeX#211]
Hello!

I'm not sure if this is a duplicate request (despite my best efforts).

 I am currently inputting **MathML** and rendering **HTML** output with MathJax. I would love to do this with KaTeX.

**Comment by xymostech** [comment]
Hello!

Unfortunately, adding another kind of input (like MathML, or even things like AsciiMath) is mostly infeasible at this point. The parser is fairly specialized for understanding TeX, and we currently don't even support all of the things in TeX that we want to support yet, so we might work on this, but probably not soon in the future.

**Comment by spicyj** [comment]
@jonathankroll Curious: why do you prefer MathML for input?

**Comment by spicyj** [comment]
Makes sense. You could probably find some automated way to convert that to TeX but I don't think we'll add one to KaTeX itself.

**Comment by panbhag** [comment]
can someone suggest a way to convert mathml to tex

**Comment by kevinbarabash** [comment]
I found http://www.orcca.on.ca/~elena/ORCCA_MathML2002_WebPoster.htm, but I haven't actually tried it.
