### ISSUE TITLE
Support for ESSTIX font

### ISSUE THREAD

**Issue by raichu** [Khan/KaTeX#216]
Please consider adding [esstix](https://www.ctan.org/pkg/esstix) [font](https://en.wikipedia.org/wiki/STIX_Fonts_project#ESSTIX) ([ttf](http://www.w3.org/Amaya/Distribution/esstix.tar.gz)).

**Comment by spicyj** [comment]
Curious: why esstix instead of stix? Merging into #42.

**Comment by raichu** [comment]
Essix is *the* font used in many old science books.
Trying to capture that.

**Comment by raichu** [comment]
BTW, could you re-open this issue?
#42 is quite a different issue: it's about alternative scripts (mathrm, mathcal etc.) of a certain font.
Like any other complete math font, ESSTIX font comes with its own mathrm, mathcal, etc.

**Comment by spicyj** [comment]
Oops, I guess I was too hasty. #123 is similar enough though that I'll just track both there.
