### ISSUE TITLE
Protect from text-indent

### ISSUE THREAD

**Issue by ruricolist** [Khan/KaTeX#217]
If an element has the `text-indent` property set, then any math that appears within it is spaced out ridiculously. If you go to the KaTeX page, for example, and edit the CSS to add a rule like `body { text-indent: 1em}`, you can see it for yourselves. 

The problem, of course, is that `text-indent` is being inherited and applied to elements displayed as blocks. The fix should be as simple as setting `.katex { text-indent: 0}` in your CSS.

**Comment by xymostech** [comment]
Indeed, text-indent does make the math look annoying. Could you submit a pull request to fix that?

**Comment by ruricolist** [comment]
I made a pull request. Do I need to sign the CLA for something this small?

**Comment by xymostech** [comment]
Yes, the CLA needs to be signed for all pull requests.

**Comment by ruricolist** [comment]
OK, I've signed the CLA.
