### ISSUE TITLE
Equivalent of DeclareMathOperator?

### ISSUE THREAD

**Issue by kirbyfan64** [Khan/KaTeX#221]
I'm toying with using KaTeX instead of MathJax for the [Felix language category theory primer](http://felix-lang.org/share/src/web/articles/category_theory_01.fdoc). The file uses MathJax's `DeclareMathOperator`, and KaTeX is throwing a parse error. What should I use instead?

**Comment by xymostech** [comment]
We don't currently have anything like `DeclareMathOperator` in KaTeX. Since `\DeclareMathOperator` is basically the same as `\operatorname`, this should be merged into #145.

**Comment by spicyj** [comment]
(In conjunction with support for defining macros #37.)

**Comment by RoyiAvital** [comment]
@xymostech , I find `DeclareMathOperator` to be useful to generate operators in all the document instead of writing them again and again:

```md
$$
\DeclareMathOperator{\rank}{rank}
$$

Now I can use it:

$$
\rank \left( \boldsymbol{A} \right) = 4
$$
```

Any chance to have it?
