### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by franciscop** [Khan/KaTeX#222]
When using katex with contrib/auto-render, the file "./splitAtDelimiters" is attempted to be included using the back-end library `require()`, but it doesn't work in the browser.

Code from grunt to do it:

    concat: {
      dist: {
        src: [
          'static/katex.min.js',     // Katex math rendering
          'static/katex-render.js',  // Automatic katex render
          ...
          'static/javascript.js'  // This specific file
        ],
        dest: 'public/javascript.js',
      }
    },

Then when loading javascript.js, the Console says:

![problem](https://cloud.githubusercontent.com/assets/2801252/7224336/cad9e5a0-e76b-11e4-8e8b-eae4a3eda5fa.png)

That line is this:

    var splitAtDelimiters = require("./splitAtDelimiters");

![line](https://cloud.githubusercontent.com/assets/2801252/7224360/0444a578-e76c-11e4-965d-71f434932ddb.png)

My call to the library is by doing this, although I don't think this changes anything

    renderMathInElement(document.body, { delimiters: [{ left: '$$', right: '$$', display: true }] });

So, while this could be solved by messing with that file and just concatenating the previous file, the problem would continue for anyone following the readme.md.

Proposed solution: either include the other file in the same one or edit the instructions about how to include it.

**Comment by xymostech** [comment]
How are you trying to load the auto-render file? You should be including the built auto-render.min.js file, not the un-built auto-render.js file, unless you are including it via browserify/webpack/etc. to serve on your page.

I should be more explicit about including that file. If you use the built file (for example, [from cdnjs](https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/contrib/auto-render.min.js)), does it work?

**Comment by franciscop** [comment]
That solved my problem, thank you @xymostech
