### ISSUE TITLE
Minor kerning issue?

### ISSUE THREAD

**Issue by dt1973** [Khan/KaTeX#226]
Might have stumbled upon a minor kerning issue. `EUR` appears as `EU R`:

http://jsbin.com/xegoxomasa/1/edit?html,js,output

**Comment by xymostech** [comment]
This is not a kerning issue. That is the same as how it appears when viewed in LaTeX:

![image](https://cloud.githubusercontent.com/assets/217900/7456159/2370145c-f237-11e4-95ee-b8aa6b1fa373.png)

and in MathJax:

![image](https://cloud.githubusercontent.com/assets/217900/7456194/69d5b19a-f237-11e4-807b-af3a44d21ac6.png)

**Comment by dt1973** [comment]
Thanks. Lowercase `eur` looks good though.
