### ISSUE TITLE
Add support for \cancel

### ISSUE THREAD

**Issue by dt1973** [Khan/KaTeX#229]
Is there a way to do diagonal strikethroughs in KaTeX?
- http://docs.mathjax.org/en/latest/tex.html#cancel
- https://groups.google.com/forum/#!msg/mathjax-users/tuFHn3EkSic/6NMAkL_CvqAJ

Thanks!

**Comment by freemaths** [comment]
Also interested in this. I use \cancel to show working. Can Katex support this?

**Comment by kasperpeulen** [comment]
would love this as well

**Comment by kevinbarabash** [comment]
This is fixed in [v0.8.0](https://github.com/Khan/KaTeX/releases/tag/v0.8.0).
