### ISSUE TITLE
Can render LaTex?

### ISSUE THREAD

**Issue by bguiz** [Khan/KaTeX#230]
- Does KaTex have any plans to support LaTex in addition to Tex?
- http://www.quora.com/Whats-the-difference-between-TeX-and-LaTeX

**Comment by spicyj** [comment]
KaTeX supports parts of LaTeX and parts of TeX. We don't have a comprehensive reference of supported features currently but already have some LaTeX-specific commands (e.g., `\frac`, `\binom` from amsmath) and will add more, including some environments, in the future.

**Comment by bguiz** [comment]
I would like to know if there is a goal for KaTex to support all of LaTex

If this is the case, perhaps we should catalogues the ones that have
already been implemented, and the ones still outstanding? This looks like
an exhaustive list: http://en.wikibooks.org/wiki/LaTeX/Command_Glossary

W: http://bguiz.com

**Comment by PeterBocan** [comment]
KaTeX is *math typesetting* for the web, not the replacement or some kind of "web version" of LaTeX/TeX. If you want to, you can go and do something like TeX for website typesetting, that would be nice, but I'm happy with markdown since last year.
