### ISSUE TITLE
Support multiple fonts

### ISSUE THREAD

**Issue by scaljeri** [Khan/KaTeX#233]
I'm using both KaTeX and MathJax to render formulas. I use MathJax as a fallback if KaTeX can't render the formula. Now, the problem is that I (sometimes) get a mixture for formulas rendered with different font. 

For MathJax I've defined to use `STIX-Web` font, but Mathjax has more fonts available

   * 1. TeX
   * 2. STIX-Web
   * 3. Asana-Math
   * 4. Neo-Euler
   * 5. Gyre-Pagella
   * 6. Gyre-Termes
   * 7. Latin-Modern

I noticed that KaTex renders formulas using `KaTeX_Main`. Does KaTex support multiple fonts ? If so, where is this documented / how can I change the font. If not, are there any plans to support this ? Any help to align both libraries would be appreciated, thnx

**Comment by PeterBocan** [comment]
KaTeX does not support other fonts because it will require new metrics for rendering.
See https://github.com/Khan/KaTeX/issues/123 and https://github.com/Khan/KaTeX/issues/231.

**Comment by scaljeri** [comment]
Ok thanks! Are there plans in the near future to support this ?

**Comment by PeterBocan** [comment]
When it's done, but this feature is not the main goal for these days. :)

**Comment by spicyj** [comment]
Closing in favor of the other issues.
