### ISSUE TITLE
0.3.0 not on npm

### ISSUE THREAD

**Issue by mydigitalself** [Khan/KaTeX#234]
Hey folks, we use KaTeX for Gitter where it's very popular amongst some of our communities. Was in the process of upgrading some of our markdown processors and wanted to move up to 0.3.0, but noticed it's not published on npm yet, is there any reason for that?

**Comment by spicyj** [comment]
Looks like an oversight. Just pushed 0.3.0.

**Comment by mydigitalself** [comment]
Sweet, thanks for the super-fast response too.
