### ISSUE TITLE
Font question

### ISSUE THREAD

**Issue by mydigitalself** [Khan/KaTeX#235]
Me again. Was trying to look at the Wiki documentation about the fonts just to understand what _Fraktur _Greek _AMS and _Caligraphic are for. Are they needed or just variations?

**Comment by spicyj** [comment]
KaTeX_AMS contains some of the symbols. The others aren't currently used:

https://github.com/Khan/KaTeX/blob/v0.3.0/static/fonts.less#L50-L69
