### ISSUE TITLE
Add support for \S

### ISSUE THREAD

**Issue by scottdraves** [Khan/KaTeX#237]
Uncaught ParseError: KaTeX parse error: Expected '}', got '\S' at position 16: displaystyle{\S̲}

as reported by http://khan.github.io/KaTeX/

should produce a section symbol

**Comment by kirbyfan64** [comment]
Does KaTeX support section symbols? K didn't think it did.

**Comment by scottdraves** [comment]
I finally found https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX.
I would recommend linking to that from the top-level README.
And for undefined symbols, maybe just rendering as "?" would be better than throwing an exception.

**Comment by kirbyfan64** [comment]
Well, I think the newest version of KaTeX continues on error and renders the other stuff anyway. I think.

**Comment by kevinbarabash** [comment]
@scottdraves if you disable the `throwOnError` option then KaTeX will render the unsupported source command in red.  See https://github.com/Khan/KaTeX#rendering-options for details.

**Comment by kevinbarabash** [comment]
After doing a little research it appears that we're missing glyph 0x78 from cmsy10.  This should be relatively easy to fix by:
- [ ] updating https://github.com/Khan/MathJax-dev/blob/master/fonts/OTF/TeX/makeFF
- [ ] following the instructions in https://github.com/Khan/KaTeX/tree/master/dockers/MathJaxFonts
- [ ] updating https://github.com/Khan/KaTeX/blob/master/metrics/mapping.pl
- [ ] running make metrics
- [ ] updating https://github.com/Khan/KaTeX/blob/master/src/symbols.js

**Comment by scottdraves** [comment]
thanks for the tip, setting that options sounds like a good idea, will do.
but yea, you should have that symbol as well.

**Comment by kevinbarabash** [comment]
Added in #1110.
