### ISSUE TITLE
Differential 

### ISSUE THREAD

**Issue by mtaboga** [Khan/KaTeX#238]
Hello and compliments on KaTeX, a very promising piece of software.
I was wondering whether there is any supported way of writing differentials (like the dx at the end of an integral). Usually, people recommend to use the LaTeX command \mathrm{d}x , but it does not seem to be supported yet in KaTeX. Any suggestion?

**Comment by kevinb7** [comment]
Support for ```\mathrm``` should be coming shortly.  See pull request https://github.com/Khan/KaTeX/pull/132 for details.  In the meantime I would suggest using ```dx```.

**Comment by spicyj** [comment]
`\text{d}x` will also work in the meantime.
