### ISSUE TITLE
Font anti-aliasing for = looks bad in Chrome

### ISSUE THREAD

**Issue by qbolec** [Khan/KaTeX#248]
Look at https://jsfiddle.net/901jrhsu/ it tries to display x=2 in a span.
My user agent is:
```
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36
```
What I see is this:
![katex](https://cloud.githubusercontent.com/assets/133093/8145571/5fa70804-120d-11e5-82cb-c445c1454d9c.png)
The problem is that bars of equality sign are not of the equal width/color.
By changing font-size to different values I can produce other strange results (sometimes the upper bar is gray, sometimes they are both a bit blurry).

Not sure if this is KaTeX's or Chrome's problem, but I know that it works fine with MathJax :)

**Comment by spicyj** [comment]
If any contributors are interested, we should try using http://www.freetype.org/ttfautohint/. Also interesting reading: http://tex.stackexchange.com/q/1390.

**Comment by kevinb7** [comment]
Fixed by https://github.com/Khan/KaTeX/commit/ce99abd1f209b49680910fb9a93a7a45c0025f25.
