### ISSUE TITLE
I use \rm{} but it doesn t work

### ISSUE THREAD

**Issue by monokeroslun** [Khan/KaTeX#252]

**Comment by PeterBocan** [comment]
Use 
        
       \text{}

**Comment by kevinb7** [comment]
Being implemented in https://github.com/Khan/KaTeX/pull/132.

**Comment by kevinb7** [comment]
I was planning on implementing it that pull request but it turned out to be more complicated that being a simple alias `\mathrm`.

**Comment by edemaine** [comment]
I just bumped into this.  (I know `\rm` is deprecated, but it's still so much shorter to type than `\mathrm{...}`.)  These old (LaTeX 2.09) font commands are defined in `article.cls` as follows:

```latex
\DeclareOldFontCommand{\rm}{\normalfont\rmfamily}{\mathrm}
\DeclareOldFontCommand{\sf}{\normalfont\sffamily}{\mathsf}
\DeclareOldFontCommand{\tt}{\normalfont\ttfamily}{\mathtt}
\DeclareOldFontCommand{\bf}{\normalfont\bfseries}{\mathbf}
\DeclareOldFontCommand{\it}{\normalfont\itshape}{\mathit}
\DeclareOldFontCommand{\sl}{\normalfont\slshape}{\@nomath\sl}
\DeclareOldFontCommand{\sc}{\normalfont\scshape}{\@nomath\sc}
```

The last argument is how they behave in math mode.  For example, `\rm xxx` behaves like `\mathrm{xxx}` in math mode but `\normalfont\rmfamily xxx` (not supported by KaTeX) in text mode, whereas `\sl xxx` behaves like `\textsl{xxx}`.

Ideally these could be implemented in terms of macros, though I'm guessing that #605 would need modification to allow requesting an "inline" argument, like how `sizeFuncs` and `styleFuncs` are currently parsed.  @gagern Is this something that would be reasonable to implement, or should we just implement these font-changing commands directly in Parser.js?  (We'd also need different expansions for math mode and text mode -- not sure if that's already supported.)

**Comment by gagern** [comment]
I think this will need support from Parser, and in that case it might be best to do it completely inside the parser. The main problem as I see it is that the macro expander has no clue as to how far the argument should continue. Sure, it will stop at end of input, and likely at the next unbalanced `}`, but what about `&`? What about `]`? If we were to move all the handling of optional arguments into the macro expander, we might stand a better chance, but I don't think that's realistic any time soon.

**Comment by edemaine** [comment]
Fair enough.  This was surprisingly easy to implement (#675) -- unfortunately, because existing font commands (e.g. `\textbf`) are implemented as if they are full-reset commands (like `\bf`), whereas they are only supposed to set one aspect of the font.  That's for another issue...
