### ISSUE TITLE
vertical space above fraction line is too small for \frac

### ISSUE THREAD

**Issue by kevinb7** [Khan/KaTeX#253]
source: 
```
\left( x \right) \left( x^2 \right) \left( \frac{a}{b} \right) \left( \frac{a^2}{b} \right) \left( \dfrac{a}{b} \right) \left( \dfrac{a^2}{b} \right)
```

LaTeX (zoomed in so the size doesn't match exactly):
![screen shot 2015-06-18 at 12 55 03 pm](https://cloud.githubusercontent.com/assets/1044413/8239472/4242bc40-15b9-11e5-99c1-95de20c6abf5.png)

khan.github.io/KaTeX:
![screen shot 2015-06-18 at 12 48 46 pm](https://cloud.githubusercontent.com/assets/1044413/8239450/1850c8aa-15b9-11e5-99cb-674d64b4b90b.png)

localhost:7936 (master):
![screen shot 2015-06-18 at 12 53 35 pm](https://cloud.githubusercontent.com/assets/1044413/8239464/32c9eeb4-15b9-11e5-884a-2dc96307dad3.png)

**Comment by xymostech** [comment]
Huh. When you take the screenshots, are you using the browser zoom feature or increasing the font size? Also, are those the same expressions? The first `a/b` looks like it's in displaystyle, while yours looks like it's in textstyle? (note that stuff on khan.github.io/KaTeX automatically adds `\displaystyle` to the generated code)

**Comment by kevinb7** [comment]
I didn't realize that \displaystyle was being added automatically.
