### ISSUE TITLE
need support for euro symbol

### ISSUE THREAD

**Issue by Schaan** [Khan/KaTeX#254]
Hi, I couldn't find a way to type euro symbol like this `€`. With a european keyboard-layout this can be typed directly, but it can't be rendered within KaTeX, even if I put this € in a `\text`. It can be rendered in mathjax without problem.

I must say I'm not sure either if euro would exist in the world for a long time in the future... But I really type this a lot in my notes at the time.. I hope someone could help on this.

**Comment by henzestplus** [comment]
if someone could add the eurosign in one of the font files, I can add the eurosign, hopefully according to \eurosym with \euro and \EUR{}

**Comment by henzestplus** [comment]
Just for the heads up, I managed to add the Euro Sign to the regular fonts, and have \euro working in KaTeX, now I am working on \EU{}.

**Comment by kevinbarabash** [comment]
@henzestplus which .tfm files did you use?

**Comment by henzestplus** [comment]
What pull request is this about? The one that got closed because there should be a euro sign in the fonts, or the one that got closed because there is no euro sign in the fonts? The first I just copied from existing TeX fonts where I guessed the fonts where based on. The other just the ones included. It does not exist in them as I stated before, and it shows a "missing metrics" message, but it shows the sign.

**Comment by kevinbarabash** [comment]
I had a look at the pull requests and realized what a silly question that was to ask.  Sorry about that.

There's some info https://github.com/Khan/KaTeX/issues/15 on how to go about updating the fonts.  I'm going to be looking into later this week to see if I can add ß, æ, Æ, œ, Œ, ø, Ø to our fonts.  I'll see if there's a way to add the euro symbol as well.  Once we get the symbol into the font the rest should be pretty straight forward.

**Comment by henzestplus** [comment]
no problem. the code part is ready, so when yo got them in, let me know when I can do a pull request again.

**Comment by kevinbarabash** [comment]
I'm going to close this in favor of #1107 which covers missing monetary indicators in general.
