### ISSUE TITLE
Function argument restructuring

### ISSUE THREAD

**Issue by gagern** [Khan/KaTeX#255]
Currently the arguments to a function handler are first the name of the function, then the arguments of the function as separate arguments, then the positions of these arguments, with `this` pointing at the parser. All of this feels pretty mixed-up. Things become even worse for the newly merged environments, where we need two more arguments, `pos` and `mode`.

I can think two possible solutions. Either make the number of arguments fixed. I.e. always pass `parser, func, args, positions` in a fixed order, with `args` being an array of arguments, and `this` unset (i.e. equal to `window` in non-strict mode). Or let the function arguments in TeX and JS agree completely, wrapping everything else in `this`. So you'd have a custom-made `this` object (some small JSON constructed for the purpose), with `this.parser`, `this.lexer`, `this.name` and so on.

For the positions, an alternative to the `positions` array might be blurring the distinction between `ParseNode` and `ParseResult`, so that the object which holds the type also holds the position. That would mean keeping position information throughout the tree, but I believe that it would greatly simplify things in a number of places.

*This is a spin-off from https://github.com/Khan/KaTeX/pull/246#issuecomment-113141856, one of two.*

**Comment by kevinb7** [comment]
I feel like ```ParseNode``` and ```ParseResult``` should probably be merged into one.  The main goal of ```ParseResult``` is to add position information to each node.  Libraries like esprima and acorn which parse JavaScript into an AST add location metadata to each node as code is being parsed.  It seems to work well.  Having the start and end locations of each node might open up some interesting use cases.  It would have the more immediate effect of removing the need for positions.  It also removes an extra layter of indirection in many places.

I like the idea of having ```parser```, ```lexer```, ```name```, and ```mode``` on ```this``` and passing in the args from the latex function as is... with optional arguments coming at the end?

Thoughts @xymostech @spicyj ?

**Comment by xymostech** [comment]
> make the number of arguments fixed. I.e. always `pass parser, func, args, positions` in a fixed order, with `args` being an array of arguments, and `this` unset

I prefer this much more than the custom `this` value. Abusing `.apply` just to tack on extra values seems really strange. Maybe we could instead pass in an `options` parameter as the first argument that contains `parser`, `lexer`, `name`, `mode`, `positions`, etc?

**Comment by gagern** [comment]
Having parser, lexer and so on accessible by name, not position, certainly seems desirable to me. I guess I'd call that object `context`, since to me `options` sounds more like JSON-structured data, which the parser is not. If we had ES6 with its argument destructuring syntax, I'd very much favor this approach with the arguments in an array. As it is, using it means we loose the naming of the arguments in the function head. We can probably make up for that to some degree by following a convention of always decomposing the arguments array at the very beginning of the body.

Seeing how @kevinb7 and @xymostech favored different approaches, and myself being indifferent, I'll wait a bit to see whether a consensus emerges one way or another.

**Comment by kevinb7** [comment]
@gagern I'm in agreement with @xymostech.  The only reason why I suggest the other approach is that it wouldn't have induced as many changes.  Since https://github.com/Khan/KaTeX/pull/262 already touches a lot of the code base we may as well do the right thing and make handlers less magical.

**Comment by kevinb7** [comment]
Also, it's good to differentiate ```context``` from ```options```.

**Comment by xymostech** [comment]
:+1: `context` sounds good

**Comment by kevinbarabash** [comment]
Closed by https://github.com/Khan/KaTeX/pull/356.
