### ISSUE TITLE
Break up array of function declarations

### ISSUE THREAD

**Issue by gagern** [Khan/KaTeX#256]
In `functions.js`, the functions are stored in two big arrays, namely `functions` and `duplicateFunctions`. This makes it hard to mix code which is not a LaTeX function in with the rest. To prove my point, see how the `delimiters` constant array is located just before `duplicateFunctions`, while in fact it belongs to the implementation of the delimiter functions which is quite a bit down from that. This makes reading those functions harder.

I'd prefer a way where each function definition occurs at the top level, so that there is no motivation to separate things location-wise which belong together conceptually. Ideally, we'd design that in such a way that the distinction between single-name and multi-name functions becomes less pronounced, so that if a function grows a second name, it doesn't have to get moved around, thus making the diff smaller and easier to read.

How about something like this:

```js
declareFunction(["\\name1", "\\name2"], {
    numArgs: 2
}, function(…) {
    …
});
```

I guess that if there is only a single name, the first argument could be simplified from an array to a single string. And if the number of arguments is the only option, the second argument could be simplified to a single number. The `declareFunction` could take care of all the defaults currently handled in the loop at the end of the file, which has the added benefit of restricting any variables it uses to the scope of that function. And finally, having the code indented like this means the body of the handler has only four spaces of indentation, not sixteen as is currently the case for `duplicateFunctions`. Similar changes could be made for environments.

*This is a spin-off from https://github.com/Khan/KaTeX/pull/246#issuecomment-113141856, one of two.*

**Comment by kevinb7** [comment]
I think this makes a lot of sense.  We'd probably want to do this for symbols as well.  I'd like to hear @xymostech's and @spicyj's thoughts on this.

**Comment by gagern** [comment]
Come to think of it, `groupTypes` in `buildHTML.js` is suffering from a mild case of the same: one big array, where you can't simply insert auxiliary functions. There my preferred notation would be changing the `genfrac: function(…) {` to `groupTypes.genfrac = function(…) {`, thus reducing the nesting depth by one level and allowing for other code to get mixed with the group rendering code.

**Comment by kevinb7** [comment]
Why use a different pattern in this case?

**Comment by gagern** [comment]
Mainly to get rid of quotes. `funcs["\\frac"] = { … }` would not work well with several functions sharing one implementation (i.e. `duplicateFunctions`), and would still have to contain quotation marks due to the name which is not a valid identifier. However,

```js
groupType("genfrac", function(…) { … });
```

looks more verbose and obscure than

```js
groupTypes.genfrac = function(…) { … };
```

since I'd wonder what that string is, whether it's more than an identifier naming a property. But I don't insist on this. If you prefer having installer function in all the cases, that's fine. Experiments indicate that with such an installer function the result might even get ulified more efficiently, since the function is assigned a single-letter name while the object variable is not.

**Comment by kevinb7** [comment]
I was curious more than anything else.  Since there aren't other arguments in this case, it does look quite verbose (and non-idiomatic) to write ```groupType("genfrac", function(…) { … });```.

**Comment by spicyj** [comment]
> since the function is assigned a single-letter name while the object variable is not.

Both should get munged to a single letter; if that's not happening we should fix our uglify config.

**Comment by gagern** [comment]
>> since the function is assigned a single-letter name while the object variable is not.

> Both should get munged to a single letter; if that's not happening we should fix our uglify config.

Yes, they do get mangled down. Apparently there was something strange about my toy example. So one more reason to stick with the idiomatic assignment version.

Does the lack of more substantial comments to this issue indicate silent agreement on the parts of @xymostech and @spicyj? Or should we wait for explicit approval before considering the PR for inclusion?

**Comment by kevinb7** [comment]
@gagern conceptually, I think the changes are fine.  I think the main issues with https://github.com/Khan/KaTeX/pull/262 is that it's a huge pull request and we have limited resources.  Splitting it up makes it easier to review, but it still takes time.  We should really add something to CONTRIBUTING.md that states our preference for small pull requests and our rationale behind it.

Please see https://github.com/Khan/KaTeX/issues/266#issuecomment-115564114 for more details.

**Comment by kevinbarabash** [comment]
I believe what was discussed here has been implemented.
