### ISSUE TITLE
Support bold fonts

### ISSUE THREAD

**Issue by gagern** [Khan/KaTeX#259]
The KaTeX repository contains several bold fonts, but apparently there are no functions to switch to them. It would be nice to change that.

Perhaps this can build on the work being done in #132?

**Comment by kevinb7** [comment]
Adding support for ```\mathbf``` in https://github.com/Khan/KaTeX/pull/132.

**Comment by PeterBocan** [comment]
Is it released in latest version? I mean the font support.

**Comment by kevinb7** [comment]
Not yet.  I still need to get https://github.com/Khan/KaTeX/pull/291 and https://github.com/Khan/KaTeX/pull/292 merged in.

**Comment by gagern** [comment]
I should have indicated that I'm closing this as a duplicate, or rather a subset of 132.
