### ISSUE TITLE
Accept unicode from mathematical alphabets on input

### ISSUE THREAD

**Issue by gagern** [Khan/KaTeX#260]
While #243 is discussing ways of accepting unicode characters as input for those situations where the output is using the same unicode symbol, we don't use special symbols on output for the fonts #132 is woking on, but instead use regular latin letters with a special font. Nevertheless it would be nice if we could still accept these special unicode symbols on input.
#51 already gave some translation tables, but in my eyes it essentially boils down to these sets:
- 𝔸𝔹ℂ𝔻𝔼𝔽𝔾ℍ𝕀𝕁𝕂𝕃𝕄ℕ𝕆ℙℚℝ𝕊𝕋𝕌𝕍𝕎𝕏𝕐ℤ𝕜
- 𝔄𝔅ℭ𝔇𝔈𝔉𝔊ℌℑ𝔍𝔎𝔏𝔐𝔑𝔒𝔓𝔔ℜ𝔖𝔗𝔘𝔙𝔚𝔛𝔜ℨ𝔞𝔟𝔠𝔡𝔢𝔣𝔤𝔥𝔦𝔧𝔨𝔩𝔪𝔫𝔬𝔭𝔮𝔯𝔰𝔱𝔲𝔳𝔴𝔵𝔶𝔷
- 𝒜ℬ𝒞𝒟ℰℱ𝒢ℋℐ𝒥𝒦ℒℳ𝒩𝒪𝒫𝒬ℛ𝒮𝒯𝒰𝒱𝒲𝒳𝒴𝒵
- 𝓐𝓑𝓒𝓓𝓔𝓕𝓖𝓗𝓘𝓙𝓚𝓛𝓜𝓝𝓞𝓟𝓠𝓡𝓢𝓣𝓤𝓥𝓦𝓧𝓨𝓩

The first two of these sets should be fairly non-controversial. For the latter two, I'm less sure. Unicode doesn't distinguish between script and caligraphic, so we could map the third to either `\mathscr` or `\mathcal`. The last set is obviously bold, and we only have a bold version of KaTeX_Caligraphic, so perhaps we should map everything to `\mathcal` and add some boldification (see #259) to the latter.

When working with string literals for these beasts, keep in mind that many of these letters are outside of the BMP, so they are encoded using two UTF-16 code units in JavaScript. A simple `charAt` won't always suffice for these cases. I believe that a conforming JavaScript RegExp engine should be able to deal with non-BMP codepoints.

**Comment by gagern** [comment]
Another thing that might be entered different from how we'd render it are accents. They might get entered using precomposed symbols, but NFD normalization could split that up into a symbol and an accent, which we might have in our fonts and might be able to render accordingly.

**Comment by kevinb7** [comment]
> When working with string literals for these beasts, keep in mind that many of these letters are outside of the BMP, so they are encoded using two UTF-16 code units in JavaScript.

We should probably use https://github.com/zloirock/core-js#ecmascript-6-string--regexp to deal with this.

@gagern I'm trying to understand the use case for implementing this.  What's your workflow such that these characters would end up in a KaTeX string?

I do think we should do NFD, but that feels like it should be separate issue.

**Comment by gagern** [comment]
One use case is when I copy and paste stuff from a different web document which uses Unicode. A second use case is pasting from my own E-Mail, where I often use Unicode to write down math. A third use case is using the compose key in my Linux keyboard configuration, which allows me to enter all these greek and double-struck letters rather quickly, and which makes the input text shorter and easier to read. And finally, for accents, I'm from Germany so umlauts are common in my daily work. More likely for `\text` than for math symbols, though. Having them in a separate issue feels fine.

**Comment by gagern** [comment]
According to [my roadmap](https://gist.github.com/gagern/656ab9538306b90460b1), this issue here would be without unsatisfied dependencies now, but seeing how the lexer currently won't accept these symbols on input, I believe that it is probably best put on hold until https://github.com/gagern/KaTeX/commit/8496a1e40f8dfbfc8dd7d2e7b5096bd5c2b01c02 or something similar extends the scope of the lexer.

**Comment by kevinbarabash** [comment]
@ronkok is there anything left to do on this?

**Comment by ronkok** [comment]
I believe that this issue can be closed. We resolved the script/calligraphic ambiguity in favor of script. Having done so, there are no Unicode code points available with which to support calligraphic.

Except for that nuance, we now support everything requested in this PR, and more.
