### ISSUE TITLE
Snapshot alternatives

### ISSUE THREAD

**Issue by gagern** [Khan/KaTeX#263]
In https://github.com/Khan/KaTeX/pull/246#issuecomment-112148381 I asked about whether PhantomJS could/should be used to create snapshots, instead of Selenium. Today [I gave that a try](https://github.com/gagern/KaTeX/commits/phantomjs-experiments), using the phantomjs 1.9.0 package that comes with Ubuntu 14.04 (though 15.04 is still at 1.9.0). I stayed with Docker for now, since that (with Boot2Docker) appears to be the most reliable option for cross-platform reproducibility, but I envisioned packaging phantomjs and its libs into a tarball which could be used with a `LD_LIBRARY_PATH` override, on Linux without Docker and Ubuntu and all that stuff along. [Here is the Dockerfile.](https://github.com/gagern/KaTeX/blob/phantomjs-experiments/dockers/Phantom/Dockerfile)

I used this to execute a script which was accessed through the `/KaTeX` mount and named on the command line. The docker I created is in no way KaTeX-Specific and therefore highly reusable. (I'll likely upload it to the DockerHub if I ever create an account there.) I had the script access the KaTeX development server running outside the docker, on my development machine, thus avoiding the need for node and other stuff inside the docker.

So far, so good. But when I got [the first results](https://github.com/gagern/KaTeX/commit/7a1b0158f95ca06cf52a3f9742cf4020301ae3d3), things looked *really bad.* Quite a number of test cases had severe problems with vertical positioning. So what should we learn from this? One thing to learn is that the QtWebKit version used by that version of PhantomJS doesn't seem particularly well suited to rendering our output. If that browser is affected, how many other browsers might be affected as well? Should we diagnose the bug, make sure that QtWebKit is violating some spec to render stuff the way it does, then file a bug report? Or should we try to work around the issue, assuming that others might be using QtWebKit or something related in one way or another, so we should support it?

Another thing I learned is that even in the days of the WHATWG, it matters quite a lot what browser you are using. Should we therefore extend our snapshots to not only cover Firefox, but at least Chrome as well? If we do, then I would suggest we stop building our own specific docker image, and instead build on the [selenium images available from the docker hub](https://registry.hub.docker.com/repos/selenium/). That way, users don't have to build images themselves, which can take considerable time in a VM, but instead just download them. And at 531.5M the standalonge firefox image for selenium is still smaller than the 790.6M for the KaTeX screenshotter as it currently stands. We could do some of the stuff I did in my experiments: run the development server outside the docker, so that you need no modifications to the images in order to run the tests.

The current version of PhantomJS is 2.0.0. Building that from source takes ages, but I tried [this docker image](https://registry.hub.docker.com/u/servebox/phantomjs/). The vertical spacing was better with that, but the fonts were all wrong. I'm not sure whether that's some artifact from the build environment, or another bug in PhantomJS. I guess I'll compile a version on Gentoo tomorrow, see what that does, to distinguish between these possibilities.

**Comment by spicyj** [comment]
PhantomJS's WebKit is extremely old. We support current-ish versions of Chrome/Firefox/Safari/etc and down to IE8. Looking into the selenium images seems like a good idea (I didn't realize those existed). Ideally we could screenshot IE too but I don't know of a good way to do so.

**Comment by gagern** [comment]
> Ideally we could screenshot IE too but I don't know of a good way to do so.

My best bet would be using [BrowserStack](https://www.browserstack.com/). They [write](https://www.browserstack.com/pricing):

> **Free for Open Source**  
> We love open source projects. Choose any of our plans. [Contact us](https://www.browserstack.com/contact) with details of your project.

To you want to take that approach? If so, if there is any chance that arbitrary contributors, including new ones, could make use of the service, then all the docker setup might be superfluous. But I fear that access to the relevant authentication credentials would be a problem, and we'd need docker or something similar still for local tests.

**Comment by spicyj** [comment]
Good idea. I had looked at BrowserStack earlier but it looked at that time like screenshots probably weren't available for open source projects. Maybe they now are.

**Comment by gagern** [comment]
Will someone who's officially an owner of this project contact BrowserStack, and report back here on this issue?

**Comment by kevinb7** [comment]
@gagern I'm not particularly keen on doing multi-browser testing.  We are aware of a few rendering issues, but for the most part we haven't seen that many rendering complaints.  I think the main purpose of the snapshot tests is to make sure that the layout doesn't change.  I think it would be unlikely that a change would result in a layout change in a different browser but not in Firefox.  If we saw a higher incidence of rendering issues and different renderings in different browsers then it might be worthwhile to pursue this.  Here's the list of rendering bugs that I remember.

- https://github.com/Khan/KaTeX/issues/45 (stock Android browser, not much we can do)
- https://github.com/Khan/KaTeX/issues/40 (square root is wonky)
- https://github.com/Khan/KaTeX/issues/60 (square root is wonky)
- https://github.com/Khan/KaTeX/issues/248 (equals sign hinting could be better)

**Comment by spicyj** [comment]
I would find cross-browser screenshotting valuable. A couple times I've looked at the markup we generate and thought that it could be simplified, only to find (hours later) that it breaks positioning in IE. Would be much easier if it could be automated. I'll write them.

**Comment by kevinb7** [comment]
@spicyj good point.  @gagern I'll contact them and see what they can do for us as an open source project.  We probably just care about screenshots.  I've used one of their live sessions in the past, but debugging was a bit of pain.  It's easier to use http://dev.modern.ie/tools/vms/ for that.

**Comment by spicyj** [comment]
@kevinb7 I already emailed, as I said I would in my comment.

**Comment by kevinb7** [comment]
@spicyj updated my comment to reflect this.  I have not emailed them so I think we're all good.  Thanks for emailing them.

**Comment by spicyj** [comment]
:+1:

**Comment by kevinb7** [comment]
Thanks to @spicyj we now have an open source account with BrowserStack.

**Comment by gagern** [comment]
I've had a closer look at [the API](https://www.browserstack.com/screenshots/api). The way I see it, the **first** (and most simple) step should be uploading our test cases (i.e. the test.html with all its dependencies) to some public web server (like some subdirectory of http://khan.github.io/KaTeX/ via [gh-pages](https://github.com/Khan/KaTeX/tree/gh-pages)), devising a script to issue a bunch of snapshot requests for that and collect the results, then save them somewhere for further study, perhaps including diffs created by ImageMagick.

I wonder whether the way `test.html` can be used to include *any* HTML into a document can be used for a cross-site scripting attack on `khan.github.io`. If there is at least some danger of that, we should either create a corresponding set of static pages, or devise some other scheme which restricts the set of possible inputs to our list of test cases. Perhaps by including the `ss_data.json` one way or another (via ajax or inside a `<script>` tag) and using the key as a query parameter.

The **second** step could be tweaking that setup to make use of a [local testing connection](https://www.browserstack.com/local-testing) so that an in-development version can be tested before it gets merged into master. This should be particularly useful when trying to improve some rendering which is at the moment unsatisfactory.

As a **third** step, we might one day make this part of Travis tests, by make the credentials available to Travis using an [encrypted environment variable](http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables). But I guess that's quite a bit in the future, if ever.

**Comment by gagern** [comment]
I've created snapshots for a bunch of configurations ([code](https://github.com/gagern/KaTeX/tree/browserstack/browserstack), [results](https://github.com/gagern/KaTeX/tree/browserstackResults)). Findings:

1. IE 6, 7 and 8 yield empty windows for all test cases. Is this an IE problem, or a Browserstack problem?
2. **Accents** missing for Chrome 15 and 20 and 25 on Windows 7, but not for 25 on OS X. Accents for Firefox on Windows look ugly (two different line widths), no matter the versions. Horizontal placement of accents looks wrong on Safari, Safari 8 in particular.
3. **Arrays** fails spectacularly for Chrome 15, but this might be a sporadic problem since I think I saw this rendered correctly in some run. Firefox 15 on Windows has some problems with medium-sized delimiters, which are not present in FF 10 or 20. Safari 5.1 has wrong vertical placement.
4. **ArrayType** in Chrome 15 and Safari 5.1 has wrong vertical position.
5. **BinomTest** in Chrome 15 and 20 and in Firefox 15 on Windows is lacking big delimiters. From IE 10 to 11 some positions shifted, the horizontal one in the smallest binomial coefficient definitely for the worse. Chrome 15 and 20 as well as Safari 5.1 have incorrect vertical position.
6. **Cases:** Chrome 15 lacks the big curly brace, in 20 it's incomplete.
7. **DeepFontSizing** on Chrome 15 and 20 and Safari 5.1 has wrong vertical placement, and on Chrome 20 and Firefox 10 it also lacks some symbols.

I could continue with the other test cases, but I'm not sure a much longer list will add value at this point. What versions do we want to officially support? A look at the [timeline of browsers](https://en.wikipedia.org/wiki/Timeline_of_web_browsers) might be useful. Given my choice, I'd like to officially require IE 9 or later, FF 20 or later, Chrome 25 or later, Safari 6 or later. If you want me to, I can change the set of browsers to narrow down the point of sufficient support between FF 15 and 20 as well as between Chrome 20 and 25. Do you agree?

**Comment by gagern** [comment]
Vertical placement in Chrome improves significantly from 22 to 23. However, Chrome 24 on BrowserStack apparently has problems processing our SqrtRoot test case, which never leaves the `processing` state. So requiring Chrome 25 or later sounds prudent. The arrows in the Accents test case first appear in Chrome 35 on Windows, they are still absent in Chrome 34 on Windows 7. Do we want to address this, or require Chrome 35 (from May 2014)?

The delimiters in the Arrays test case on Firefox are far more erratic, disappearing and reappearing between versions over a wide range of versions. Perhaps there is some kind of non-determinism going on here. I've seen missing delimiters as late as FF 25.

**Comment by kevinbarabash** [comment]
@gagern I think this is resolved thanks to all of your work in this area.
