### ISSUE TITLE
\llap and \rlap should render their content in text mode

### ISSUE THREAD

**Issue by gagern** [Khan/KaTeX#270]
In LaTeX, `\llap`and `\rlap` render their content in text mode. I found this while creating LaTeX screenshots as part of #268. The image has KaTeX to the left, LaTeX to the right, and a diff of both below.

![lap3](https://cloud.githubusercontent.com/assets/190759/8351954/6bf921dc-1b31-11e5-926a-700c9dffc6a7.png)

The `RlapBug` test case also looks different in LaTeX: its numerator is centered. Is this a consequence of the mode change, in some way?

_(With a bit of luck, fixing this issue will also get rid of the weird non-determinism of the `Lap` example when creating screenshots.)_

**Comment by spicyj** [comment]
Wow! Today I learned. I guess I now remember that `\mathllap` and friends are provided by `mathtools`: https://www.tug.org/TUGboat/tb22-4/tb72perlS.pdf

**Comment by kevinbarabash** [comment]
This is fixed on master.  Still need to do a release with it.
