### ISSUE TITLE
render unsupported commands and symbols as red source text

### ISSUE THREAD

**Issue by kevinb7** [Khan/KaTeX#273]
![screen shot 2015-06-26 at 11 56 31 pm](https://cloud.githubusercontent.com/assets/1044413/8390672/ff416ac0-1c5e-11e5-8715-8412e23c350c.png)

This provides feedback for users as to what going wrong without having to look at the console.  This is especially useful in interactive systems used by content creators.

**Comment by spicyj** [comment]
As an option, presumably.

**Comment by kevinb7** [comment]
You bet.  There could be a color parameter too.

**Comment by spicyj** [comment]
If you're feeling crafty, it could be like

```
handleError: (text) => `\color{red}{${text}}`
```

or something.

**Comment by kevinb7** [comment]
Showing other errors might be useful, but it might be annoying to see stuff like ```Expected '}', got 'EOF'``` at the end of rendering as you're typing.

**Comment by spicyj** [comment]
MathJax seems to just shows your input in a box for errors like that. `$\x{$` displays as:

![image](https://cloud.githubusercontent.com/assets/6820/8766367/1a15b2ba-2dea-11e5-9c2a-944dd7cf7780.png)

**Comment by kevinb7** [comment]
That shouldn't be too difficult.

**Comment by cben** [comment]
Input in a box easy enough with current API (catch error, put text in a span).  (Though a built-in option with default style could be handy.)
But accepting unknown \foo and going on with parsing would be a real advance.
(Of course it has to be optional — if I'm trying KaTeX and falling back to MathJax, I wan't an error for \foo in case MJ does handle it)
