### ISSUE TITLE
add a support matrix to the README.md?

### ISSUE THREAD

**Issue by Pomax** [Khan/KaTeX#276]
Given the still in-development status of KaTeX, it might be worth-while to put a support matrix into the README.md, so that users can see whether the "standard library" commands and environments their code uses is supported or not (and if there is an open issue for it, a link to that issue). A lot of nice environments landed in the past few months, a support matrix would go a long way to making users aware of those changes since last they checked.

**Comment by kevinb7** [comment]
Agreed.  Eventually would like to see https://github.com/Khan/KaTeX/issues/103 as well.

**Comment by spicyj** [comment]
That's what https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX was _supposed_ to be.

**Comment by kevinb7** [comment]
After thinking about it putting it directly in the README would make it cluttered.  How about we:
- [ ] link to that wiki page from the README
- [ ] update the wiki page
- [ ] update CONTIBUTING.md to make sure people update the wiki when adding new stuff
- [ ] make it part of a code review checklist?
- [ ] auto-generate a list of supported commands and save it in COMMANDS.md and link from the README to COMMANDS.md

**Comment by Pomax** [comment]
I'd certainly try to make the information immediately findable, so ideally it's in the README.md (because people rarely click through from a readme if they just want the summary). One idea would be to generate the support matrix based on the unit tests every time KaTeX is built, and then automatically update the README.md with that information (it's fairly easy to grep a README.md for a section `## Supported macros and environments` up to the next `#`). That way people won't need to click through, and no one has to maintain the support matrix, tests passing will set support to "true" and everything that wasn't marked true stays false. Or `X`, or red, or whatever works =)

**Comment by kevinbarabash** [comment]
I think KaTeX is big enough that we should probably have better documentation as part of the homepage and more actively direct people from the gitHub.com/Khan/KaTeX to the homepage.
