### ISSUE TITLE
parse error in subscripts

### ISSUE THREAD

**Issue by norbusan** [Khan/KaTeX#277]
Hi,
the following code produces a parse error (in 0.4.3)
  $\bigwedge_{n \not= m} ...$
with the error being
`````
ParseError: KaTeX parse error: Expected '}', got '\not' at position 35: igwedge_{n \not̲= m} ....
`````

**Comment by kevinb7** [comment]
We don't support ```\not``` yet.  For the time being use ```\neq``` instead of ```\not=```.
