### ISSUE TITLE
Add support for the cases environment

### ISSUE THREAD

**Issue by azotova** [Khan/KaTeX#278]
While #246 added support for the `\begin`...` \end` environment (which is terrific!), it would be also great to support `cases` environment in order to create systems of simultaneous equations (examples here: https://kogler.wordpress.com/2008/03/21/latex-multiline-equations-systems-and-matrices/).

**Comment by kevinb7** [comment]
The ```cases``` environment looks really useful, especially for piecewise functions.

**Comment by gagern** [comment]
Relevant part of `amsmath.sty`:

```tex
\renewenvironment{cases}{%
  \matrix@check\cases\env@cases
}{%
  \endarray\right.%
}
\def\env@cases{%
  \let\@ifnextchar\new@ifnextchar
  \left\lbrace
  \def\arraystretch{1.2}%
  \array{@{}l@{\quad}l@{}}%
}
```

The most important here seems to be the non-default `\arraystretch`, which the current `array` implementation [doesn't support yet](https://github.com/Khan/KaTeX/blob/2f7a54877a412058fe2a134d973aa6fb0d448f50/src/buildHTML.js#L514).

**Comment by kevinb7** [comment]
Implemented by @gagern.  This is now on master, but isn't yet part of an official release.
