### ISSUE TITLE
Spaces have zero-width in HTML generated from text mode

### ISSUE THREAD

**Issue by senshu** [Khan/KaTeX#281]
Using KaTeX 0.4.3

Steps to reproduce:

1. Write a formula using the `\text` function where the argument contains spaces. For instance: `\text{a b c}`
2. Render it to HTML.

Observed result:

In the generated HTML:
* On screen, the text looks like there are no spaces at all ("abc").
* The markup contains an empty `<span class="mord mspace">` for each space.

From the stylesheet `katex.less`, I see that there is no default width associated with the `mspace` class. As a consequence, the width of the span element is zero. An additional class, such as `thinspace`, is needed.

Currently, the only workaround I could find was to use an explicit spacing function, but they are not supported in text mode:

```latex
\text{a} \, \text{b} \, \text{c}
```

**Comment by spicyj** [comment]
It should include a nonbreaking space (https://github.com/Khan/KaTeX/blob/41e3fa66599b125677919673c0139324beec3f0c/src/symbols.js#L2507). Try at http://khan.github.io/KaTeX/ and I think you'll find that it works.

How are you loading the JS? I'm guessing an encoding problem.

**Comment by senshu** [comment]
> It should include a nonbreaking space

OK. I sould have tried the demo before.

My equations are embedded in Markdown files. First, all equations are converted to HTML, then, [marked](https://github.com/chjj/marked) is run on the resulting files.
Actually it seems that [the marked lexer converts non-breaking spaces to ordinary spaces](https://github.com/chjj/marked/blob/master/lib/marked.js#L140).

I suppose that there would be no problem if KaTeX generated an HTML entity instead of a plain character.

BTW I have also tried to run marked first but other issues arise since TeX source is incorrectly processed as Markdown in some cases.

**Comment by spicyj** [comment]
A single space should still be fine, though of course it won't break. If you're mangling the HTML that KaTeX generates after you get it, it's hard for us to make any guarantees about how things will work. Generating `&nbsp;` could work better in some cases but what's to stop marked from converting that to a space too? I think using a nbsp unicode character is clear in intent.

One thing you could consider is substituting in some sort of placeholder to the markdown, running marked over it, then swapping in the HTML where the placeholder was. That's what Khan Academy did for a long time. Now, we use https://github.com/Khan/simple-markdown (which is designed to be extensible) in conjunction with some [custom rules](https://github.com/Khan/perseus/blob/dc8536c264587f1c27ae3fecc99e469fb2319a12/src/perseus-markdown.jsx) to parse math.

**Comment by senshu** [comment]
Thanks for taking the time to answer. I agree that the issue is in marked, not in KaTeX (the author of marked has a different opinion though: https://github.com/chjj/marked/issues/363).

I will try to find a solution that fits my workflow. Unfortunately, I already have a large document base that relies on marked and I'm not ready to switch to another markdown processor yet.
