### ISSUE TITLE
replace fontforge with freetype-py or fonttools

### ISSUE THREAD

**Issue by kevinb7** [Khan/KaTeX#288]
We only use fontforge to extract font metrics, but it's big and requires extra dependencies like XQuartz on Mac OS X.  I found installing fontforge on Mac OS X difficult because it was compiled with a different version of Python so I had to install that version of Python alongside the official one and change one of the scripts to use that version.  

freetype-py on the other hand is smaller and easier to install.  I ran the following two commands and was up and running in minutes:
- brew install freetype
- pip install freetype-py

It's also pretty easy to use:
```
import freetype
face = freetype.Face("static/fonts/KaTeX_Main-Regular.ttf")
face.load_char('S')
print face.glyph.metrics.horiAdvance
...
```
This should make it easier for people who want to add even more font commands after https://github.com/Khan/KaTeX/issues/132 lands like ```\mathsfbf```, etc. or use alternative fonts like AMS Euler or STIX as requested in https://github.com/Khan/KaTeX/issues/123.

**Comment by gagern** [comment]
Have you also considered [fonttools](https://github.com/behdad/fonttools)? As far as I can tell, it is pure Python, with no dependency on freetype, which should ease portability quite a bit. In particular, it is to be hoped that it works with the OS X version of Python, with no need to install custom Python versions.

So far I've only been using the `ttx` command line tool from fonttools to extract the `cmap` tables from the fonts, see https://github.com/gagern/KaTeX/commit/86030f7ca43ea3966c5027dafdf44d2ad5c86f03. But it can parse many other TTF tables as well, and I don't think one would have to go via the XML file but could use it directly as a Python package.

**Comment by gagern** [comment]
> `print face.glyph.metrics.horiAdvance`

That could be read from the [`hmtx` table](http://www.microsoft.com/typography/otspec/hmtx.htm) using fonttools, but we don't actually store horizontal advance, do we?

The way I read [`extract_ttfs.py`](https://github.com/Khan/KaTeX/blob/d61a04c80d14577212e3e98e83ff2da0c7a70907/metrics/extract_ttfs.py#L63), the skew and italic correction come from somewhere else, and only the height and depth come from the TTF, namely form the bounding box of the character. `ttx` exports the bounding box using the `yMin` and `yMax` attributes of the `TTGlyph` elements of the [`glyf` table](http://www.microsoft.com/typography/otspec/glyf.htm). So the data should be accessible via fonttools. If you want to, you can have a look at how fonttools [handles the `glyf` table](https://github.com/behdad/fonttools/blob/master/Lib/fontTools/ttLib/tables/_g_l_y_f.py).

**Comment by kevinb7** [comment]
> Have you also considered fonttools? As far as I can tell, it is pure Python, with no dependency on freetype, which should ease portability quite a bit.

Definitely worth investigation.

**Comment by gagern** [comment]
Making good progress here, will have a pull request soon.

**Comment by gagern** [comment]
I'm trying to track down some non-determinism here. Character 305 of the Main-Regular font sometimes has skew correction 0.02778 and sometimes 0.0. Character 567 is affected in a similar fashion, and occasionally I've seen *many* symbols change their data, but right now I can't reproduce this.

At first I thought these problems to be due to the fact that `extract_ttfs.py` uses `ord(char)` as an index when writing its result, which does not overwrite the existing value with index `str(ord(char))` so it's pure luck which of the two will end up in the final result. But the issue with character 305 is already present one step earlier, at the output of `extract_tfms.py`. Perhaps there is another similar mistake somewhere in there.

**Comment by kevinb7** [comment]
I ran `./mapping.pl | ./extract_tfms.py > test.json` a few times and the skew for character 305 was `0.0` each time.

**Comment by gagern** [comment]
OK, looks as if we had some problem in `mapping.pl`. The character 305 of Main-Regular is sometimes associated with `cmr10` and sometimes with `cmmi10`.

**Comment by kevinb7** [comment]
Nice find.  We should be using `cmmi10` for both `\imath` and `\jmath` because these glyphs don't exist in `cmr10`.
http://www.math.union.edu/~dpvc/jsmath/symbols/cmr10.html
http://www.math.union.edu/~dpvc/jsmath/symbols/cmmi10.html

**Comment by gagern** [comment]
Yes, there are conflicting mappings [for cmr10](https://github.com/Khan/KaTeX/blob/master/metrics/mapping.pl#L23) and [for cmmi10](https://github.com/Khan/KaTeX/blob/master/metrics/mapping.pl#L151).

**Comment by gagern** [comment]
I think we should have some code to catch this kind of mistake and complain loudly…

**Comment by gagern** [comment]
Have a look at [my metrics branch](https://github.com/gagern/KaTeX/commits/metrics) to see the direction I'm going. Right now I think it's easier to complain in the normal course of operation and not have a unit test. Here is the complete list of things we have to fix:

```
Duplicate mapping 8723 for Main-Bold
Duplicate mapping 305 for Main-Bold
Duplicate mapping 567 for Main-Bold
Duplicate mapping 44 for Main-Bold
Duplicate mapping 46 for Main-Bold
Duplicate mapping 46 for Main-Regular
Duplicate mapping 44 for Main-Regular
Duplicate mapping 305 for Main-Regular
Duplicate mapping 567 for Main-Regular
Duplicate mapping 8723 for Main-Regular
```

**Comment by kevinb7** [comment]
> Right now I think it's easier to complain in the normal course of operation and not have a unit test

That makes sense.

**Comment by kevinb7** [comment]
We might still want to have tests to make sure the check is picking up issues that we think it should.

**Comment by gagern** [comment]
Instrumenting perl code is no fun, so I don't know how to achieve this and I don't think it's worth the effort. After all, we just saw that it picks up problems.

**Comment by gagern** [comment]
> Nice find. We should be using `cmmi10` for both `\imath` and `\jmath` because these glyphs don't exist in `cmr10`.

I disagree. \x10 and \x11 of `cmr10` are dotless i and j, and they match the \u0131 and \u0237 of the KaTeX_Main-Regular font since they are roman. So I'd say we delete the other mapping, resp. ensure that's against the Italic font.

**Comment by kevinb7** [comment]
Sorry, `\imath` and `\jmath` from `cmmi10` should map to Main-Italic and `\imath` and `\jmath` from `cmr10` should map to Main-Regular.

**Comment by gagern** [comment]
Would you agree that \x3A and \x3B of [cmmi10](http://www.math.union.edu/~dpvc/jsmath/symbols/cmmi10.html) likely refer to punctuation for old numerals?

**Comment by kevinb7** [comment]
> Have a look at my metrics branch to see the direction I'm going.

Looks good so far.  I left a couple of comments on some of the commits.

**Comment by kevinb7** [comment]
\x3A looks kind of a like the dot product operator because it's in the middle of the cell, but that maybe be because it doesn't have much height.  Are there specific unicode code points you're looking to map them to?
