### ISSUE TITLE
Support accents in all fonts that have them

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#289]
Right now we're using non-combining glyphs for most accents.  These are only available for ```Main-Regular``` and ```Main-Bold``` font faces.  We'd like to be able to use the accent glyph for the current font if it exists.  This depends on https://github.com/Khan/KaTeX/pull/132 which is adding general font support for things like ```\mathbb```, ```\mathfrak```, ```\mathbf```, etc.

Different accents require different horizontal shifts for the combining glyph to be lined up correctly.  These shifts are listed in mapping.pl.  If a horizontal shift exists for a particular accent then it should be exported to fontMetrics.js  These shift metrics should be stored in a separate table because there's not that many and we don't want to add extra entries to the main fontMetrics table if most of the values are 0.

At some point in the future we should probably do the same for skew metrics.

**Comment by brunovcosta** [comment]
up

**Comment by kevinbarabash** [comment]
This is fixed on master, but isn't in the current release.
