### ISSUE TITLE
How to deal with absolute dimensions

### ISSUE THREAD

**Issue by gagern** [Khan/KaTeX#296]
In KaTeX, all dimensions are given in `em`, which is relative to the current font size. However, there are some dimensions in the TeX world which are given in `pt` or some similar absolute value. Currently, expressing such dimensions in the DOM is either pretty complicated (manually resetting the size and style up front) or not accurate (if the current font is not the 10pt default).

The prime example which comes to my mind here is the `\nulldelimiterspace=1.2pt` discussed in https://github.com/Khan/KaTeX/pull/135#discussion-diff-32872033 and https://github.com/Khan/KaTeX/issues/249#issuecomment-119094270. If things are to look the way they do in TeX, then we have to make that box always 1.2/ptPerEm times the size of the unsized text style font size.

But how? I can think of several alternatives.
1. Add classes to reset to `textstyle` and `size5`, so that the size is always relative to the default font size. This is what I did in [@7dc8b68](https://github.com/gagern/KaTeX/blob/7dc8b6809239fe9be820e838b271ec274dc0a4cd/src/buildHTML.js#L158-L164).
2. Express the spacing as kerning (using `makeKern`) and then provide some function which takes the current `options` and the size in `pt` and does all the neccessary computation. #135 is using `makeKern`, but so far the resulting size is still relative to the current size and style.
3. Deliberately deviate from LaTeX and declare that all dimensions should scale with the font size.

**Comment by kevinbarabash** [comment]
This has been addressed in #732.
