### ISSUE TITLE
Systematic testing of error messages

### ISSUE THREAD

**Issue by gagern** [Khan/KaTeX#297]
We have a lot of error messages a.k.a. `ParseError` exceptions all over the place, and I feel like many of them don't receive any testing at all. Would it make sense to systematically add unit tests for all of them, ensuring that the right message gets generated, with the right error position indication? Should that go into `katex-spec.js` or some other file instead?

Come to think of it, such a systematic testing of rare code paths might well be the first step towards some code coverage control, e.g. using [istanbul](https://www.npmjs.com/package/istanbul). But that's a different issue, so let's stick to exceptions for now.

**Comment by kevinb7** [comment]
Good idea.  We should probably split `katex-spec.js` into separate spec files at some point.  Coverage is a good idea too.
