### ISSUE TITLE
Split fontMetrics in manually edited part and auto-generated part

### ISSUE THREAD

**Issue by gagern** [Khan/KaTeX#301]
I'm slightly conderned about the way `fontMetrics.js` contains a large amount of data (even more the more fonts we deal with) which is auto-generated, but also has some parts which are to be edited manually. For one thing, the whole diff usually doesn't show up on git. It would in my opinion be preferable to have one file which is *purely* auto-generated, and have another which contains all the hand-written parts. The auto-generated part could even be some JSON, I think. So you'd say

```js
var metricMap = require("fontMetricsData");
```

and let the generation process write to `fontMetricsData.json` (simply overwriting its content) instead of modifying `fontMetrics.js`. I haven't tested whether browserify can deal with JSON, but if not, adding a simple `module.exports =` to the front and calling it `fontMetricsData.js` isn't too hard.

Personally, I'd like to have the JSON formatted with one glyph per line, so that modifications can be seen more easily in the diff. On the other hand, we might want to think about ways to compactify that data, changing the field names into something position-dependent.

**Comment by kevinb7** [comment]
I was going to open an issue for this.  Thanks for doing so.  We should dump the data into file with a .json extension, then we don't have to worry about ```module.exports = ```.

**Comment by gagern** [comment]
Solved by #303.
