### ISSUE TITLE
Unit test code in /metrics

### ISSUE THREAD

**Issue by kevinb7** [Khan/KaTeX#302]
Suggested by @gagern in https://github.com/Khan/KaTeX/issues/288#issuecomment-120007428 after he found duplicate entries in mapping.pl in Main-Regular for `\imath` and `\jmath`.

**Comment by gagern** [comment]
If you want to unit-test things about fonts and their metrics, have a look at https://github.com/gagern/KaTeX/commit/7a209d7a618f367c553ae69bd07f4bd07eae7a2e?diff=unified. This is not unit testing the sanity checks in the various metrics scripts, but instead performing additional sanity checks which might require manual verification. For example

    Verify name yen of KaTeX_AMS-Regular glyph U+00a5 matches Yen of msam10 glyph 85=0x55

indicates a harmless naming discrepancy while

    Verify name underscore of KaTeX_Main-Regular glyph U+005f matches endash of cmr10 glyph 123=0x7b

sounds more disturbing. Investigating that (just as an example) I found out that in OT1 encoding, `\_` doesn't produce a character but some `\rule` instead. With `\usepackage[T1]{fontenc}` I get a box `\T1/cmr/m/n/10 _` but then `dvips` uses `sfrm1000.pfb` for that part of the file, and we aren't reading metrics from cm-super fonts at the moment. Perhaps we should.

I encourage you to look at the list which is part of that commit, and point out any lines in the output you think are worth investigating. I will do the same. And of course you can re-open this ticket here, unless you prefer a new one for the slightly different focus of the tests, namely not on the code but on the data.

By the way, note that the commit indicated above also produces font charts with various information, which might be very useful when investigating the reported issues but which I didn't include in the commit but generated in `build/charts`. So you might want to check out the [fontcheck branch](https://github.com/gagern/KaTeX/commits/fontcheck) and actually run the code to get a look at these files.

**Comment by kevinb7** [comment]
Interesting.  I will check out the branch this weekend.  @xymostech @spicyj will probably know more about some of these discrepancies.
