### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by gagern** [Khan/KaTeX#304]
In [this commit comment](https://github.com/gagern/KaTeX/commit/c20f06da510b228c0a83b6fdb561534581181cea#commitcomment-12086835) @kevinb7 wrote:

> wow, we were really out of date

as a reaction to me updating the browserify dependency from 2.29.1 to 10.2.4.

We're out of date with other dependencies as well, although not by as much:

```
$ npm outdated
Package           Current       Wanted  Latest  Location
clean-css          2.2.23       2.2.23   3.3.5  clean-css
express             3.3.8        3.3.8  4.13.1  express
jasmine-node  2.0.0-beta4  2.0.0-beta4  1.14.5  jasmine-node
less                1.7.5        1.7.5   2.5.1  less
```

Regarding Jasmine: the [jasmine package](https://www.npmjs.com/package/jasmine) is at 2.3.1 and I'd consider that a proper upgrade since jasmine-node [hasn't seen a commit](https://github.com/mhevery/jasmine-node/commits/master) in a long time.

Should we upgrade all these dependencies? What kinds of checks should we run to ensure that everything still works as it should?

**Comment by kevinb7** [comment]
My understand is that express 4 is not compatible with express 3 so we'll probably have to make changes.  In terms of checks to run, we'll want to run all of the tests and make the server sill works.

**Comment by gagern** [comment]
If people follow semantic versioning, every bump in major version number indicates some kind of incompatibility. Whether that actually affects us is a different question, though.

**Comment by gagern** [comment]
Reading https://github.com/strongloop/express/wiki/Migrating-from-3.x-to-4.x will help migrating the server. There is indeed a lot that changed there, but the migration instructions are well-written.

**Comment by kevinb7** [comment]
Unless there's a good reason to migrate we probably shouldn't bother.  I'm going to close this.  If there are dependencies that should be upgraded for specific reasons like bug fixes or features that we need let's deal with those on a per case basis.
