### ISSUE TITLE
"Built with KaTeX" page

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#305]
I was thinking it might be cool to show off other projects that are built using KaTeX.  Three.js does this, imo, to great effect: http://threejs.org/.

I saw a cool project on HN this morning that uses KaTeX: 
- https://news.ycombinator.com/item?id=9863152 
- https://github.com/AndrewBelt/hack.chat

Does anyone know of other projects?  Is there a way to search for projects that us KaTeX?

**Comment by kevinb7** [comment]
Here's a lit of projects that depend on KaTeX: http://registry.npmjs.org/-/_view/dependedUpon?group_level=3&startkey=%5B%22katex%22%5D&endkey=%5B%22katex%22%2C%7B%7D%5D&skip=0&limit=1000

**Comment by kevinb7** [comment]
http://stackoverflow.com/questions/18796890/how-do-you-find-out-which-npm-modules-depend-on-yours suggests some tools which wrap this REST API.

**Comment by gagern** [comment]
Not every user of KaTeX uses npmjs to get it. How can we find the others? Go through the [3,900 hits for `katex.min.js` reported by Google](https://www.google.de/search?q=%22katex.min.js%22)?

**Comment by spicyj** [comment]
If we have a prominent list in the readme, people will probably see it and add themselves (if we ask them to).

**Comment by spicyj** [comment]
Most npm users won't count as dependents anyway because their apps aren't pushed to npm.

**Comment by kevinb7** [comment]
http://khan.github.io/react-components/#tex

**Comment by kevinb7** [comment]
http://algebra.js.org/

**Comment by kevinb7** [comment]
gitter

**Comment by spicyj** [comment]
https://www.expii.com/

**Comment by xymostech** [comment]
slides.com

**Comment by kevinbarabash** [comment]
http://acko.net/blog/mathbox2-pt2/

**Comment by kevinbarabash** [comment]
https://github.com/ianarawjo/KaTeX-iOS

**Comment by gagern** [comment]
* [Dropbox Paper](https://paper.dropbox.com/) as per #551.
* [Bokeh](http://bokeh.pydata.org/en/latest/) using [an extension](http://bokeh.pydata.org/en/latest/docs/user_guide/extensions_gallery/latex.html#userguide-extensions-examples-latex).
* [CindyJS](http://cindyjs.org/) which is what got me involved.

What do we do about this collection of projects? Put it in the [README](https://github.com/Khan/KaTeX/blob/master/README.md)? Put it in the [Wiki](https://github.com/Khan/KaTeX/wiki)? Put it on the [website](https://github.com/Khan/KaTeX/tree/gh-pages)? All of these?

**Comment by kevinbarabash** [comment]
We could start with the README b/c it's low cost but high visibility (compared to the wiki).

**Comment by edemaine** [comment]
* Gradescope
* Facebook Messenger
* Presumably some Khan Academy stuff :-)

Just discovered this list.  I agree that a section of the README would be cool: this will really show the importance of KaTeX.  Maybe just a comma-separated list of linked titles would be a good start (though of course images/logos would be cooler, but harder to maintain).

**Comment by utkarshrai** [comment]
Hi, This is currently the only issue labeled "good first issue". I would like to take this. Thinking of adding few popular names in the main ReadMe and add a link to a gist containing all the other names.

**Comment by willymcallister** [comment]
Please include spinningnumbers.org.

**Comment by kevinbarabash** [comment]
https://docs.gitlab.com/ee/user/markdown.html#math

**Comment by kevinbarabash** [comment]
https://beta.observablehq.com

**Comment by kevinbarabash** [comment]
https://www.npmjs.com/package/katex has a list of npm packages which depend on KaTeX.

**Comment by ylemkimon** [comment]
There is also https://github.com/Khan/KaTeX/network/dependents, but I don't know how to sort it.

**Comment by ccreus** [comment]
In case you find it relevant, we are happy users of KaTeX for the exercise statements in [RACSO](https://racso.cs.upc.edu) (an online judge used in the subject «Theory of Computation» at the [Polytechnic University of Catalonia](https://www.upc.edu/en?set_language=en))

**Comment by kevinbarabash** [comment]
The page now exists, we just need to add links from above to it.  See https://github.com/Khan/KaTeX/blob/master/website/pages/en/users.js.

**Comment by kevinbarabash** [comment]
We should add `khanacademy.org`. 🙂

**Comment by ylemkimon** [comment]
@kevinbarabash I couldn't find a square logo for Khan Academy, so I've placed GitLab logo as a placeholder. I didn't expect the PR to get merged soon. 😄

**Comment by kevinbarabash** [comment]
@ylemkimon I'll look up that info and will post it here.

**Comment by edemaine** [comment]
I added most of the explicit examples above in #1569.  Exceptions:
* http://algebra.js.org/ mentions how to use it in conjunction with KaTeX (for rendering the output of `toTex()`), but I don't think it directly uses KaTeX.
* http://acko.net/blog/mathbox2-pt2/ seems to be in the same category
* I haven't gone through the many NPM dependants.
