### ISSUE TITLE
Implement \colon as amsmath does

### ISSUE THREAD

**Issue by gagern** [Khan/KaTeX#307]
Currently KaTeX implements `\colon` as if it were simply defined as `\mathpunct{:}`. However, `amsmath.sty` gives its definition as follows:

``` tex
\renewcommand{\colon}{\nobreak\mskip2mu\mathpunct{}\nonscript
  \mkern-\thinmuskip{:}\mskip6muplus1mu\relax}
```

I don't know exactly what all of this means, but it's obviously a deal more complicated than what we currently implement. I found this using the tool from #294.

**Comment by gagern** [comment]
I just realized that without the `amsmath` package, `:` indeed behaves as `\mathpunct{:}`. It is defined as `\mathchar"603A` according to `\show\colon`, and there is a line

```tex
\DeclareMathSymbol{\colon}{\mathpunct}{operators}{"3A}
```

in `fontmath.ltx`. But I think on the whole KaTeX is behaving like LaTeX *with* the `amsmath` package loaded, right?

`amsmath.dtx` has this information about the definition of `\colon`:

> `\colon` is for a colon in math that resembles a text colon: small space on the left, larger space on the right. The `:` character by itself is treated as a `\mathrel` i.e. large, equal spacing on both sides.

Unfortunately, this doesn't make the situation much clearer to me.

**Comment by kevinb7** [comment]
> But I think on the whole KaTeX is behaving like LaTeX with the amsmath package loaded, right?

I think that's a fair assumption.  We should probably explicitly state that somewhere.

**Comment by xymostech** [comment]
TeX shows:

![image](https://cloud.githubusercontent.com/assets/217900/8681978/692d9e2c-2a1f-11e5-89ca-57013dc3d20e.png)

LaTeX shows:

![image](https://cloud.githubusercontent.com/assets/217900/8681983/705472a2-2a1f-11e5-9969-6596aeb4e430.png)

**Comment by xymostech** [comment]
Just looking through the definition, it looks like this means: 

```tex
% Don't allow a linebreak before the :
\nobreak
% Insert a 2mu space
\mskip2mu
% Add an empty punct element (maybe for spacing next to other elements?) I guess the acutal `:` is wrapped in {}, so maybe it's treated as an ord from the right but a punct from the left?
\mathpunct{}
% Add a -\thinmuskip space if we're not in scriptstyle or scriptscriptstyle
\nonscript\mkern-\thinmuskip
% Add an actual colon
{:}
% Add a 6mu + 1mu space
\mskip6muplus1mu
% End the macro
\relax
```

Which should be pretty easy to implement? I guess this probably makes more sense to write as a macro, once we have those, since having a specific "\colon" type seems a bit wasteful.

**Comment by gagern** [comment]
OK, the `\nobreak` doesn't affect us, since we don't break anyway. The skips are easy enough, and we can ignore the `plus1mu` stretch of the latter since we don't stretch anything. `{:}` indeed produces a `\mathord{:}`. So far things are clear to me.

What I'm less clear about is the distinction between `\mskip` and `\mkern`. Is it that an `\mskip` could be subject to line change while an `\mkern` can not?

Intuitively I'd have thought that the `\mskip2mu` gets turned into an atom in its own right, but apparently that's not the case. So the `\mathpunct{}` should indeed affect the spacing before the `\colon`.

Looking at the table from chapter 18, one can see that the implicit spacing between a `\mathpunct` and a `\mathord` is `\thinmuskip` but no space is added in script and smaller styles. So the explicit kerning here cancels the implicit spacing, cuaisng the two atoms to follow one another with no glue in between.

If we wanted to do this as a macro, we'd need to implement those low-level atom-changing commands like `\mathpunct`. Might be a good idea in any case, since they are powerful building blocks for a lot of stuff.

**Comment by xymostech** [comment]
> Is it that an `\mskip` could be subject to line change while an `\mkern` can not?

That's correct, as far as I (or stackoverflow anyway) understands it. 

> So the explicit kerning here cancels the implicit spacing, cuaisng the two atoms to follow one another with no glue in between.

Ah, nice catch! That's very interesting.

**Comment by edemaine** [comment]
Just bumped into this old issue while searching for something else.  Now that we have macro support, what would remain is supporting `\mathpunct` (as @gagern wrote) and `\nonscript`.  (TIL `\nonscript`, which is specific to glues!)  Neither is especially high priority, but could be fun to implement.

**Comment by danielhollas** [comment]
This is slightly relevant to KA, since in certain locales the \div symbol should be colon instead. 
e.g. instead of
$6 \div 3 = 2$ 
we need 
$6 \colon 3 = 2$ 

With the current implementation, is much better to use simple \colon or \mathbin{:}
$ 6 : 3 = 2$

**Comment by kevinbarabash** [comment]
@danielhollas we haven't done any work to support automatic localization of TeX content.  TeX is very much a presentation layer and doesn't really know what `\div` is other than it's a binary operator.  I think automatic localization is outside the scope of KaTeX.  We provide access to the parse tree, but it's still in flux so use at your own risk.  That being said if you or anyone knows of a project that does automatic localization of TeX let me know.

**Comment by danielhollas** [comment]
No no, sorry for misunderstanding, I was not suggesting anything like that. I only wanted to point out the context in which \colon might be used.

I only stumbled upon this issue, because KA linter currently does not allow translating \div. For multiplication, it allows \mult -> \cdot translation, so I originally thought the \div -> \colon is the correct equivalent. But unless this particular issue is solved and merged, that is not the case.

Sorry for off topic post.

**Comment by ronkok** [comment]
Closed via #1410.

**Comment by q2apro** [comment]
Apologize for jumping into the thread.

Katex renders a division colon by adding a space:

![image](https://user-images.githubusercontent.com/6764548/93216336-47ba2200-f770-11ea-9f4c-4462571a2ca6.png)

`= \frac{24\color{blue}{:6}}{30\color{blue}{:6}}`

Expected from the latex code is however:

![image](https://user-images.githubusercontent.com/6764548/93216407-5c96b580-f770-11ea-870c-3597c5ba5778.png)

Which can only be achieved by using `{:}` instead of directly `:`.

Since it is essential for us (100,000s of posts of users) to have `:` rendered without space, how can we set up Katex to render accordingly. Thanks!

**Comment by edemaine** [comment]
@q2apro If you want `:` to act like `{:}`, you can pass in a settings object like this:
```js
{
  macros: {":": "{\\char`:}"}
}
```

In the future, it would be better to create a new issue rather than re-using an old one.

**Comment by q2apro** [comment]
You are right: https://github.com/KaTeX/KaTeX/issues/2514

PS: What's the best place to throw in the `macro` [option](https://katex.org/docs/options.html)? We are using the auto-renderer extension.
