### ISSUE TITLE
allow commands to be marked as `non-standard` and provide an option to enabled them

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#315]
`non-standard` commands should be disabled by default.

**Comment by spicyj** [comment]
Once we have macro support via JS configuration it would be nice to just remove them completely and move them to KA-specific configs.

**Comment by kevinb7** [comment]
Some non-standard commands might not be expressible with just a macro, e.g. `\cssId` and `\cssClass`.

**Comment by kevinb7** [comment]
But yes, I agree those that can be expressed as macros should be once that's in place.

**Comment by kevinbarabash** [comment]
Any thing that's non-standard should not be enable in strict mode moving forward.
