### ISSUE TITLE
KaTex on KhanAcademy

### ISSUE THREAD

**Issue by DollarAkshay** [Khan/KaTeX#316]
Why cant KaTex be used on KhanAcademy ?

**Comment by kevinb7** [comment]
@DollarAkshay it is being used on KhanAcademy.  Sometimes though we fallback to MathJax for LaTeX commands that we don't handle yet.

**Comment by spicyj** [comment]
I assume @DollarAkshay is referring to the discussion areas.

**Comment by kevinb7** [comment]
That's a good idea.  I think we'd want to have a way to preview comments as well so that people can check that their math is right.

**Comment by xymostech** [comment]
This is pretty clearly not a KaTeX issue.
