### ISSUE TITLE
`\int\limits` in textstyle doesn't correctly produce limits

### ISSUE THREAD

**Issue by xymostech** [Khan/KaTeX#318]
In KaTeX, `\int\limits_x^y z` produces:

![image](https://cloud.githubusercontent.com/assets/217900/8913817/4c42d788-3450-11e5-8a60-caf5c3195380.png)

whereas in TeX, it produces:

![image](https://cloud.githubusercontent.com/assets/217900/8913858/809f44bc-3450-11e5-88cc-1215edd0f0b2.png)

`\nolimits` and `\limits` was recently introduced in #314

**Comment by kevinb7** [comment]
@xymostech good catch.  @JeffEverett could you have a look into this if you have some time?
