### ISSUE TITLE
`\dag` shouldn't be smaller in script/scriptscriptstyle.

### ISSUE THREAD

**Issue by xymostech** [Khan/KaTeX#320]
It looks like `\dagger` is correct, but `\dag` is a macro `\mathhexbox 279` that makes it so the `\dagger` character doesn't change in size when in script or scriptscriptstyle. It also means that `\dag` isn't a `bin`, it's an `ord`, but it looks like we already handle that.

TeX `a^{\dag} a^{\dagger} x \dag y \dagger z`:
![image](https://cloud.githubusercontent.com/assets/217900/8966500/8a60ac2e-35e6-11e5-9f1b-aca2fb43c004.png)

KaTeX `a^{\dag} a^{\dagger} x \dag y \dagger z`:
![image](https://cloud.githubusercontent.com/assets/217900/8966525/aaba2e5a-35e6-11e5-91c3-16d2394ba592.png)

**Comment by kevinbarabash** [comment]
@xymostech it looks like this is redefined in `amsmath`.  `pdflatex` renders the following document
```
\documentclass{article}
\usepackage{amsmath}
\begin{document}
$$ a^{\dag} a^{\dagger} x \dag y \dagger z $$
\end{document}
```
to
<img width="414" alt="screen shot 2018-01-31 at 12 48 03 am" src="https://user-images.githubusercontent.com/1044413/35607106-97f41a58-0620-11e8-98cf-2661d7b0a55b.png">

**Comment by edemaine** [comment]
Agreed. So KaTeX is already "correct"!
