### ISSUE TITLE
When building katex using webpack an additional loader is needed for json.

### ISSUE THREAD

**Issue by blaiprat** [Khan/KaTeX#322]
Hi, with the 0.5.0 release the big object from `fontMetrics.js` has been moved to their own JSON file `fontMetricsData.js`. That forces me to add the `json-loader` in my project configuration just for this specific file. 

Not a terrible problem I know, but I was wondering if it can be saved as a javascript file, prepending the `module.exports =` to the file when generating it and saving it with the `js` extension.

**Comment by kevinb7** [comment]
I don't see a problem with doing this.  Would you be able to submit a pull request?

**Comment by blaiprat** [comment]
I've been checking the scripts, I'm not fluent with python, but I'll give it a try.

**Comment by blaiprat** [comment]
Thanks for merging the pull request
