### ISSUE TITLE
fraction bar too high in tonicdev integration

### ISSUE THREAD

**Issue by kevinb7** [Khan/KaTeX#332]
https://tonicdev.com/nicole/katex
<img width="137" alt="screen shot 2015-08-21 at 6 33 42 pm" src="https://cloud.githubusercontent.com/assets/1044413/9421584/312e83ec-4833-11e5-93a4-aacd0661ff84.png">
My guess is that one of the styles from outside of the katex container is bleeding in.

**Comment by xymostech** [comment]
Very strange. I can't find any styles that are being changed in the frame, but I remember seeing something like this before on android. Probably needs more investigation.

**Comment by tolmasky** [comment]
This seems unrelated to Tonic, it reproduces in a normal plain html file for me:

<html>
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/katex.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/katex.min.js"></script>
    </head>
    <body>
        <script>
            document.body.innerHTML = katex.renderToString("x^{2} + \\frac{4}{3}x + 4", { displayMode: true });
        </script>
    </body>
</html>

I can open a new bug "fractions are broken" if you prefer.

**Comment by spicyj** [comment]
Missing DOCTYPE?

**Comment by tolmasky** [comment]
Is HTML5 a requirement? If it is I'm happy to consider it fixed as missing doctype.

**Comment by spicyj** [comment]
Not HTML5 necessarily, but we probably don't work great in quirks mode. Any valid doctype should work (though `<!DOCTYPE html>` is of course the shortest). Does that fix it?

**Comment by tolmasky** [comment]
Yup, pushing a fix to tonic now. Thanks!

**Comment by spicyj** [comment]
Sweet. We should add a warning for this though. (jQuery doesn't support quirks mode, for instance.)

**Comment by xymostech** [comment]
We do have a warning for it! https://github.com/Khan/KaTeX/blob/master/katex.js#L33

**Comment by tolmasky** [comment]
Yeah the problem here is that that warning doesn't happen on the client if its rendered on the server (which is what was happening here). It'll actually be kind of a common case if you do lots of server rendering of stuff as opposed to relying on it coming in on the client.

**Comment by spicyj** [comment]
Ahh, gotcha.
