### ISSUE TITLE
gitter vs freenode

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#335]
We have a freenode irc channel set up called #katex that's the current official chat room.  There's an "unofficial" chat room at https://gitter.im/Khan/KaTeX.  The benefit of gitter that I see is that you can use markdown to format posts including posting images.

**Comment by kevinb7** [comment]
@spicyj has discovered that gitter uses KaTeX for math support.

**Comment by spicyj** [comment]
It's been the case since last September. :) Scroll back to see.

**Comment by xymostech** [comment]
By "official" do you mean "mentioned in CONTRIBUTING.md"? The irc channel seems more universal, but gitter is pretty great too. I'm all for changing it, maybe we should set the topic in the irc channel to direct to gitter.

As a side note, do we know if gitter has an up-to-date(-ish) version of KaTeX?

**Comment by kevinb7** [comment]
"mentioned in CONTRIBUTING.md" and a gitter badge in README.md.  I don't know which version of KaTeX they're running.  We could open an issue in their bug tracker whenever we release a new version.

**Comment by kevinbarabash** [comment]
Since there doesn't seem to be any opposition to adding a gitter tag, I'm going to add the gitter tag back and update CONTRIBUTING.md.

**Comment by kevinbarabash** [comment]
Closed by https://github.com/Khan/KaTeX/pull/360.
