### ISSUE TITLE
. vs ,

### ISSUE THREAD

**Issue by scaljeri** [Khan/KaTeX#336]
As a decimal sign I use the , (comma) instead of the . (dot). However KaTex adds some space after the comma. Is it possible to configure KaTeX such that you can tell it what the decimal-sign is ?

**Comment by hastebrot** [comment]
Could you preprocess the math formula with a regular expression?

I use the comma in written math, but have never seen it used in a LaTeX formula in the wild. It is very common in programming languages to use a point as decimal sign.

**Comment by hastebrot** [comment]
Maybe you could write `{,}` instead of `,`.

**Comment by scaljeri** [comment]
A regex will absolutely work, thnx! Is there any change this could be made configurable ?

**Comment by kevinb7** [comment]
According to the third answer on http://tex.stackexchange.com/questions/24156/comma-as-decimal-point-leading-to-confusion the siunitx package provides a ```\num``` command which can be used like ```\num{1,5}``` to do the formatting you're looking for.  I think this would be more feasible than having a general configuration option that changes the behavior of ```,```.

**Comment by xymostech** [comment]
I think `{,}` is the correct way to do this. That SO question mentions it, and the TeXbook calls it out specifically too:
![image](https://cloud.githubusercontent.com/assets/217900/9475609/97f37524-4b1c-11e5-9560-70d97dd29d1f.png)

We could maybe add something like the `\num` command, but this seems like a bit of overkill for now (and would probably just end up with us implementing an internal should-commas-have-space setting anyway).
