### ISSUE TITLE
array and matrix environments don't ignore trailing newlines

### ISSUE THREAD

**Issue by wchargin** [Khan/KaTeX#337]
Everyone likes trailing commas! But trailing newlines in matrices seem to add an extra newline :cry: 

LaTeX source to test:

``` tex
\documentclass{article}

\pagestyle{empty}

\usepackage{amsmath}

\begin{document}

\[
  \begin{bmatrix}
    a & b \\
    c & d \\ 
  \end{bmatrix}
\]

\end{document}
```

LaTeX output:
![LaTeX output doesn't show the blank line](https://cloud.githubusercontent.com/assets/4317806/9445137/6186c528-4a3f-11e5-8f98-6da74ebe0e94.png)

KaTeX output:
![KaTeX output has an extra blank line](https://cloud.githubusercontent.com/assets/4317806/9445130/57098c98-4a3f-11e5-96dc-4039d416097f.png)

**Comment by WChargin** [comment]
For reference, the Other Library has the behavior of LaTeX:
![The Other Library agrees with pdflatex](https://cloud.githubusercontent.com/assets/4317806/9445236/eb81eb90-4a3f-11e5-9e43-83ad9399b7fa.png)

**Comment by xymostech** [comment]
:+1: Thanks for this! Trailing newlines should definitely be accepted.
