### ISSUE TITLE
Parser error with mathbf in superscript

### ISSUE THREAD

**Issue by weidendo** [Khan/KaTeX#344]
Using current master (Sep 9, 15), I get the following:

KaTeX parse error: Got function '\mathbf' with no arguments as superscript at position 15: \mathbf{G} = e^̲\mathbf{F} =

There is an argument, but it probably is not parsed as part of the superscript?

**Comment by kevinb7** [comment]
@weidendo definitely a bug.  Thanks for reporting this.  I'll have a look at it this evening.

**Comment by kevinb7** [comment]
Looks like the greediness should be set to 2 for this.

**Comment by gagern** [comment]
Is greediness a concept in TeX as well? Or is it simply that any expandable macro gets expanded before the math formula gets assembled, so the `\mathbf{F}` will produce a single group which will then be placed into the exponent as is? If so, should we try to systematically assign greediness based on whether the function in question is an expandable macro or an unexpandable command in TeX?

**Comment by kevinb7** [comment]
> Or is it simply that any expandable macro gets expanded before the math formula gets assembled

I'm not sure if there are an exceptions to that rule, but it seems like that would be reasonable default behavior.

> should we try to systematically assign greediness based on whether the function in question is an expandable macro or an unexpandable command in TeX?

Definitely something worth looking into.

**Comment by kevinbarabash** [comment]
I'm not seeing this bug on master which was just released in https://github.com/Khan/KaTeX/releases.  Please re-open if you can repro this.
