### ISSUE TITLE
Dead link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by utensil** [Khan/KaTeX#370]
CONTRIBUTING.md has a link to https://github.com/Khan/KaTeX/blob/master/test/screenshotter/ss_data.json but it's 404 and should be https://github.com/Khan/KaTeX/blob/master/test/screenshotter/ss_data.yaml .

**Comment by kevinbarabash** [comment]
Closed by https://github.com/Khan/KaTeX/pull/372#issuecomment-149284690.
