### ISSUE TITLE
No character metrics for '■' in style 'Main-Regular'

### ISSUE THREAD

**Issue by miestasmia** [Khan/KaTeX#374]
When using `\blacksquare` Chrome 46 spits out a warning `No character metrics for '■' in style 'Main-Regular'`.

**Comment by Locercus** [comment]
I think this might be part of a larger Unicode support issue that'd need to be resolved. If need be, I can try test it in other browsers as well.

**Comment by kevinbarabash** [comment]
@Locercus I'm not sure what's causing this.  We do have metrics for `\blacksquare` which is `\u25a0` (or 9632 in decimal), see https://github.com/Khan/KaTeX/blob/a81c4fe78df1b19401883cff4f8af2b1c0f5b033/src/fontMetricsData.js#L206.  If could test it in another browser that would be great.  I have a feeling though that this isn't a browser problem.

**Comment by Locercus** [comment]
Can confirm it happens in Firefox 41 as well as Opera 31 too. I'm on GNU+Linux so I can't test IE or Safari.

**Comment by kevinbarabash** [comment]
This is a Linux only bug but it is reproducible.

**Comment by t-k-** [comment]
I also spot this warning, the square box displays correctly. No idea how to suppress this warning.

(my browser: Chromium 52.0.2743.85)

**Comment by Menci** [comment]
`\notin` also trigger the bug.

But it displays correctly.

**Comment by kevinbarabash** [comment]
For `\blacksquare` we're passing the wrong style to `fontMetrics.getCharacterMetrics(value, style);` in `makeSymbol`.  It should be `"AMS-Regular"` but we're passing `"Math-Regular"`... or the metrics should for `\blacksquare` should be in the `"Math-Regular"` table.  I'd need to investigate further to determine which it is.

**Comment by kevinbarabash** [comment]
`\notin` legitimately does not have metrics.  It's in our KaTeX_Math-Regular font files, but it doesn't exist in `mapping.pl`.  A person would need to have a look at https://github.com/Khan/MathJax-dev/blob/master/fonts/OTF/TeX/makeFF (which is used to generate our font files) to see how `\notin` (decimal unicode character 2209) makes its way into the font.

**Comment by kevinbarabash** [comment]
Closed by https://github.com/Khan/KaTeX/pull/618.

**Comment by upupming** [comment]
If I write Chinese in Math code, I will get this warning, too:

![image](https://user-images.githubusercontent.com/24741764/50563249-27f18900-0d56-11e9-8b08-c236f8d37237.png)

**Comment by edemaine** [comment]
@upupming Please open a new issue, along with the text you're trying to render (in addition to the screenshot). Thanks!

**Comment by upupming** [comment]
Thanks, I will open another issue!

**Comment by ChidaoDouyu** [comment]
I met the similiar issue.
`No character metrics for '⁡' in style 'Main-Regular' and mode 'text'`
