### ISSUE TITLE
Deprecate IE8 support, based on Microsoft's January 2016 hard deadline.

### ISSUE THREAD

**Issue by Pomax** [Khan/KaTeX#377]
Based on https://support.microsoft.com/en-us/gp/microsoft-internet-explorer as of January 12, 2016, only IE9 and up will be supported for consumer versions of Windows (IE7/8 will still be supported for very old versions of Windows Embedded, but this is not a platform that KaTeX targets).

This is a hard deadline and a shift in how Microsoft will be supporting browsers going forward (only officially supporting whatever is the latest version for each flavour of Windows) and as such testing with, and support for, IE8 can be deprecrated. 

(Once Vista hits its EOL, IE9 can also be deprecated, but that won't officially be until April 2017)

**Comment by gagern** [comment]
Did KaTeX even work in IE8? https://github.com/Khan/KaTeX/issues/263#issuecomment-128927322 suggests otherwise, but I didn't confirm that suggestion. In any case, the browserstack results discussed there might be useful in formulating official support statements.

**Comment by spicyj** [comment]
It used to, at least. KA has since dropped support for IE8 so it's possible it regressed and no one noticed.

**Comment by xymostech** [comment]
I'm pretty sure it regressed when we introduced MathML support, which was a while ago. There might be a way to bring it back if we really care, but unless we actuallly set up tests it'll probably break again.

**Comment by kevinbarabash** [comment]
@Pomax is there specific work that you think should be done for this?

**Comment by Pomax** [comment]
not really, the docs said KaTeX supported IE8, which sounded like there'd be unnecessary shim code at least in one place, but I've not looked at the codebase in a really long time now >_>

**Comment by kevinbarabash** [comment]
I guess we should update the docs at the very least to reflect that IE8 support no longer works.
