### ISSUE TITLE
Chinese text in formula causes ParseError

### ISSUE THREAD

**Issue by Vdragon** [Khan/KaTeX#379]
I tried to input my formula `球表面積 = 4\pi 半徑 ^2 = 4\pi(6.37 × 10^3 公里)^2 = 509904363.8 平方公里(km^2)` (translation: `\text{sphere surface area} = 4\pi radius^2 = 4\pi (6.37 \times 10^3 km)^2 = 509904363.8 km^2`) in the [demo page](http://khan.github.io/KaTeX/) but it throws a `Uncaught ParseError: KaTeX parse error: Unexpected character: '球' at position 14: \displaystyle{̲球表面積 = 4\pi 半徑` error, I wonder if CJK text handling is not available in KaTeX?

However the same formula renders correctly on ReText with MathJax rendering enabled:
![_001](https://cloud.githubusercontent.com/assets/1192163/10871195/d7f6d128-811a-11e5-86d2-43fdb92703db.png)

**Comment by Pomax** [comment]
Looks like the fact that they're missing from the fonts used for LaTeX styling causes a throw.

**Comment by kevinbarabash** [comment]
Closing in preference of https://github.com/Khan/KaTeX/issues/380.
