### ISSUE TITLE
Make KaTeX accessible

### ISSUE THREAD

**Issue by dylanb** [Khan/KaTeX#38]
Make KaTeX accessible to people with disabilities in particular screen reader users as they are most affected by the current limitations

**Comment by xymostech** [comment]
Hello everyone, thanks for all the feedback here. I've been distracted by other projects, but I'm going to be making a pull request soon about making KaTeX accessible, taking a hybrid MathML + aria-hidden HTML approach. I'd love to get some feedback and a hand in testing it out in different environments if anyone would like to help out.

**Comment by NSoiffer** [comment]
I'm glad to hear you are getting back to this. You probably should take a look at what wikipedia has done to deal with accessible math:  if the user has selected the option  "MathML with SVG or PNG fallback (recommended for modern browsers and accessibility tools)", they render the TeX on their server and then send down MathML and the fallbacks.  To set the options, login, choose appearances, and scroll to the bottom for math options.
For more info, see this [wikimedia page](https://www.mediawiki.org/wiki/Extension:Math). The more sites that do things the same way, the more impetus there is for accessibility tools to handle that.

**Comment by Hywan** [comment]
\o/

**Comment by fred-wang** [comment]
@NSoiffer You can try it on http://katex.xymostech.com/

**Comment by NSoiffer** [comment]
That works with the new MathPlayer+NVDA. I haven't tried anything else, but
that's a positive sign.

**Comment by brucemiller** [comment]
I'm not sure what "works" should mean here: on Firefox it is not using MathML, but span-soup.  Ultimately, you'd want to send MathML to browsers that support it, right?   It looks OK, though, although it's all quite huge, but I'm guessing from the CSS that that is intentional.

**Comment by NSoiffer** [comment]
If you use the develop tools in Firefox to look at the DOM, you'll see
MathML is in there. NVDA finds the MathML and gives it to MathPlayer to
speak.

As for who/what is doing the rendering, that I'm not sure about. For screen
reader accessibility, that doesn't matter. When you need to do sync
highlighting, potentially that might matter. E.g., if some code modifies
the MathML to change the background color on the mfrac, would the display
change correctly?

     Neil

**Comment by fred-wang** [comment]
Yes, the fact that the MathML rendering is hidden is a problem for assistive technologies that rely on the visual rendering such as sync highlighting or, as mentioned by Apple devs, touch screen support. However, the main issue is that KaTeX currently does not generate MathML at all, so Emily's work is already a big progress. This generates MathML + HTML with only CSS selectors to select which one that is visible, so assistive technologies can immediately obtain the MathML DOM and it's easy to write a browser add-on / greasemonkey script to force MathML to be rendered for more advanced assistive technologies or native browser rendering.

**Comment by xymostech** [comment]
> When you need to do sync highlighting, potentially that might matter. E.g., if some code modifies the MathML to change the background color on the mfrac, would the display change correctly?

 @NSoiffer The display would not update. Is that a serious problem? Are there lots of times when that would happen? I'm not sure if there's a good general way to watch for changes to the DOM to propogate them over to the HTML version.

**Comment by NSoiffer** [comment]
If you want the DOM to propagate to the rendering, Shadow DOM seems like
the way to go. But unless you use a polyfill, your probably got a couple of
years to wait for all the browsers to implement it.

**Comment by xymostech** [comment]
The accessibility patches were landed in the new release of KaTeX ([v0.2.0](https://github.com/Khan/KaTeX/releases/tag/v0.2.0)). Hopefully the new, accessible version should start appearing around soon. (there isn't a way for developers to disable accessibility, so anywhere that it's used should have the new features)

I ran some performance tests on the new version versus the old release. It looks like we took a ~20% speed hit, which is a little sad but not bad for things being screen-readable now: http://jsperf.com/katex-vs-accessible-katex

I'm going to close this issue for now. If anyone runs into any serious problems, I'd be happy to re-open or make smaller issues. Thanks for all of the feedback, everyone!

**Comment by NSoiffer** [comment]
FYI: I spoke the JAWS developer for math support and he said they expect
JAWS will start reading MathML in the near future -- I forwarded the test
page on to him.

**Comment by fred-wang** [comment]
Follow-up issues for people who care about the visual rendering too:
https://github.com/Khan/KaTeX/issues/197
https://github.com/Khan/KaTeX/issues/198

**Comment by fred-wang** [comment]
For the record, I've updated my mathjax-native-mathml extensions to force KaTeX to display its MathML output too:
- Mozilla add-on: https://addons.mozilla.org/en-US/firefox/addon/mathjax-native-mathml/
- Safari add-on: http://fred-wang.github.io/mathjax-native-mathml-safari/mathjax-native-mathml.safariextz
- Greasemonkey script (unfortunately that one does not work well due to issue #197): https://openuserjs.org/scripts/fred.wang/MathJax_Native_MathML/
