### ISSUE TITLE
Question: What's difference between LaTeX/KaTeX?

### ISSUE THREAD

**Issue by IndieKA** [Khan/KaTeX#382]
http://mathim.com/
LaTeX based. But is there is any difference?

**Comment by xymostech** [comment]
The syntax that KaTeX supports is LaTeX-like, and it supports a subset of the LaTeX functions. You can see a [list of functions that KaTeX supports here](https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX).

The chat you linked to looks like it uses MathJax, another library for rendering LaTeX in the browser.

**Comment by jebob** [comment]
Functions now stored here: https://katex.org/docs/supported.html
