### ISSUE TITLE
Subscripts wrong baseline

### ISSUE THREAD

**Issue by mathijshenquet** [Khan/KaTeX#390]
Rendering a subscript like `x_A, y_A` renders the subscript of the y lower then the subscirpt of the x. Probably because it uses the boundingbox of the letter it is subscripting.

Attached is a reference rendering from LaTeX
![latex](https://cloud.githubusercontent.com/assets/242143/11166219/b721ae6c-8b2b-11e5-8296-bd7b74eaadab.PNG)

And the output from KaTeX
![xatex](https://cloud.githubusercontent.com/assets/242143/11166220/b736961a-8b2b-11e5-944b-c1d607d8703e.PNG)

**Comment by kevinbarabash** [comment]
This is what I'm seeing using Chrome on Mac OS X using the http://khan.github.io/KaTeX/.
![screen shot 2015-11-14 at 3 31 24 pm](https://cloud.githubusercontent.com/assets/1044413/11166359/d65326ea-8ae4-11e5-82d5-74078c848b62.png)

@mathijshenquet what browser/OS are you using?  Which version of KaTeX are you using?

**Comment by kevinbarabash** [comment]
I also noticed that the font for `x` and `y` are not in italics.  Can you post the complete source code for the math that you're rendering?

**Comment by mathijshenquet** [comment]
Yes further testing indicated the problem only occurs when using \mathbf. So the full text case should be `\mathbf{x}_A, \mathbf{y}_A`. Probably because the new \mathbf block 'forgets' that it is text.

**Comment by digitalheir** [comment]
I can confirm this issue. 

The span containing the subscript under `span.vlist > span` has different CSS assigned to it: the `top` value for `\mathbf x_A` is `0.15em`, and for `\mathbf y_A` it's `0.24444em`. 

Changing the second to `0.15em` makes the text look fine.
