### ISSUE TITLE
\mathcal crashes KaTeX

### ISSUE THREAD

**Issue by jluttine** [Khan/KaTeX#391]
Not sure if this is already reported or expected behaviour: https://github.com/getnikola/nikola/issues/2174#issuecomment-157078262

If there's `\mathcal` in my math, KaTeX doesn't render and Javscript gives the following error in the console:

```
Error: KaTeX parse error: Expected 'EOF', got '\mathcal' at position 9:
```

**Comment by kevinbarabash** [comment]
`\mathcal{ABC}` works on http://khan.github.io/KaTeX/.  What version of KaTeX are you using?

**Comment by jluttine** [comment]
I'm using this:

```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.css">
```

Is there a link which always points to the latest release of `katex.min.css`?

**Comment by spicyj** [comment]
What version of the JS do you have?

**Comment by jluttine** [comment]
Oh, Nikola's template uses version 0.3.0..
```
<script src="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/katex.min.js">
```
That should be updated. Is there a link to the latest release which could be put to templates so that it doesn't need to be updated in the templa? Alternatively, Nikola could provide a setting in conf.py to specify which version to use, that'd be ok too.

**Comment by kevinbarabash** [comment]
@jluttine unfortunately there isn't.  Please see https://github.com/Khan/KaTeX/issues/239 for details.

**Comment by cben** [comment]
Well, #239 mentions http://cdn.jsdelivr.net/katex/latest/katex.min.js as a solution (currently at 0.5.1).

**Comment by kevinbarabash** [comment]
I'm not sure who's updating jsdelivr.  @cben glad to hear that it's up to date.

**Comment by spicyj** [comment]
I think it updates automatically from npm.
