### ISSUE TITLE
Support for \oiint

### ISSUE THREAD

**Issue by RobinLinus** [Khan/KaTeX#392]
Are there any plans to support \oiint ?

**Comment by kevinbarabash** [comment]
No plans in particular.  Pull requests are welcome.

**Comment by williamstein** [comment]
I just did a quick test at https://khan.github.io/KaTeX/ and it looks liek $\oint$ is now supported.  Can somebody close this issue.

**Comment by kevinbarabash** [comment]
@williamstein this issue is about `\oiint` which is different from `\oint`.

**Comment by edemaine** [comment]
It looks like KaTeX supports `\int`, `\iint`, `\iiint`, `\oint`, but no variations with more `i`s.  They are all implemented as symbols in the font.  I checked [esint](http://mirror.hmc.edu/ctan/macros/latex/contrib/esint/esint.pdf) which implements `\oiint`, and it also uses symbols in a font.  So I think to address this we would need to add symbols via [the fonts repo](https://github.com/KaTeX/katex-fonts).

**Comment by kevinbarabash** [comment]
I've created an issue to track this in the fonts repo: https://github.com/KaTeX/katex-fonts/issues/20
