### ISSUE TITLE
Convert Bin + Rel/Close/Punct to Ord + Rel/Close/Punct

### ISSUE THREAD

**Issue by spicyj** [Khan/KaTeX#4]
6. If the current item is a Rel or Close or Punct atom, and if the most recent previous atom was Bin, change that previous Bin to Ord.

**Comment by spicyj** [comment]
(Also bins at the end of an expression, see #355.)

**Comment by WChargin** [comment]
Copying the table I posted there for reference (TeXbook, Chapter 18):
![Table of atom conversions](https://cloud.githubusercontent.com/assets/4317806/9838389/60158a94-5a11-11e5-96b6-9fdc2b1de8d9.png)

**Comment by cbreeden** [comment]
I felt like it's worth clarifying the explanation of `*` since it certainly is possible to write `++`, `+.` etc...

![rules](https://cloud.githubusercontent.com/assets/12069845/15454278/cf64d112-1ff9-11e6-839d-4c1dfde48f6f.png)

**Comment by WChargin** [comment]
@cbreeden: Right; this conversion process is the topic of this issue :)

**Comment by cbreeden** [comment]
@WChargin: Right, sorry :confused: I was just slightly confused for the deduction of converting `bin` to `ords` if they are last in the list (#355), until I was able to find this _between_ rules 18 and 19.  Knuth tricked me! :blush:

**Comment by cbreeden** [comment]
I did take a look at this issue a few days ago, however, and my conclusion was that given the current model we would probably just need to implement a `next` for the next token [here](https://github.com/Khan/KaTeX/blob/master/src/buildHTML.js#L197).  But I'm sure this was already known.

**Comment by kevinbarabash** [comment]
@cbreeden It seems like pass the `next` group to all the `groupTypes` handlers would get you what you need.

**Comment by cbreeden** [comment]
I did that 😊
