### ISSUE TITLE
Is it possible to use  Katex with React Native?

### ISSUE THREAD

**Issue by kwangkim** [Khan/KaTeX#400]
I am developing a mobile app which requires math expressions.
Facebook's React Native looks promising but it does not support the latex.

I tried to make a plugin which supports math using katex.renderToString, but it did not work well since NSAttributedString did not render the html code from katex.renderToString properly.
I also tried DTCoreText.
https://github.com/Cocoanetics/DTCoreText

Of course, we can use the Webview partially. But I do not think it will give a benefit of React Native.
https://github.com/ianarawjo/KaTeX-iOS

Therefore I am using ionic with katex. But I really want to avoid the webview if it is possible.

Could you give me a suggestion?

**Comment by kevinbarabash** [comment]
I have not used React Native, but my understanding is that it doesn't use `<span>` or `<div>` but has `<text>` and `<view>` elements which are supposed to be generally equivalent.  It shouldn't be too hard to make this substitution.  The larger problem is the CSS rules we use for styling items.  React Native uses inline styles but we have a number of classes that would have to be converted to use inline styles.

> Of course, we can use the Webview partially. But I do not think it will give a benefit of React Native.

What benefit would you lose?  If you don't want to use a Webview directly you could create a React Native wrapper around it.

**Comment by xymostech** [comment]
We're planning on making it easier in the future to build different renderers for the output of the KaTeX parse tree. In the meantime, using a webview is probably your best bet.

**Comment by kwangkim** [comment]
@kevinbarabash Webview is slow and I think that's why Facebook want to introduce RN.
@xymostech That sounds great. If you give some instructions for developing  renderers, 3rd parties may make  many other renderers.

**Comment by YshadowZ** [comment]
@xymostech  Hello, do you have a date for this(build different renders) in mind?

**Comment by der-ede** [comment]
Also interested here.
Are there plans to render KaTex in RN?

**Comment by kevinbarabash** [comment]
I don't know if it makes sense to use KaTeX's approach to typesetting for RN.  KaTeX produces node heavy markup which would require a lot of `View`s in RN.  I've heard that RN doesn't handle this case very well.

**Comment by der-ede** [comment]
Hi @Kevin:
So rather precompile as png or what would you suggest?

Regards

**Comment by kevinbarabash** [comment]
I don't think there is a good solution at the moment.  I think the solution for math in react native would be to use native rendering libraries and create a custom RN component that uses those libraries.  I found https://github.com/kostub/iosMath that could be adapted to work in RN, but it wraps a web view which seems like a pretty heavyweight solution.

**Comment by der-ede** [comment]
Thank you for the respond.
Well, WebView was what we were trying to get away from with RN actually :)

**Comment by 3axap4eHko** [comment]
Just released https://www.npmjs.com/package/react-native-katex

**Comment by edemaine** [comment]
Looks cool!  Should we link to this from https://github.com/Khan/KaTeX#libraries ?

**Comment by kevinbarabash** [comment]
@3axap4eHko you may want to add a comment in the README.md that states that it's a wrapper around `WebView` so that people know this up front.  Also, you may want to expose the various options that `katex.render()` supports.

**Comment by FirdousNath** [comment]
how to render katex in webview? Kindly provide any code or tutorial link please !

**Comment by edemaine** [comment]
@FirdousNath Check out #1155

**Comment by kabonKoda** [comment]
> Just released https://www.npmjs.com/package/react-native-katex

React native devs do not like anything related to webview .... that's the main reason why use react native
