### ISSUE TITLE
Webview rendering problem in cordova(ios).

### ISSUE THREAD

**Issue by kwangkim** [Khan/KaTeX#401]
I am making a mobile quiz app for my students.
I used ionic+meteor  which also use cordova for mobile.
Math part worked well for website and emulator.
But I got a very strange result on the actual machine.
I think it is because ios webview cannot handle the mathml part of katex
 properly.
This there any way to turn off mathml code.

For the katex directive in angular, I used 
https://www.npmjs.com/package/angular-katex

On a native app (Broken math expression)
![screenshot 2015-11-26 22 55 43](https://cloud.githubusercontent.com/assets/10469752/11433831/01f2b9c2-9491-11e5-8434-45116f48f372.png)
On a safari browser( Correct math expressions)
![screenshot 2015-11-26 22 56 21](https://cloud.githubusercontent.com/assets/10469752/11433833/126924e4-9491-11e5-97cd-5427d03c7d36.png)

**Comment by kwangkim** [comment]
I just checked whether mathml affected or not by using 
```
        var katexNode = makeSpan(["katex"], [
            htmlNode
        ]); 
```
in buildtree.js

Answer is no.  Katex did not render html-code properly without mathml part.

I do not know why it did not render well.

**Comment by xymostech** [comment]
It looks like the CSS is not being loaded correctly. The main math part isn't rendering correctly, not just the MathML. Also, the CSS hides the MathML completely, so if the CSS is loaded the MathML shouldn't even be visible. Let me know if that helps. It's cool to see KaTeX being used in your app!

**Comment by kevinbarabash** [comment]
It would be nice to have an option not to render the MathML.

**Comment by spicyj** [comment]
> It would be nice to have an option not to render the MathML.

Why? It's important for accessibility and shouldn't cause problems when the CSS is properly loaded.

**Comment by kevinbarabash** [comment]
My understanding is that MathML didn't do what we wanted it to do in terms of accessibility and we ended up rendering to plain text for the <TeX> component for react-components.

**Comment by xymostech** [comment]
I think that MathML is the correct general solution going forward (as people mentioned in #38), but the requirements for our SAT product were perhaps different than general accessibility (IIRC, most of the problem was around getting the screenreader to read the text when new math appears on the page, but I bet that's our fault and not that of the screenreaders). Playing around with the generated MathML using a screenreader that supported it showed that they worked fine.

**Comment by kevinbarabash** [comment]
My misunderstanding.  I'm glad to know that MathML is helping people.

**Comment by kwangkim** [comment]
I did a simple tweak. I realized ionic + cordova did not render html properly. Instead, it rendered mathml correctly. I am not sure whether  ios webview+cordova has a bug. 

I slightly modified buildTree.js to test it with a RenderMode option.
I think having a  rendering Mode option is a good idea for the future. 
```
var buildHTML = require("./buildHTML");
var buildMathML = require("./buildMathML");
var buildCommon = require("./buildCommon");
var Options = require("./Options");
var Settings = require("./Settings");
var Style = require("./Style");

var makeSpan = buildCommon.makeSpan;

var buildTree = function(tree, expression, settings) {
    settings = settings || new Settings({});

    var startStyle = Style.TEXT;
    if (settings.displayMode) {
        startStyle = Style.DISPLAY;
    }

    // Setup the default options
    var options = new Options({
        style: startStyle,
        size: "size5"
    });

    // `buildHTML` sometimes messes with the parse tree (like turning bins ->
    // ords), so we build the MathML version first.
    // var htmlNode = buildHTML(tree, options);
    // 'Html only mode'
    var katexNode={};
    var mathMLNode={};
    var htmlNode={};
    if(settings.RenderMode ==="MATHML" ){
        mathMLNode = buildMathML(tree, expression, options);
        katexNode = makeSpan(["katex"], [
            mathMLNode
        ]);      
    }   else if( settings.RenderMode==="HTML" ){
        htmlNode = buildHTML(tree, options);
        katexNode = makeSpan(["katex"], [
           htmlNode
        ]);         
    }   else{
        mathMLNode = buildMathML(tree, expression, options);
        htmlNode = buildHTML(tree, options);
        katexNode = makeSpan(["katex"], [
            mathMLNode, htmlNode
        ]);
    }
    if (settings.displayMode) {
        return makeSpan(["katex-display"], [katexNode]);
    } else {
        return katexNode;
    }
};
```

**Comment by spicyj** [comment]
@kwangkim Are you sure you included the stylesheet correctly?

**Comment by kwangkim** [comment]
I used the  bower to install Katex which includes font files.
I just put them in my index.html
```
    <link rel="stylesheet" href="lib/KaTeX/dist/katex.min.css">
    <script src="lib/katex/dist/katex.min.js"></script>
    <script src="lib/katex/dist/contrib/auto-render.min.js"></script>
    <script src="lib/angular-katex/angular-katex.min.js"></script>
```
As you saw above, it works perfectly with emulator, safari, chrome etc except an actual phone.
So I do not think it is a Katex bug.

**Comment by xymostech** [comment]
It looks like you capitalized KaTeX differently in your CSS vs JS paths. your phone might be using a case-sensitive filesystem while your computer doesn't. Could you try

```
<link rel="stylesheet" href="lib/katex/dist/katex.min.css">
```

**Comment by kwangkim** [comment]
@spicyj @xymostech You are right. Webview in ios was case sensitive.
```
<link rel="stylesheet" href="lib/katex/dist/katex.min.css">
```
It works well on the phone.

Thank you very much.

By the way, I really hope KaTex supports React Native soon.
