### ISSUE TITLE
new command overrightarrow

### ISSUE THREAD

**Issue by trollanfer** [Khan/KaTeX#402]
This command would be very useful for two letters vectors. the vec one is ugly !

**Comment by xiaokaike** [comment]
+1 please support  

![image](https://cloud.githubusercontent.com/assets/4251499/14524996/f170dcaa-026d-11e6-8dc8-2d4d7e6d6656.png)

**Comment by kevinbarabash** [comment]
This probably shouldn't be too hard to do.  I would look at how `\overline` is done and then combine that with `\rightarrow`.  This will probably require knowing how wide `\rightarrow` is.

**Comment by tleb** [comment]
Any update? I don't have the knowledge to help, sadly.

**Comment by kevinbarabash** [comment]
I think this is worth keeping open.  `\vec` may be okay for some uses, but we definitely want `\overrightarrow`.

**Comment by kevinbarabash** [comment]
This was added in [v0.8.0](https://github.com/Khan/KaTeX/releases/tag/v0.8.0).

**Comment by jhaavard** [comment]
Seems like the arrow on top is missing when using \vec. The SVG markup is there. Anyone else getting the same behaviour?

**Comment by edemaine** [comment]
@jhaavard No, it works fine for me. Please open a separate issue about your specific conditions.
