### ISSUE TITLE
Support \widehat

### ISSUE THREAD

**Issue by digitalheir** [Khan/KaTeX#407]
Like `\hat`, but wide:

![left: \hat, right: \widehat](https://cloud.githubusercontent.com/assets/178797/11506416/c05c39b2-984f-11e5-98b3-117e1746becd.png)

left: `\hat`, right: `\widehat`

**Comment by kevinbarabash** [comment]
We'll have to grab additional glyphs for wide accents.  Having width metrics would help with this but we could fake it by counting the number of characters inside the `\widehat`.

**Comment by jraimbau** [comment]
There are a series of similar commands, with other symbols, that should probably be dealt together with <code>\widehat</code>, e.g. <code>\widetilde</code> (for the tilda), <code>\overrightarrow</code> and <code>\overleftarrow</code> (for the arrows).

**Comment by Sukii** [comment]
Yes, it is more like \overbrace{asdfghjkl} which works fine in MathJax (there you have something to start with).
Even in classical LaTeX or MathJax the \widehat doesn't work that well, see:
http://tex.stackexchange.com/questions/100574/really-wide-hat-symbol

**Comment by kevinbarabash** [comment]
This was added in [v0.8.0](https://github.com/Khan/KaTeX/releases/tag/v0.8.0).
