### ISSUE TITLE
Maxwell's equations don't seem to work

### ISSUE THREAD

**Issue by jackparmer** [Khan/KaTeX#411]
Via http://www.intmath.com/cg5/katex-mathjax-comparison.php?processor=MathJax

![image](https://cloud.githubusercontent.com/assets/1865834/11765175/4aa4e380-a11a-11e5-8318-01058eb711ae.png)

Seems related to: https://github.com/Khan/KaTeX/issues/61

**Comment by kevinbarabash** [comment]
The code for `aligned` environment has been merged, but we still need to do a release.
