### ISSUE TITLE
Cross-product doesn't render

### ISSUE THREAD

**Issue by jackparmer** [Khan/KaTeX#413]
Via http://www.intmath.com/cg5/katex-mathjax-comparison.php?processor=MathJax

![image](https://cloud.githubusercontent.com/assets/1865834/11765193/21535826-a11b-11e5-8a5f-0cdfda12a189.png)

**Comment by kevinbarabash** [comment]
The follow code from the link does rendering although the spacing/sizing doesn't quite match the screenshot above:
```
\mathbf{V}_1 \times \mathbf{V}_2 =  \begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
\frac{\partial X}{\partial u} &  \frac{\partial Y}{\partial u} & 0 \\
\frac{\partial X}{\partial v} &  \frac{\partial Y}{\partial v} & 0
\end{vmatrix}
```
Is this issue about the rendering?

**Comment by mbourne** [comment]
Jack's screen shot is the MathJax rendering.

I updated my copy of KaTeX and now that equation is fine (except for the problem of fractions overlapping each other that I mentioned before). I don't think the cross-product was giving the problem in KaTeX rendering - it was \mathbf.

**Comment by jackparmer** [comment]
Yes, sorry for the lack of detail. here is a screenshot of the KaTeX rendering:

![image](https://cloud.githubusercontent.com/assets/1865834/11793869/076ad80a-a27c-11e5-9774-9ba25552266d.png)

(You can see the rendering online here: http://www.intmath.com/cg5/katex-mathjax-comparison.php) 

The issue as @mbourne pointed out is the fraction overlapping. 

@mbourne Even without \mathbf, I'm seeing fraction overlap in cross product notation:

![image](https://cloud.githubusercontent.com/assets/1865834/11794022/14519634-a27d-11e5-8876-66989909c123.png)

**Comment by kevinbarabash** [comment]
Here's the LaTeX rendering:
<img width="597" alt="screen shot 2015-12-14 at 1 50 25 pm" src="https://cloud.githubusercontent.com/assets/1044413/11795179/2caf08a0-a26a-11e5-957f-ef41734bd437.png">

Here's the KaTeX rendering (using what's in the repo):
<img width="588" alt="screen shot 2015-12-14 at 1 51 11 pm" src="https://cloud.githubusercontent.com/assets/1044413/11795212/56b5af50-a26a-11e5-86e6-7c17a1bb2e49.png">

I believe we have the correct rendering using LaTeX as our guide.  The following article suggests passing `\\` an optional param to make vertical adjustments: http://tex.stackexchange.com/questions/33502/vertical-spacing-between-fractions-in-matrix-environment.  We currently don't support this, but we probably should look at adding it.
