### ISSUE TITLE
How can convert katex html to katex formula ?

### ISSUE THREAD

**Issue by vxba** [Khan/KaTeX#418]
when render katex formula to html.
How can convert katex html to katex formula  again?

**Comment by kevinbarabash** [comment]
It can't.  One option would be to save a copy of the original KaTeX formula before typesetting it.  It might also make sense to add a feature that embeds a copy of the original KaTeX formula in the HTML.  What use case do you need the original formula for?

**Comment by vxba** [comment]
I making tool can add and edit math formula.
It's same as here http://www.wiris.com/editor/demo/en/mathml-latex.
Do you have a solution for this?
thank kevinbarabash !

**Comment by sthoch** [comment]
The span.katex>span.katex-mathml>math>semantics>annotation tag contains the LaTeX Code. Is this what you are looking for?

**Comment by vxba** [comment]
yes I see it but my problem is when use change the formula rendered by katex then change  the LaTeX Code too. Do you know a solution for me ?
thank you sthoch!

**Comment by kevinbarabash** [comment]
https://github.com/Khan/KaTeX/issues/358 has a link to WYSIWYG math editor that uses KaTeX.

**Comment by vxba** [comment]
Thank you so much kevinbarabash!

**Comment by mourad1081** [comment]
I am sorry to post something that has been closed since 2015 but Google brought me here and I wrote a little function (using jQuery) that does the trick. I use it to convert my Katex formulas to CKeditor : 


```javascript
function htmlKatexToFormula(container) {
    var formulas = container.find('span.katex');
    for(var i = 0; i < formulas.length; i++) {
        var originalFormula = $(formulas[i]).find('annotation').text();

        if ($(formulas[i].parentNode).hasClass('katex-display'))
            formulas[i] = '\\[' + originalFormula + '\\]';
        else
            formulas[i] = '\\(' + originalFormula + '\\)';
    }

    container.find('.katex').each(function (key, val) {
        $(val).replaceWith(formulas[key]);
    });
}
```


Before using Ckeditor's setData(), I call the little function above in order to modify the html.
