### ISSUE TITLE
Add support for official npm package

### ISSUE THREAD

**Issue by pe8ter** [Khan/KaTeX#419]
It would great if Khan Academy supported the built KaTeX library available through npm.

The current KaTeX package named 'katex' on npm does not appear to be maintained by Khan Academy. Even if this assessment is technically incorrect, the package has issues. Instead of representing the built library with minified code and fonts included, it is a CLI interface for converting KaTeX into HTML markup.

**Comment by kevinbarabash** [comment]
https://www.npmjs.com/package/katex is the official npm package.  I believe this is a duplicate of https://github.com/Khan/KaTeX/issues/114 and https://github.com/Khan/KaTeX/issues/148.

**Comment by pe8ter** [comment]
Yeah, this is a dupe. I would still say that it's confusing that the named maintainer of the npm project isn't Kahn, but oh well.

Close away, Mr. McManus!

**Comment by spicyj** [comment]
`require('katex')` should work if you're using browserify or webpack. The two maintainers of the katex package currently are the two top contributors to the repo: https://github.com/Khan/KaTeX/graphs/contributors. We don't have a Khan Academy npm account at the moment.
