### ISSUE TITLE
Add support for alternative math fonts

### ISSUE THREAD

**Issue by daturkel** [Khan/KaTeX#42]
LaTeX has support for quite a few math fonts/alphabets. #19 references the need for \mathrm (roman fonts), but there are quite a few, as we can see [here](http://tex.stackexchange.com/questions/58098/what-are-all-the-font-styles-i-can-use-in-math-mode). The high priority ones, which don't require any nonstandard packages, would probably be:
\mathrm
\mathcal
\mathbb (requires amsfonts/amssymb)
\mathbf

**Comment by PeterBocan** [comment]
+1 
what can I do to implement this feature? (cc @xymostech @spicyj )

**Comment by raichu** [comment]
Please consider adding [esstix](https://www.ctan.org/pkg/esstix) [font](https://en.wikipedia.org/wiki/STIX_Fonts_project#ESSTIX) ([ttf](http://www.w3.org/Amaya/Distribution/esstix.tar.gz)).

**Comment by spicyj** [comment]
Merging into #19.
