### ISSUE TITLE
Speed test doesn't work

### ISSUE THREAD

**Issue by astoilkov** [Khan/KaTeX#420]
It fails with:

```
Uncaught ReferenceError: MathJax is not defined.

message: Uncaught ReferenceError: MathJax is not defined
fileName: https://jsperf.com/katex-vs-mathjax
lineNumber: 129
```

**Comment by edemaine** [comment]
Just bumped into this as well. The problem is this code in the speed test:

```html
<link href="http://xymostech.com/katex/katex.min.css" rel="stylesheet" type="text/css">
<link href="http://xymostech.com/katex/fonts/fonts.css" rel="stylesheet" type="text/css">
<script src="http://xymostech.com/katex/katex.min.js"></script>
```

It would work if it could be changed to:

```html
<link href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css" rel="stylesheet" type="text/css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/fonts.css" rel="stylesheet" type="text/css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js"></script>
```

**Comment by kevinbarabash** [comment]
Looks like someone made the proposed changes in https://jsperf.com/katex-vs-mathjax/47.  It's still not working, but it looks like an unrelated issue in the setup code.

**Comment by oddhack** [comment]
Perhaps this link could be removed from the README until it's working - I just ran into this as well (also giving a "ReferenceError: katex is not defined" as well as the MathJax error).

**Comment by mbourne** [comment]
&lt;shamelessplug&gt; 
  In the meantime, here's my KaTeX-MathJax speed comparison: http://www.intmath.com/cg5/katex-mathjax-comparison.php 
&lt;/shamelessplug&gt;

**Comment by kevinbarabash** [comment]
@mbourne would you be okay with us pointing to your speed comparison in the README?

**Comment by edemaine** [comment]
@mbourne Great examples! (And wow, what a speedup -- I get 25x on desktop and 50x on mobile.)  Helpful also to have the bad examples.  I tried the cross product example and, while it indeed looks bad in KaTeX and good in MathJax, it actually looks *the same as KaTeX* in PDFLaTeX.  Another solution would be to change the `\\` into `\\[0.5ex]` for example, which works in LaTeX and KaTeX (didn't try MathJax).  On the other hand, Maxwell's Equation looks much better in MathJax than KaTeX, so that's a bug.

**Comment by stevem6** [comment]
Maxwell's Equations look fine with extra vertical spacing eg using \\\\ \\\\. See IntMath Samples option at http://sixthform.info/katex/examples/demo.html
I also used different (and variable) vertical spacing for the Cross Product, but then I expect to do that sort of adjustment in LaTeX when using fractions in matrices or align environments etc, so I'm not bothered by the need to do so in KaTeX.

**Comment by mbourne** [comment]
@kevinbarabash: Feel free to include it in the README.

@edermaine: Thanks for your kind comments.

**Comment by reagle** [comment]
I just tried the online version <http://jsperf.com/katex-vs-mathjax/> and it fails. I'm a newbie, but this looks bad for your project when your own test can't complete!

Testing in Chrome 55.0.2883 / Mac OS X 10.11.6

**Comment by kevinbarabash** [comment]
Now that we're pointing to http://www.intmath.com/cg5/katex-mathjax-comparison.php in the README maybe we should delete the jsperf test.

**Comment by edemaine** [comment]
Oh, do you have access to change the jsperf test?  I thought we had to make a new one.  I think jsperf would be better/good in addition -- it has trustworthy measurement technology.

**Comment by kevinbarabash** [comment]
I can't get jsperf.com to even load.  If it comes back online we can re-open this and try to figure out how to update the perf test.  If we're concerned about accuracy of the new katex-mathjax comparison we might look at using https://github.com/bestiejs/benchmark.js (this is what jsperf uses), but the difference in speed right now is at least an order of magnitude so I wouldn't bother.
