### ISSUE TITLE
\centerdot displays as a low dot

### ISSUE THREAD

**Issue by ronkok** [Khan/KaTeX#421]
The `\centerdot` symbol function displays as a low dot. It should display as, well, a center dot. The problem is the glyph for U+22C5 in the AMS font. If `symbols.js` were to point `\centerdot` at the main font, it would be better.

**Comment by kevinbarabash** [comment]
@ronkok thanks for the report.  Yeah, that's totally the wrong glyph.  It looks like `\centerdot` is an alias for `\cdot` or vice versa.

**Comment by spicyj** [comment]
In real LaTeX it shows as a low square for me:

![image](https://cloud.githubusercontent.com/assets/6820/12039268/cb8d9e1e-ae13-11e5-8bc2-5908170a05cf.png)

I don't think it should be a cdot alias? Wouldn't make much sense since centerdot is in amssym and cdot is in the core.

**Comment by kevinbarabash** [comment]
It looks like MathJax is doing the wrong thing here.  I'm going to revert that last commit.

**Comment by ronkok** [comment]
Point taken. I was confused by:
1. The name `\centerdot` sounds like it should be a centered dot, and 
2. The STIX package makes `\centerdot` a synonym to `\cdotp`.

But AMS and three other packages all display it the same way that KaTeX displays it.

I withdraw my issue. Thank you for your patience.

**Comment by kevinbarabash** [comment]
Commit reverted. @spicyj thanks for noticing my mistake so quickly.
