### ISSUE TITLE
incorrect spacing of operators when combining fonts and sub-/sup-scripts

### ISSUE THREAD

**Issue by ccreus** [Khan/KaTeX#424]
The spacing to the right of + is wrong with an expression like: 
a+\mathtt{a}_1
The spacing is correct when either \mathtt or _1 is omitted.

This behavior also occurs when:
- using \mathit, \mathsf, etc., instead of \mathtt
- using a superscript ^1 instead of the subscript _1
- changing + by other operators with some spacing to their right, like >, \leq, \mid, etc.

**Comment by kevinbarabash** [comment]
Thanks for the bug report.  I've verified the issue, but I'm not sure what's causing it.

**Comment by kohler** [comment]
This is a duplicate of #534.
