### ISSUE TITLE
How to add degree sign?

### ISSUE THREAD

**Issue by evgeniy-storozhenko** [Khan/KaTeX#426]
Hi guys, could you help me with that issue? I just try this simple code:

```
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="katex.min.css">
    <script src="katex.min.js"></script>
</head>
<body>

<div id="katexBlock">
</div>

<script>
    var exp = "sin(30^{\circ})";
    var elem = document.getElementById("katexBlock");
    elem.innerHTML = katex.renderToString(exp);;
</script>

</body>
</html>
```

but result is:
<img width="103" alt="result" src="https://cloud.githubusercontent.com/assets/6041943/12139015/14374db0-b47f-11e5-92b7-9be613f7b4d1.png">

**Comment by kevinbarabash** [comment]
The example works on http://khan.github.io/KaTeX/.  In this case though you don't need to wrap `\circ` in a group.  Also the `\sin` operator is the correct way to write "sin".  `\sin(30^\circ)`.  Which version of KaTeX are you using?

**Comment by xymostech** [comment]
I think the problem is that you're not actually escaping the backslash in your equation. Your line should probably read

```
var exp = "sin(30^{\\circ})";
```

You also probably should put a doctype at the top of your HTML file, or you might run into strange bugs.

**Comment by evgeniy-storozhenko** [comment]
xymostech, thank you! It works!
