### ISSUE TITLE
_\vec{r} doesn't work 

### ISSUE THREAD

**Issue by wackywendell** [Khan/KaTeX#427]
This works: `A_{\vec{r}}`

But this doesn't: `A_\vec{r}`

The latter compiles with latex successfully, although it does give an error.

This is similar to #247, possibly the same; Latex does compile this one, though, and so it would be nice if Katex did too.

**Comment by xymostech** [comment]
My version of LaTeX doesn't successfully compile `A_\vec{r}`, it says "! Missing { inserted." Where are you using it that it does compile?

**Comment by kevinbarabash** [comment]
It also does not work in my version of LaTeX which is pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015).   It works in MathJax though.  I'm going to close as won't fix b/c we want to maintain LaTeX compatibility.

**Comment by wackywendell** [comment]
Using the standard pdflatex provided by ShareLatex (which is just compiling with latex server side), you do get an error, but it also compiles and shows both examples just fine. See [here](https://www.sharelatex.com/project/5697eb5b9439f4be522732cb).

On my machine (Arch linux, Tex Live 2015.38835-1), running pdflatex does give that error, but if you just hit enter to continue the output comes out correct. Similarly, using `pdflatex -interaction nonstopmode main.tex` also yields correct output, with no user input required to continue.

I don't know what your stance is on things that produce an error but still compile, but if you really wanted to maintain latex compatibility as close as possible, it seems like this should error (as it does now) but *also* produce the expected output, e.g. `abc_\somecommand{xyz}` ↔ `abc_{\somecommand{xyz}}`.

**Comment by xymostech** [comment]
Hmm, interesting! TeX is much better at error recovery than we are. I'll make a feature request for some sort of error recovery. Thanks for reporting!

**Comment by wackywendell** [comment]
That sounds like an excellent idea! Great!
