### ISSUE TITLE
add support for matrices

### ISSUE THREAD

**Issue by vks** [Khan/KaTeX#43]
It would be great to support things like `\begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}` like MathJax does.

**Comment by hobson** [comment]
+1 for {matrix} and {bmatrix}. Really need it for linear algebra on slides.com and reveal.js presentations

**Comment by paxidently** [comment]
+1

**Comment by slametapr** [comment]
+1 for matrix

**Comment by karoltarasiuk** [comment]
oh yeah +1

**Comment by PeterBocan** [comment]
waiting for that day and then I'll move my ass from MathJax to KaTeX. +1!

**Comment by RodrigoCard** [comment]
I am allowed to say +1 :+1:  here too? :)

**Comment by gagern** [comment]
Can we close this, now that #246 has been merged?

**Comment by xymostech** [comment]
Yes! Fixed by #246

**Comment by PeterBocan** [comment]
Uhm... I'm feeling the next upcoming release gonna be soon with a whole lotta of sweets.

**Comment by NateZimmer** [comment]
+1 ... was this ever implemented?

**Comment by gagern** [comment]
@NateZimmer: yes, #246 implemented this, and KaTeX releases since [0.4.0](https://github.com/Khan/KaTeX/releases/tag/v0.4.0) include that code. Simply give it a try on https://khan.github.io/KaTeX/. If something about matrices doesn't work as expected, that would likely be a separate issue.
