### ISSUE TITLE
Greater than and Less than??

### ISSUE THREAD

**Issue by maryfries** [Khan/KaTeX#430]
I can't get > or < to work. As soon as I insert them, that span disappears and all KaTeX spans after it stop working too.

That is, this HTML,
![image](https://cloud.githubusercontent.com/assets/6549787/12685128/81975a76-c690-11e5-8b5a-259e822ac4e6.png)

Produces this result:
![image](https://cloud.githubusercontent.com/assets/6549787/12685042/0157a000-c690-11e5-9f3a-0cffa060f693.png)

The second list item works as soon as I remove the > sign.

It the second list item also works fine with \geq instead of >
![image](https://cloud.githubusercontent.com/assets/6549787/12685070/2f79a514-c690-11e5-8859-07df2bbf2ef9.png)

And of course, "& g t ;" doesn't work in the span at all.

Am I missing something here or is this a bug? I can't imagine no one has caught this before. 

What's the right way to use a greater than or less than sign with KaTeX?

**Comment by spicyj** [comment]
```
<span class="katex">n &gt; 2</span>
```

should definitely work.

**Comment by spicyj** [comment]
If not, can you post a simple jsbin that shows the problem?

**Comment by maryfries** [comment]
It does not work. 

I'm not familiar with jsbin. Can you provide more details?

**Comment by spicyj** [comment]
Here's two examples of how to do it:

http://jsbin.com/zebiwodeto/edit?html,output

**Comment by maryfries** [comment]
I'm still not sure what you want me to do. If I put that code on my page it works.

But < s p a n   c l a s s = " k a t e x " > n   & g t ;   2 < / s p a n > does not work on my site, though everything else in KaTeX has been fine.

**Comment by spicyj** [comment]
Well, how are you running katex?

**Comment by spicyj** [comment]
By the way: you can make code formatting by putting backticks around a piece of text instead of putting spaces between every letter.

**Comment by maryfries** [comment]
Looks like we have a local copy of katex.min.js and katex.min.css

Also we have this:
``llab.mathDisplaySetup = function () {
    var cssFile, jsFile, css, js;
    cssFile = llab.paths.css_files.math_katex_css;
    jsFile  = llab.paths.math_katex_js;
    css = getTag('link', cssFile, 'text/css');
    css.rel = "stylesheet";
    js = getTag('script', jsFile, 'text/javascript');
    $(js).attr({'onload': 'llab.displayMathDivs()'});
    document.head.appendChild(css);
    document.head.appendChild(js);
}``

``llab.displayMathDivs = function () {
    $('.katex, .katex-inline').each(function (idx, elm) {
        katex.render(elm.innerHTML, elm, {throwOnError: false});
    });
    $('.katex-block').each(function (idx, elm) {
        katex.render(elm.innerHTML, elm, {
            displayMode: true, throwOnError: false
        });
    });
}``

**Comment by spicyj** [comment]
Try changing `.innerHTML` to `.textContent`.

**Comment by maryfries** [comment]
That worked!! Thanks!!!

**Comment by spicyj** [comment]
No problem. :)
