### ISSUE TITLE
Underscore support in \text

### ISSUE THREAD

**Issue by reupen** [Khan/KaTeX#432]
Any reason underscores in a `\text` expression e.g. `\text{ab\_d}` don't work?

It raises the following error:
`Error: KaTeX parse error: Expected '}', got '\_' at position 24: tyle{\text{ab\_̲d}}`

(As a workaround, `\text{ab}\_\text{d}` seems to do the job though.)

**Comment by kevinbarabash** [comment]
Fixed on `master`.
