### ISSUE TITLE
Parsing --1 fails

### ISSUE THREAD

**Issue by jwmerrill** [Khan/KaTeX#433]
``` javascript
var katex = require('katex')
katex.__parse('--1')
// ParseError: KaTeX parse error: Expected 'EOF', got '--' at position 2: --̲
//     at new ParseError (/Users/jwm/src/latex-to-asciimath/node_modules/katex/src/ParseError.js:29:16)
```

**Comment by xymostech** [comment]
Are you sure you're using literal dashes (`-`) and not something else? It works fine for me!

![image](https://cloud.githubusercontent.com/assets/217900/12794949/8bfad9d6-ca6c-11e5-8a31-147e0afd4568.png)

**Comment by jwmerrill** [comment]
This appears to affect master, but not the latest release. I bisected it down to d423bec08921b.

**Comment by kevinbarabash** [comment]
@jwmerrill thanks for the bug report and bisecting.  We'll fix this before the next release.

**Comment by arnodel** [comment]
Specifically the following regex:
```js
var tokenRegex = new RegExp(
    "([ \r\n\t]+)|(" +                                // whitespace
    "---?" +                                          // special combinations
    "|[!-\\[\\]-\u2027\u202A-\uD7FF\uF900-\uFFFF]" +  // single codepoint
    "|[\uD800-\uDBFF][\uDC00-\uDFFF]" +               // surrogate pair
    "|\\\\(?:[a-zA-Z]+|[^\uD800-\uDFFF])" +           // function name
    ")"
);
```

The 'special combinations' line will match 2 or 3 consecutive minus signs.  I can't figure out what that could be for

**Comment by arnodel** [comment]
Ok, it's come back to me: -- and --- are valid tokens that render to long and very long dashes (see e.g. http://tex.stackexchange.com/questions/3819/dashes-vs-vs).

The problem seems that KaTeX now parses -- and --- as single tokens (correctly) but still doesn't know how to render them.

**Comment by arnodel** [comment]
In fact it seems from a few tests with LaTeX and it emerges that `--` (resp. `---`) is tokenised to two `-` tokens (resp. 3) in math mode.  So I guess that is what KaTeX should do?  In that case, the fix is simple enough, change the `tokenRegex` definition in `Lexer.js` to:

```js
var tokenRegex = new RegExp(
    "([ \r\n\t]+)|(" +                                // whitespace
    "[!-\\[\\]-\u2027\u202A-\uD7FF\uF900-\uFFFF]" +  // single codepoint
    "|[\uD800-\uDBFF][\uDC00-\uDFFF]" +               // surrogate pair
    "|\\\\(?:[a-zA-Z]+|[^\uD800-\uDFFF])" +           // function name
    ")"
);
```

**Comment by kevinbarabash** [comment]
This was fixed on master in https://github.com/Khan/KaTeX/commit/4a9c2acbf7a50a6205cc3f42f374a4b3047c9bf1, but isn't in the most recent deploy.

**Comment by kevinbarabash** [comment]
I believe this change was part of the [v0.7.0](https://github.com/Khan/KaTeX/releases/tag/v0.7.0) release.
