### ISSUE TITLE
Accessing From Filesystem Fails

### ISSUE THREAD

**Issue by Vandivier** [Khan/KaTeX#434]
Consider the below snippet of HTML.

The snippet successfully renders output in conjunction with JSFiddle and Javascriptaroo, but it fails when saved as a local HTML file and accessed in the Firefox browser by a local path like 'C:Users\Jimbo\Desktop\my-test.html'

```html
<!DOCTYPE html>
<head>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.js"></script>
</head>
<body>
<div id="results"></div>
<script>
var eq = 'f(x) = \\int_{-\\infty}^\\infty\\hat f(\\xi)\\,e^{2 \\pi i \\xi x}\\,d\\xi';
katex.render(eq, document.getElementById('results'));
</script>
</body>
```

**Comment by spicyj** [comment]
In what way does it fail?

**Comment by Vandivier** [comment]
Primarily, nothing is rendered.

The console also throws katex is undefined and an irrelevant encoding error:

ReferenceError: katex is not defined
The character encoding of the HTML document was not declared...

**Comment by spicyj** [comment]
Oh. Change the URLs to start with "https://" or "http://".
