### ISSUE TITLE
Fractions do not descend far enough when rendered through wkhtmltopdf

### ISSUE THREAD

**Issue by cdparks** [Khan/KaTeX#435]
I'm using Ubuntu 14.04, KaTeX 0.5.1, Chrome 48.0.2564.97 (64-bit), and wkhtmltopdf 0.12.1 (with patched qt).

This is a cut down version of my HTML document:
```html
<!DOCTYPE HTML>
<html>
  <head>
    <title>Worksheet</title>
    <meta charset="UTF-8">
    <style>
      .content .katex-display {
        display: inline-block !important;
        margin: .1em 0 .1em 1em !important;
        width: auto !important;
      }
    </style>

    <link rel="stylesheet" type="text/css" href="./katex.min.css">
    <script type="text/javascript" src="./katex.min.js">
    </script>

    <script type="text/javascript" src="./contrib/auto-render.min.js">
    </script>

  </head>
  <body>
    <div class="content">
      <p><strong>1. </strong>Which of the fractions below represents a whole broken into a total of 7 equal parts? Select all that apply.
      </p>
      <p>
        $$A)\ \frac{1}{7}$$ $$B)\ \frac{2}{7}$$ $$C)\ \frac{1}{8}$$ $$D)\ \frac{6}{7}$$ $$E)\ \frac{7}{8}$$
      </p>
      <p>
        <strong>2. </strong>
        You cut a pizza into 6 equal pieces.  If you eat one piece, what fraction of the pizza did you eat?
      </p>
      <p>
        Choose one: [ \(\frac{1}{3}\) | \(\frac{1}{4}\) | \(\frac{1}{5}\) | \(\frac{1}{6}\) ]
      </p>
    </div>
    <script>
      renderMathInElement(document.body)
    </script>
  </body>
</html>
```

This renders nicely in Chrome:
![crm-katex](https://cloud.githubusercontent.com/assets/592078/12831996/3b4a4964-cb4c-11e5-8378-09312101475c.png)

However, when I render to PDF using wkhtmltopdf, I get this:
![wk-katex](https://cloud.githubusercontent.com/assets/592078/12832007/4d0ed070-cb4c-11e5-996d-2a2872ffa23e.png)

The fractions don't appear to descend as much as they do in Chrome. I've tried to play with the styles that are being generated, but it's not obvious to me how they work (especially the various `struts` and `fix-baseline`).

**Comment by xymostech** [comment]
This unfortunately sounds more like a problem with wkhtmltopdf than with KaTeX. You could try filing an issue there? You might also want to try visiting the page in qt webkit, and see what it looks like there? I have no idea how it works though.

**Comment by remko** [comment]
@cdparks Did you end up filing an issue there? Or did you find a workaround?
