### ISSUE TITLE
Add support for \pmod \underline

### ISSUE THREAD

**Issue by iwtwiioi** [Khan/KaTeX#438]
I am trying to use KaTeX instead of MathJax. But some keywords are not supported such like \pmod \underline. It's important for me. Would you add these keywords?
Thanks.

**Comment by abejfehr** [comment]
`\underline` was already requested in #209

**Comment by kevinbarabash** [comment]
`\pmod` was requested in https://github.com/Khan/KaTeX/issues/393.  Closing as duplicate.
