### ISSUE TITLE
UTF-8 TeX or XeTeX

### ISSUE THREAD

**Issue by Sukii** [Khan/KaTeX#440]
Hi,

MathML in Firefox supports most unicode characters including most language scripts.
I suppose that KaTeX implements only a small subset of the unicode like TeX but since most modern browsers support unicode characters by default, why not implement utf-8 version of TeX like XeTeX?
We could mix Tamiil script and write in TeX: "ர=1". 

Suki

**Comment by kevinbarabash** [comment]
@Sukii this will be support out of the box in the next release.
