### ISSUE TITLE
\Bbbk should render a "k" using Fraktur

### ISSUE THREAD

**Issue by ronkok** [Khan/KaTeX#443]
Back in early January, I edited the KaTeX wiki page for function support, and added documentation of many symbols. But I only added the ones that I could independently verify as working correctly.

So this issue is just to mention that I omitted two symbols at that time. `\Bbbk` and `\Game` are both coded into symbols.js. However, `\Bbbk` fails to render properly in FireFox, Chrome, IE, and Edge. `\Game` renders well in most browsers, but fails in Chrome (for Windows).  Below is a screenshot from Chrome.

I don't mean to imply that this needs urgent attention. `\Game` and `\Bbbk` are both pretty obscure. But I thought you might like to know.

![Game-Bbbk](http://copyasmarkup.com/Game-Bbbk.PNG)

**Comment by ronkok** [comment]
Update: I just checked and Chrome now renders `\Game` properly.  The `\Game` part of this issue is now moot.

`\Bbbk` still renders exactly like `\text{k}`.

**Comment by kevinbarabash** [comment]
@ronkok thanks for reporting this.  It looks like https://github.com/Khan/KaTeX/blob/e6de31d2d622f01aae6d465cf332a268332942f4/metrics/mapping.pl#L943 should be in the `"Fraktur-Regular"` section.

**Comment by kevinbarabash** [comment]
For anyone following this `\Bbb{k}` works correctly and can be used in lieu of `\Bbbk` until it's fixed.

**Comment by kevinbarabash** [comment]
This is fixed in [v0.8.0](https://github.com/Khan/KaTeX/releases/tag/v0.8.0).
