### ISSUE TITLE
Customize formule style

### ISSUE THREAD

**Issue by invkrh** [Khan/KaTeX#446]
I am using katex on my blog via cdn
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.js"></script>
```
The default css is not fit to the theme of my blog. 
Is there a way to change the formule css style on client code ?
I am using auto-render. A formule is like the following
```
$$
\begin{array}{clc}
(3, 4) &\rightarrow f(x) = (3x + 4) \% 12 \\
x = 0, 1, 2 .. 11 &\rightarrow f(x) = 4, 7, 10, 1, 4, 7, 10, 1, 4, 7, 10, 1
\end{array}
$$
```
I can not get the class of the formule html element. A workaround is make the formule block surrounded by <div class="math"> ... </div>. It is tedious.

In MathJax, I can easily add class to all of the formule block:
```html
<script type="text/x-mathjax-config">
  MathJax.Hub.Queue(function() {
    // Fix <code> tags after MathJax finishes running. This is a
    // hack to overcome a shortcoming of Markdown. Discussion at
    // https://github.com/mojombo/jekyll/issues/199
    var all = MathJax.Hub.getAllJax(), i;
    for(i = 0; i < all.length; i += 1) {
        all[i].SourceElement().parentNode.className += ' has-jax';
    }
});
</script> 
```
And edit the css code of class `has-jax`

I am not sure Katex has this kind of feature.

Any idea ?

**Comment by xymostech** [comment]
Can you not apply styles to the `span.katex` elements? I'm not sure what the `.has-jax` class does.

**Comment by invkrh** [comment]
Thank you. It works. I find the class name in the document.
I should have been more careful.

**Comment by kevinbarabash** [comment]
@invkrh has the issue been resolved?

**Comment by invkrh** [comment]
Yes, it is resolved.
I close the issue
