### ISSUE TITLE
Position error when superscript is used with a long subscript

### ISSUE THREAD

**Issue by quxiaofeng** [Khan/KaTeX#447]
```
\[ x^l_{i^{l+1}+i, j^{l+1}+j, d} \]

\[ {x^l}_{i^{l+1}+i, j^{l+1}+j, d} \]

\( x^l_{i^{l+1}+i, j^{l+1}+j, d} \) or \( {x^l}_{i^{l+1}+i, j^{l+1}+j, d} \)
```

is rendered as

![image](https://cloud.githubusercontent.com/assets/1077425/13547390/f5d337ce-e30b-11e5-9861-84cc13cf529d.png)

**Comment by xymostech** [comment]
You are definitely right! It looks like the `text-align: center` that's applied by `.katex-display` is somehow applying to everything inside. Looks like putting `text-align: initial` on `.katex` fixes it, I'll make a pull request for that.

Thanks! Also, how are you enjoying using KaTeX on your website?

**Comment by quxiaofeng** [comment]
KaTeX is a great solution for my website. I have been using it in multiple pages and sites. It is fast and easy to be integrated into other templates. It is quite easy to add LaTeX equation support with just several lines of code.

However, I am still confused about the future of KaTeX. There are something that I really need to use, which is really annoying for now, for example, the "\arg\min" problem. Solving this problem needs function definition or redefinition. However, I do not know whether it will slow down the rendering of KaTeX.
