### ISSUE TITLE
Inline mode isn't actually inline

### ISSUE THREAD

**Issue by cavaunpeu** [Khan/KaTeX#449]
When using `katex.renderToString` with `displayMode: false`, the rendered math is still put on a new line, yet un-centered. When `true`, it is centered on the newline. Is there a way to get truly inline math?

**Comment by xymostech** [comment]
KaTeX produces inline math for me using `katex.renderToString`: http://jsbin.com/katesavunu/edit How are you using it specifically?

**Comment by cavaunpeu** [comment]
@xymostechI built a React component to render inline LaTeX:

```javascript
import React from 'react'

class InlineLatex extends React.Component {
    render() {
        var math = katex.renderToString(this.props.data);
        return (<p dangerouslySetInnerHTML={ {__html: math} }/>);
    }
}

module.exports = InlineLatex;
```

I then render the component in a separate `.js` file as part of an ordered-list:

```javascript
<ol>
    <li>
        foo <InlineLatex latex={"x_{a,b}"} /> bar
    </li>
```

The result is as follows:

<img width="214" alt="screen shot 2016-03-06 at 1 39 49 pm" src="https://cloud.githubusercontent.com/assets/7306239/13556163/eea95682-e3a0-11e5-9dab-2bbf58d60b0d.png">

**Comment by spicyj** [comment]
Try using a `span` instead of a `p`.

**Comment by cavaunpeu** [comment]
hehe. bingo. closed. thanks @spicyj and @xymostech.
