### ISSUE TITLE
Some characters have higher baseline than others

### ISSUE THREAD

**Issue by uranusjr** [Khan/KaTeX#45]
![screen shot 2014-09-16 at 11 39 30](https://cloud.githubusercontent.com/assets/605277/4282229/9b44b0c6-3d53-11e4-997d-41183de6e48e.png)

Top: http://khan.github.io/KaTeX/ in iframe. Bottom: custom rendering.

The smaller characters have a higher baseline than others. The `k`s even look like superscript.

[HTML file](https://gist.github.com/uranusjr/2882e927d055d02891f7). I used the CSS/JS/font files directly from the v0.1.0 release. Tested on OS X 10.9.4. The above was rendered with Safari 7.0.6, but other browsers also yield the same result.

**Comment by stefman2** [comment]
On a similar vein, I had noticed that, in my setup, which uses katex.renderToString(), KaTex was not positioning any subscripts lower at all. The CSS generated by KaTex seems to assume everything is already positioned, and has ...style="top:0.15em..." for positioning subscripts. So, to get it to work for me, I needed to change this to style="position:relative; top:0.15em..." in the output CSS and now it works.  (Explicitly setting a position attribute to "relative" in <span> tags containing the entire KaTex expression did not seem to work either.)
Any idea on what is causing KaTex elements to lose their position attributes, and whether Katex ought to rectify this in katex.renderToString()?

**Comment by xymostech** [comment]
@stefman2 Are you including the katex CSS file on your website? You need the main KaTeX CSS (which should have `position: relative` rules) as well as the generated HTML from `katex.renderToString`.

**Comment by stefman2** [comment]
Yes, I am including katex.min.css.  All the typesetting looks fine except for subscripts, and that minor change seems to do the trick as far as I can tell. I will look into this some more and try to isolate the problem; perhaps there is an issue with other CSS I have on the pages in question.

**Comment by mbourne** [comment]
Hello again

I'm still seeing subscripts rendered as superscript (almost) in IE v11, Win 7 with KaTeX 0.5.0 js and css.

![image](https://cloud.githubusercontent.com/assets/7541940/9375113/69e3aef6-472f-11e5-9c3b-2bf8f6a74d2e.png)

And on the same browser, superscripts end up too high 

![image](https://cloud.githubusercontent.com/assets/7541940/9375147/ca15c50c-472f-11e5-96fb-e9ed77282aab.png)

Here's the same portion on Chrome:

![image](https://cloud.githubusercontent.com/assets/7541940/9375163/f0977c70-472f-11e5-8af0-6cb2463e2b13.png)

The subscript problem is particularly troubling...

Regards
Murray

**Comment by ylemkimon** [comment]
Closing as it warns quirks mode (https://github.com/Khan/KaTeX/commit/ea5ee95dbec689953c35fa552e1170061a8a945d) and #661 is fixed.

**Comment by ylemkimon** [comment]
Please open a new issue if the problem still exists.
