### ISSUE TITLE
How to define \pmod?

### ISSUE THREAD

**Issue by netw0rkf10w** [Khan/KaTeX#452]
Hello,

Could anybody please tell me how to define the function `\pmod`? 
`\pmod a` is displayed as `(mod a)`

Thank you in advance.

**Comment by xymostech** [comment]
It doesn't seem like our current function support has a good way to do this. You could add a function in src/functions.js which returns a new type entirely (like `pmod`) and then handle it in both src/buildHTML.js and src/buildMathML.js.

However, `\pmod` sounds like something that would be easily solved using macros. We don't support those yet, however. See #250

**Comment by netw0rkf10w** [comment]
@xymostech :+1: Thanks!
