### ISSUE TITLE
Is katex responsive ?

### ISSUE THREAD

**Issue by invkrh** [Khan/KaTeX#455]
I am using katex for my math blog. It view point of mobile is a problem, since katex does not seem to be responsive.

If a formula is too long, its width will be larger than the outer container, which breaks responsive design. 
The whole view point is scaled. It is not normal. I think js code makes the formulas appear in this way.

The only way to shorten the width is to set `font-size` to a smaller value on `.span.katex` class.
I have tried set `width` property to a smaller value, but it does not work.

Any way to put the formula exactly within its parent elements, when the view point is small, like smart phone.

**Comment by spicyj** [comment]
We would like inline formulas to wrap across lines but haven't had the time to implement it.

**Comment by spicyj** [comment]
I guess #327 tracks that.
