### ISSUE TITLE
ETA for a new release?

### ISSUE THREAD

**Issue by mbourne** [Khan/KaTeX#458]
There's been lots of new goodies, but no new release since Sep 2015.

Looking forward to it!

**Comment by medonja** [comment]
That would be awesome. It seems like the project needs some revival :)

**Comment by kevinbarabash** [comment]
@mbourne wow, I didn't realize it had been that long.  There's definitely new stuff on master that we should release.

**Comment by kevinbarabash** [comment]
Done.  With lots of help from @xymostech, thanks!
