### ISSUE TITLE
Sample code doesn't work?

### ISSUE THREAD

**Issue by eneim** [Khan/KaTeX#459]
I parse this: ```c = \\pm\\sqrt{a^2 + b^2}``` into katex page but It doesn't render the form.

<img width="831" alt="screenshot 2016-04-13 12 17 41" src="https://cloud.githubusercontent.com/assets/1776230/14481845/c6ced7b0-0171-11e6-85d1-5e0820148f9c.png">

**Comment by xymostech** [comment]
The example is a javascript string, in which the backslashes are escaped. You don't need the extra backslashes when you type it into the example page. So you should type in: `c = \pm\sqrt{a^2 b^2}`, and it works: 
![image](https://cloud.githubusercontent.com/assets/217900/14482062/53bcc496-00ed-11e6-8dbe-8562cd83b6b4.png)
