### ISSUE TITLE
CJK Characters cause parse error

### ISSUE THREAD

**Issue by episodeyang** [Khan/KaTeX#460]
Hi, 

I noticed the problem is referred to here: #380. 

As of now, passing any CJK characters (Chinese, Japanese, and Korean) into the math lead to parse error.

What kind of work does it take to support CJK characters?

Thanks,
Ge

**Comment by spicyj** [comment]
It would require a font that can render them and enough information about the metrics so that the math can be placed around it properly. Closing in favor of #380.
