### ISSUE TITLE
Is there any versioning of KaTeX?

### ISSUE THREAD

**Issue by YakovL** [Khan/KaTeX#462]
There's a [question on Stackoverflow](http://stackoverflow.com/questions/36666141/greek-fonts-for-katex) which I wanted to comment in a way like "I don't have this issue, what's the version of KaTeX you are using?" but stumbled upon the fact that I can't find any versioning numbers neither in files (readme) nor in the `katex` object itself. Is there any versioning at all and if not why is that?

**Comment by spicyj** [comment]
Consuming KaTeX from npm, bower, cdnjs, or GitHub releases will all give a version number, though you're correct it doesn't appear in the file itself.

As for the actual question linked, we don't currently support Greek letters as input. See #243.
