### ISSUE TITLE
Collision with bpgdec8a.js of Fabrice Bellard's BPG decoder.

### ISSUE THREAD

**Issue by polemon** [Khan/KaTeX#467]
I noticed that when using `bpgdec8a.js` of [Fabrice Bellard's BPG decoder](http://www.bellard.org/bpg/), it seems to interrupt KaTeX in rendering math.

I have a couple of examples ready:

- [KaTeX](http://polemon.org/markdown/qmath_katex_nobpg.html)
- [KaTeX + bpgdec8a.js](http://polemon.org/markdown/qmath_katex_bpg.html)

There are no errors when viewing either HTML page. Both files are identical, except the second one loads `bpgdec8a.js` to display BPG images (no BPG images are present on either pages).
I'm using pandoc to create these pages from a markdown source, in case anyone wonders.

I've contacted Fabrice Bellard, and he suggested, that both scripts may intercept the `window.onload` property, however looking through `katex.min.js` I couldn't find `window.onload` being referenced.

However `pandoc` puts a function into `window.onload`, to scan through the document for math objects.

At this point I'm not sure how to work around that problem. MathJax works fine with the BPG Javascript decoder scripts. Not being able to have both, KaTeX and BPG is not so much a problem, as it threw a pretty uncomfortable gotcha at me, since it just kept KaTeX from rendering math.

So, this isn't supposed to be a bug report as such, instead more of an advisory note, that these two things don't work together.

**Comment by xymostech** [comment]
@polemon Huh, interesting! Indeed, this doesn't sound like a `KaTeX` problem, but thanks for letting us know.

A solution might be convincing the libraries to use `window.addEventListener("load", ...)` instead of setting `window.onload`, so that they can both run.

**Comment by polemon** [comment]
OK, I guess I'll let the BPG developer know about this. Maybe he'd be willing to change things.
In the mean time, I'll see if I can find a work-around and post here if I find anything.
