### ISSUE TITLE
\stackrel support

### ISSUE THREAD

**Issue by shd101wyy** [Khan/KaTeX#468]
Any plan to add support for `\stackrel`?

Thanks

**Comment by kevinbarabash** [comment]
Yes, that is on our list of priority items.

**Comment by shd101wyy** [comment]
Thank you very much! 
KaTeX is a fancy library!

**Comment by kevinbarabash** [comment]
Reopening as this isn't tracked anywhere.

**Comment by kevinbarabash** [comment]
This has been added to `master`.
