### ISSUE TITLE
Fonts dont always load during automated screenshot chrome test

### ISSUE THREAD

**Issue by mathijshenquet** [Khan/KaTeX#470]
Some selenium chrome test containing special fonts (mathbb, mathfrak, etc) randomly fail on my system. Visually the characters set in the special fonts are invisible. Possibly this is related to[1](https://productforums.google.com/forum/#!topic/chrome/kBzYJZV-qMM;context-place=topicsearchin/chrome/category$3Amac|sort:relevance|spell:false)

**Comment by kevinbarabash** [comment]
We could try using https://github.com/typekit/webfontloader to force load fonts before taking the screenshot.

**Comment by kevinbarabash** [comment]
The screenshotter has been fairly reliable of late so I'm going to close this issue.
