### ISSUE TITLE
Certain chars inside `\text` crash KaTeX: `#$%^&{}_`

### ISSUE THREAD

**Issue by lolmaus** [Khan/KaTeX#474]
Got this formula:

```
I =
\frac
{\text{# new cases}}
{\text{population at risk}}
```

It renders nicely in MathJax, but KaTeX crashes on the hash char:

> Uncaught ParseError: KaTeX parse error: Expected '}', got '#' at position 32

Note that escaping the hash char (which I think should not be necessary inside `\text{}`) does not prevent the crash.

PS When fixing this, please make sure all possible characters are addressed, not just the hash char.

**Comment by kevinbarabash** [comment]
> PS When fixing this, please make sure all possible characters are addressed, not just the hash char.

Are there other characters causing a crash?

**Comment by lolmaus** [comment]
I've just tried, and these ones fail: `#$%^&{}`. I expect all of them to work without escaping, except for curlies which should obviously be escaped.

**Comment by spicyj** [comment]
$ should start math mode, % makes a comment in LaTeX. Maybe #^& are all okay though…

**Comment by lolmaus** [comment]
@spicyj How can you start math mode from inside `\text{}`?

PS That list is not explicit, some other chars might be broken as well.

**Comment by spicyj** [comment]
```
\text{my favorite variable is $x$}
```

**Comment by lolmaus** [comment]
@spicyj Why not `\text{my favorite variable is } x`? If you allow math mode inside `\text`, should you also allow `\text` inside math mode inside `\text`?

Woah, I just tried it in MathJax and it does allow such nesting.

Anyway, your code doesn't work in KaTeX! And doing `\$` inside `\text` should also be possible, right?

**Comment by spicyj** [comment]
Yeah, we have #5 tracking that it doesn't work in KaTeX. Doing `\$` inside `\text` should be possible, yes.

**Comment by sthoch** [comment]
`_` is a culprit, as well.

**Comment by astoilkov** [comment]
We have some users that use MathJax and complaint the missing feature in KaTeX. Do you have any estimate when we could expect this resolved? This way we could inform our users when they could expect it.

Thanks.

**Comment by kevinbarabash** [comment]
This hasn't really been an issue for our use case AFAIK.  We don't have anyone doing dedicated development so I can't give an estimate.  Pull requests to address this are welcome.
