### ISSUE TITLE
throwOnError confusing

### ISSUE THREAD

**Issue by johanneswilm** [Khan/KaTeX#475]
the name "throwOnError" sounds like it would cover all types of errors. It is unclear whether it is supposed to cover all types of errors or only those based on yet unknown latex commands.

This throws a parse error:

```
katex.render('2+x{',document.body,{throwOnError:false})
```

**Comment by lolmaus** [comment]
Also ran into this issue. It looks like a bug to me.

**Comment by shuttle1987** [comment]
From by discussions in this PR https://github.com/Khan/KaTeX/pull/540 I now realize that `throwOnError` only changes how KaTeX handles the behavior of unsupported TeX commands. It doesn't currently deal with other parsing related issues, those will still throw exceptions.

**Comment by edemaine** [comment]
FWIW, I too was confused by this.  Effectively, the option is "throw on use of incorrect \command" -- not what I expected.

**Comment by edemaine** [comment]
Fixed by #1169.
