### ISSUE TITLE
Support Arabic/Persian (UTF-8) and other unicode Characters

### ISSUE THREAD

**Issue by pouriaMaleki** [Khan/KaTeX#476]
It seems that ([KaTeX](khan.github.io/KaTeX)) can't handle formulas with Persian chars

sample:

```
f(x) = \int_{-\infty}^\infty
    \hat f(\xi)\,e^{2 \pi i \xi x}
    \,d\xi\text{hello}
```

but Persian sample will throw:

```
f(x) = \int_{-\infty}^\infty
    \hat f(\xi)\,e^{2 \pi i \xi x}
    \,d\xi\text{سلام}
```

```
katex.min.js:formatted:362
Uncaught ParseError: KaTeX parse error: Expected '}', got 'س' at position 95:   \,d\xi\text{س̲لام}}
```

Is there any chance you know where the problem is or tell me where I can find the source of problem to fix it (and send a PR).

**Comment by xymostech** [comment]
We don't have font metrics for the Persian characters you're trying to render, so we throw instead of rendering something that looks bad. Closing in favor of #380, where we've discussed this more.

**Comment by pouriaMaleki** [comment]
Thanks @xymostech and other dudes on the team, nice and tidy work :)

Can you guys give me some tips and directions for adding new mono-space font for those chars and metrics and how to show them (escape from throwing)?

**Comment by pouriaMaleki** [comment]
I do think these 2 PR's might be useful for me, right?

https://github.com/Khan/KaTeX/pull/409/files#r60113059

https://github.com/Khan/KaTeX/pull/410/commits/d2ae5ed2f374a1b8ef404f312dd335bf5cfb810c

**Comment by sassanh** [comment]
@pouriaMaleki were you able to use Persian characters in KaTeX?

**Comment by pouriaMaleki** [comment]
Unfortunately not completely, I did some research and code reading, but my
friend @hosseinAgha started to work on it.

**Comment by HosseinAgha** [comment]
@sassanh I'm going to fix this in the following month.   
I will mention this issue as soon as pull request was ready.

**Comment by sassanh** [comment]
@HosseinAgha Thanks. Currently I had to turn back to MathJax but I'm looking forward for your pr.
