### ISSUE TITLE
Cubic (and others) roots are not supported

### ISSUE THREAD

**Issue by dryabov** [Khan/KaTeX#48]
Example: \sqrt[3]{x} should be rendered as ![](http://latex2png.com/output//latex_f5ae4867e22efaa63e4b1a2df960f3ef.png)

**Comment by jtrinklein** [comment]
looking forward to this feature, is it on the roadmap?

**Comment by ystreibel** [comment]
Hi, this issue is already here in v0.3.0
![katex_sqrt](https://cloud.githubusercontent.com/assets/3459111/7702545/358324da-fe31-11e4-97ce-25dcd5603681.png)
How could I do ?

**Comment by kevinb7** [comment]
@ystreibel this bug was fixed after v0.3.0 was released. If you build katex.js from the source it should be fixed there.

**Comment by ystreibel** [comment]
@kevinb7 Thanks for your workaround but is not working for me.
I compile the library with the Makefile on Debian. When I use the release file katex.js, the render is not displayed on my div element.

**Comment by ystreibel** [comment]
@kevinb7 Ok it's working now ! Thanks !

**Comment by spicyj** [comment]
The website wasn't on 0.3.0; now it is.
