### ISSUE TITLE
Implement <math atom> commands

### ISSUE THREAD

**Issue by cbreeden** [Khan/KaTeX#482]
The `<math atom>` commands are: 
- \mathop
- \mathrel
- \mathord
- \mathinner
- etc...

I feel that this is a necessary step before implementing user-defined macros.  An example use is to allow for question marks placed over equal signs `\stackrel{?}{=}` which is defined by 

```
\stackrel#1#2 \mathrel {\mathop {#2}\limits ^{#1}}
```

Or for user-defined operators like `\def\limsup {\mathop{\overline\mathrm{lim}}\limits}`.

I started working on an implementation and I was able to for the most part except that `\mathop{=}\limits^{?}` wouldn't work primarily due to TeX logic living in BuildHTML.js.  Certainly I could hack it out, but there were other issues involved such as implementing `\mathrel` commands would essentially require a new `relgroup`, just like there is a [`mathordgroup`](https://github.com/Khan/KaTeX/blob/master/src/buildHTML.js#L232) and so on to allow recursive expansion.  This brought me to conclude that it would most likely be better to wait for a new parser/AST implementation before continuing.

**Comment by WChargin** [comment]
See also #4.
