### ISSUE TITLE
Style changes breaks spacing

### ISSUE THREAD

**Issue by cbreeden** [Khan/KaTeX#486]
While playing around with the parser I noticed that KaTeX creates a new mathlist once it finds a style change, ie `\textstyle`.  This make sense sense this is how style changes will be displayed in html, and is probably a good optimization for what is _usually_ desired.

With input:
```
1\textstyle+2
```
HTML output (roughtly, using jade)
```jade
span.textstyle
    span.mord 1
    span.textstyle
        span.mbin +
        span.mord 2
```
Output:
![styles](https://cloud.githubusercontent.com/assets/12069845/15637062/280a2e8e-25d6-11e6-8eab-d49ade013241.png)

Expected Output:
![texput](https://cloud.githubusercontent.com/assets/12069845/15637072/5804237e-25d6-11e6-98fc-89dad6374aab.png)

Another, slightly more realistic example:

![phantom](https://cloud.githubusercontent.com/assets/12069845/15733162/da43a192-2848-11e6-9c1c-05540e61a2a2.png)

Not an important issue.  I'm just leaving this here future reference.

**Comment by PeterBocan** [comment]
Probably missing one space on the left side.

**Comment by cbreeden** [comment]
A thought crossed my mind.  Perhaps it would be worth while to style the margins using something like `mbin-mord` (no need to worry about transitivity issues, we are only setting the left margin of each), or better yet just setting a `thin/med/thick-skip` for each required atom.  The small cost in an extra calculation in BuildHTML may be outweighed by a smaller css file.

**Comment by kevinbarabash** [comment]
@cbreeden iirc, there are some macros which modify the values of some of the `skip` values so have these defined in code would be useful for macro support as well.  I've been doing some reading and spacing and apparently math mode use `muskip` as opposed to `skip`.

**Comment by cbreeden** [comment]
@kevinbarabash I decided to look at how MathJax handled this and it appears that MathJax will inline _everything_.  Certainly this makes it easier to handle overriding `skip` and `muskip` values easier.  Though it might be better to place the default values in css and then inline values that will be overridden.

**Comment by cbreeden** [comment]
Closing as a duplicate of #30
