### ISSUE TITLE
Subscripts and superscripts inside franctions are centered; should be left-aligned

### ISSUE THREAD

**Issue by digitalheir** [Khan/KaTeX#488]
Consider the term `\frac{1}{x_{666}^{9}}`

We would expect this to render as follows:

![photo489820666715058905](https://cloud.githubusercontent.com/assets/178797/15675877/3de7e4ca-2744-11e6-8fc4-8ce347dbbcfc.jpg)

Instead, 9 is centered wrt 666:

![photo83060647871494590](https://cloud.githubusercontent.com/assets/178797/15675892/525cc52e-2744-11e6-9145-3ea86731ccd7.jpg)

This doesn't happen outside of fractions, but may also occur in some other 'modes'?

![screenshot from 2016-05-31 15-29-19](https://cloud.githubusercontent.com/assets/178797/15675915/757d2f6c-2744-11e6-8a51-1bcd39a5e2fe.png)

**Comment by kevinbarabash** [comment]
@digitalheir thanks for the bug report.  This should be relatively easy to fix.
