### ISSUE TITLE
Remove symbols from functions.js

### ISSUE THREAD

**Issue by cbreeden** [Khan/KaTeX#495]
I was working on a `parser.js` refactor to simplify the logic and reduce how deeply nested the call stack is for various things like calling functions.  I realized that one of the complications which arises is that there is somewhat of a conflict between `functions.js` and `symbols.js` which therefore requires every 'isSymbol' check to be also consulted with an 'isFunction' and is essentially the reason `ParseFuncOrArgument` is required.

The conflicts are found in `symbol: true` operators defined in `functions.js` and accents defined in `functions.js`.  Perhaps it may be worth while defining:
- `defineNewAccent(...)` so that accents in `functions.js` can map to symbols (but they are not symbols themselves), and 
- `declareMathOperator(...)` to define operator symbols which included the required `limits: Bool`.  This would require a change in the `ParseNodes` API as far as I can tell.

I'm going to ignore this for now, and continue with the refactor with no ParseNode changes, with the additional logic to handle this.  I'm just leaving this here for future reference.

**Comment by ylemkimon** [comment]
Closing as we now have typed `ParseNode`s. Please reopen the issue if it still needs refactoring.
