### ISSUE TITLE
Support for \gt

### ISSUE THREAD

**Issue by scaljeri** [Khan/KaTeX#497]
Maybe this is a latex issue, I'm not sure. The only thing I know is that it works in MathJax. Anyway, I have the `>` sign as

    \gt

As I said, MathJax renders this as expected, but KaTeX throws an error. Any suggestions why ?

**Comment by sthoch** [comment]
`\gt`is supported by KaTeX (https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX) and it is rendering on https://khan.github.io/KaTeX/. Your error must be elsewhere, providing the error message would help pinpointing where.

**Comment by scaljeri** [comment]
Sorry, I was using versions 0.5.1, with v0.6.0 it works!
