### ISSUE TITLE
add support for /textrm

### ISSUE THREAD

**Issue by szhuge** [Khan/KaTeX#498]
Just discovered that \textrm doesn't work but \mathrm does.  We use \textrm, would be awesome to have that supported as well!

**Comment by spicyj** [comment]
We do have \text.

**Comment by deltakam** [comment]
Then, it wouldn't it be great to have \textrm as an alias to \text? Equations are usually not written just to work with KaTex.

I would vote for aliasing \mbox, too.

**Comment by spicyj** [comment]
mbox and text differ at least in their behavior when used in a subscript or superscript and you should generally prefer text in LaTeX too. I'm not sure on text vs textrm.

**Comment by spicyj** [comment]
To be clear: not saying we shouldn't support either of those, but we should make sure to do it properly.

**Comment by deltakam** [comment]
I agree that we should do it properly, but if it will take forever, it would be better to have it as an alias -- it will have different effect so it might be ugly but for most cases not too serious. I would rather have it ugly than having the whole equation not drawn properly.
