### ISSUE TITLE
Travis screenshot tests get stuck

### ISSUE THREAD

**Issue by gagern** [Khan/KaTeX#499]
There apparently is some chance that a Travis screenshot test will get stuck, until it gets killed by Travis after 10 minutes with no output.

```
Starting container for selenium/standalone-chrome:2.48.2
Container c624b8e09ffb started, creating screenshots...
(node:4721) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Selenium driver at http://172.17.42.1:32769/wd/hub
KaTeX URL is http://172.17.42.1:46648/

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

I've failed to reproduce this locally using selenium-webdriver 2.48.2 or 2.53.3. I've added some debug output to `screenshotter.js` and found that on Travis it fails after the driver has been built in `buildDriver` but before the first screenshot has been taken to tune the window size in `setSize`. So it looks as though the problem lies somewhere in essentially the following [chain of commands](https://github.com/Khan/KaTeX/blob/b49eee4de70e787e557f4bfd0b787a728dcaae81/dockers/Screenshotter/screenshotter.js#L219-L232):

``` js
driver.manage().timeouts().setScriptTimeout(3000).then(function() {
    return driver.manage().window().setSize(1024, 768);
}).then(function() {
    return driver.takeScreenshot();
}).then(function(img) {
    // process screenshot
});
```

This fails to reach its final step. I can't see anything wrong with this code, so I guess a Selenium bug of some kind might be involved as well. Nevertheless, we should try to find it or work around it, in order to avoid having to re-trigger Travis tests on a regular basis.

**Comment by kevinbarabash** [comment]
Re-triggering Travis is a bit of a pain.  Maybe there's some way that we could stop screenshot tests before they time out.

**Comment by gagern** [comment]
I'll look into that approach.

**Comment by gagern** [comment]
[My watchdog branch](https://github.com/gagern/KaTeX/commits/watchdog) has a workaround that should detect Travis getting stuck. It's built on #494, and it entails quite a number of code changes considering it's only a workaround. I've been trying to test this but so far I have been unable to reproduce the Travis problem, in a dozen runs or so. Apparently there were some screenshots taking more than one minute in one run, but not the huge delay while waiting to set the size. I wonder whether Travis somehow made the problem go away. So I'd suggest we wait a bit, see if the problem persists, and consider using that approach if it does and after #494 got merged.

**Comment by kevinbarabash** [comment]
Travis has been pretty good recently, especially considering the number of PRs we've had in the last couple of months.  I'm going to close this for now.
