### ISSUE TITLE
Update to less 2

### ISSUE THREAD

**Issue by gagern** [Khan/KaTeX#500]
Running some of the build tools (like the server) on a recent version of node will print the following message:

> fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

This is due to us using an outdated version of [less](https://www.npmjs.com/package/less). We are at 1.7.5 but latest is 2.7.1. That's a new major version, so there will be breaking changes. Luckily they are [well documented](http://lesscss.org/usage/#v2-upgrade-guide), so we should see whether any of that affects us, and then switch to using that version.

Other packages might be worth updating as well:

* browserify (10.2.6 to 13.0.1)
* clean-css (2.2.23 to 3.4.18)
* eslint (1.10.3 to 3.0.1)
* express (3.3.8 to 4.14.0)
* glob (5.0.15 to 7.0.5)
* pako (0.2.7 to 1.0.1)
* uglify-js (2.4.24 to 2.7.0)

The last one, uglify-js, is just a semver-minor upgrade, so that *should* not break anything if they do their versioning right. For the others, we'd have to identify breaking changes and see whether they affect us.

Do you want all these upgrades in one PR if possible, or would you prefer just upgrading less and leaving all the other versions alone as long as they don't cause any serious trouble?

**Comment by kevinbarabash** [comment]
Doing the upgrades as separate PRs.  I'm not particularly keen on upgrading stuff unless it's actually causing an issue.  I'd don't really understand the impact of what the error message is saying.  Does it mean if a native module is updated while the server is running that it won't reload it?  It seems like a bit of an edge case with an easy workaround: reload the server.

**Comment by gagern** [comment]
@kevinbarabash: The way I understand https://github.com/nodejs/node/pull/5102, the graceful-fs module does something that is supported in node 6 only for the sake of graceful-fs, ant that won't be supported in node 7 at all, throwing an exception instead. So for node 6 the woraround is ignoring the warning. For node 7 we'll be in trouble unless we manage to update by then. It should be fairly easy to verify that for the current KaTeX input, the new version of less produces functionally the same output as the old one, so the deliverables won't suffer. I'll check that as part of preparing a pull request for less. I wonder whether any of the other packages may have benefits to upgrading. browserify and uglify might result in smaller files or better performance, for example. Worth checking?
