### ISSUE TITLE
Support international operators

### ISSUE THREAD

**Issue by pashinin** [Khan/KaTeX#509]
Can we add these functions to KaTeX?

```
ParseError: KaTeX parse error: Expected 'EOF', got '\ctg' at position 6
```

In LaTeX when we use:

```
\usepackage[russian]{babel}
```

We have these additional functions:

```
\tg  \arcctg \th \ctg \sh \cth \arctg \ch \cosec
```

**Comment by PeterBocan** [comment]
It could be possible to redefine an alias to 

    \tan \cot \tanh

etc.

**Comment by pashinin** [comment]
Well, it should not be displayed as "tan", it should be "tg". It should not be just a pointer to the same function.

**Comment by kevinbarabash** [comment]
@pashinin is `tg` the Russian way of denoting `tan`?

**Comment by pashinin** [comment]
Yes, I think for all post Soviet countries. I didn't even know what "cot" is, but know "ctg".

**Comment by PeterBocan** [comment]
@kevinbarabash Czech and Slovak, too.

**Comment by kevinbarabash** [comment]
See https://en.wikibooks.org/wiki/LaTeX/Internationalization for details.
