### ISSUE TITLE
\varnothing should be more rounded than \emptyset

### ISSUE THREAD

**Issue by hudakharrufa** [Khan/KaTeX#512]
I get that they refer to the same thing but \varnothing should look more rounded, yet they both look exactly the same when rendered. I don't like how they currently look :( Any hope for a fix?

**Comment by spicyj** [comment]
Seems like a bug. Looks like varnothing is correctly defined to use the AMS font in our symbols file, but that isn't making its way to the actual DOM output we generate.

**Comment by kevinbarabash** [comment]
`\varnothing \emptyset` should produce the following output:
![screen shot 2016-07-29 at 2 48 50 pm](https://cloud.githubusercontent.com/assets/1044413/17264408/98cc75ce-559b-11e6-8b60-95bfbfa1abd4.png)

**Comment by kevinbarabash** [comment]
Closed by https://github.com/Khan/KaTeX/pull/618.
