### ISSUE TITLE
Warn when there isn't a DOCTYPE

### ISSUE THREAD

**Issue by jason-s** [Khan/KaTeX#517]
https://gist.github.com/jason-s/785a6a8fe10192f33b6d2eac8c1612cc

![image](https://cloud.githubusercontent.com/assets/738893/17537327/946ace32-5e50-11e6-8008-ebf619141497.png)

The `K_p` and `K_i` line should have a bunch of subscripts, instead they are "midscripts" or something weird.

Source math:

```
<div class="math">
\[(a + b)^2 = a^2 + 2ab + b^2\]</div>
<p>blah blah blah</p>
<div class="math">
\[y = K_p x_{err} + \int K_i x_{err} \ dt\]</div>
</div>
```

**Comment by jason-s** [comment]
Is there something I can override for basic.css to fix it?

**Comment by xymostech** [comment]
What does the HTML for the page that you're testing this on look like? Does it have a doctype? It sounds sorta like what happened here: https://github.com/Khan/KaTeX/issues/332 which was fixed by adding a `<!DOCTYPE html>` doctype.

**Comment by xymostech** [comment]
Never mind, I see that you have the html file you were using in the gist. Looks like maybe this is the same issue as in https://github.com/Khan/KaTeX/issues/45 or https://github.com/Khan/KaTeX/issues/183, but we never figured out the problem there. What browser are you using?

**Comment by jason-s** [comment]
This was Chrome on Windows 7 (whatever the autoupdater is at, as of today). I will try with Firefox/IE/Opera tomorrow and see how they do.

**Comment by jason-s** [comment]
OK, updated info (all on my Windows 7 PC):

- Chrome Version 51.0.2704.103 m: this is the version I use as of today, problem occurs
- Firefox 47.0: same problem
- IE 11: same problem
- Opera 12.16: same problem

If I use `<!DOCTYPE html>` the issue goes away. (so this may be a valid workaround for me.)

**Comment by spicyj** [comment]
You should use `<!DOCTYPE html>` to trigger standards mode in browsers. Even jQuery doesn't support quirks mode. We could probably warn when you don't have a doctype though.

**Comment by jason-s** [comment]
That should be added to the front page https://github.com/Khan/KaTeX

**Comment by kevinbarabash** [comment]
We were warning, but no longer warn b/c quirks mode is now supported on `master`.

**Comment by kevinbarabash** [comment]
Although https://github.com/Khan/KaTeX/pull/608 was reverted, we were already warning on missing doctype.  See https://github.com/Khan/KaTeX/blob/master/katex.js#L34-L44.
