### ISSUE TITLE
Vertical misalignment when using Katex with transitional and frameset DOCTYPES in HTML4 and XHTML1.0

### ISSUE THREAD

**Issue by joelostblom** [Khan/KaTeX#519]
I am having issues using Katex with Pandoc, which seems to be related to the DOCTYPE for the HTML4 documents. Pandoc uses the transitional XHTML 1.0 DOCTYPE by default, which causes some characters (such as fraction lines and subset notation) to be offset vertically and displayed above their correct position (as reported in #332 and #517).

I tested all the [doctypes listed at w3schools](http://www.w3schools.com/tags/tag_doctype.asp). The HTML5, strict HTML4, XHTML1.1 and strict XHTML1.0 below all work fine.

```
<!DOCTYPE html>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
```

The transitional and frameset HTML4 and XHTML 1.0 listed below cause the vertical character offset.
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">
```

I can easily circumvent these issues by using Pandoc HTML5 template with `<!DOCTYPE html>`, but I wonder if there is any recommendation on which DOCTYPES to use for different document formats to have the most robust rendering of Katex elements. Should I just stay away from transitional and frameset DOCTYPES and use any of the other 4, or are there more things to look out for? 

I also noted that when removing the initial hyphen from any of the not working DOCTYPES, they start to work. Maybe this is just because it becomes an invalid DOCTYPE spec and it falls back to strict or something along those lines?

I originally reported this here https://github.com/jgm/pandoc/issues/3077 and the full document I used for testing is the following.
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <title></title>
  <style type="text/css">code{white-space: pre;}</style>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.js"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.css" /><script type="text/javascript">window.onload = function(){var mathElements = document.getElementsByClassName("math");
  for (var i=0; i < mathElements.length; i++)
  {
   var texText = mathElements[i].firstChild
   katex.render(texText.data, mathElements[i])
  }}
  </script>
</head>
<body>
<p><span class="math inline">J(\theta_0, \theta_1) = \frac{1}{2m} \sum\limits_{i=1}^m(h_\theta(x^i) - y^i)^2</span></p>
</body>
</html>
```

**Comment by spicyj** [comment]
Yeah, we only support standards mode in browsers, which precludes using a transitional or frameset doctype, which both trigger quirks mode. Strict or the HTML5 doctype are both fine. We plan to warn for this and are tracking in #517.
