### ISSUE TITLE
I want to add my own function, how can I do that?

### ISSUE THREAD

**Issue by t-k-** [Khan/KaTeX#520]
For example, I want KaTeX to parse \qvar{x} (and result in a colored "x"), so I need to add `qvar` as a new function? How can I do that?

P.S. \qvar is a popular definition of wildcard variable in NTCIR and other research standards.

**Comment by kevinbarabash** [comment]
The ability to defined macros via the options object was added recently.  The following should work:
```
katex.render("\\qvar{x}", div, {macros: {"\\qvar": "\\color{red}"}});
```
and should produce the same output as:
```
katex.render("\\color{red}{x}", div);
```

**Comment by t-k-** [comment]
Thank you for your reply. I tried using your CDN: https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js

But not working as expected, it has a ParseError:

> ParseError: KaTeX parse error: Expected 'EOF', got '\qvar' at position 5: \qvar̲{x}

What could probably be wrong?

**Comment by t-k-** [comment]
It is my bad, after building master branch code, I get it working. Sweet!

Thank you for your help! I will close this issue.

**Comment by t-k-** [comment]
BTW. I see no documentation on KaTeX, is there any that I am not aware of?

If not, why not host a sphinx repo/site just like what MathJax does? I just learned how to setup sphinx, so tell me if you need my help.

**Comment by kevinbarabash** [comment]
@t-k- sorry, I keep forgetting what's on master vs. the latest release... probably time for new release.  As for documentation there, what we have can be found on https://github.com/Khan/KaTeX and https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX.  We should update it after the next release.  What's a sphinx repo/site?

**Comment by t-k-** [comment]
I see, so I do not find anything related to the macros option. 

What I mean a sphinx site is something built with [sphinx](http://www.sphinx-doc.org/en/stable/) documentation (like [this one](http://docs.mathjax.org/en/latest/start.html) used by MathJax), it is easy and quick to setup and is open to public editing using Github pull request.
