### ISSUE TITLE
KaTeX cuts off math on mobile

### ISSUE THREAD

**Issue by altosaar** [Khan/KaTeX#521]
How can I get KaTeX to allow horizontal scrolling? 

I'm using jekyll katex, and it cuts off equations:

http://mobiletest.me/iphone_5_emulator/?u=https://jaan.io/unreasonable-confusion/

![image](https://cloud.githubusercontent.com/assets/5317244/18014823/97265d2c-6b79-11e6-815d-7450374dedbe.png)

**Comment by xymostech** [comment]
Hmm, interesting! Our math doesn't have a good way to wrap right now, so the best solution I can think of is to add some CSS which allows for scrolling:

```
.katex-display {
    overflow-x: auto;
}
```

**Comment by kevinbarabash** [comment]
Another option is to scale it down to fit the space.  Since we don't know which behavior a developer wants for their site it's safest for us to not make any decision in this regard.
