### ISSUE TITLE
XSS possibility?

### ISSUE THREAD

**Issue by kevinburke** [Khan/KaTeX#523]
Hi,
Is it possible that the result of `Katex.renderToString(value)` could contain valid HTML submitted as part of `value` ? E.g. if I tried entering 

```
'">><marquee><img src=x onerror=confirm(1)></marquee>"></plaintext\></|\><plaintext/onmouseover=prompt(1)>
<script>prompt(1)</script>@gmail.com<isindex formaction=javascript:alert(/XSS/) type=submit>'-->"></script>
<script>alert(document.cookie)</script>">
<img/id="confirm&lpar;1)"/alt="/"src="/"onerror=eval(id)>'">
<img src="http://www.shellypalmer.com/wp-content/images/2015/07/hacked-compressor.jpg"> 
```

or some similar XSS vector. I've tried using 

```
\begin{verbatim}<IMG SRC="javascript:alert('XSS');">\end{verbatim}
```

for example, but I get an error that the environment `verbatim` is unknown. I'm not super familiar with the boundaries of LaTeX, but I didn't read anything about whether the result of `renderToString()` is safe, or should be safe.

My use case is, one user might enter LaTeX, we save the output of `renderToString()` and show it in another user's browser. I am hoping that that's a safe operation.

**Comment by spicyj** [comment]
It should be safe. It is possible for users to break the layout of your site and slow it down with malicious inputs – see #109, #158 – but definitely no XSS unless we have a severe bug.

**Comment by kevinburke** [comment]
Thanks!

**Comment by kevinburke** [comment]
Sorry one more question - will the error message ever reflect the input?

**Comment by kevinbarabash** [comment]
There are only a few environments that we currently support like `aligned`, `*matrix`, and `cases`.  `verbatim` is not one of them.
