### ISSUE TITLE
Missing commands

### ISSUE THREAD

**Issue by nefedor** [Khan/KaTeX#525]
Following commands are not currently working:
\widetilde{aaa} \widehat{bbb} \overleftarrow{ccc} \overrightarrow{ddd} \overbrace{eee} \underbrace{fff} \overset{a}{ggg} \underset{a}{hhh} \widehat{iii}
It would be nice to have them. 

UPD. As well as:
\aa \AA \AE \ae \l \L \O \o \oe\OE \SS \ss \pounds \cent \euro \S \P \copyright \not\equiv \xrightarrow[a]{b} \xleftarrow[a]{b} 
And equation systems:
\begin{align*}
a &= 1\\ 
b + 1 &= 2
\end{align*}

**Comment by kevinbarabash** [comment]
@nefedor many of these have already been reported previously.  Please search for existing issues.
Instead of `\begin{align*}` you can use `\begin{aligned}`.

**Comment by kevinbarabash** [comment]
@nefedor I'm going to close this.  Please a new issue for specific commands (or groups of related commands) that aren't currently supported and don't have an existing issue.
