### ISSUE TITLE
Support `\dots`

### ISSUE THREAD

**Issue by xymostech** [Khan/KaTeX#528]
Initially reported in https://github.com/Khan/KaTeX/issues/526

In plain LaTeX, This is the same thing as `\ldots`, but with AMSMath, `\dots` does something more complex, and tries to figure out if it should become an `\ldots` or a `\cdots` by looking at the elements around it: http://tex.stackexchange.com/a/77742

**Comment by edemaine** [comment]
I've implemented AMSMath's behavior in #599, aside from one spacing issue I could use help with (described there) -- is there an easy way to add some positive or negative horizontal space next to a symbol returned by a function?

**Comment by kevinbarabash** [comment]
Dots support has been added in #794.
