### ISSUE TITLE
Arrow on vector doesn't display

### ISSUE THREAD

**Issue by jbg77** [Khan/KaTeX#529]
How can I fix it, I using the 6.0.

Thank in advance!

**Comment by kevinbarabash** [comment]
@jbg77 can you post the TeX code you're seeing the issue with?

**Comment by jbg77** [comment]
It's `\vec{f}`

I'm using phantomJs, with the doctype: [https://github.com/Khan/KaTeX/issues/514](#514)

**Comment by kevinbarabash** [comment]
Can you add some debugging to your phantomjs script to printout which resources it's downloading.  See http://phantomjs.org/troubleshooting.html.

**Comment by edemaine** [comment]
Should be fixed by #670. Please reopen if you're still having trouble.
