### ISSUE TITLE
Support '\buildrel'

### ISSUE THREAD

**Issue by daniloascione** [Khan/KaTeX#530]
Please add support for plain Tex \buildrel macro.
Ex: R^t\buildrel\gamma\over\longrightarrow p

**Comment by kevinbarabash** [comment]
@daniloascione we're keen to support `\stackrel` because we have a fair amount of content that uses that.  It seems like `\stackrel{\gamma}{\longrightarrow} should do the same thing once `\stackrel` is implemented.

**Comment by kevinbarabash** [comment]
I'm going to close this as support for `\stackrel` has been added to `master`.
