### ISSUE TITLE
Crammed layout when using \hat

### ISSUE THREAD

**Issue by wster** [Khan/KaTeX#535]
Hey guys – thanks for an awesome library!

I think I just noticed a bug when using `\hat{x}`. The hat symbol overlays whatever's inside the brackets. Here's a screenshot:

<img width="33" alt="screen shot 2016-09-18 at 00 29 32" src="https://cloud.githubusercontent.com/assets/747600/18611374/1b14af98-7d37-11e6-8331-90f85729cd4f.png">

The issue is the same in all major browsers, and I have verified that there is no CSS on my part that is screwing up the layout.

**Comment by kevinbarabash** [comment]
`\hat{x}\hat{\omega}` looks fine https://khan.github.io/KaTeX/.

<img width="60" alt="screen shot 2016-09-17 at 3 44 36 pm" src="https://cloud.githubusercontent.com/assets/1044413/18611426/be801536-7ced-11e6-8a19-73e55f9e6dc2.png">

 It looks like your rendering is using a different font.

**Comment by wster** [comment]
You're right! I had relocated the fonts folder, which resulted in the issue.

Sorry for the false alarm.
