### ISSUE TITLE
same equation, different font size issue

### ISSUE THREAD

**Issue by tylerlong** [Khan/KaTeX#536]
I am not sure if it's a bug, it's pretty weird.

The following two equations are equivalent:

```
\dfrac{ \tfrac{1}{2}[1-(\tfrac{1}{2})^n] }{ 1-\tfrac{1}{2} } = s_n

\frac{{\frac{{1}}{{2}}{\left[{1}-{\left(\frac{{1}}{{2}}\right)}^{{n}}\right]}}}{{{1}-{\left(\frac{{1}}{{2}}\right)}}}={s}_{{n}}
```

But they are rendered in different size:

![image](https://cloud.githubusercontent.com/assets/733544/18613704/851878a4-7db2-11e6-871d-f402a02d4312.png)

### How to reproduce it **quickly**

Open http://mdp.tylingsoft.com/ and copy paste the following:

```
`$\dfrac{ \tfrac{1}{2}[1-(\tfrac{1}{2})^n] }{ 1-\tfrac{1}{2} } = s_n$`

`$\frac{{\frac{{1}}{{2}}{\left[{1}-{\left(\frac{{1}}{{2}}\right)}^{{n}}\right]}}}{{{1}-{\left(\frac{{1}}{{2}}\right)}}}={s}_{{n}}$`
```

**Comment by xymostech** [comment]
They are definitely not equivalent, one uses `\dfrac` and the other uses `\frac`. In `\dfrac` (essentially short for `\displaystyle\frac`) the top and bottom of the fraction are rendered in textstyle (the normal font size). In plain `\frac`, the top and bottom of the fraction are rendered in scriptstyle, which is smaller than textstyle. So, this isn't a bug in KaTeX, it's just how TeX works!

You can search the internet for "difference between \\frac and \dfrac" and get more detailed answers.
