### ISSUE TITLE
use katex with my own (non-dom/html) rendering target

### ISSUE THREAD

**Issue by sidorares** [Khan/KaTeX#537]
Hi,
I'd like to use katex just as layout engine only: input is tex source + font name/metrics hooks, output is list of positioned glyph boxes. Is it easy to achieve currently?

**Comment by gagern** [comment]
My render-to-canvas experiments from #251 work in this way. There are some plans in #376 to offer a box-based representation at a more general level. Also notice that KaTeX only uses its own fonts, so naming fonts as part of the input appears pointless.

**Comment by sidorares** [comment]
thanks @gagern , this is very helpful! Yes, basically my question is a duplicate of #376
