### ISSUE TITLE
Invalid input type gives cryptic error

### ISSUE THREAD

**Issue by shuttle1987** [Khan/KaTeX#539]
Recently I ran into a situation where the wrong type was passed to `renderToString`:

`katex.renderToString({bogusInputType: "yes"})`

Somewhat as expected this gives a `TypeError`, but it is due to something unrelated:

`TypeError: input.slice is not a function`

Tracking this down I found that this comes from within `ParseError`,  but I'm concerned that it getting this deep without being handled earlier. The error handling here is purely coincidental and will be sidestepped entirely if the input is sliceable such as:

`var result = katex.renderToString(["OK input", {bogusInputType: "yes"}], {throwOnError: false})`

Using the settings flag to not throw on ParseError still raises the same exception from within ParseError. After looking carefully through the docs/code I came to understand that "throwOnError" is only for LaTeX parsing errors, not more general error handling, so this is to be expected. However it is a bit confusing at first when using KaTeX and adding some example code that clearly shows this would help new users.

Here's this in action: https://runkit.com/shuttle1987/57e13d446eefb414003d303d

I'm more than happy to make a PR to improve this. I propose that non-string input throws immediately and with a message that makes it really clear why the input is invalid.

**Comment by gagern** [comment]
I'd welcome a PR to this effect.

**Comment by gagern** [comment]
Fixed per #540.
