### ISSUE TITLE
Got wrong space of LaTeX "\!=\!=\!="?

### ISSUE THREAD

**Issue by bzsy** [Khan/KaTeX#541]
hi all,

I have tried to render **`2Na_2O_2+2H_2O\ \!=\!=\!=\ 4NaOH+O_2\uparrow`** by KaTeX and MathJax.
It looks like KaTeX ignored the`\!` before `=`.
Hope anyone can help, thanks a lot :)

**KaTeX:**
![image](https://cloud.githubusercontent.com/assets/3096023/18949291/4e99e826-866d-11e6-84bf-00edba35e869.png)

**MathJax:**
![image](https://cloud.githubusercontent.com/assets/3096023/18949311/5ea1126c-866d-11e6-981c-a209127d1214.png)

**Comment by sthoch** [comment]
Interesting: `==` results in less spacing between the equal signs than `=\!=` ...

As a workaround you can use `{=}\!{=}\!{=}`.

**Comment by gagern** [comment]
I can think of two possible reasons.

1. A binary operation which is not surrounded by stuff compatible with a binary operation gets demoted to an ordinary symbol. According to #4 we don't do that yet, although #492 contains a pull request for this which needs review.

2. I'm not sure how spacing constructs factor into this Ord/Bin/… classification. It might well be that they are ignored for the sake of adjacency computation. (Someone should read this up in the TeX book but I don't have time just now.) If so, I guess our CSS doesn't reflect this fact.

**Comment by bzsy** [comment]
Thank you guys. `{=}\!{=}\!{=}` works well.

**Comment by kevinbarabash** [comment]
Fixed on `master`.
