### ISSUE TITLE
Is there a possibility to use bare parser?

### ISSUE THREAD

**Issue by nickkolok** [Khan/KaTeX#554]
I need a bare Latex parser, i. e. I don't need rendering, macro expanding, etc. I need a function which gets a string and returns tree-like object, something like HTML node tree.

Could such function be found in KaTeX?

**Comment by xymostech** [comment]
Hello @nickkolok! KaTeX doesn't offer a great way to do this right now, but there is a somewhat-undocumented `KaTeX.__parse` that might do what you want: https://github.com/Khan/KaTeX/blob/master/katex.js#L72 Note that the output of this isn't stable and might change from version to version.

We're also thinking about separating out the renderer and parser a little bit via #376 that you might be interested in. We don't have anything for you to use right now, though.

**Comment by kevinbarabash** [comment]
@nickkolok not sure how you're packaging things, but if your build system supports tree shaking then doing `import { __parse } from "katex"` might be sufficient for you.  Extracting macro expanding from the parser would be quite difficult.
