### ISSUE TITLE
How to catch error with renderToString ?

### ISSUE THREAD

**Issue by hojas** [Khan/KaTeX#556]
How to catch error with renderToString ?

**Comment by gagern** [comment]
The same way you catch other exceptions in JavaScript: using a [`try … catch …` construct](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch). If this doesn't answer your question, then please try rephrasing it to provide more context about what you are trying to achieve and how this approach fails for you.

**Comment by hojas** [comment]
@gagern thanks.
