### ISSUE TITLE
Latin-1 support.

### ISSUE THREAD

**Issue by Karl-D-Asmussen** [Khan/KaTeX#558]
Currently, `katex.render()` will balk at parsing strings containing extended latin letters; like `æøå`. This is a problem in case one wishes to typeset mathematics which is not in English.

**Comment by gagern** [comment]
#409 has some work to this effect, at least inside `\text`. Outside it's a bit hard since KaTeX uses its own fonts with known metrics, and those fonts currently don't contain the symbols you request.

**Comment by kevinbarabash** [comment]
I'll try to push https://github.com/Khan/KaTeX/pull/409 across the finish line this weekend.

**Comment by kevinbarabash** [comment]
My hope was to eventually follow that up with a diff to add accents over the characters with the goal of supporting most of the characters in the [latin-1](http://unicode.org/charts/PDF/U0080.pdf) unicode block.

**Comment by kevinbarabash** [comment]
Maybe #409 isn't necessary anymore now that https://github.com/Khan/KaTeX/pull/508 has been merged.  @Karl-D-Asmussen you might want to give `master` a try.

**Comment by appeye** [comment]
Ah great work! I've missed this. Looking forward to the next release!

**Comment by edemaine** [comment]
I believe this issue is now fixed / can be closed.

**Comment by kevinbarabash** [comment]
I've renamed this issue so people don't think we support all languages yet.
