### ISSUE TITLE
Parse error on --

### ISSUE THREAD

**Issue by cbreeden** [Khan/KaTeX#561]
I haven't tried a git clone or anything, but <https://khan.github.io/KaTeX/> gives me a parse when I input `--`.

Input: `x--1`.  
Expected result: equivalent to `\displaystyle\mathord{x}\mathop{-}\mathord{-}\mathord{1}`.
Actual Result: `Uncaught Error: KaTeX parse error: Expected '}', got '--' at position 17: isplaystyle{x--̲1}`

**Comment by xymostech** [comment]
Duplicate of #433 I think?

**Comment by cbreeden** [comment]
I think so, sorry! Github doesn't play well while searching for "--" :)

**Comment by xymostech** [comment]
:) No problem. Thanks for reporting!
