### ISSUE TITLE
When will next release ready?

### ISSUE THREAD

**Issue by dyzpku** [Khan/KaTeX#562]
Hi there, is there any time table for next release including recent modifications like CJK support? Thanks a lot.

**Comment by edemaine** [comment]
0.7.0 published yesterday! (thanks to @xymostech)

**Comment by bigtan** [comment]
@edemaine but there are only source code but no compiled code, why ?

**Comment by edemaine** [comment]
The NPM module has minified code in `dist` as usual.  Do you mean the lack of CDN update?  I'm not sure why that is -- perhaps takes a while?

**Comment by bigtan** [comment]
@edemaine There is a katex.tar.gz/katex.zip in release v0.6.0 and detailed release note, I mean why there is no such thing for the latest release v0.7.0 ?

**Comment by edemaine** [comment]
@xymostech See above questions.

**Comment by xymostech** [comment]
@bigtan it took us a bit to write the release notes, sorry. It should be released now!

**Comment by edemaine** [comment]
@xymostech I still don't see 0.7.0 on CDN.  Is that supposed to be instant, or do we just need to wait a while?

**Comment by xymostech** [comment]
@edemaine cdnjs is supposed to update it automatically, I think we just wait. :(
