### ISSUE TITLE
Add support for \atop

### ISSUE THREAD

**Issue by NexiePrado** [Khan/KaTeX#563]
I just trying to render formule like
```
$\\mathrm{\\normalsize{~+2~~~~+3~~~+4~-2~~~~}\\atop\\Large{Mg_xAl_2(SiO_4)_3}}$
```
But it rendered nothing. How I can render nested text expressions?

**Comment by kevinbarabash** [comment]
We don't support `\atop` yet.

**Comment by kevinbarabash** [comment]
Support has been added to `master`.
