### ISSUE TITLE
How to support \everymath?

### ISSUE THREAD

**Issue by rdnz** [Khan/KaTeX#575]
Comparing with MathJax, KaTex formula by default does not show the multiple lines style. It tries to show each formula in a single line, thus causing some symbols very small to read.

The hard solution is to add \displaystyle at the beginning of each formula.

This is too tedious to work. In LaTeX there is a line:

\everymath{\displaystyle}

But it seems that KaTeX does not support this? Anything I might missed? Thanks...

**Comment by kevinbarabash** [comment]
Closing in preference of https://github.com/Khan/KaTeX/issues/450.  `\everymath` doesn't make sense if you want it to affect other math strings rendered by `KaTeX`.
