### ISSUE TITLE
Add support for \i and \j

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#576]
These are non-italic versions of `\imath` and `\jmath` that are used in vector notation.

**Comment by kevinbarabash** [comment]
KaTeX_Main-Bold unfortunately contains the wrong glyphs for `\i` and `\j`.  This is because `makeFF` in `https://github.com/Khan/MathJax-dev` maps two different glyphs to the same code point.  Here are the conflicting lines:
- https://github.com/Khan/MathJax-dev/blob/master/fonts/OTF/TeX/makeFF#L667-L668
- https://github.com/Khan/MathJax-dev/blob/master/fonts/OTF/TeX/makeFF#L789-L790 (should be removed)

**Comment by kevinbarabash** [comment]
I think this should be pretty easy to fix.  We'll want to fix it in https://github.com/KaTeX/katex-fonts though.

**Comment by edemaine** [comment]
@kevinbarabash's PR #1029 already did this, as part of the Unicode accent revamp. I just double-checked that it works on master (but not on the demo site, which I guess is using an older version). Forgot there was an old issue about it!
