### ISSUE TITLE
move gh-pages to docs/ folder

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#577]
https://github.com/blog/2228-simpler-github-pages-publishing

**Comment by kevinbarabash** [comment]
@gagern I remember you had some concerns about moving the .gif that's in the gh-pages branch into the main branch, is that correct?  I was thinking of moving that file to S3 so that it doesn't have to live in the main repo.

**Comment by gagern** [comment]
Yes, @kevinbarabash, I had some minor concern wrt. repo size. Not a problem for a few GIFs now. Things will become problematic if at some point we decide that we want a gallery of one hunderd high resolution renderings comparing engines, or something of this kind. That would force developers to download stuff they never use. But even that would be preferable to having images deployed using yet another technology. So if you are positive about moving docs, I'd say leave the images in. That way we can at least collaborate on docs the same way we do for sources, without having to learn additional tools and granting additional permissions.

**Comment by kevinbarabash** [comment]
We could ask people to make pull requests against the `gh-pages` branch.  Another option is to create a separate repo for the web page... this doesn't seem to offer much benefit from using `gh-pages` b/c it would require a separate checkout.  I think for let's continue to use `gh-pages` consider the number of changes to have been negligible and I don't foresee many pull requests to that branch.
