### ISSUE TITLE
\mathit uses the wrong font

### ISSUE THREAD

**Issue by kohler** [Khan/KaTeX#584]
Consider: 

```tex
$helfo x \; \mathit{helfo x}$
```

Here’s what `\showlists` says. Note that `\mathit` uses a different font (`\fam4`).

```
\mathord
.\fam1 h
\mathord
.\fam1 e
\mathord
.\fam1 l
\mathord
.\fam1 f
\mathord
.\fam1 o
\mathord
.\fam1 x
\glue(\mskip) 5.0mu plus 5.0mu
\mathord
.\mathord
..\fam4 h
.\mathord
..\fam4 e
.\mathord
..\fam4 l
.\mathord
..\fam4 f
.\mathord
..\fam4 o
.\mathord
..\fam4 x
```

Here’s the texcmp diff (red = katex).

![image](https://cloud.githubusercontent.com/assets/410647/21053714/a83ad486-bdf8-11e6-8efe-ad1d97893b44.png)

This highlights the spacing diffs but `\mathit` has different glyphs too—the narrower glyphs of the text italic font.

SOLUTION: Basically I think `\mathit` should use `font-family: KaTeX_Main`, rather than `font-family: KaTeX_Math`. Also, `\mathit` should not apply italic corrections—none of the `\math…` font commands should. But I'm not clear on any finer differences between KaTeX_Main and KaTeX_Math fonts.

**Comment by kevinbarabash** [comment]
Right now we apply a `.mathit` class to math atoms as well as atoms within `\mathit`.  We'll need to create a new class to differentiate the two.
