### ISSUE TITLE
Add support for \bm

### ISSUE THREAD

**Issue by dyzpku** [Khan/KaTeX#585]
Hi there, recently we also find that there isn't a function can make the text both bold and italic in KaTeX. All the functions that make text bold will also make text no longer italic.  The target effect is as bellow. 
![image](https://cloud.githubusercontent.com/assets/11351293/21131188/3bad129a-c148-11e6-9b09-b709cfc5ea93.png)
Do you have any plan to support italic bold text or any suggestion? Thank you!

**Comment by kevinbarabash** [comment]
It should be noted that `\boldmath` also makes the operators bold.

**Comment by dyzpku** [comment]
Thanks for reply! The `\boldmath` function is also not yet supported in release v0.6.0 right? Does it mean that you will support `\boldmath` in later version? Thank you!

**Comment by kevinbarabash** [comment]
I'm sure we will at some point.

**Comment by sunsheeppoplar** [comment]
Would love to help contribute. Been looking around the code for a bit and was wondering where I could start for this problem. Thanks!

**Comment by gagern** [comment]
@sunsheeppoplar: Thanks for that offer! ❤️

I'd start by looking at [`\mathrm` and `\mathbf`](https://github.com/Khan/KaTeX/blob/f742fbf9f2ad75b0b2428cc84744b9b24e6abfe6/src/functions.js#L571-L595), see how they are implemented. Feel free to ask if you get stuck following the flow of these commands through the engine.

**Comment by jeanm** [comment]
As far as I know, `\boldmath` is a declaration, so it will make the whole formula bold until you `\unboldmath`. You must also [include the math mode expressions within the scope of the declaration](http://texblog.net/help/latex/boldmath.html), which makes it quite impractical.

In my field we would normally use `\boldsymbol` from the `amsmath` package, although it seems that this has now been superseded by [`\bm`](http://www.ctan.org/pkg/bm).

**Comment by edemaine** [comment]
@jeanm I just tested, and you're correct: `Command \boldmath invalid in math mode`.  (Though maybe not terrible to add support for it within math mode...)  AMSMath's `\boldsymbol` and/or `\bm` seem like reasonable goals too.

**Comment by kevinbarabash** [comment]
It looks like `\bm` can accept an atom or a group.  I'm going to switch this issue to support `\bm` because it'll be less work and will still produce the desired output.

**Comment by edemaine** [comment]
Apparently there is also fixmath's `\mathbold`. [Here's a visual comparison.](http://tex.stackexchange.com/questions/595/how-can-i-get-bold-math-symbols)  `\bm` is probably the right decision, given that AMS recommends it.

**Comment by sunsheeppoplar** [comment]
Sorry, y'all, got a bit caught up with transitioning at work. Is this still something y'all are looking at or has a PR been proposed elsewhere that encompasses this?

**Comment by tscholak** [comment]
This is still very much needed.

**Comment by stapeleliz** [comment]
I'm using Katex on my math-lessons website. Questions and answers are bolded and, naturally, these questions and answers commonly contain variables. It would be _really_ nice to be able to format bolded AND italicized letters. Is anybody working on this issue currently? Thank you!

**Comment by kevinbarabash** [comment]
@stapeleliz no one is currently working on this to my knowledge.  I'd like to do #816 first.  Since it's blocking this and a couple of other issues I'll take on that issue.

**Comment by stapeleliz** [comment]
Okay; thank you!

**Comment by aterenin** [comment]
Just wanted to comment that this feature is very badly wanted.

A note that both \boldsymbol and \mathbf are important - the former produces bold italic symbols, including bold greek letters, that often refer to vectors, whereas the latter produces bold non-italic symbols that often refer to matrices.
