### ISSUE TITLE
Support for `\verb`

### ISSUE THREAD

**Issue by allisonshaw** [Khan/KaTeX#588]
Are there plans to support `\verb` in the near future? If not, is there an alternative to manually escaping every character KaTeX treats as special? 
There are times where putting some verbatim material without all the escaping is certainly useful.

**Comment by kevinbarabash** [comment]
No plans to implement this per se, but a PR would welcome.  It seems a little tricky because it treats characters differently from the default.

**Comment by gagern** [comment]
I think I'd implement `\verb` at the lexer level. As we don't have catcodes and all that, doing it any other way would be *very* tricky. On the other hand, it would be fairly easy to match `/\\verb(.)(.*?)\1/` or similar (perhaps `/\\verb\s*(\S)(.*?)\1/` if TeX allows whitespace between the command and the delimiter), and return that as a special kind of token, to receive appropriate processing down the line.

**Comment by edemaine** [comment]
Implemented in #614, following @gagern's suggestion.

**Comment by edemaine** [comment]
#614 was merged.

**Comment by kevinbarabash** [comment]
@edemaine thanks for closing.
