### ISSUE TITLE
"display" equation + auto-render = Inline equation

### ISSUE THREAD

**Issue by vihanb** [Khan/KaTeX#589]
So here's a screenshot of the page before I run `renderMathInElement(document.body);`:

<img width="399" alt="screen shot 2016-12-23 at 8 21 10 pm" src="https://cloud.githubusercontent.com/assets/15314511/21465183/5cf43eb2-c94d-11e6-96fb-81bcead566c9.png">

And now after I run the command:

<img width="427" alt="screen shot 2016-12-23 at 8 21 45 pm" src="https://cloud.githubusercontent.com/assets/15314511/21465184/732f064e-c94d-11e6-8db6-17233c102664.png">

It may not be apparent from the screenshot but it is being rendered the exact same as an inline equation despite the default for `\[ ... \]` `display: true`

Happens even when I pass:

```javascript
{
 delimiters: [
   {left: "$$", right: "$$", display: true},
   {left: "\\[", right: "\\]", display: false},
   {left: "\\(", right: "\\)", display: false}
  ]
}
```

for the second argument

**Comment by xymostech** [comment]
@vihanb When you say "rendered the exact same as an inline equation" do you mean "centered"? Here's a jsbin with some inline math and then some display math: http://jsbin.com/sikehuxofu/1/edit?html,output

![image](https://cloud.githubusercontent.com/assets/217900/21621587/8b5f8cd4-d1ae-11e6-86bc-7cd285877191.png)

The display math is centered and on a new line, but it's also in display style, so the `\sum` is larger. It's also wrapped in a `div.katex-display` element, which is what turns it into a display element:

![image](https://cloud.githubusercontent.com/assets/217900/21621632/bf1a2ba6-d1ae-11e6-816b-c23de96b098f.png)

So, I'm pretty sure that it's being correctly rendered as inline math, but you must have CSS on your site which is centering it.

**Comment by gagern** [comment]
If I understand this correctly, the problem is that the `katex-display` wrapper is absent here.

> Happens even when I pass: …

No surprise there: you explicitely set `display: false` for the `\[…\]` syntax. With default settings the behavior is more surprising. I can't reproduce that aspect.

**Comment by ylemkimon** [comment]
If this is still an issue, please reopen it. Thank you!
