### ISSUE TITLE
NPM distribution: include .less source?

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#595]
I am trying to use KaTeX in [Meteor](https://www.meteor.com/), which supports importing NPM packages and referring to parts of it.  As it stands, I can `require 'katex'` and get access to the API, and I can `import 'katex/dist/katex.min.css';` to get the minified CSS in my package.

This works fine if my fonts directory is `fonts`.  I'd like to be able import what is essentially `static/katex.less` but be able to specify my own value of `@font-folder`.  This would require a slightly modified version of the `.less` source code to be included in the NPM distribution.  (Currently, none of it is.)  Would this be possible?

**Comment by edemaine** [comment]
Ah, I realize that this would also require including the `static/fonts` directory in the NPM distribution, or a different NPM distribution like `katex-fonts` if you think it's too big to include by default.

**Comment by kevinbarabash** [comment]
@edemaine is this still an issue?

**Comment by edemaine** [comment]
It's not an issue for me anymore, as I found a workaround (I copy the CSS while doing a regex operation to change references to the font directory).  I think it could be nice to include `static/*.less` in `files` in `package.json`.  (One could argue that `*.less` should even be in the `src` directory...)  But not a big deal either way.

**Comment by kevinbarabash** [comment]
We could easily move katex.less into `src` now.

**Comment by kevinbarabash** [comment]
I'm going to close this now that katex.less has been moved into src and fonts.less is in KaTeX/katex-fonts.
