### ISSUE TITLE
\Box symbol gives warning

### ISSUE THREAD

**Issue by Joe312341** [Khan/KaTeX#600]
When trying to use \Box I get the following warning in Chrome:

`No character metrics for '□' in style 'Main-Regular'`

It does display correctly though.

**Comment by edemaine** [comment]
I'm new here, so I don't know the exact problem, but I observe that character 9633 (□) is defined in style AMS-Regular but not in style Main-Regular in `src/fontMetricsData.js`.  Confused why this isn't automatic via `metrics/extract_ttfs.py`.  (Also, can you set a style somehow?)

**Comment by edemaine** [comment]
I'd really like some clarification on this... When testing locally with `make serve`, both `\cdots` and `\ldots` complain with a similar error (but different style):

```
No character metrics for '⋯' in style 'Size1-Regular'
```

As a result, they do not display correctly (their baseline is elevated) on Chrome.

**Comment by Joe312341** [comment]
I am also getting this error in Firefox and Safari

**Comment by kevinbarabash** [comment]
@edemaine it sounds like that's the bug.  That should be pretty easy to fix.

**Comment by edemaine** [comment]
Finally tracked this down.  See #609.

**Comment by kevinbarabash** [comment]
Closed by https://github.com/Khan/KaTeX/pull/618.
