### ISSUE TITLE
Different lines in {cases} environment collide

### ISSUE THREAD

**Issue by oddhack** [Khan/KaTeX#603]
There's an apparent rendering bug in this code:

\\[ \begin{aligned}
d =
  \begin{cases}
    level_{base},     & \lambda \leq \frac{1}{2} \\
    nearest(\lambda), & \lambda > \frac{1}{2},
                        level_{base} + \lambda \leq
                        q + \frac{1}{2} \\
    q,                & \lambda > \frac{1}{2}, level_{base} + \lambda > q + \frac{1}{2}
  \end{cases}
\end{aligned} \\]

where the 1/2 fractions bump into the content of the cases above and below them. This doesn't happen when rendered by LaTeX. I did poke through the other issues first and it's not obvious this is a duplicate, though it may be. Seeing this in both Firefox and Chromium.

![eq41](https://cloud.githubusercontent.com/assets/4693344/21717158/078ef652-d3c4-11e6-99ee-f8329425ea6f.gif)

**Comment by gagern** [comment]
The real error here appears to be that LaTeX does switch to inline mode for `{cases}`, while KaTeX renders the lines in display mode. Thus the fractions are too large to fit without colliding. If you change the `\frac` to `\dfrac` and render this in LaTeX, the result looks pretty much the same:

![LaTeX rendering](https://cloud.githubusercontent.com/assets/190759/21721515/0164605e-d429-11e6-8fb5-ea239ae99f37.png)

If you want to use display mode (or have constructs in there which require more vertical space even in inline mode), then adding space via an optional argument to the `\\` command is the way to go, just as in LaTeX.

**Comment by edemaine** [comment]
TIL `\dfrac`.  Also, `mathtools.sty` defines `dcases` that behaves like the current KaTeX `cases`, and `nccmath.sty` defines `darray` that behaves like the current KaTeX `array`.

In addition to fixing `{cases}` to switch to text mode, we need to fix `{array}` similarly.

**Comment by edemaine** [comment]
Fix in #606.

**Comment by oddhack** [comment]
Closing this as there's a fix from #606 in the pipeline; in the meantime I did as @gagern suggested and used `\\\\[0.5em]` as a workaround. Thanks!
