### ISSUE TITLE
Sqrt is rendered broken for some symbols

### ISSUE THREAD

**Issue by spontaliku-softaria** [Khan/KaTeX#609]
Enter `\sqrt \Box` on demo page, square root is being rendered without horizontal line and inner element.
Looks like this happens with any symbol which generates "No character metrics for..." warning - it has no metrics and heuristic in sqtr builder makes empty span.

**Comment by edemaine** [comment]
This should be the same issue as #600.

**Comment by kevinbarabash** [comment]
Closed by https://github.com/Khan/KaTeX/pull/618.
