### ISSUE TITLE
text mode bugs in 0.7.0

### ISSUE THREAD

**Issue by stevem6** [Khan/KaTeX#610]
Many thanks for the 0.7.0 release.
 
A couple of bugs for the new\text commands:
\textbf gives italics ie the same as \textit 
\textsc gives an error:  `Expected 'EOF', got '\textsc' at position 1: \̲t̲e̲x̲t̲s̲c̲{text} `

**Comment by kevinbarabash** [comment]
We don't support `\textsc` yet, I've updated the release notes to remove that.  `\textbf` not being bold is definitely a bug.

**Comment by kohler** [comment]
I see `\textbf` giving boldface as expected. Can you give a full string that produces the wrong result?

**Comment by stevem6** [comment]
You are right it's my mistake! I had this Javascript line 
`txt = txt.replace(/\\textbf\{([\s\S]+?)\}/g, '<strong>$1</strong>');`
 in a page that was originally written using KaTeX version 0.6.0. Removing that line does indeed render `\textbf` as boldface with 0.7.0.

Is the live preview at https://khan.github.io/KaTeX/ still using 0.6.0 as it would be a useful place to double-check problems like this?

Thanks

**Comment by stevem6** [comment]
Given that `\textbf` does work correctly and that the live preview now supports 0.7.0 this can be closed.
