### ISSUE TITLE
katex parse error

### ISSUE THREAD

**Issue by df19900725** [Khan/KaTeX#616]
I use editor.md in my website, when I type in the text:
`$$\{x_{i}|i=1,2,...,N\}$$`

katex give me an error:

`KaTeX parse error: Expected '}', got '…' at position 14: {x_{i}|i=1,2,…̲,N}`

While in the website of katex, https://khan.github.io/KaTeX/ it goes to right. Why?

**Comment by gagern** [comment]
Looks like something is replacing `...` (three separate dots) to `…` (the Unicode symbol for horizontal ellipse). Best you write your formula as `$$\{x_{i}|i=1,2,\ldots,N\}$$`, which is better style anyway and has the benefit of avoiding this issue, too.

**Comment by kevinbarabash** [comment]
@df19900725 please reopen if the suggested change doesn't address your issue.
