### ISSUE TITLE
Add kerning to \vdots

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#620]
TL;DR: we need `\kern 6.0` on top of our `\vdots`.

Running `pdflatex` on the following code:
```
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\tracingonline=1
\showboxbreadth=\maxdimen
\showboxdepth=\maxdimen
$\vdots \showlists$
\end{document}
```
produced the following output
```
\mathord
.\vbox(15.05554+0.0)x2.77779
..\kern 6.0
..\hbox(1.05554+0.0)x2.77779
...\OT1/cmr/m/n/10 .
..\glue(\baselineskip) 2.94446
..\hbox(1.05554+0.0)x2.77779
...\OT1/cmr/m/n/10 .
..\glue(\baselineskip) 2.94446
..\hbox(1.05554+0.0)x2.77779
...\OT1/cmr/m/n/10 .
```

**Comment by kevinbarabash** [comment]
The difference can be see in https://github.com/Khan/KaTeX/pull/606#issuecomment-271159484.

**Comment by gagern** [comment]
The macro appears to be defined as

```tex
\vbox {\baselineskip 4\p@ \lineskiplimit \z@ \kern 6\p@ \hbox {.}\hbox {.}\hbox {.}}
```
I'm somewhat surprised that we have a single unicode symbol for this, while TeX combines three plain dots here. An alternative to building a vbox with kerning would be adjusting the height of the glyph in the font, right?

**Comment by kevinbarabash** [comment]
Adjusting the height sounds like a good solution.

**Comment by gagern** [comment]
Can we even change the height of a single glyph of the font, without changing the line height of the font in total? In that case, the nested vbox would be better again.

**Comment by kevinbarabash** [comment]
@gagern that's a good point.  A vbox is the way to go.
