### ISSUE TITLE
\vec problem in Chrome

### ISSUE THREAD

**Issue by ronkok** [Khan/KaTeX#629]
The accent `\vec` will not appear in Chrome on a page whose CSS includes: `body {text-rendering: optimizeLegibility;}`

All the other accents work fine and `\vec` works fine in all the browsers that I've tested, other than Chrome. Odd.

**Comment by kevinbarabash** [comment]
Verified.  Thanks @ronkok.

**Comment by ronkok** [comment]
This issue was resolved by PR #670.
