### ISSUE TITLE
\mathop should center lone characters

### ISSUE THREAD

**Issue by gagern** [Khan/KaTeX#630]
Something I learned writing https://github.com/Khan/KaTeX/issues/145#issuecomment-272824892: if `\mathop{…}` is given a single character as an argument, it should vertically center that character. So `$X-\mathop{X}-y-\mathop{y}$` renders as

![TeX screenshot](https://cloud.githubusercontent.com/assets/190759/21979721/7c7eec64-dbe0-11e6-9d06-d1b512249855.png)

in TeX but not in KaTeX. I'm not sure where the actual rules are which govern this, but it might be we're overlooking more than just this one exotic corner case, so I thought I'd mention it.

**Comment by ronkok** [comment]
I believe this issue was resolved by PR #745.
