### ISSUE TITLE
Bold greek letters

### ISSUE THREAD

**Issue by szhorvat** [Khan/KaTeX#633]
Is it possible to use bold Greek letters with KaTeX?  I would prefer upright bold, but standard italic bold is also fine for as long as it is distinguishable from non-bold letters.

If this is not yet possible, please consider this a feature request.

With MathJax I can do this using `\boldsymbol{\alpha}`.

**Comment by edemaine** [comment]
See #585.  I'm afraid there isn't a way to do it until then (though I didn't try the latest release and its Unicode support... e.g. `\textbf{α}`).
