### ISSUE TITLE
Does documentclass work?

### ISSUE THREAD

**Issue by asmsuechan** [Khan/KaTeX#643]
Hi, I tried to use `documentclass` by katex, however it didn't work. Is this a bug or my mistake? If my mistake, could you give me some advice?

```tex
\documentclass[12pt]{article}
\setlength{\parindent}{0pt}
\begin{document}
this
\end{document}
```

![2017-01-22 12 24 49](https://cloud.githubusercontent.com/assets/11307908/22179675/1ace62d4-e09e-11e6-8f9a-e5e277fa5608.png)

**Comment by gagern** [comment]
KaTeX *only* typesets formulas. It does not typeset whole TeX documents. So you can't use all those declarations in the head of a file, nor the ones used to form individual paragraphs. You can put into KaTeX the things you'd put between `$…$` or `$$…$$` or `\(…\)` or `\[…\]`.

**Comment by asmsuechan** [comment]
Got it. Thanks for your answer!
