### ISSUE TITLE
Copy/paste support

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#645]
If you use select/copy/paste on a webpage containing KaTeX objects (in Chrome at least), you get the math expression twice (in some format), because of the MathML and HTML versions.  What is the "correct" behavior?

1. At the least, we can remove one copy (e.g. MathML) via [CSS user-select: none](https://css-tricks.com/almanac/properties/u/user-select/).  This seems natural given that MathML is already visually hidden.  This lets you select substrings of the formula... but it's still pretty hit-or-miss what you might get (sub/superscripts/lines/etc. disappear, lots of invisible space characters get copied).

2. I think it might be nice to make the LaTeX source code get copied, perhaps in combination with [CSS user-select: all](https://css-tricks.com/almanac/properties/u/user-select/) to make selection all-or-nothing.  (Selecting substrings wouldn't make a lot of sense in this context.)  I'm not sure whether the current `<annotation>` field can be made to be copyable, though, and I'm not sure it's worth a second copy of the LaTeX source.  (The `<annotation>` tag is also missing `$`s or `$$`s for display mode.  This seems correct for MathML, but isn't what I'd expect when copy/pasting...)

Anyway, I thought we could discuss desirable behavior before implementing anything.  In limited experiments, I haven't gotten either approach to work...

**Comment by ronkok** [comment]
Yes, it would be cool if the LaTeX code could be copied. Even Microsoft Word [now accepts LaTeX input](https://blogs.msdn.microsoft.com/murrays/2017/07/30/latex-math-in-office/).

One way to accomplish this would be to make the entire KaTeX span into a toggle switch that would, when clicked, display the LaTeX code. One way to do this needs only some CSS and a unique ID by means of the [checkbox hack.](https://css-tricks.com/the-checkbox-hack/).

**Comment by edemaine** [comment]
@ronkok In my application, there is a mix of text and math, with several equations, and I'd like to be able to copy/paste the entire thing.  Clicking each equation would be tedious, and also somewhat counterintuitive...

Your message prompted me to look up the HTML5 clipboard APIs. Amusingly, [Section 3.3](https://www.w3.org/TR/clipboard-apis/#Mathematic) gives our exact motivation:

> Mathematical information: With content such as mathematics, simply copying rendered text and pasting it into another application generally leads to most of the semantics being lost. MathML often needs to be transformed to be copied as plain text, for example to make sure "to the power of" is shown with the caret "^" sign in a formula plain-text input. The XML source could also be placed in the clipboard with the appropriate transformation occurring at paste time."

It's a Working Draft, but e.g. the copy event [has support in Chrome, Edge, Firefox](https://developer.mozilla.org/en-US/docs/Web/Events/copy).

Unfortunately, I don't see a way to make a `<span>` render specially when copy/pasting a region that includes it...

**Comment by edemaine** [comment]
MathJax has a related issue, https://github.com/mathjax/MathJax/issues/1350, where they complained about the doubled copy caused by MathML.  It seems there is a pure CSS solution to this subproblem as in [this commit](https://github.com/dpvc/MathJax/commit/4182b58c14c484903cec4eb7ebabc66f2174e9dd).  We should probably do this at a minimum.

**Comment by edemaine** [comment]
Relatedly, if we set a style of `user-select: text` on the `<annotation>` element, the LaTeX code will appear in the copy/paste.  However, I've been unable to get `user-select: none` to prevent the HTML from copy/pasting.  [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) points out that "Selection can contain these elements."

**Comment by edemaine** [comment]
I figured out how to do copy/paste mangling via a custom `copy` event handler.  [Here's a jsfiddle demo](https://jsfiddle.net/edemaine/hazzrd1d/).  I'll suggest this as an optional add-on in `contrib`.

**Comment by kevinbarabash** [comment]
@edemaine please re-open if there's additional work that you think needs doing.
