### ISSUE TITLE
problems with unicode

### ISSUE THREAD

**Issue by Pomax** [Khan/KaTeX#65]
Tried to convert the following:

```
Bézier(n,t) = \sum_{i=0}^{n}
                        \underset{binomial\ term}{\underbrace{\binom{n}{i}}}
                        \cdot\
                        \underset{polynomial\ term}{\underbrace{(1-t)^{n-i} \cdot t^{i}}}
```

But got an unexpected error about the text used:

```
KaTeX parse error: Unexpected character: 'é' at position 1: B_ézier(n,t) = \
```

Given native-unicode XeLaTeX, the (somewhat misguided but mostly fully functional) `utf8` package in regular LaTeX, and the unicode support in HTML, CSS and JS, that should probably not be erroneous but parsed like any other "letter"

(I remember reading you based part of this on the original TeX  Book on the Reddit thread, in which case you definitely need to expand the regular character class to cover a short rather than an int, to capture the 65k characters defined in Unicode BMP 0)

**Comment by AugierLe42e** [comment]
Hi, it seems like I also have this problem with the minus sign :

    ParseError: KaTeX parse error: Unexpected character: '–' at position 39: _{i=1}^{n}(x_i ̲– m)^2

Though it works perfectly with plus sign.

**Comment by Pomax** [comment]
@AugierLe42e you probably want to file that as a separate issue, rather than as part of a greater unicode problem. Your problem reduction suggests it's a sequence parsing error (no error without spaces, error with spaces) rather than a unicode problem (it's not saying that the minus symbol is unsupported or unrecognized)

**Comment by xymostech** [comment]
@AugierLe42e The character you copied from the KaTeX error (`–`, which is unicode's U+2013) isn't parseable by KaTeX. Changing it to a normal minus sign (`-`) should work.

However, that character doesn't appear in the expression you pasted? Are you sure you copied it from the correct source?

**Comment by AugierLe42e** [comment]
This is that character my keybord produces on Mageia Linux 4. I copied/pasted the expression from an article I just wrote. I didn't change the sign. However, the parsign fails when the minus sign is surrounded by whitespaces and pass when not.

**Comment by xymostech** [comment]
@AugierLe42e What are you using to edit that expression? Your editor might be turning `-` into `–` (an en dash) when you put it between spaces.

**Comment by Pomax** [comment]
if your article is online and published through a CMS: it replaced your plain minus sign with the almost-always-incorrectly en-dash (U+2013), a character that is exclusively for numerical ranges.

**Comment by AugierLe42e** [comment]
I thought it was that at firt, yes (I'm on WordPress CMS) but, actually, same result by typing it directly in the text (HTML mode of WP).

**Comment by Pomax** [comment]
Yeah, the WP editor can  do this for you as you type. Try typing `-` into something like a text editor, and you'll see it stay a normal hyphen.

**Comment by kevinb7** [comment]
The fonts we're currently using don't have accented characters like é so we could construct them, but there a other characters like æ and ß which we wouldn't be able to construct.  For those we'd have to add/switch fonts.  Perhaps latin modern: http://www.ctan.org/tex-archive/fonts/lm/.

**Comment by Pomax** [comment]
wait, we're doing this on the web, why do we need .mf *fonts* as opposed to normal opentype fonts with a one-time-run generation of the metrics file for the font? if XeLaTeX's `fontspec` can do this, I'm pretty sure that same approach would work fine for KaTeX, while keeping things as webby as possible.

**Comment by kevinb7** [comment]
I'm not familiar with ```fontspec```.  I had a quick look at https://github.com/wspr/fontspec/ and it looks like it might be useful.  One thing about "any font they want" is that not all fonts will support everything.  Also, all the ```KaTeX-``` fonts in ```static/fonts``` are quite small compared to XITS.  The nice thing about having different character sets in different font files is that you can load what you need.  One of KaTeX's strengths is its speed and wouldn't want to sacrifice that.

**Comment by Pomax** [comment]
they don't, so we can respect CSS here and go "if you know which font you want, you better also have a metrics file available: please use the KaTeX bootstrapping options object to indicate where that file lives" and leave it to the user to break out of the predefined font set. That way everyone wins (KaTeX simply has to offer the build tool, which'll be in the repo anyway, and users who want "their own font" can go hogwild)

**Comment by quxiaofeng** [comment]
Is \underset{}{} supported?

**Comment by kevinbarabash** [comment]
@quxiaofeng not it isn't.  Please open a separate issue as `\underset` is unrelated to unicode support.

**Comment by ronkok** [comment]
The op's example string will now render, both directly and within `\operatorname`:
![bezier](https://user-images.githubusercontent.com/16403058/34967380-2391404c-fa17-11e7-9340-4e53c843d7f0.PNG)
I realize that Unicode is an ongoing project, but maybe we could close this one issue?

**Comment by Pomax** [comment]
Feel free to close it. If there's a solution that's common in TeX land (like `\textit{}`) that works both in normal LaTeX documents as well as in KaTeX, then the original problem the issue was filed over has been resolved, and any further thoughts are follow-up for a different issue that refers back to this one.
