### ISSUE TITLE
Integral renders funky with larger font sizes in Chrome

### ISSUE THREAD

**Issue by mrtnkl** [Khan/KaTeX#651]
When using `\\displaystyle\\int_{}` KaTeX uses the **KaTeX_Size2-Regular** webfonts, which render funky in Chrome when certain scaling applied. 

Hah, as I was writing this and creating the fiddle below I discovered that Chrome 56 fixed it ;-)
Anyway, in case anyone has this issue and you want a bug reproduction, here's the fiddle:

https://jsfiddle.net/mrtnkl/azng8m7y/1/

**Comment by kevinbarabash** [comment]
@mrtnkl can you post a screenshot of what the issue was?

**Comment by kevinbarabash** [comment]
Closing as this is fixed on Chrome 56 and greater.
