### ISSUE TITLE
Rendering of String.raw`\xi` fails

### ISSUE THREAD

**Issue by jkm** [Khan/KaTeX#652]
I figured out that you can use `String.raw` to avoid escaping of `\`. Without the escaping the code looks cleaner to me. That's why I prefer it.

For example use

```javascript
katex.render(String.raw`\alpha`, tex);
```

to render `\alpha`.

Interestingly the code fails to render `\xi`.

```javascript
katex.render(String.raw`\xi`, tex);
```

Here is a full minimal example

```html
<!DOCTYPE html>
	<head>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css" integrity="sha384-wITovz90syo1dJWVh32uuETPVEtGigN07tkttEqPv+uR2SE/mbQcG7ATL28aI9H0" crossorigin="anonymous">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js" integrity="sha384-/y1Nn9+QQAipbNQWU65krzJralCnuOasHncUFXGkdwntGeSvQicrYkiUBwsgUqc1" crossorigin="anonymous"></script>
	</head>
	<body>
		<div id="tex"></div>
	<script>
		window.onload = function() {
			var tex = document.getElementById("tex");
			katex.render(String.raw`\xi`, tex);
			// work around
			//katex.render("\\xi", tex);
		}
	</script>
	</body>
</html>
```

Any ideas why this fails to render?

**Comment by jkm** [comment]
It seems to be a Javascript issue since `var str = String.raw`\xi`;` causes a problem. It's fine to close this here, if you wish. Maybe anyone with deeper Javascript knowledge can enlighten me.

**Comment by kevinbarabash** [comment]
@jkm https://tc39.github.io/proposal-template-literal-revision/ will allow unescaped `\` in custom template strings so 
```
String.raw`\xi`
```
still won't work, but you'll be able to define a `katex` function and then do
```
katex`\xi`
```
Unfortunately, it doesn't look like babel supports it yet.  It is a stage 3, according to https://github.com/tc39/proposals, so that's promising.
