### ISSUE TITLE
Using KaTeX in non-web applications?

### ISSUE THREAD

**Issue by cesss** [Khan/KaTeX#655]
Hi,

I need to display LaTeX math (or a subset of it) in an application written in C++ which runs offline. For the display, the app needs access to data structures defining the math expression typesetting either in vector or bitmapped form (preferably vector, but bitmapped would be better than nothing).

I've been searching libraries doing this for a couple of years, and the only solutions I found are to either embed a custom LaTeX distribution within the app (thus turning it into a heavy weight installation file), or using Matplotlib (but its LaTeX supported subset is perhaps too limited, and it's written in Python, so it requires interfacing Python with C++, and embedding the Python files in the app). The other alternative I found is MathJax, but, again, using it from an application is non-trivial, and you need to embed a web browser inside your app.

A few days ago, I found iosMath. It looks almost exactly like what I'm looking for, except for the fact that it depends on Cocoa Frameworks, so it only runs on iOS and MacOS.

Now I found KaTeX. It's a web toolkit, so I guess it would have the same implications as MathJax (the need to embed a web browser inside your app), but I'm asking here with the hope that it could be used in a simpler way, or that you know of any KaTeX-derived works or alternatives that might be suitable for C++ offline apps.

Thanks!

**Comment by edemaine** [comment]
KaTeX does not require web / web browser; it only requires [Node](https://nodejs.org/en/).  However, the output is HTML, so you would need an HTML/CSS renderer of some sort to display the results.  Hopefully that fits within what you can embed...

**Comment by gagern** [comment]
You might be interested in #251 which discusses a way to render KaTeX output to a HTML5 canvas. Combining that with [node-canvas](https://github.com/Automattic/node-canvas) it should be able to generate PDF or SVG. You'll likely have to write some code to register the appropriate fonts, as the CSS used by KaTeX won't be used in this approach. If I find the time, I might hack a proot of concept tool for this whole approach, but don't rely on me finding that time…

**Comment by kevinbarabash** [comment]
We're looking at creating an intermediate representation for graphical rendering.  Please follow https://github.com/Khan/KaTeX/issues/376.
