### ISSUE TITLE
Feature request: support \colonequals or similar

### ISSUE THREAD

**Issue by katef** [Khan/KaTeX#657]
A couple of TeX packages provide macros for this; `:=` has special spacing, where the dots are made symmetrical.

There's also the unicode codepoint, U+2254.

Thank you!

**Comment by kevinbarabash** [comment]
I think it'll take a while to get the right glyph.  Would it be useful to have the `\colonequals` command output `:=` for now and then when we have the correct glyph it will start outputting the correct glyph?

**Comment by gagern** [comment]
I think I've seen `\coloneqq` for this, too. Yes, I think having the command first and the glyph when we can get it would make sense. I also wonder whether we could hack something like a `\raisebox` and use that to move the colon to the symmetrical position, at least approximately. The proper type for the whole thing, I guess mathrel, would seem important, too.

**Comment by katef** [comment]
I agree about getting the markup supported now (a `\raisebox` or similar sounds fine!) and drawing a proper glyph later.

SO lists a few ways to mark that up for TeX: http://tex.stackexchange.com/questions/4216/how-to-typeset-correctly

**Comment by edemaine** [comment]
FWIW, [oberdiek's colonequals](http://ctan.mackichan.com/macros/latex2e/contrib/oberdiek/colonequals.pdf) implements it via `\vcenter`.  I imagine implementing `\vcenter` in KaTeX would be on the tricky side, though #637 is related.

**Comment by edemaine** [comment]
The `\raisebox` solutions seem pretty good, actually -- because they use `ex` measurements, they should scale reasonably to other font sizes.  However, KaTeX doesn't actually support `\raisebox`.  `\raisebox` would be useful for #224 (`\LaTeX`) too.

**Comment by edemaine** [comment]
I looked a little closer at `mathtools` which implements a centered colon very simply as
```latex
\def\vcentcolon{\mathrel{\mathop\ordinarycolon}}
\providecommand\ordinarycolon{:}
```
i.e. just `\mathrel{\mathop:}`.  In LaTeX, this centers the colon:

![colon_eq](https://cloud.githubusercontent.com/assets/2218736/25505981/461d901c-2b72-11e7-9510-58a3f077a00a.png)

In KaTeX, `\mathrel{\mathop:}=` and `:=` seem to render exactly the same (with the colon not centered, like on the right).  Is this a known issue?

**Comment by edemaine** [comment]
I found where this behavior is implemented in TeX: [Documentation of \mathop](https://tex.stackexchange.com/questions/368673/documentation-of-mathop/368700)

When the argument to `\mathop` is a single character, it gets centered vertically.  Perhaps this could be implemented by tweaking buildHTML's `groupTypes.mclass` (when `group.value.mclass === 'mop'`), e.g. using the in-process `\raisebox` implementation (#685).

Anyway, I think we can split this issue into two: define `\colonequals` to mean `\mathrel{\mathop:}=` (I'll work on a PR), and fix `\mathop` to vertically center single-character arguments (#725).
