### ISSUE TITLE
Subscripts not showing up correctly

### ISSUE THREAD

**Issue by autarkaw** [Khan/KaTeX#659]
The html file when run shows the subscripts not as subscripts.  They look like superscripts.  See attached screen shot.  It is the equation after "guess" and "root".   

Please help!  What am I doing wrong for such a simple case.

I am using Chrome.

![katex_issue_subscripts](https://cloud.githubusercontent.com/assets/22177337/23073074/3da2b6a2-f502-11e6-8186-0823b14f7585.jpg)

_________________
This is my html file and  the content is given below as well https://p9.secure.hostingprod.com/@mathforcollege.com/ssl/03nle/newton/NewtonRaphsonMethodExampleProblem2b.html 
_________________
<html>
<script src='https://lib.smartsparrow.com/simcapi-js-1.2.2.min.js'></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js"></script>
<script src="NewtonRaphsonMethodExampleProblem2b.js">
</script>
</html>

______________________
This is my .js file and  the content is given below as well
https://p9.secure.hostingprod.com/@mathforcollege.com/ssl/03nle/newton/NewtonRaphsonMethodExampleProblem2b.js 
_______________________

var x = []
x.push((Math.floor(Math.random()*(3-2)*10)/10)+2);

var equation = katex.renderToString("x^2 = 22");
var initial = katex.renderToString("x_{0}  = "+x+"");
var second = katex.renderToString("x_{2}");

document.write("Given the equation "+equation+" and an initial guess "+initial+", the second iterative value of its root, "+second+" by Newton-Raphson method is<br><br>");

for (i = 1; i <=2;i++){
nrm2 = x -(Math.pow(x,2)-22)/(2*Math.pow(x,1));
x=nrm2;
}
//document.write(nrm2);

var simModel5 = new simcapi.CapiAdapter.CapiModel({
nrm2: nrm2, 
simEnabled: true
});

simcapi.CapiAdapter.expose('nrm2',simModel5);
simcapi.CapiAdapter.expose('simEnabled', simModel5,{writeonly:true})

simcapi.Transporter.notifyOnReady();

**Comment by xymostech** [comment]
You need to add a doctype to your HTML file to make KaTeX render correctly. (there is a warning in the console telling you this!) See e.g. #332

**Comment by autarkaw** [comment]
Thank you.  It worked. 

Autar Kaw 
http://autarkaw.com
