### ISSUE TITLE
Integral symbol too small, interval values seem too big/placed incorrectly

### ISSUE THREAD

**Issue by Pomax** [Khan/KaTeX#66]
Comparison shot between MathJax and KaTeX for definite integrals:

![image](https://cloud.githubusercontent.com/assets/177243/4298346/c0f5dd0a-3e1f-11e4-8690-ac36a2f2499a.png)

**Comment by kevinb7** [comment]
@Pomax please re-open if this is still an issue for you.

**Comment by spicyj** [comment]
(We added a new flag…)

```
katex.render("c = \\pm\\sqrt{a^2 + b^2}", element, { displayMode: true });
```

**Comment by kevinb7** [comment]
That flag centers stuff on the test page.  Not sure how it will affect @Pomax's layouts.
