### ISSUE TITLE
Rendering a string with unescaped dollars

### ISSUE THREAD

**Issue by Rokt33r** [Khan/KaTeX#665]
Even `throwOnError` set `false`, KaTeX always throws the parser error when rendering a string with **unescaped dollars**.

```
> console.log(katex.renderToString('$', {throwOnError: false})
ParseError: KaTeX parse error: Expected 'EOF', got '$' at position 1: $̲
```

**Comment by kevinbarabash** [comment]
KaTeX starts in math mode so the dollar symbol must be escaped.

**Comment by edemaine** [comment]
See also #475 as relevant. (Maybe we should improve that documentation...)

**Comment by Rokt33r** [comment]
I think KaTeX should throw another type of error for this.
It is confusing because both of them look same type. Most people would expect same behavior.

Unescaped dollars :`KaTeX parse error: Expected 'EOF', got '$' at position 1: $̲`
Invalid command : `KaTeX parse error: Expected 'EOF', got '\alpa' at position 1: \a̲l̲p̲a̲`
