### ISSUE TITLE
frac as sqrt optional exponent causes overlap

### ISSUE THREAD

**Issue by hermanbergwerf** [Khan/KaTeX#666]
Example: `\sqrt[\frac{a}{b}]{c}`

Screenshots:
MathJax | KaTeX
| --- | --- |
![screenshot from 2017-03-10 18-59-50](https://cloud.githubusercontent.com/assets/4458965/23806903/c692f392-05c3-11e7-9b2a-8387b16a3df8.png) | ![screenshot from 2017-03-10 18-59-34](https://cloud.githubusercontent.com/assets/4458965/23806904/c6935fd0-05c3-11e7-8fc8-3d72ffeb3146.png)

I'm not sure what the specs say, but I've seen this issue a couple of times and I thought I should report it.

**Comment by edemaine** [comment]
KaTeX aims to match LaTeX as closely as possible.  LaTeX renders that math as follows:

![latex_sqrt_frac](https://cloud.githubusercontent.com/assets/2218736/23823615/38d9dee6-0634-11e7-8da1-ee966ea92102.png)

So KaTeX is working more or less as intended (currently a slight horizontal offset from LaTeX, though KaTeX's offset is actually more readable...).

**Comment by hermanbergwerf** [comment]
I understand. Thanks for the explanation.
Interesting to see that KaTeX is (at least in this case) even more compliant than MathJax. And I do agree the borders on MathJax are ugly. It was even worse at other zoom levels (one potential cause is that people have determined to border to be 1px thick or something. Then when zoomed out everything looks fine because of anti-aliasing and because border rendering probably ceils to 1px (for example when specifying in em), but when zooming in, well, you guessed it).
