### ISSUE TITLE
how to output a matrix?

### ISSUE THREAD

**Issue by saintthor** [Khan/KaTeX#667]

**Comment by saintthor** [comment]
i found the doc.

**Comment by edemaine** [comment]
This is a place to ask about KaTeX, not LaTeX. A Google search for "latex matrix" brings uo tons of useful guides, e.g.: http://www.maths.tcd.ie/~dwilkins/LaTeXPrimer/Matrices.html

**Comment by saintthor** [comment]
i was asking how to do it in KaTeX.
since there is no docs about it, i tried the ways in latex.

**Comment by edemaine** [comment]
Both matrix and array environments are supported in KaTeX.

**Comment by saintthor** [comment]
is there any guide about how to write it in KaTeX style?
i tried some latex strings. some of them works in katex. some not.

**Comment by edemaine** [comment]
#269 gives a list of missing features. Is that what you'd like?

**Comment by saintthor** [comment]
it seems not. for example, to draw a matrix in latex:

\[ \left( \begin{array}{ccc}
a & b & c \\
d & e & f \\
g & h & i \end{array} \right)\] 

this works in katex too. if there is no better way.

**Comment by edemaine** [comment]
The following also works in KaTeX.  These are the two ways to do matrices in LaTeX/AMSTeX...

```latex
\left(\begin{matrix}
  1 & 0 \\
  0 & 1
\end{matrix}\right)
```

**Comment by kevinbarabash** [comment]
@saintthor https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX contains a list of all supported environments.
> array‡ matrix bmatrix Bmatrix pmatrix vmatrix Vmatrix cases aligned darray† dcases†

**Comment by saintthor** [comment]
thank you.
