### ISSUE TITLE
\sqrt function is sometimes overlapping with its content

### ISSUE THREAD

**Issue by keshavkaul** [Khan/KaTeX#673]
I'm using `renderToString` to convert tex to html string. Following is my test environment: 
1. Using react-native ios 6 simulator.
2. Rendering html inside ios web view.
3. tex - `\sqrt{7^2}`

Result:
<img width="207" alt="screen shot 2017-04-01 at 2 53 14 am" src="https://cloud.githubusercontent.com/assets/3319809/24570150/9fe4a37e-1687-11e7-9f91-7e9040ee6487.png">

Any ideas on the issue?

**Comment by kevinbarabash** [comment]
@keshavkaul can you provide a minimal example of the code being used that reproduces this?

**Comment by gagern** [comment]
Closing for now, feel free to reopen if more details are available.
