### ISSUE TITLE
problem rendering matrix with sub

### ISSUE THREAD

**Issue by kikko088** [Khan/KaTeX#674]
Hi, I get an error trying to render this simple eq:
\(\begin{bmatrix} a_{1,1} \end{bmatrix}\)
the problem seems to ben a_{1,1} , where is the error? 

Francesco

**Comment by edemaine** [comment]
Your example renders fine on the [demo app](https://khan.github.io/KaTeX/):

![bmatrix](https://cloud.githubusercontent.com/assets/2218736/24734214/271e89de-1a4a-11e7-9c4d-dcc51a0f8777.png)

What problem/error are you having?  If I had to guess, it'd be that you're not specifying the doctype correctly.  See #661.

**Comment by gagern** [comment]
Closing for now, feel free to reopen if more details are available.

**Comment by looeee** [comment]
I'm having the same problem. It seems like any with a \begin and \end won't render. So for example, this works, as do many more complex expressions:

```
$$
\dbinom{n}{k}
$$
```

But this doesn't, and it seems any other expressions that start with \begin also don't:
```
$$
\begin{pmatrix}
  a & b \\
  c & d
\end{pmatrix}
$$
```

Even though both expression do work in the example app. I'm including Katex as described on the [autorender](https://github.com/Khan/KaTeX/blob/master/contrib/auto-render/README.md) page, by including this at the foot of my page: 

``` html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css" integrity="sha384-TEMocfGvRuD1rIAacqrknm5BQZ7W7uWitoih+jMNFXQIbNl16bO8OZmylH/Vi/Ei" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js" integrity="sha384-jmxIlussZWB7qCuB+PgKG1uLjjxbVVIayPJwi6cG6Zb4YKq0JIw+OMnkkEC7kYCq" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/contrib/auto-render.min.js" integrity="sha384-IiI65aU9ZYub2MY9zhtKd1H2ps7xxf+eb2YFG9lX6uRqpXCvBTOidPRCXCrQ++Uc" crossorigin="anonymous"></script>
<script>renderMathInElement(document.body);</script>
```

Perhaps it's a problem with autorender?

**Comment by edemaine** [comment]
@looeee We'd probably need a full example to help diagnose.  It's likely a bug with your particular setup, not katex or autorender.  Can you also try `\cr` instead of `\\`?  Or does a matrix without `\\` also fail?

**Comment by looeee** [comment]
`\cr` works! 

Thanks 😄  

Yeah I figured it out - it's because I'm writing in markdown and the `//` is replaced with a `<br>`.
