### ISSUE TITLE
Text font commands don't stack right

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#676]
`\textbf{\textit{x}}` should produce a bold-italic "x", but it currently produces a nonbold italic "x" because all KaTeX commands reset the entire font.  My understanding is that this is correct for math font commands (`\mathbf{\mathit{x}}` correctly produces a nonbold italic "x"), but incorrect for text font commands.  (How asymmetric...)  By contrast, `\text{\textbf{\it x}}` (using `\it` implemented in #675) should produce a nonbold italic "x", because old font commands like `\it` *should* reset the font.

~~This would be a moot point if there weren't bold italic fonts available, but there are.~~ This would also require creating Main-BoldItalic fonts; see below.

**Comment by kevinbarabash** [comment]
Nice find.

**Comment by ronkok** [comment]
@kevinbarabash Many issues, like this one, are blocked by missing font glyphs. It would be helpful if we had a single list that identified all of the desired glyphs. Then, if someone took on the font task, they would have a ready-made TO DO list. I wouldn't mind putting together such a list.

Would you rather have it in an issue or a project?

**Comment by kevinbarabash** [comment]
@ronkok a project would be a good way to track this kind of stuff.  Updating fonts is currently blocked on creating a separate repo for fonts.  I'll try to tackle this this weekend.

**Comment by rrandallcainc** [comment]
Was going to open an issue on this, but just came across this. 

I'm attempting to do: \textsf{\textbf{Hello world}}, and while it renders in bold, it does not render in Sans Serif font.

Is there any update on this issue? What can I do to help?

**Comment by kevinbarabash** [comment]
@rrandallcainc it looks like we have the fonts.  I think `Option#withFont` needs to be updated to so that instead of simply replacing the `.font` property, we'd modify it.  It might even make sense to turn `.font` into `.fonts` so that we can toggle the active fonts by adding/removing them from the list of fonts.  We'll also need to apply one or more font classes from https://github.com/Khan/KaTeX/blob/master/static/katex.less.

**Comment by rrandallcainc** [comment]
@kevinbarabash Okay, I'll give this a shot. Thanks.

**Comment by rrandallcainc** [comment]
@kevinbarabash I noticed in: https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX that there's no support yet for a bold/itatlic Sans Serif font (along with others), but it looks like they are contained inside of the "fonts" folder. Do we know what's blocking these from being exposed?

**Comment by kevinbarabash** [comment]
@rrandallcainc you'll need to create an entry in mapping.pl that looks something like:
```
$map{cmss10} = {
  "SansSerif-Regular" => [ ... ],
};
```
I don't know what the actual font names are.  My guess would be `cmsb10` and `cmsi10`.

**Comment by rrandallcainc** [comment]
@kevinbarabash @edemaine It looks like \textbf{\textit{x}} should be rendering a Main-BoldItalic font. However, I don't see that available either through Katex or MathJax-Dev. Am I missing something?

**Comment by kevinbarabash** [comment]
@rrandallcainc if it's not in either place it can be added, but this will mean regenerating the fonts.  Before we do that I'd like to merge in https://github.com/Khan/KaTeX/pull/891 so that we can the size of the KaTeX repo relatively small.  If you have some time maybe you could look over that diff.

**Comment by edemaine** [comment]
@rrandallcainc My original post was probably confused by the existence of `Math-BoldItalic` (and `KaTeX_Math-BoldItalic.ttf`).  But you're right, `Main-BoldItalic` doesn't seem to exist yet.
