### ISSUE TITLE
Some symbols are associated with a non-existing "math" font.

### ISSUE THREAD

**Issue by arnog** [Khan/KaTeX#677]
Symbols \coprod, \bigvee, \bigwedge...\smallint are assigned the fontFamily "math". It should probably be "main". See symbol.js:564-581.

**Comment by edemaine** [comment]
Oops, yeah, that seems to be a typo (dating pretty far back).  Most font test code just compares vs. "ams", so this wouldn't matter, but I do see at least one test vs. "main", so good to fix.  I created #678 to fix it.  Doesn't affect any screenshots/tests.
