### ISSUE TITLE
Need `gathered` environment

### ISSUE THREAD

**Issue by konn** [Khan/KaTeX#682]
LaTeX has a `gather` and `gather*` environments (and also `gathered`, which is analogous to what `aligned` is for `align`) for center-aligned (or un-aligned) multiline equations, but they seems absent in KaTeX.

**Comment by edemaine** [comment]
Thanks, I didn't know about amsmath's `gather`/`gather*`/`gathered`.  KaTeX ought to support `gathered`, whereas `gather`/`gather*` would belong in a text-level wrapper (not yet written) as described in #603.

Intuitively, `\begin{gathered} ... \end{gathered}` seems similar to `\begin{array}{c} ... \end{array}`, so I ran a test:

```latex
$$\begin{gathered} \text{gathered}   \\ x^2+y^2=z^2 \\ x < y \end{gathered} =
  \begin{array}{c} \text{array\{c\}} \\ x^2+y^2=z^2 \\ x < y \end{array}
$$
```
![gathered](https://cloud.githubusercontent.com/assets/2218736/25488183/63c76b3a-2b34-11e7-8cbf-fc8fca8c1c11.png)

The only difference seems to be in the line spacing.  This shouldn't be hard to implement, provided we can figure out what the correct spacing is...  [amsmath](http://mirror.jmu.edu/pub/CTAN/macros/latex/required/amsmath/amsmath.pdf) seems to implement this via `\spread@equation` which I've yet to grok.

**Comment by kevinbarabash** [comment]
I'm guessing the `gathered` implementation changes the line spacing "constant" temporarily while in the environment.  We should add a dictionary for line spacing and other constants using `\setlength`, e.g. `\setlength{\jot}{10pt}` changes the line spacing... then `gathered` could be implemented using a macro.

**Comment by kevinbarabash** [comment]
I've opened an issue for `\setlength` support, see https://github.com/Khan/KaTeX/issues/687.

**Comment by arnog** [comment]
The extra space between rows in the `gathered` environment is the same extra spacing from the `aligned` environment, introduced by the `\jot` command (3pt). 

There's another important difference between `gathered` and `array{x}`, the cells of the former are in `displaystyle` while the cells of the later are in `textstyle`. See for example:
```
\begin{gathered} \text{gathered}   \\ \frac12 x^2+y^2=z^2 \\ x < y \end{gathered}
     =
  \begin{array}{c} \text{array\{c\}} \\ \frac12 x^2+y^2=z^2 \\ x < y \end{array}
```

<img width="282"  src="https://cloud.githubusercontent.com/assets/760798/25675355/04de3a72-2ff3-11e7-8e14-8aba49db46f4.png">

**Comment by edemaine** [comment]
Added in #725

**Comment by kevinbarabash** [comment]
This has been merged with `master` so I'm going to close this.

**Comment by abourque72** [comment]
Hi, I'm confused... was this ever actually added? It doesn't work for me:

`$$\begin{gathered} \Gr_\lam=\left\{ \L\in\Gr\mid t^{\lam_1}\O^n\subset \L \subset t^{\lam_n}\O^n \\ \text{ and } \dim\frac{\L\cap t^i\O^n}{t^{\lam_1}\O^n}=\sum_{j=i}^{\lam_1-1}|\{ k\mid \lam_k\leq j \}| \text{ for all } \lam_n\leq i\leq \lam_1 \right\}. \end{gathered}$$`

displays one line.
