### ISSUE TITLE
Issue around `\middle` and spacing

### ISSUE THREAD

**Issue by konn** [Khan/KaTeX#683]
KaTeX ignores any spacing command on the left of `\middle`:

For example, In the image below, space should be inserted before `|` but no space is rendered, although the space right after `|` is properly rendered:
<img width="802" alt="2017-04-27 23 20 23" src="https://cloud.githubusercontent.com/assets/21860/25487755/2271a58a-2ba0-11e7-98f6-a4e1eb7cff27.png">

Even worth, however many spacing commands are inserted before `\middle|`, they are all ignored, e.g. `\left.a\ \ \ \ \ \ \ \ \ \ \middle| \ b\right.` will be rendered same as the above.

**Comment by edemaine** [comment]
Thanks for the bug report!  That is weird.  I've confirmed that both `\ ` and `~` before `\middle` disappear, so it's not just space characters being dropped (e.g. while parsing).  Presumably it's a `\kern` getting absorbed somehow...

As a temporary workaround, I found that wrapping the space in braces works:
```latex
\left.a{\ }\middle|\ b\right.
```

**Comment by edemaine** [comment]
I found the issue: [this code in buildHTML.js](https://github.com/Khan/KaTeX/blob/master/src/buildHTML.js#L73-L94) puts spaces inside a group with the `\middle`, while keeping `isMiddle` true, so the space + `\middle` end up getting replaced by the delimiter.  I see two possible fixes:
1. Change that code to not put spaces into `\middle` specifically.
2. When *parsing* `\left...\right` in `Parser.js`, split the body into two parts if there's a `\middle`, replacing "body" with something like "beforeMiddle" and "afterMiddle".  In other words, change the parse tree structure to be more natural with respect to middle.  Then there can't be any conceptual errors like this.
