### ISSUE TITLE
Suggestion: allow katex options to be passed to auto-render

### ISSUE THREAD

**Issue by benstevens48** [Khan/KaTeX#690]
At the moment the auto-render module is missing some key features. One of these is the ability to pass katex options to be used during rendering, for example custom macros.

I suggest that the options argument of `renderMathInElement` should have a property called `katexOptions` which would be passed to the `katex.render` function (obviously the display option should be overridden as appropriate).

**Comment by edemaine** [comment]
This feature is already nearly complete; see #656.

**Comment by benstevens48** [comment]
Ah yes, I didn't see that. For what it's worth I think it would be simplest to implement this as I suggested above (possibly with a different name) since keeping the katexOptions (to pass to katex.render) completely separate is conceptually simple for both writing the code and for the user and is future-compatible, and merging and un-merging the two sets of options seems like an added complication. This seems to be quite standard in a lot of javascript stuff e.g. compilerOptions in the typescript config file and a lot of the gulp plugins which wrap some other module. But I don't want to delay anything!
