### ISSUE TITLE
Suggestion: don't force global katex for auto-render to work

### ISSUE THREAD

**Issue by benstevens48** [Khan/KaTeX#692]
At the moment you have to declare katex globally for auto-render to work. The easiest way not to force this would be to add katex as a property of the renderMathInElement options which could be used by the user to supply an instance of katex, although this is perhaps slightly cumbersome. Alternatively you could do a conditional require if require is defined and katex is not defined globally, using a relative path so katex would be pulled in automatically assuming the directory structure is correct (and make sure katex isn't bundled during the build).

**Comment by edemaine** [comment]
Could you give an example setting where this would be useful?  I assume you're in browser -- are you just trying not to pollute the `window` namespace?

**Comment by benstevens48** [comment]
Yes I suppose I'm just trying not to pollute the window namespace. I'm using a module loader to load all my javascript files and it seems to go against the trend a little bit to force a module to be globally defined. I suppose it's not a big issue at the moment though.

**Comment by kevinbarabash** [comment]
We could change `renderMathInText` so that it takes an optional third argument which is a reference to `katex`.

**Comment by benstevens48** [comment]
Yes I guess something like that would be the easiest although I'd put it in the options object to avoid having lots of extra parameters. Having thought about it a conditional require might cause problems for some module loaders. It's not a big issue but then again it would also but quite simple to add this extra option.
