### ISSUE TITLE
KaTex and multi-line braces

### ISSUE THREAD

**Issue by skillogs** [Khan/KaTeX#693]
Hi,

I try to make that kind of multiline equation with a brace but don't manage to do it with KaTex, anyone can help me?

![image](https://cloud.githubusercontent.com/assets/28511939/25783640/f0c02b52-335f-11e7-9908-3a3a814d5f60.png)

**Comment by ronkok** [comment]
This code:

```
\left\{ \begin{array}{l}
     2x + y = 6 \\
     y = 7
 \end{array} \right.
```

… should do the trick.

**Comment by kevinbarabash** [comment]
TIL that `\right.` adds an empty delimiter.

**Comment by skillogs** [comment]
I don't know why, but the multi-line coding doesn't work for me...

**Comment by kevinbarabash** [comment]
@skillogs what version of KaTeX are you using?

**Comment by edemaine** [comment]
@skillogs Here's how @ronkok's code renders on the demo app.  What do you get?  (What does "doesn't work" mean?)

![multiline](https://cloud.githubusercontent.com/assets/2218736/25806463/40ed6222-33d1-11e7-8920-7ae5db5608ba.png)

**Comment by edemaine** [comment]
Let us know if you need more help getting this working.
