### ISSUE TITLE
Feature Request: Support multiple values in exponents/superscript in math notation

### ISSUE THREAD

**Issue by jl98** [Khan/KaTeX#694]
Was told to post this issue here from Caret Editor: https://github.com/careteditor/caret/issues/349

**Comment by edemaine** [comment]
Could you clarify what you want here?  `$x^2^3$` does not compile in LaTeX, which is why it doesn't compile in KaTeX either.

**Comment by jl98** [comment]
My apologies, I misinterpreted the issue, and found a solution. I was misusing round brackets vs. curly brackets.
