### ISSUE TITLE
rendering TeX

### ISSUE THREAD

**Issue by pyramation** [Khan/KaTeX#701]
Hi, this library seems to compare itself to MathJAX, however, the more research seems to show it's actually only an equation rendering system, and MathJAX is more comparable to TeX because  it renders strings like `here is a function $f(x)$, ...`.

Am I missing something, or is documented how to do this somewhere?

There was an issue here (https://github.com/Khan/KaTeX/issues/3) that says it may be a possibility, where on the roadmap is this?

For example, how does one go about rendering this in KaTeX?

```
Here is a $r_2(n) = \{ (a,b) \in \mathbb{Z} | a^2 + b^2 = n \}$, which counts the number of representations of $n$ as a number of 2 squares.
```

**Comment by waywaaard** [comment]
MathJax is also an equation rendering system like KaTeX, only that it automatically renders all wrapped LaTeX nodes.

The same is possible using the auto render plugin https://github.com/Khan/KaTeX/blob/master/contrib/auto-render/README.md 

KaTeX uses an synchronous approach for rendering LaTeX, which makes it a faster than MathJax

**Comment by kevinbarabash** [comment]
@pyramation KaTeX and MathJax both only typeset math within `$` (or otherwise specified) delimiters.  https://github.com/Khan/KaTeX/issues/3 is about general support of TeX which is substantially more than just rendering math inside `$` delimiters.  The focus of KaTeX is rendering of math, not recreating the full TeX system.

**Comment by pyramation** [comment]
@kevinbarabash I understand, I actually wrote the library #3 was referring to. @waywaaard (thanks) I think that's generally what I'm talking about.

**Comment by edemaine** [comment]
See also the related issue I raised (and eventually plan to do): #604
