### ISSUE TITLE
How to write with the aligned environment in html

### ISSUE THREAD

**Issue by MathSalomon** [Khan/KaTeX#705]
Hello friends.

 I want to write in a simple HTML page simple the following math expression in latex code under the Katex rendering
                `$$\begin{aligned}`
		`x&=y & X&=Y & a&=b+c\\ `
		`x'&=y' & X'&=Y' & a'&=b\\ `
		`x+x'&=y+y' & X+X'&=Y+Y' & a'b&=c'b`
		`\end{aligned}$$`
I've tried with <span class="tex" data-expr="$$\begin{aligned}...\end{aligned}"></span>
But I can not get it.

Here I show how I have left that page

![snapcap2293](https://cloud.githubusercontent.com/assets/28682842/26032374/8228ea24-3857-11e7-8146-bd290b85818b.jpg)
![snapcap2291](https://cloud.githubusercontent.com/assets/28682842/26032375/82307762-3857-11e7-9e69-d84b9d4faf18.jpg)

Someone help me?
Thanks in advance.

**Comment by kevinbarabash** [comment]
@MathSalomon the page you linked to is using version 0.1.1 of KaTeX.  If you upgrade your version of KaTeX to the most recent version it should work.

**Comment by MathSalomon** [comment]
@kevinbarabash Many thanks!, 
I changed it to  ` https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css ` and `https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js` in the preamble. And now the environment begins {begin}. Many thanks :)
