### ISSUE TITLE
Support for rendering a number line

### ISSUE THREAD

**Issue by samridhgupta** [Khan/KaTeX#707]
Hi all,

I came across this QnA at Tex Stackexchange detailing on drawing number lines in Tex. How would I be able to accomplish that in Katex? Or if it is not supported in Katex, what are my alternatives? Any help would be appreciated. Thanks.

**Comment by ronkok** [comment]
KaTeX can not do that sort of thing. I think your best bet would be to use a dedicated drawing program. There are many available. For a drawing like the one you want, perhaps [SVG-Edit](https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svg-editor.html) would work.

**Comment by edemaine** [comment]
Personally I'd recommend [Inkscape](http://inkscape.org/) for an SVG drawing program.  And maybe [LaTeXiT](https://www.chachatelier.fr/latexit/) to put LaTeX labels in the figure.

**Comment by PeterBocan** [comment]
Supporting TikZ would need a package to itself. 👍

**Comment by mbourne** [comment]
If you have a lot of number lines to draw, you may want to consider:

(1) JSXGraph (but it's overkill for this situation)

(2) My [ASCIIsvg-IM.js](http://www.intmath.com/cg3/asciisvg-im-js-demo.php) (see a number line example about half way down the page)

(3) My PHP port of the above which does all the SVG-production work on the server and caches the results. This page has number line examples: [Properties of Inequalities](http://www.intmath.com/inequalities/1-properties-inequalities.php)

You can overlay KaTeX as in the first example on [this page](http://www.intmath.com/counting-probability/14-normal-probability-distribution.php)
