### ISSUE TITLE
texcmp woes

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#708]
I've never been able to run the texcmp docker via `texcmp.sh`.  I get this permission error:

```$ sudo ./texcmp.sh
+ imgname=katex/texcmp
+ tag=1.1
++ docker images
++ awk '/katex\/texcmp *1\.1/{print $3}'
+ imgid=01e4c2f34b2d
++ dirname ./texcmp.sh
+ cd .
+ npm install
npm WARN texcmp@ No repository field.
+ [[ -z 01e4c2f34b2d ]]
++ cd ../..
++ pwd
+ base=...../KaTeX
+ docker run --rm -v ...../KaTeX:/KaTeX -w /KaTeX/dockers/texcmp katex/texcmp:1.1 nodejs texcmp.js

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied '/KaTeX/dockers/texcmp/texcmp.js'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at Object.Module._extensions..js (module.js:473:44)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

A little more investigation on trying to access that file within the docker:

```$ sudo docker run --rm -v ...../KaTeX:/KaTeX -w /KaTeX/dockers/texcmp katex/texcmp:1.1 ls -l texcmp.js
-rw-r--r-- 1 20028 20028 9115 May 16 13:16 texcmp.js
$ sudo docker run --rm -v ...../KaTeX:/KaTeX -w /KaTeX/dockers/texcmp katex/texcmp:1.1 cat texcmp.js
cat: texcmp.js: Permission denied
```

I tried chmod'ing the files to world readable, but I'm on AFS, so it seems that I need to make the files world readable via `fs sa . system:anyuser read`.  This is odd to me, because the screenshotter docker runs fine without such a setting.  Any chance that the calls to docker could be unified between screenshotter and texcmp to behave like the screenshotter one? (I guess inheriting permissions from the calling user.)

I *can* run `texcmp.js` from the command line without docker, but because my ImageMagick is old, I need to tweak the command line slightly:

```diff
diff --git a/dockers/texcmp/texcmp.js b/dockers/texcmp/texcmp.js
index 56e32ea..06686b5 100644
--- a/dockers/texcmp/texcmp.js
+++ b/dockers/texcmp/texcmp.js
@@ -156,11 +156,11 @@ function processTestCase(key) {
         const uh = Math.max(browser.height + by, latex.height + ly); // u. h.
         return execFile("convert", [
             // First image: latex rendering, converted to grayscale and padded
-            "(", pngFile, "-grayscale", "Rec709Luminance",
+            "(", pngFile, "-colorspace", "Gray",
             "-extent", uw + "x" + uh + "-" + lx + "-" + ly,
             ")",
             // Second image: browser screenshot, to grayscale and padded
-            "(", browserFile, "-grayscale", "Rec709Luminance",
+            "(", browserFile, "-colorspace", "Gray",
             "-extent", uw + "x" + uh + "-" + bx + "-" + by,
             ")",
             // Third image: the per-pixel minimum of the first two images
```

According to [this ImageMagick page](http://www.imagemagick.org/Usage/color_mods/#grayscale), these are probably equivalent, so perhaps we could change that to support more ImageMagick versions?

**Comment by gagern** [comment]
The screenshotter merely runs an existing selenium image inside the docker. All the javascript logic and file access happens outside the docker. texcmp on the other hand builds its own docker image, and used to mount a host directory in there to access the script, screenshot definitions and existing screenshots. In #722 I changed that; please give that one a try and report back.

I haven't tried `-colorspace Gray` yet. If #722 works for you, feel free to give that one a try with those arguments, and propose a pull request if that works. According to [the `-grayscale` doc](http://www.imagemagick.org/script/command-line-options.php?#grayscale), `colorspace Gray` implies Rec709Luma which is different from Rec709Luminance. The former is apparently non-linear. I don't have strong feelings either way, though.

**Comment by edemaine** [comment]
[Description of Luma vs Luminance](https://en.wikipedia.org/wiki/Luma_(video)#Use_of_relative_luminance).  I guess Luma uses "gamma-compressed components" whereas Luminance uses raw R,G,B.  Note sure what this means without a gamma specification... maybe there's a default?  I certainly haven't noticed the conversion being bad, perhaps especially because the things we're comparing are generally grayscale.

I just ran a test on this very message:

![test](https://user-images.githubusercontent.com/2218736/27012664-239f8754-4ea2-11e7-9cbd-bc0d3a3339e5.png)

`-grayscale Rec709Luma` and `-colorspace Gray` (identical files):

![test1](https://user-images.githubusercontent.com/2218736/27012665-30ab379a-4ea2-11e7-88e6-a411d390a34f.png)

`-grayscale Rec709Luminance`:

![test2](https://user-images.githubusercontent.com/2218736/27012667-3752faec-4ea2-11e7-99a0-d743993d7fef.png)

In my browser, these look the same; but in Irfanview and `identify` I see a big difference: `Rec709Luminance` has a different colorspace (RGB) whereas others use sRGB, same as the original screenshot.  On my monitor, `Rec709Luminance` looks much darker (even in the grays which shouldn't be changing).  I have read that `Rec709Luma` deals with input colorspace better.

[Incidentally, with upgraded Docker, I now get `SyntaxError: Use of const in strict mode.` in `/KaTeX/dockers/texcmp/texcmp.js:5`.]
