### ISSUE TITLE
Font sizing commands

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#709]
Here is a simple test illustrating two bugs in `\normalsize`:

`\text{a}, \text{\normalsize a}, \frac{\text{a}}{\text{\normalsize a}}`

![aaa](https://cloud.githubusercontent.com/assets/2218736/26109438/9962b6a8-3a1d-11e7-97a1-67977937c459.png)

First, there's a space before `a` in `\text{\normalsize a}` (in the denominator).  Second, the size isn't actually changed!  Here's how it's supposed to render, in LaTeX: (note larger `a` in denominator)

![aaa](https://cloud.githubusercontent.com/assets/2218736/26109660/f9635184-3a1d-11e7-9032-50bc3ef23db0.png)

I'm worried that I don't understand how sizing nodes are meant to behave in KaTeX.  This comment worries me a little:

```javascript
groupTypes.sizing = function(group, options) {
    // Handle sizing operators like \Huge. Real TeX doesn't actually allow
    // these functions inside of math expressions, so we do some special
    // handling.
```

How are sizing commands supposed to work in math mode in KaTeX, given that they don't work in LaTeX?  In any case, the way they're working in text mode doesn't match LaTeX, so that's presumably a bug.

**Comment by kohler** [comment]
Font size in KaTeX is controlled by two kinds of CSS class, explicit sizing classes like .size5 and styling classes like .scriptstyle. The “sizing” code thinks that resetting the size class suffices to get a desired size. It doesn't suffice because a surrounding span might have a style class.

**Comment by kohler** [comment]
See #719 for a fix.

**Comment by kevinbarabash** [comment]
Closing since #719 has been merged.
