### ISSUE TITLE
Multiple powers not printed very clearly

### ISSUE THREAD

**Issue by hermanbergwerf** [Khan/KaTeX#711]
I am not sure how this is printed in the reference implementation (not sure what to look at), but `{10^{10}}^{100}` is not displayed in a way that I find particularly readable. Below are the output of KaTeX and the rendering engine used by LyX:

| KaTeX | LyX |
| --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/4458965/26313130/280c3a5a-3f0a-11e7-9c0d-c91cef5a205a.png) | ![image](https://cloud.githubusercontent.com/assets/4458965/26313112/1f72695a-3f0a-11e7-9f6d-b2f62014e5ee.png) |

**Comment by edemaine** [comment]
Our reference is LaTeX, which seems to do the more natural vertical spacing but match the font sizes of KaTeX (which makes sense):

![10](https://cloud.githubusercontent.com/assets/2218736/26318798/620c06ec-3eea-11e7-8c57-ac0cb0ac1cf7.png)

So the vertical layout definitely seems like a bug.

**Comment by hermanbergwerf** [comment]
I noticed `10^{10^{100}}` is fine. Perhaps my TeX is wrong. Or the way certain styles are applied are wrong (not sure what the expected output is supposed to be.
