### ISSUE TITLE
Subscript in braces doesn't work.

### ISSUE THREAD

**Issue by piojanu** [Khan/KaTeX#713]
Hi!

There is problem with rendering subscripts in braces.
$$R_{t} = r_t$$ this will work, but when you add braces to second variable it won't: $$R_{t} = r_{t}$$.
![image](https://cloud.githubusercontent.com/assets/23562932/26469248/9398a646-4199-11e7-8992-a38fd946b519.png)
I use KaTeX in Remark with auto math rendering. With MathJax it works properly (EDIT: Strange but i MathJax works only in inline but not in block. In KaTeX doesn't work at all.).

Thanks,
PJ

**Comment by piojanu** [comment]
Sorry my bad. It's bug in Remark.

**Comment by edemaine** [comment]
Yeah, `_blah_` is getting inverted into italics, so the two `_`s in your expression cause trouble.
