### ISSUE TITLE
Matrix rendering

### ISSUE THREAD

**Issue by autarkaw** [Khan/KaTeX#714]
Hello:
I am trying to use katex to show a matrix thru a js file called by an HTML file.  It gives me an error right at the "var equation" line
Uncaught Error: KaTeX parse error: Unexpected character: '' at position 0: ̲egin{bmatrix}

THIS IS THE JS FILE
var equation = katex.renderToString("\begin{bmatrix} a & b \\ c & d \end{bmatrix}");
document.write("Equation is  "+equation);

THIS IS THE HTML FILE
<!DOCTYPE html>
<html>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js"></script>
<script src="matrixcheckv05.js">
</script>
</html>

The two files are at http://www.eng.usf.edu/~kaw/katexdemo/ 
What am I doing wrong?
Best Wishes
Autar

**Comment by edemaine** [comment]
You need to escape your backslashes in JavaScript, like so:

```javascript
var equation = katex.renderToString("\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}");
document.write("Equation is "+equation);
```

`\b` expands to the bell character, `\x02`.

**Comment by autarkaw** [comment]
Thank you for your quick response.  It worked.
