### ISSUE TITLE
The componenents of formula cut each other under High Contrast mode in Windows [and Solution]

### ISSUE THREAD

**Issue by GeeLaw** [Khan/KaTeX#716]
Environment: Windows 10.

## Reproduction Step

1. Go to [KaTeX demo page](https://khan.github.io/KaTeX);
2. Type `f(x) = \int_{-\infty}^\infty\hat f(\xi)\,e^{2 \pi i \xi x} \,d\xi`, which is actually the default formula;
3. Turn on High Contrast and observe.

I am using my own High Contrast scheme. The result is that some parts of the formula are cut by other parts. As seen below:

![Example](https://cloud.githubusercontent.com/assets/4462444/26514603/12dbebf0-4273-11e7-80e1-b8a99ca19361.png)

## Cause

Under High Contrast mode, it is assumed that any background graphics should be removed.* Especially those with transparency or gradient that might reduce visual recognisability. Elements KaTeX uses to build the formula has `transparent` background set and as a result, they are restored back to the scheme-defined background colour.

\* There is a longer story regarding background images. Windows is now smart enough not to remove some images so that the widely used technique to display an image without `img`, without setting appropriate properties in CSS, will still work under High Contrast mode.

## Solution

The solution is simple. We just need to disable this adjust. To do this, add the following rule to CSS:

```css
.katex * { -ms-high-contrast-adjust: none !important; }
```

This disables resetting the background. Note that using this rule will still let `.katex` change its `color` and `background` according to the scheme, which is expected and desired. It can be seen that with the rule added, the formula is now readable.

![Repairment](https://cloud.githubusercontent.com/assets/4462444/26514673/947b2356-4273-11e7-8e71-35b501eea065.png)

## Finally…

I am just too lazy to make a pull request or anything. Please help yourself :-)

**Comment by edemaine** [comment]
Thanks for the report plus solution! I have Windows 10 so will give this a try to confirm, then turn it into a PR.

**Comment by ronkok** [comment]
This is terrific. It fixes an Edge problem I have had in PR #670, where I use `background: linear-gradient` to draw the lines for `\cancel`, `\bcancel`, and `\xcancel`. Thank you for this information.

**Comment by edemaine** [comment]
Just confirmed.  I found that it was enough to add the rule

```css
.katex * { -ms-high-contrast-adjust: none !important; }
```

because [according to the documentation](https://msdn.microsoft.com/en-us/library/hh771863(v=vs.85).aspx) the property is inherited.

PR now available as #724.

**Comment by GeeLaw** [comment]
That's the other point I mentioned earlier:

> This disables resetting the background. Note that using this rule will still let `.katex` change its color and background according to the scheme, which is expected and desired. It can be seen that with the rule added, the formula is now readable.

When there is an unremoved image under the formula, the formula will **not** have background added to it, resulting less contrasted text (text-on-image, instead of text-on-background + textbox-on-image).

Imagine a title with hero image that looks like this under non-High Contrast theme:

![image](https://user-images.githubusercontent.com/4462444/27194400-bbfd4c30-5202-11e7-88e7-6b7e2d3e671a.png)

The background is a hero image, therefore might well be kept for branding reason. The expected rendering under High Contrast White is

![image](https://user-images.githubusercontent.com/4462444/27194449-e0e7cd4a-5202-11e7-9a8d-3dae0c54d57a.png)

But if we set `.katex { -ms-high-contrast-adjust: none !important; }`, that will look like

![image](https://user-images.githubusercontent.com/4462444/27194475-f84c8ee4-5202-11e7-84f6-cab5b21f4b83.png)

**Note** If the `color: white` is set on the element (or on a selector that selects the element), it will not be adjusted to black, but `color` is often inherited from ancestors, therefore disabling adjusting on this element does not prevent it from inheriting the scheme value. That is also why disabling adjusting on descendants of `.katex` does not prevent it from having the scheme-defined foreground color -- they are inherited from `.katex`, which *is* adjusted.

*Semantically*, things that need transparent background are those components of the formula, and the formula itself requires background adjusting, therefore I have suggested and still suggests this way:

```css
.katex * { -ms-high-contrast-adjust: none !important; }
```

**Comment by edemaine** [comment]
Thanks for your expertise and explanation here.  I made another PR (#733) to fix this in the way you originally intended -- sorry for missing the subtlety before.  The rule looks slightly different in Less, but I checked that it compiles to this CSS:

```css
.katex * {
  -ms-high-contrast-adjust: none !important;
}
```
