### ISSUE TITLE
Font size not changing

### ISSUE THREAD

**Issue by shanuvshaji** [Khan/KaTeX#721]
Error Log-

E/AndroidProtocolHandler: Unable to open asset URL: file:///android_asset/themes/style.css

**Comment by edemaine** [comment]
It sounds like your browser is having trouble loading the KaTeX CSS?  Are you developing an Android app?  I don't have experience with bundled assets, but it sounds like your problem is there somewhere, and not specific to KaTeX.

**Comment by edemaine** [comment]
I'm closing this for now, but if you provide more information about how you're using KaTeX, we'd be happy to consider more.
