### ISSUE TITLE
Bad font while using \frac and inline mode i.e writing math inside \(   \) .

### ISSUE THREAD

**Issue by nitishkumarnitc** [Khan/KaTeX#723]
Font goes very small when I use fraction, for example -
```
    If \(\frac{z_2}{z_1}\) is imaginary, then \(\begin{vmatrix} \frac{2z_1+3z_2}{2z_1-3z_2} \end{vmatrix}\) is.
```
Is it possible to make it look good.

**Comment by edemaine** [comment]
If you want to make the text within your fractions bigger / the usual size, you'll want to switch `\frac` to `\dfrac`, or put `\displaystyle` after each `\(`.  This behavior is the same as LaTeX.

**Comment by nitishkumarnitc** [comment]
Thank you @edemaine .

**Comment by edemaine** [comment]
Happy to help.  (Dynamic programming FTW!)
