### ISSUE TITLE
\mathop{x} should center single-character x

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#726]
`\mathop` is a TeX feature, and it has some subtlety in its implementation described in [Documentation of \mathop](https://tex.stackexchange.com/questions/368673/documentation-of-mathop/368700).

Specifically, when the argument to `\mathop` is a single character, it should get centered vertically.  Perhaps this could be implemented by tweaking buildHTML's `groupTypes.mclass` (when `group.value.mclass === 'mop'`), e.g. using the in-process `\raisebox` implementation (#685).

It's a minor bug, but comes up in defining custom symbols such as #657.

**Comment by ronkok** [comment]
I believe this would work:
````
groupTypes.mclass = function(group, options) {
    if (isCharacterBox(group.value.body) && group.value.mclass === "mrel") {
        let node = buildGroup(group.value.body, options);
        const shift = ((node.height + node.depth) / 2) - node.depth -
            options.style.metrics.axisHeight;
        node = buildCommon.makeVList([
            {type: "elem", elem: node},
        ], "shift", shift, options);
        return makeSpan([group.value.mclass], [node], options);
    } else {
        const elements = buildExpression(group.value.value, options, true);
        return makeSpan([group.value.mclass], elements, options);
    }
};
````

given a tweak in `functions.js`:
````
// Math class commands except \mathop
defineFunction([
    "\\mathord", "\\mathbin", "\\mathrel", "\\mathopen",
    "\\mathclose", "\\mathpunct", "\\mathinner",
], {
    numArgs: 1,
}, function(context, args) {
    const body = args[0];
    return {
        type: "mclass",
        mclass: "m" + context.funcName.substr(5),
        value: ordargument(body),
        body: body,
    };
});
````

**Comment by edemaine** [comment]
Thanks @ronkok!  I went to try this, but then realized (a) I wrote that `groupTypes.mclass` is relevant when in fact `\mathop` compiles to `groupTypes.op`, and reasonably given this error, (b) you misinterpreted `\mathrel` as the relevant command instead of `\mathop`.  I'm not aware of vertical magic in `\mathrel` (please correct me if I'm wrong).  The code in `groupTypes.op` is quite a bit more complicated, and appears to already be trying to do some vertical magic.  If you can make sense of it, I'd appreciate what you think ought to work in that case...
