### ISSUE TITLE
Manual vertical spacing in arrays is off

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#728]
Consider the following example, which renders essentially correctly:
```latex
=\begin{pmatrix}
    \frac{1}{5} & \frac{5}{12} & \frac{7}{20} \\
    \frac{1}{5} & \frac{1}{6} & \frac{1}{10} \\
    \frac{1}{5} & -\frac{1}{6} & \frac{1}{10}
  \end{pmatrix}
```
KaTeX:
![pmatrix1](https://user-images.githubusercontent.com/2218736/27006740-53cacd32-4e0a-11e7-8e3e-69cbae483f02.png)
LaTeX:
![pmatrix](https://user-images.githubusercontent.com/2218736/27006737-3a460e76-4e0a-11e7-819a-8b2db095d845.png)

Now I go to tweak the vertical spacing.  But the added vertical spacing in KaTeX is much smaller than I ask for:

```latex
=\begin{pmatrix}
    \frac{1}{5} & \frac{5}{12} & \frac{7}{20} \\[0.5em]
    \frac{1}{5} & \frac{1}{6} & \frac{1}{10} \\[1em]
    \frac{1}{5} & -\frac{1}{6} & \frac{1}{10}
  \end{pmatrix}
```

KaTeX:
![pmatrix2](https://user-images.githubusercontent.com/2218736/27006739-3c96ad98-4e0a-11e7-9b7c-f68cf3ea93ae.png)
LaTeX:
![pmatrixx](https://user-images.githubusercontent.com/2218736/27006762-cc029f3c-4e0a-11e7-8e87-de4169ff98fc.png)

Inspection of the HTML confirms that the first gap increases by less than 0.1em, despite the request for 0.5em.

I know why this is happening and I think I know how to fix it.  But I don't understand why LaTeX doesn't behave the same way.

[lttab.dtx](http://tug.ctan.org/macros/latex/base/lttab.dtx) defines `\\` as follows:

```latex
\def\@argtabularcr[#1]{%
  \ifnum0=`{\fi}%
    \ifdim #1>\z@
      \unskip\@xargarraycr{#1}%
    \else
      \@yargarraycr{#1}%
    \fi}
\def\@xargarraycr#1{\@tempdima #1\advance\@tempdima \dp \@arstrutbox
   \vrule \@height\z@ \@depth\@tempdima \@width\z@ \cr}
\def\@yargarraycr#1{\cr\noalign{\vskip #1}}
```

This seems to be implemented fairly faithfully in KaTeX [in buildHTML.js](https://github.com/Khan/KaTeX/blob/master/src/buildHTML.js#L627-L649).  When the specified optional gap is positive, instead of vskipping by that amount, we create a strut that's as deep as a regular line plus the requested gap.  When you have extra-deep cell contents like a `\frac`, this should not create a gap as large as the requested gap.  This seems to be what the code is doing, and it's what KaTeX does... yet it's not what LaTeX does.  Am I misreading the LaTeX source somehow?

**Comment by ronkok** [comment]
This may no longer be an issue. The KaTeX rendering now looks like LaTeX.
![arrayspacing](https://user-images.githubusercontent.com/16403058/29945301-839f2a68-8e55-11e7-8999-18c29048b047.PNG)

**Comment by edemaine** [comment]
Agreed -- great news!  Must have been from those `makeVList` changes.  Thanks for spotting.
