### ISSUE TITLE
Same MathFormula syntax show differently in ios and android while using same katex .

### ISSUE THREAD

**Issue by ParveshChauhan** [Khan/KaTeX#738]
I am using katex for my app in both platform(ios and android) ,so the formula show differently .In ios it appears properly (syntax is $(\\frac{21}{10})$ ) but this is not working in android .Same this syntax( "\\(\\frac{1}{2}\\)") is working in android but not in ios.

**Comment by edemaine** [comment]
Can you post screenshots? Are you using an app or the browser? If an app, can you try a browser?

**Comment by ParveshChauhan** [comment]
I am using app which runs on both platforms(ios and android) and connected to same backend server and app getting data in form of JSON. Different syntax supported on both platforms as i explained in question. And according to my app structure, i use webView for rendering Katex syntax. I am attaching screenShots.

![android](https://user-images.githubusercontent.com/27333048/27418785-09b1be2e-573b-11e7-8a8b-070e5705182f.png)

![iphone](https://user-images.githubusercontent.com/27333048/27419064-7978a0a0-573c-11e7-9e3f-bd4ff872ff7f.PNG)

**Comment by kevinbarabash** [comment]
@ParveshChauhan check out https://github.com/lingarajsankaravelu/Katex for an example of how to use KaTeX with an Android webview.

**Comment by ParveshChauhan** [comment]
@kevinbarabash Thanks for reply but actually I need help in ios because in Android I have done already. I am facing problem in ios for same syntax, In above I am showing that Katex syntax works in one and for same syntax not in another.

**Comment by kevinbarabash** [comment]
I'm confused.  The iOS screenshot looks like it's rendering correctly.

**Comment by ParveshChauhan** [comment]
ya its render correctly but not for syntax( "\\(\\frac{1}{2}\\)") which is working fine in android.

**Comment by ParveshChauhan** [comment]
And one more question, why it is not supporting this symbol (÷ ,> ,<)

**Comment by edemaine** [comment]
One thing I see is that, on iOS, you're getting two backslashes (`\\frac`).  This is likely incorrect; it would need to be `\frac` to render correctly.  So maybe the JSON is getting extra escapes in iOS but not Android...

Anyway, we can't really see anything from this level of detail.  You'll need to get into the Webview's JavaScript console and include any KaTeX-related error messages for us to know what's going on.

Regarding symbols: you need to use a LaTeX command, namely `\div`, to produce ÷.  We do hope to support direct Unicode symbols at some point (there are many issues and PRs related to this), but not yet.  `<` and `>` should work, but likely HTML is getting in the way of that.  You can always use `\lt` and `\gt` to get around that.

**Comment by ParveshChauhan** [comment]
Thanks

**Comment by edemaine** [comment]
Feel free to reopen the issue if this didn't fix your problems (and you can provide more information like console logs).

**Comment by ParveshChauhan** [comment]
thanks for your help, only one issue remain that how to wrap the content in katex view.

**Comment by edemaine** [comment]
Sorry, what do you mean?

**Comment by ParveshChauhan** [comment]
![img_0482](https://user-images.githubusercontent.com/27333048/27648771-3d9db456-5c4d-11e7-8eaf-c05856444a50.PNG)


The text in top red area is not wrap means not fit in view although i specify the width and height of view. I use methods like aWebView.scalesPageToFit = YES; and Scaling methods but it not works for me. Please tell me any method to wrap content inside view.

**Comment by edemaine** [comment]
KaTeX does not support wrapping of formulas.  See #327 for the issue and some workarounds.  In your case, I would suggest splitting the text into multiple formulas, as most of your content is text, not math.

**Comment by ParveshChauhan** [comment]
not supporting HTML tags.
