### ISSUE TITLE
Server side rendering 

### ISSUE THREAD

**Issue by nitishkumarnitc** [Khan/KaTeX#758]
I have some math expression like 
$string=If \( \alpha \) and  \( \beta \) are different complex numbers with \(|\beta|=1,\) then \( \vert \dfrac{\beta-\alpha}{1-\bar\alpha\beta} \vert\) is equal to 
I want to get html for this (basically i want to store that).
I am doing $string=katex.renderToString($string). When i try to render $string I am not getting the proper result. I think their should be some way to pass the delimater.
Can somebody please help me in this? Thanks :)

**Comment by xymostech** [comment]
We have [an extension](https://github.com/Khan/KaTeX/tree/master/contrib/auto-render) which can handle rendering math inside of delimiters, but it currently only works on the client side. On the server side, you'll need to manually split up your string and `katex.renderToString()` the individual parts.

**Comment by edemaine** [comment]
This is a duplicate feature request of #604.  Definitely something I'd like to do, but haven't had a chance to do yet.  But there is some code linked there that you could try using as a basis.
