### ISSUE TITLE
Soften the edge of the diagonal lines in cancel

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#760]
http://jsfiddle.net/nuxcbqqq/26/

with antialiasing
<img width="401" alt="screen shot 2017-07-08 at 6 54 58 pm" src="https://user-images.githubusercontent.com/1044413/27989788-237b021c-640f-11e7-8791-634be4a29bfa.png">

without antialiasing
<img width="401" alt="screen shot 2017-07-08 at 6 55 55 pm" src="https://user-images.githubusercontent.com/1044413/27989791-37d2b232-640f-11e7-99ed-95260e413c67.png">

**Comment by kevinbarabash** [comment]
This is what's already being done.  I guess the difference is in the current code we have a hard edge vs. a soft one.

**Comment by kevinbarabash** [comment]
I've modified the `.cancel` styling in katex.less by subtracting/adding 0.5px to the leading and trailing edges of the cancel line.
```
.cancel {
    background:
        linear-gradient(to top left,
            rgba(0,0,0,0) 0%,
            rgba(0,0,0,0) ~"calc(50% - 0.04em - 0.5px)",
            rgba(0,0,0,1) ~"calc(50% - 0.04em)",
            rgba(0,0,0,1) ~"calc(50% + 0.04em)",
            rgba(0,0,0,0) ~"calc(50% + 0.04em + 0.5px)",
            rgba(0,0,0,0) 100%);
}
```
It seems to look good at a variety of font sizes (12px, 20px, 30px, 72px):
<img width="29" alt="screen shot 2017-07-08 at 7 15 04 pm" src="https://user-images.githubusercontent.com/1044413/27989866-ecbed6ba-6411-11e7-8048-5b43f17efc6d.png">
<img width="52" alt="screen shot 2017-07-08 at 7 15 12 pm" src="https://user-images.githubusercontent.com/1044413/27989868-f1c1a7be-6411-11e7-969f-20375cf3f020.png">
<img width="76" alt="screen shot 2017-07-08 at 7 15 18 pm" src="https://user-images.githubusercontent.com/1044413/27989869-f3b70a28-6411-11e7-8e32-955ccc898d4e.png">
<img width="162" alt="screen shot 2017-07-08 at 7 15 27 pm" src="https://user-images.githubusercontent.com/1044413/27989871-f673a97e-6411-11e7-9116-661a7dc9c119.png">

**Comment by ronkok** [comment]
Interesting. I made those `\cancel` lines nice and thick after preliminary work showed that thin lines looked like their edges were too blurry.  

The change proposed here looks good to me.

**Comment by sthoch** [comment]
Have you tested this on a variety of browsers? in a different project, we ran into problems with subpixel rendering in gradients that led to inconsistent behaviour.

**Comment by kevinbarabash** [comment]
@sthoch see the #761 for the results of testing.
