### ISSUE TITLE
static/main.js assumes attachEvent is supported if input events are not

### ISSUE THREAD

**Issue by hallvors** [Khan/KaTeX#771]
Hi, just a small issue that came up when I was testing using KaTeX with the PDF generator Prince XML. Here:
https://github.com/Khan/KaTeX/blob/master/static/main.js#L6
the code detects *input event* support using the reasonable shortcut of looking for an `oninput` property. However, it then proceeds to assume that `attachEvent()` is supported if oninput is not defined. The `attachEvent` method should be detected separately.

Thanks for a great script :)

**Comment by hallvors** [comment]
I hope you will accept this pull request however minor this issue might be: https://github.com/Khan/KaTeX/pull/772
Thanks for your attention.

**Comment by edemaine** [comment]
Could you clarify what sort of environment Prince XML is providing, and why `main.js` (usually only used for testing) is useful in your context?

Also, should the event handling of `permalink` be similarly protected?

**Comment by hallvors** [comment]
Prince XML supports much of the DOM but not everything. As its purpose is generating static PDFs from web pages and does not render pages to a user and handle user input it supports very few events. This fix is of course not Prince XML-specific as such, the issue will affect any legacy browser that does not support the input event and does not emulate IE's attachEvent method.

It is very useful to be able to run test suites / test pages of various libraries in Prince to check compatibility. I can work around this issue easily, but I thought I would suggest a fix anyway :).

You could apply the same fix to permalink listener setup, however you are definitely not the only script or page to assume attachEvent is supported if addEventListener isn't - there are millions of scripts out there and because of the compatibility pressure this assumption is considered pretty safe by now. 

Again, I know this is a very minor issue likely affecting very few people, so if you choose not to spend time on integrating and testing the fix I'll understand.

**Comment by edemaine** [comment]
Thanks for the background!  I guess I'm confused in your PR #772 why you change the handling of `input` in a way that's asymmetric to the way we handle `permalink`.

Does Prince XML support `addEventListener` just not `oninput`?  If so, it seems we should change `if ("oninput" in input) {` to `if ("addEventListener" in input) {` -- this makes more sense, and is symmetric with `permalink`.

On the other hand, if Prince XML supports neither `addEventListener` and `attachEvent` (which would make sense given that it's role is PDF export), then it seems we need to protect both calls to `attachEvent`, not just one.
