### ISSUE TITLE
Rendering the tex string `"\left(\dots\right)" leads to a error

### ISSUE THREAD

**Issue by navigium** [Khan/KaTeX#773]
I tried to render the tex string

```latex
"\left(\dots\right)"
```

which works perfectly fine in regular LaTeX implementations. In KaTeX I got the following error:

```
KaTeX parse error: Expected '\right', got '\dots' at position 7: \left(\̲d̲o̲t̲s̲\right)
```
I'm using KaTeX out of Ember but this shouldn't make a difference as my Ember component just passes the string to the `katex.render()` function:

```js
katex.render(tex, el, {
    displayMode: display
});
```

**Comment by navigium** [comment]
Oh, I just realized that `\dots` isn't supported by KaTeX. Feel free to close this issue unless you consider `\dots` not being supported an issue.

**Comment by edemaine** [comment]
Yep, already #528.  Please use `\cdots` or `\ldots` until `\dots` gets implemented (or define a macro for `\dots` -> `\ldots`, which is what I do personally for now).

**Comment by navigium** [comment]
Thank you for your fast reply. That's what I'll do then.
