### ISSUE TITLE
Add support for automatic rendering of tags

### ISSUE THREAD

**Issue by matthaywardwebdesign** [Khan/KaTeX#78]
Not sure whether this would be something that is needed, but I know I personally would use. 

We should add the ability to automatically render all math inside a `<math>` tag.

For example

`<math>y=x^{22}+4</math>`

Would be rendered and automatically replaced with the rendered string. 

I have this working and would be happy to submit a pull request provided that it is ok.

**Comment by cben** [comment]
Indeed, this is much simpler than finding all math between certain delimeters,
but already useful for output of various converters that can somehow mark math in the HTML.  However a bit more flexibility is needed than just a class name:

  - kramdown translates markdown with $$-delimited inline and display math into MathJax-compatible<script type="tex/math">...</script> or <script type="tex/math; mode=display">...</script>tags.  Example code: [Jekyll layout using KaTeX](https://github.com/cben/sandbox/blob/gh-pages/_layouts/katex.html) converts [this markdown](https://github.com/cben/sandbox/blob/gh-pages/katex.md) into [this](https://cben.github.io/sandbox/katex).
    `script` tags require katex output to be inserted alongside the script, whereas `span` or `div` tags should replace the original element.
  - `pandoc --mathjax` translates math into `<span class="math">\( ... \)</span>` and `<span class="math">\[ ... \]</span>`
  - `rst2html --math-output=mathjax` produces `<span class="math">\( ... \)</span>` and `<div class="math">\begin{equation*} ... \end{equation*}</div>`

**Comment by kevinb7** [comment]
@cben https://github.com/Khan/KaTeX/tree/master/contrib/auto-render searches for delimiters which can be specified so it should handle the use cases you've listed.
