### ISSUE TITLE
NOT Support HTML tags in my ios app

### ISSUE THREAD

**Issue by ParveshChauhan** [Khan/KaTeX#782]
I am using katex in my ios app and it failed to render HTML tags like `<small><i>` etc . When I try to render HTML tags it shows blank text view .

**Comment by kevinbarabash** [comment]
@ParveshChauhan can you provide some more details about what you're trying to do?  What HTML are you loading into the web view in your app?

**Comment by ParveshChauhan** [comment]
Like I want to display this <i>simplify: </i> so i use `<i>simplify: </i>` code but text view is empty ,shows nothing.

**Comment by kevinbarabash** [comment]
If the currency symbol is within the LaTeX code you're trying to render you will get an exception as we don't support this unicode symbol.  Check the console for errors.  You should see something like:
```
ParseError: KaTeX parse error: Expected 'EOF', got '₹' at position 1: ₹̲
```

**Comment by ParveshChauhan** [comment]
so what should i do for render symbol or it is possible or not and what about html tags ?

**Comment by kevinbarabash** [comment]
@ParveshChauhan I'm not sure what's happening with the HTML tags not displaying.  As for adding `₹` we'll need to find a font that contains the symbol and extra metrics for it.  What package(s) are you using to rendering this in LaTeX?

**Comment by ylemkimon** [comment]
HTML tags are not LaTeX, so it will not render if given to KaTeX. Also, we have an issue to track adding currency symbols like ₹ in https://github.com/KaTeX/katex-fonts/issues/18. Please feel free to ask or open new issue if you have any other questions.

**Comment by iOSharsh** [comment]
when i try this Html type of string  "<img src=\"http://latex
The Image is not showing and 
console response is  - 
    [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x600003cf7080> F8BB1C28-BAE8-11D6-9C31-00039315CD46
    [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed
    WF: === Starting WebFilter logging for process Example
    WF: _userSettingsForUser : (null)
    WF: _WebFilterIsActive returning: NO

Please Help What i'm doing Wrong

**Comment by edemaine** [comment]
@iOSharsh That doesn't sound like a KaTeX issue.  Also, if you find an issue with KaTeX, please open a new issue with a complete example.

**Comment by iOSharsh** [comment]
@edemaine 
okay but can i explain my issues here?

**Comment by edemaine** [comment]
@iOSharsh You'd be better off posting in a help forum specific to iOS development (or wherever the issue might be). Perhaps StackOverflow?

**Comment by iOSharsh** [comment]
Hey @edemaine 
please Check is it Your's Example 
https://github.com/ratala1/KaTeX-MathView-Swift
i'm using this swift File
