### ISSUE TITLE
add a CHANGELOG.md

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#785]
- backfill with PR titles from previous releases
- require new PRs add an entry to CHANGELOG.md (add something in CONTRIBUTING.md)

**Comment by mbourne** [comment]
(Not sure where to put this comment...)

On this page, https://github.com/Khan/KaTeX/releases/tag/v0.8.1 the link in your comment correctly points to v0.8.0, but the anchor text says v0.8.1. It would reduce confusion if fixed.

**Comment by kevinbarabash** [comment]
@mbourne thanks.  I've fixed it now.

**Comment by kevinbarabash** [comment]
I'm going to close this since the release notes in GitHub already provide this info.
