### ISSUE TITLE
Options.js Module parse failed

### ISSUE THREAD

**Issue by freemaths** [Khan/KaTeX#797]
Getting the following error when trying to use 0.8.1 with React (katex@0.7.1 works fine)

./node_modules/katex/src/Options.js
Module parse failed: \node_modules\katex\src\Options.js Unexpected token (203:20)
You may need an appropriate loader to handle this file type.
|      * TODO(emily): Remove this when we have real macros
|      */
|     static colorMap = {
|         "katex-blue": "#6495ed",
|         "katex-orange": "#ffa500",

**Comment by edemaine** [comment]
This should be fixed with 0.8.2.  (@kevinbarash, more motivation)  Meanwhile, you should be able to `require("katex/build/katex.js")`

**Comment by kevinbarabash** [comment]
I'll publish 0.8.2 this evening.

**Comment by kevinbarabash** [comment]
This should be fixed now with the release of [0.8.2](https://github.com/Khan/KaTeX/releases/tag/v0.8.2).
