### ISSUE TITLE
Stretchy elements with colors are invisible with server-side rendering

### ISSUE THREAD

**Issue by glebm** [Khan/KaTeX#798]
Broken on both v0.8.1 and v0.8.2. 
```
\color{red}{\overbrace{x+y}}
```

![overbrace-red](https://user-images.githubusercontent.com/216339/29400055-9afe2390-8323-11e7-935f-2ab6d2146c60.png)

The `.stretchy` element gets `color: red` but not ` background-color: red`.

I have a live demo of server-side rendering running at [thredded.org](https://thredded.org) (v0.8.2 via [katex-ruby](https://github.com/glebm/katex-ruby)).

@ronkok

**Comment by edemaine** [comment]
Same problem also with `\textcolor`?

**Comment by glebm** [comment]
Yes

**Comment by glebm** [comment]
Perhaps this line only works client-side:

https://github.com/Khan/KaTeX/blob/d01c73c312856e07caed9392c34b97ade1958421/src/stretchy.js#L146

**Comment by edemaine** [comment]
![overbrace](https://user-images.githubusercontent.com/2218736/29416007-ce1b6bca-8332-11e7-9b4f-5bff5617158e.png)

Seems to work fine on the demo (which is probably running 0.8.1).  Perhaps you're having trouble fetching the `.svg` files?  Perhaps check out Network logging in your browser?

**Comment by kevinbarabash** [comment]
@glebm could you link to a page that shows the bug in action?

**Comment by edemaine** [comment]
FWIW, I tested on my own server which does server-side rendering, and it worked fine.

**Comment by ronkok** [comment]
That's it. I've had it. I'm starting work this minute on moving stretchy elements SVGs from external files to inline code.

**Comment by glebm** [comment]
Sorry, I'll look into it and post an update here. Might be a problem with my setup.

**Comment by ronkok** [comment]
I expect that this issue is now resolved, since all stretchy elements are inline.

**Comment by kevinbarabash** [comment]
@glebm this should be fixed with the release of [v0.8.3](https://github.com/Khan/KaTeX/releases/tag/v0.8.3).  Please reopen if the new version doesn't solve this issue.

**Comment by glebm** [comment]
The previous issue was caused entirely by me forgetting to whitelist `background-color` in the HTML sanitizer. v0.8.3 works as well.
