### ISSUE TITLE
make Options less confusing

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#804]
Currently, `options` can be passed to top-level `katex` methods.  These `options` are a plain old js object.  These are used to create a `Settings` objects.  Later, `buildTree` creates an `Options` object which is passed around as the HTML and MathML trees are generated from the parse tree.  `Options` feels similar to a rendering context like an HTML Canvas context with font (family), (font) size, color, etc.  I'd like to suggest renaming `Options` to `TypesettingContext` or just `Context` for short.

**Comment by edemaine** [comment]
I like the idea of `Context`, but beware that `functions.js` uses the term "context" for something else entirely... though potentially that could change.

I've never quite understood why we convert `options` into a `Settings` object.  We could just do `settings.whatever || defaultSettings.whatever` whenever checking a setting, and rename `options` to `settings`.  But perhaps that's an unpreferred style.

**Comment by kevinbarabash** [comment]
Good point about having two contexts.  I'll need to think some more about how we could differentiate them.  Changing `options` to `settings` though would be a good start.

**Comment by kevinbarabash** [comment]
Closing in favor of #873.
