### ISSUE TITLE
switch to webpack-dev-server for server.js

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#805]
Right now we build katex.js on each page load.  On my machine this can take from 20 to 40 seconds.  With webpack-dev-server, the server would build the bundle on file change instead of whenever the browser is reloaded.  It also opens the possibility of hot module reloading.

**Comment by edemaine** [comment]
Sounds great!  I've noticed the slowness of this lately when testing.

**Comment by rrandallcainc** [comment]
I'd be happy to take a stab at this for you.

**Comment by rrandallcainc** [comment]
Solved by: https://github.com/Khan/KaTeX/pull/902
