### ISSUE TITLE
KaTeX github organization

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#811]
After recent discussions of creating a new repo dedicated to font creation, https://github.com/Khan/KaTeX/pull/632#issuecomment-323603003, I decided to create a github organization for [KaTeX](https://github.com/KaTeX).

I was thinking we would start out with the following repos:
- KaTeX.github.io (public website)
- KaTeX (main project repo)
- KaTeX-fonts (a stripped down version of https://github.com/Khan/MathJax-dev that only contains what we need to generate our fonts along with the MathJaxFonts docker from KaTeX)

To get started we'd do the following:
- transfer ownership of this repo and https://github.com/Khan/MathJax-dev to the KaTeX org
- invite all current contributors with push access to the KaTeX org
- create new repos above as needed

This is kind of a big deal so I'd love to get everyone's thoughts and concerns before proceeding further.

**Comment by edemaine** [comment]
I'm still new to Github organizations, but this sounds fine to me.  I take it that all issues etc. get preserved by the move, which is nice.  The main change is that the git repo changes URL?  A potential worry is that someone has KaTeX's git link hard-coded (e.g. via NPM -- though not sure if this works), and they need to update.  But that's the price of living on the bleeding edge, I suppose...

**Comment by kevinbarabash** [comment]
All of the issues will be preserved with the move.  We'll probably want to create a `Khan/KaTeX` fork from `KaTeX/KaTeX` after the move that way if someone does have something hardcoded it will still work.  We should probably have a message that top of the `Khan/KaTeX` README.md pointing people to `KaTeX/KaTeX`.  There is link from https://www.npmjs.com/package/katex to `Khan/KaTeX` but we should be able to update that.  We'll need to update gitter as well.

**Comment by edemaine** [comment]
Nice idea to fork/link.  The NPM link comes from `package.js`, so if we update that and do another `npm publish` (presumably part of the release script), then we'll be all set.

**Comment by xsznix** [comment]
Based on previous experience, the fork/link shouldn't actually be necessary because GH automatically redirects old repo URLs to the new one: https://help.github.com/articles/about-repository-transfers/

**Comment by kevinbarabash** [comment]
Update: we now have https://github.com/KaTeX.  The main repo will continue to live at Khan/KaTeX for the time being though.

**Comment by kevinbarabash** [comment]
This repo has been transferred to the `KaTeX` Github organization.

**Comment by ylemkimon** [comment]
@kevinbarabash I'm excited to see the new organization is in action!

It seems a Gitter chat room should be manually created and Greenkeeper may not work.

**Comment by kevinbarabash** [comment]
We'll also have to update the badges in the README.
