### ISSUE TITLE
Support for Chinese punctuation marks in \text{}

### ISSUE THREAD

**Issue by zhzhzoo** [Khan/KaTeX#812]
Hello everybody, I'm using KaTeX and discovered that it doesn't support Chinese punctuation marks in \text{}. For example, rendering `\text{，}` raises "KaTeX parse error: Expected '}', got '，' at position 7". In China we use '。' for period, '？' for question mark, '！' for exclamation mark, '，' for comma, '、' for dun hao, '；' for semicolon, '：' for colon, '‘’“”' for quotation marks (seems already supported), '（）［ ］〔〕【】' for parentheses, '——' for dash, '……' for ellipsis, '《》〈〉' to indicate book titles. ([General rules for punctuation](http://www.moe.edu.cn/ewebeditor/uploadfile/2012/06/01/20120601102833791.pdf)) Could you help supporting Chinese punctuation marks in \text{}? Thank you very much!

**Comment by edemaine** [comment]
Thanks @zhzhzoo for the detailed request!  This looks relatively easy to do, mostly by changing some regexes.  PR #814 should do it.
