### ISSUE TITLE
Move fonts to a separate repo

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#816]
As discussed in #632, we'd like to move fonts to their own separate repo so that we can keep the size of this repo small.

TODO:
- [x] create separate repo for the fonts
- [x] add that repo as a submodule

**Comment by mbourne** [comment]
This probably doesn't matter any more, but I believe the eot syntax for old IE versions is not quite right. It currently is (e.g.):

`src:url(fonts/KaTeX_AMS-Regular.eot#iefix) format('embedded-opentype')`

However, the "iefix" should actually involve a query string (anything after that doesn't really matter), and would be better as:

`src: url(/includes/cssjs/katex/fonts/KaTeX_AMS-Regular.eot?#iefix) format('embedded-opentype')`

See the following for why: http://blog.fontspring.com/2011/02/the-new-bulletproof-font-face-syntax/

**Comment by kevinbarabash** [comment]
I've created a new repo for our fonts at https://github.com/KaTeX/katex-fonts.
