### ISSUE TITLE
Extensible Arrows \xleftharpoondown pointing the wrong way

### ISSUE THREAD

**Issue by jasonsperske** [Khan/KaTeX#822]
It appears that the https://unpkg.com/katex@0.8.2/dist/images/leftharpoondown.svg points to the right and not left as it's name/TeX alias/Up Equivalent would suggest that it should.  The Left facing half arrow (\xleftharpoonup) has the correct orientation (https://unpkg.com/katex@0.8.2/dist/images/leftharpoon.svg).

**Comment by jasonsperske** [comment]
Here is an example of the unicode (`U+21BD`) http://www.unicode.org/charts/PDF/U2190.pdf which is officially called "LEFTWARDS HARPOON WITH BARB DOWNWARDS"

**Comment by kevinbarabash** [comment]
@jasonsperske this will be fixed by #819.

**Comment by kevinbarabash** [comment]
Fixed in [v0.8.3](https://github.com/Khan/KaTeX/releases/tag/v0.8.3).
