### ISSUE TITLE
Color regex seems too permissive

### ISSUE THREAD

**Issue by marcianx** [Khan/KaTeX#825]
I noticed in `Parser#parseColorGroup()`
https://github.com/Khan/KaTeX/blob/2fbb2b0128f062f6627581d250977a6ff9604964/src/Parser.js?utf8=%E2%9C%93#L776
that the color regex is defined as
`/^(#[a-z0-9]+|[a-z]+)$/i`
which seems too permissive for HTML hex colors. To test, I tried invalid colors like `#aar` and `#aaaa` on the main site's [test playground](https://khan.github.io/KaTeX/) and the parser accepted them, but didn't colorize the content in any way. Perhaps the regex should be changed to
`/^(#[a-f0-9]{3}|#[a-f0-9]{6}|[a-z]+)$/i`
to require hex digits (0-9a-f) and the correct number of them (3 or 6).

This change would be backward incompatible, of course, rejecting invalid colors that were silently accepted but ignored on conversion to MathML before.

**Comment by kevinbarabash** [comment]
@marcianx nice find.  If you have time, a PR for this would definitely be welcome.  As for this being a backwards incompatible change, we can bump the version to v0.9.0 the next time we publish.

**Comment by marcianx** [comment]
Sure. Just checked, and my company already has CLA with Khan Academy. I'll send a fix when I have the chance.

**Comment by marcianx** [comment]
@kevinbarabash How do I resolve the khanbot asking for a CLA? My company (Google) already has a corporate-wide CLA IIUC, and it doesn't seem to make sense for me to sign a new one.

**Comment by kevinbarabash** [comment]
@marcianx that's a really good question.  Your github profile clearly shows that you're a Google employee.  I guess khanbot needs an upgrade.  It should be possible to check a github profile against the corporate signatures we have.  In the meantime, I'm going to ignore khanbot b/c I've verify that you do indeed work for Google.

**Comment by marcianx** [comment]
Well, that might have to do with having no way for it to verify that I work for where my profile claims I do (honestly, I only just added that to my profile today and just for this PR). Perhaps testing that my corp email specified in the PR actually functions might be a more reliable way to confirm.
