### ISSUE TITLE
\! results in extra root element width

### ISSUE THREAD

**Issue by dennisss** [Khan/KaTeX#836]
When rendering `\$10,\!000,\!000,\!000,\!000`, I expect it to show up with a tight horizontal spacing between the commas and zeros. This works fine, but the root element shows up with extra width (note the blank space in the right side of the blue bounding box below). So, when rendering it inline with text after it, there is extra space between the text and the math. This shows up without the extra space in MathJax

Browser: Chrome, Mac OS X

<img width="804" alt="screen shot 2017-08-31 at 3 33 29 pm" src="https://user-images.githubusercontent.com/1341104/29942627-9235beca-8e64-11e7-8108-4f78cce77d8a.png">

**Comment by kevinbarabash** [comment]
@dennisss I can't reproduce this on https://khan.github.io/KaTeX/.  What version are you using?

**Comment by dennisss** [comment]
@kevinbarabash I'm on Chrome 60.0.3112.113 (the latest version as of now), and the screenshot is from the currently served copy of https://khan.github.io/KaTeX/. It seems to work on Firefox, so possibly isolated to only Chrome.

**Comment by kevinbarabash** [comment]
@dennisss my bad.  I was selecting things using the selection cursor in the browser window instead of using the inspector to select the DOM element.  Yes, I'm seeing this behavior too.

**Comment by edemaine** [comment]
`\fbox{\$10,\!000,\!000,\!000,\!000}` further confirms this.  Time to read up on `width: auto` rules, I guess...

**Comment by kohler** [comment]
“1\!2” is rendered as `<span.mord>1</span><span.mord><span.mspace></span><span.mord>2</span></span>`.

Giving the second top-level `<span.mord>` `display:inline-block`, instead of `display:inline`, solves the problem.

**Comment by edemaine** [comment]
Confirmed. Nice solution @kohler. Given that we currently forbid line breaks in KaTeX renderings, is there any reason not to make all `span.mord`s into `display:inline-block` (same as `span.mspace`)?  Apparently the main difference between `inline` and `inline-block` is that the latter "can have a defined width" which I'm guessing is what's making this work (behaving correctly with negative-width children).

**Comment by kohler** [comment]
I found a much simpler fix.

**Comment by kohler** [comment]
I was wrong about the simple fix. It would be nice to default all katex spans to `inline-block` but this breaks accents.

**Comment by kohler** [comment]
I think the bug might be in Chrome—or at least there is a bug in Chrome. Even a targeted inline-block fix breaks several tests, including the Mod test, and I can't figure out why (meaning I can visually tell the difference but can't see why Chrome would treat `\bmod` differently in an array cell).

**Comment by edemaine** [comment]
FWIW, this bug affects `$x \bmod y$` too (because `\bmod` produces a negative medium space... not quite sure why).

**Comment by ronkok** [comment]
For the specific case of: `\fbox{\$10,\!000,\!000,\!000,\!000}`, I can eliminate the problem by applying `width: min-content;` to CSS class `.boxpad`, which selects the parent element of that string.

Edge and IE don't support `width: min-content;`. Edge doesn't need it in this case. It renders the box just fine with or without that rule. I haven't checked IE.

I'm booked up for the next few days, but if someone wanted to fix this issue, they could probably do so by applying `width: min-content;` to the various KaTeX container classes.

**Comment by edemaine** [comment]
I reported this bug, which seems to be Chrome specific, to [bugs.chromium.org](https://bugs.chromium.org/p/chromium/issues/detail?id=818440).

`width: min-content`, or the more Chrome-specific `width: -webkit-min-content`, seems to do wonders even when just defined for the `.katex` class (as it gets inherited).

I've made a more careful PR for this in #1194.

**Comment by ronkok** [comment]
>  even when just defined for the `.katex` class (as it gets inherited)

I thought about that, but I wonder about classes such as `stretchy`, which have a `width: 100%` rule. Does the `width: min-content` still get inherited? Or must it be added with more specificity after `stretchy`? Or should we redefine `stretchy` from 100% to `min-content`?

**Comment by edemaine** [comment]
It doesn't get inherited in that case -- the width would remain `width: 100%` -- but I think that's what we want in this case.  PR #1194 opts for a different approach, just setting `width: min-content` on the root `.base` element.

**Comment by edemaine** [comment]
Alas, changing `.mspace` from `display: inline-block` to `display: inline` fixes negative spaces, but breaks positive spaces.  So I'm switching back to the inheritance solution...

**Comment by ronkok** [comment]
`.frac-line`, `.underline`, `.overline`, `svg`, `.stretchy`, and `.hide-tail` all have `width: 100%`. I would expect that all of them would benefit from adding `width: -webkit-min-content`.

**Comment by edemaine** [comment]
@ronkok I'm pretty sure those need to stay `width: 100%` so that they grow to the width of the other objects / container.  I tried setting them to `width: min-content`, and it results in them being zero width.  We should just need `min-content` for things that can have children that are negative `.mspace` elements.

**Comment by ronkok** [comment]
> I tried setting them to width: min-content, and it results in them being zero width.

Okay, I agree that we can't just take the easy step of setting `.frac-line: width: min-content;`. But know that we haven't fixed the entire problem.  See the overly long frac-line below:

![widefrac](https://user-images.githubusercontent.com/16403058/36948015-05967700-1f89-11e8-89bd-82d140e850eb.PNG)

Class `vlist` contains elements in a VList.  Maybe it's the class that should get `width: min-content;`. Then it would set of a numerator or denominator to be the proper width. And the parent `frac-line` could stay at `width: 100%` in order to be stretchy.

**Comment by edemaine** [comment]
Here's how that example renders on the #1194 branch:

![image](https://user-images.githubusercontent.com/2218736/36948168-898d33bc-1fa4-11e8-94f2-cf270d7040dd.png)

I've also tried more extreme forms, and the frac line is the correct length.

I believe there's another Chrome bug that's causing some other troubles though...  If I wrap the whole thing in an `\fbox`, I get the wrong box:

![image](https://user-images.githubusercontent.com/2218736/36948181-bec4f1b4-1fa4-11e8-96ce-a40a4922bdf4.png)

I'm pretty sure this is a bug in `width: min-content` on Chrome.  It again renders perfectly in Firefox.

**Comment by ronkok** [comment]
I stand corrected. The frac-line element is a sibling of the denominator, not a parent. So your inheritance works. Nice.

**Comment by kevinbarabash** [comment]
This bug is fixed as report.  We can open a separate ticket for the `\fbox` issue.
