### ISSUE TITLE
Port MacroExpander to @flow

### ISSUE THREAD

**Issue by marcianx** [Khan/KaTeX#842]
Port `MacroExpander.js` and `macro.js` to `@flow`.

I volunteer as tribute! (...assuming no one else is already on this) ;)

**Comment by edemaine** [comment]
I'd prefer for #794 to land first, if that's possible.  (It should be good to go, just needs a final once-over.)

**Comment by marcianx** [comment]
@edemaine Absolutely.

**Comment by kevinbarabash** [comment]
#794 has landed on `master`.
