### ISSUE TITLE
Add support for \cfrac

### ISSUE THREAD

**Issue by murkle** [Khan/KaTeX#85]
As a quick fix would be nice to have it as a synonym for \frac

For later here's an example of the difference between \frac and \cfrac
http://malinc.wikidot.com/insert-formulas

**Comment by prlbr** [comment]
It seems that `\cfrac` isn’t in KaTeX v0.7.1. It would be great if it found its way into the next release. Thank you guys for all the wonderful work.

**Comment by kevinbarabash** [comment]
@prlbr see https://github.com/Khan/KaTeX/pull/135.  The code is pretty stale now though.

**Comment by prlbr** [comment]
Unfortunately I have no idea how to help or else I would offer to.
Is there a chance to handle `\cfrac` as alias of `\dfrac` until `\cfrac` is fully supported?

**Comment by edemaine** [comment]
@prlbr You can definitely add a custom macro for yourself that maps `\cfrac` to `\dfrac`. I'll have to look at adding  proper support...

**Comment by prlbr** [comment]
> @prlbr You can definitely add a custom macro for yourself that maps \cfrac to \dfrac.

Thanks for the hint, it works like a charm!

**Comment by edemaine** [comment]
`\cfrac` is defined as follows in [`amsmath.dtx`](http://tug.ctan.org/tex-archive/macros/latex/required/amslatex/math/amsmath.dtx):

```latex
%    Continued fractions. The optional arg l or r controls horizontal
%    placement of the numerators. The |\kern-\nulldelimiterspace|
%    is needed in the definition if we want the right-hand sides of the
%    fraction rules to line up. The \cs{strut} keeps the numerator of
%    a subsidiary cfrac from coming too close to the fraction rule above
%    it.
%    \begin{macrocode}
\newcommand{\cfrac}[3][c]{{\displaystyle\frac{%
  \strut\ifx r#1\hfill\fi#2\ifx l#1\hfill\fi}{#3}}%
  \kern-\nulldelimiterspace}
%    \end{macrocode}
```

LaTeX defines `\nulldelimiterspace=1.2pt`.

Ignoring the optional `[l]`/`[r]` argument, and the `\strut` which is not yet supported, a more accurate macro for `\cfrac` would thus be `"\\cfrac": "\\dfrac{#1}{#2}\kern-1.2pt".  However, I find that this still doesn't right-align the fraction lines, unlike LaTeX.  Any ideas why there's a discrepancy here?

![cfrac](https://user-images.githubusercontent.com/2218736/33088202-fa04d5cc-ceba-11e7-9c8b-29a71538fabb.png)

Screenshot of http://localhost:7936/?text=%5Ccfrac%7B1%7D%7B1%2B%5Ccfrac%7B1%7D%7B1%2B%5Ccfrac%7B1%7D%7Bx%7D%7D%7D&\cfrac=\dfrac{%231}{%232}\kern-1.2pt

Ah, experimenting a little, it seems that `\kern-2.4pt` is exactly right.  This suggests that we're doubling the space somewhere in `\frac` or `\dfrac`...

**Comment by kevinbarabash** [comment]
Nice investigation.  I'm okay with using `\kern-2.4pt` as long as we have a screenshot test for this.  That way if we fix the other lurking issue without updating the macro we'll know.
