### ISSUE TITLE
enable "loose" mode for transform-es2015-spread babel plugin

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#850]
The "loose" mode assumes that all iterables are arrays which is a safe assumption to make in our codebase.  This will save use some space when using the spread operator.  See https://babeljs.io/docs/plugins/transform-es2015-spread/.

Unfortunately, changing settings to individual plugins within a babel preset is tricky.  Probably best to use https://github.com/developit/modify-babel-preset.

**Comment by marcianx** [comment]
Ah, that's where a type-system-aware transpiler would more ideal.
