### ISSUE TITLE
Port Options.js to @flow

### ISSUE THREAD

**Issue by marcianx** [Khan/KaTeX#851]
This also requires an extremely straightforward adding of types to `fontMetrics`, `fontMetricsData`, `unicodeRegexes`, which are mostly basic constants, but also a couple of straightforward methods.

**Comment by kevinbarabash** [comment]
Options.js is being updated in #848.

**Comment by marcianx** [comment]
*Dang*, I gotta pay more attention. ;)
I'll add some comments based on insights based on my existing work, which I exported into [PR 853](https://github.com/Khan/KaTeX/pull/853).
