### ISSUE TITLE
enable trailing commas in functions in .babelrc

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#861]
https://babeljs.io/docs/plugins/syntax-trailing-function-commas/

**Comment by marcianx** [comment]
I...had no problem with trailing commas in #858 per your comment. ;)

**Comment by kevinbarabash** [comment]
Weird... I was sure that we needed the plugin.

**Comment by marcianx** [comment]
My guess is the that the `@flow` transpiler handles it before babel has to.

**Comment by kevinbarabash** [comment]
I checked using https://babeljs.io/repl/ with only the es2015 preset and it seems fine there so maybe it was only necessary in the past or maybe the plugin's being included in the es2015 preset now.
