### ISSUE TITLE
Avoid bundling overhead

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#872]
Webpack adds a little bit of overhead to each module whereas Rollup does fancy variable rewriting to avoid this.  As we continue to split up functions.js, buildHTML.js, and buildMathML.js into smaller modules, the amount of overhead will continue to grow.

**Comment by obedm503** [comment]
this would be really cool. right now the dist build has repeated babel utilities which would be avoided if using rollup's fancy scope hoisting

**Comment by kevinbarabash** [comment]
@obedm503 I know about rollup, but haven't used it.  How much work would it be to switch over?  Does it work with hot reloading?

**Comment by obedm503** [comment]
didn't know you were using webpack. I guess the same thing could be achieved using the [ModuleConcatenationPlugin](https://webpack.js.org/plugins/module-concatenation-plugin/). that would remove the duplicated utilities

**Comment by kevinbarabash** [comment]
Cool.  @obedm503 would definitely be interested in a PR for that change if have time.

**Comment by obedm503** [comment]
looking into this. can you explain the build system? from what I gather, you're using webpack during dev but browserify for production?

**Comment by kevinbarabash** [comment]
@obedm503 I moved fonts into a submodule recently and thought everything would work correctly for the publish.  It appears that isn't the case.  I'll look into the fonts issue tomorrow.

**Comment by kevinbarabash** [comment]
@obedm503 can you check if there's anything in `submodules/katex-fonts`?  If there isn't please try running:
```
git submodule sync --recursive && git submodule update --init --recursive
```
Also, are you on Windows?  There's an issue with symlinks on that platform.

**Comment by obedm503** [comment]
`prepublishOnly` now works! and no I'm not on windows.
with that out of the way, can you explain the build system?

**Comment by kevinbarabash** [comment]
Hmm... it looks like we're using browserify + babelify for building distribution files.  That being said, webpack.config.js looks like it would build at least the unminified versions as well.  I feel like we should probably move off of browserify to webpack.

**Comment by kevinbarabash** [comment]
@obedm503 I tried adding `ModuleConcatenationPlugin` but it isn't working b/c there are some files that aren't ES6 modules in the bundle, e.g.
```
        [40] ./submodules/katex-fonts/fonts/KaTeX_Main-BoldItalic.woff 78 bytes {0} [built]
             ModuleConcatenation bailout: Module is not an ECMAScript module
             ModuleConcatenation bailout: Module is not an ECMAScript module
```
and 
```
     [40] ./src/unicodeAccents.js 783 bytes {0} [built]
          ModuleConcatenation bailout: Module is not an ECMAScript module
          ModuleConcatenation bailout: Module is not an ECMAScript module
     [60] ./package.json 3.49 KiB {0} [built]
          ModuleConcatenation bailout: Module is not an ECMAScript module
          ModuleConcatenation bailout: Module is not an ECMAScript module
     [66] ./katex.webpack.js + 73 modules 565 KiB {0} [built]
          ModuleConcatenation bailout: Cannot concat with ./src/unicodeAccents.js (<- Module is not an ECMAScript module)
          ModuleConcatenation bailout: Cannot concat with ./node_modules/babel-runtime/core-js/get-iterator.js (<- Module is not an ECMAScript module)
          ModuleConcatenation bailout: Cannot concat with ./node_modules/babel-runtime/core-js/json/stringify.js (<- Module is not an ECMAScript module)
          ModuleConcatenation bailout: Cannot concat with ./node_modules/babel-runtime/core-js/object/assign.js (<- Module is not an ECMAScript module)
          ModuleConcatenation bailout: Cannot concat with ./node_modules/babel-runtime/core-js/object/freeze.js (<- Module is not an ECMAScript module)
```
The .woff files are being copied to the build folder via the `file-loader`.  I'm confused why webpack is even looking at package.json.  `unicodeAccents.js` should be easy to upgrade.  I'm not sure how to handle the `babel-runtime/core-js` files.  Any suggestions?  Does rollup have issue with code compiled with babel or do you run rollup first and then babel?

**Comment by kevinbarabash** [comment]
I see, we're grabbing the `"version"` from `package.json` in katex.js.

**Comment by kevinbarabash** [comment]
I was able to get rollup working.  The unminified bundle that it produces is smaller than webpack, but the minified version is bigger.  I passed the same options to uglify, not sure what's causing the difference.

**Comment by kevinbarabash** [comment]
It turns out that `umd` output is smaller than `cis` output.

**Comment by kevinbarabash** [comment]
@obedm503 I'd like to get your take on https://github.com/Khan/KaTeX/pull/1403.

**Comment by ylemkimon** [comment]
@kevinbarabash It cannot concat `core-js` as they are not ES6 modules. But it seems it successfully concats out source files.

**Comment by ylemkimon** [comment]
Regarding `babel-runtime`’s helpers, there will be an option to use ES6 modules in Babel 7.

**Comment by kevinbarabash** [comment]
@ylemkimon are you saying that in Babel 7, `babel-runtime`'s helpers are defined as a ES6 modules?

**Comment by kevinbarabash** [comment]
If we can get `ModuleConcatenationPlugin` working that would be preferable.  Babel 7 is still in beta.  We could give it a try to see if that fixes the issue, but we should probably hold off on actually upgrading until Babel 7 gets out of beta.

**Comment by ylemkimon** [comment]
@kevinbarabash 

> Are you saying that in Babel 7, babel-runtime's helpers are defined as a ES6 modules? Babel 7 is still in beta. We could give it a try to see if that fixes the issue, but we should probably hold off on actually upgrading until Babel 7 gets out of beta.

Yes, and AFAIK there are some discussions making `core-js` polyfills ES6 modules, too. I'm constantly trying out Babel 7 with KaTeX, and it seems it'll be easy transition.

> If we can get `ModuleConcatenationPlugin` working that would be preferable.

I've tried #1403 out, and it seems most of modules get concatenated. You can search for `CONCATENATED MODULE` comment in the unminified version to see which modules are concated. However, the minified size is 248 KB, slightly bigger than `rollup`.

**Comment by ylemkimon** [comment]
Closing as all codes are now ES6 module and all polyfills are removed and linted against.
