### ISSUE TITLE
\raisebox in MathML

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#874]
[mpadded](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mpadded) looks like the right MathML rendering for `\raisebox` (currently it's rendered like `\text`). As @ronkok [writes](https://github.com/Khan/KaTeX/pull/685#issuecomment-328572761):

> I think that one can get effective presentation MathML for `\raisebox` with code something like:
> ````
> const node = new mathMLTree.MathNode(
>         "mpadded", [buildGroup(group.value.body, options)]);
> node.setAttribute("voffset", group.value.dy.value);
> ````
>
> I have not tested that code, but I have put the HTML below into Firefox
> ````
> <math xmlns="http://www.w3.org/198/Math/MathML">
>     <mi>a</mi><mpadded voffset="0.5em">b</mpadded><mi>c</mi>
> </math>
> ````
>
> ... and it comes out looking like this:
> ![raisebox](https://user-images.githubusercontent.com/16403058/30283820-09334b7a-96ce-11e7-9fb4-a770630b1a80.PNG)

**Comment by ronkok** [comment]
Go ahead and assign this one to me.

**Comment by kevinbarabash** [comment]
I thought I was doing something wrong, but apparently, github will only let you assign collaborators not contributors.  😞

@ronkok I think your comment should suffice.  I wish github was better.

**Comment by kevinbarabash** [comment]
Apparently you assign people who are member's of your organization which would be another benefit of moving things to https://github.com/katex.

**Comment by kevinbarabash** [comment]
Implemented in #876.
