### ISSUE TITLE
Support for web components specs

### ISSUE THREAD

**Issue by lastmjs** [Khan/KaTeX#879]
Hi there,

This project is looking awesome. I'm trying to integrate it into my codebase, and I'm running into a serious issue, the root of which I believe is Shadow DOM. I don't believe the styles are penetrating into the Shadow DOM that my element is in.

Also, I think it would be amazing if this library could be officially supported as a web component. I just wanted to bring this up.

I'm not sure that anyone can help me with the Shadow DOM issue, I mostly want to bring up that I hope this library will consider supporting and embracing all of the latest standards at the appropriate time, including Custom Elements, Shadow DOM, and ES Modules.

**Comment by kevinbarabash** [comment]
@lastmjs this is outside the scope of this particular project.  After doing some quick searching it looks like Web Components doesn't support `<link>` tags inside the component, but you can import CSS via 
```
<style> @import "../my/path/style.css"; </style>
```
If you do create a Web Component wrapper for KaTeX, I'd be more than happy to link to it in the README.md.
