### ISSUE TITLE
Remove unnecessary <mrow>s from MathML output

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#880]
Any `<mrow>` with a single child and no attributes probably doesn't need to be in the tree.  We should probably have some sort of post-processing step on the MathML tree before rendering it.

**Comment by ronkok** [comment]
Also see issue #213 for `<mn>`'s split into individual characters. `<mtext>` does the same thing.

**Comment by edemaine** [comment]
No, #1309 only addressed the extra mrow at the top level. A postprocessing phase to address all 3 issues could probably be done at the end of `parseExpression`. The mtext issue in particular has use to do it in `makeTextRow` (similar to `tryCombineChars`).

**Comment by edemaine** [comment]
Cleanup in aisle #1338.
