### ISSUE TITLE
Port Parser.js to @flow

### ISSUE THREAD

**Issue by marcianx** [Khan/KaTeX#892]

**Comment by kevinbarabash** [comment]
@marcianx I think this is going to be the hardest one.  Thanks for tackling this.

**Comment by marcianx** [comment]
Yes. Yes it is. ;) I've run into at least 4 challenges.

The first two a are just a bunch of grunge work, but doable:
- `functionHandler`'s return type (in `defineFunction`) is `*`. It needs to be enumerated.
- `ParseNode`'s value type is `*`, and that needs to be enumerated `*`.
Although, who knows what surprises await. ;)

The third one is more fundamental. Many uses of `ParseFuncOrArgument` (which I've turned to `ParsedFunc | ParsedArg | ParsedDollar`) predicate strictly on whether or not it is a function, an they don't distinguish `ParsedArg` from `ParsedDollar`. It's a locally non-obvious (to me at least) implementation artifact that `ParsedDollar` cannot appear in these places and so the implementation doesn't check it. I would, of course, increase the final js size by adding thrown `Error`s, but I'm guessing that's not desired, and we might just want to `$FlowFixMe` those places to suppress the errors.

The fourth thing is that `parseImplicitGroup` methods call functions (`parseFunction`), but treat the return value as non-nullable and directly dereference it. It's not locally-obvious (at least to me) why that should be the case. I was going to try to produce cases that would fail based on local reasoning and see if they don't when running the full parser. Maybe tomorrow.

**Comment by kevinbarabash** [comment]
Yup, definitely a bit of a ball of yarn.  If possible, please try to separate this into multiple PRs.  The `ParsedDollar` is quite implicit so anything we can do to make that more explicit is probably good.  We might want to switch out `isFunction: boolean` for `type: "function" | "argument" | "dollar"`.

Is `functionHandler`'s return type the same as `ParseNode`'s `value`'s type? 

We should try to get rid of `parseImplicitGroup`.  This should be doable at this point since we're including a reference to the Parser instance in the `context` we pass to the function handlers.  This might actually be a good first step to take as its own PR.

**Comment by marcianx** [comment]
This is quite the adventure! I'm trying to go a bit more deeply into the weeds to understand the extent of the changes needed to have strong guarantees and convertibility to `@flow` without resorting to type-unsafe features like `any`.

One example I've been trying to understand is `FunctionHandler` vs `ParseNode`. The problem is that `ParseNode`'s value type can either be the output of `FunctionHandler` (let's call it `NodeData`)  _or_ something else that's been constructed in `Parser` itself (like the `"size"` `ParseNode` created there). `NodeData` has a `type` field, _but_ `ParseNode` has its own `type` field on top of that, which makes it very difficult to make them both type-safe without a lot of redundancy. For example, `NodeData` is already something like

```javascript
type NodeData = {|
    type: "sqrt",
    body: ParseNode,
    index: ?ParseNode,
|} | {|
    type: "text",
    body: ParseNode[],
    font: ?string,
|} | {|
    type: "color",
    color: string,
    value: ParseNode[],
|} | {|
    type: "enclose",
    label: string,
    backgroundColor: ParseNode,
    borderColor: ?ParseNode,
    body: ParseNode,
|} | {|
    type: "overline" | "underline",
    body: ParseNode,
|} ... // more here
```

If `ParseNode` were turned into an object with a method to construct it, then for maximal type-safety, it would have a type like

```javascript
type ParseNode = {|
    type: "\\sqrt",
    value: {|
        type: "sqrt",
        body: ParseNode,
        index: ?ParseNode,
   |},
   mode: Mode,
   ... // lexer, start, end
|} | ... // additional variants
```
and also some variants like the following that are constructed within `Parser.js` itself.

```javascript
... {|
    type: "size",
    value: {|  // has no `type` field!
        number: number,
        unit: string,
    |},
    mode: Mode,
   ... // lexer, start, end
|}
```
So now `ParseNode` serves two purposes: (1) many `ParseNode`s constructed in `Parser` serve as input into `FunctionHandler` (like the `"size"` example above), and (2) it also wraps the output of `FunctionHandler` (`NodeData`, which always provides a `type` field). I'm not sure whether we need to separate those out, but it feels a little messy to me when it comes to reasoning about things.

So I'm considering a systemic refactor of `ParseNode` so that it no longer has its own separate `type`, but becomes
{|
    data: NodeData,
    mode: Mode,
    ... // lexer, start, end
|}
IOW, we'd collapse the two redundant types. The `type`-discriminated union would then be isolated to `NodeData` which would serve as the single enumeration of all possibilities. Note that this would be slightly lossy since there are multiple functions that map to the same `NodeData` type—e.g. `\\colorbox`, `\\fcolorbox`, `\\cancel` and others map to `type="enclose"` in `functions.js`. However, if the original function name is needed, it could be stored in `NodeData` itself as an additional field.

The unfortunate thing is that `ParseNode` is being used all over the place (`Parser.js`, `functions.js` and others, `buildHTML`, `buildMathML`), most of it being untyped code. So this refactor would have to be...diligent. But I'm up for it for all that's worth.

I could start with first putting up the intended types in comment `@params` for reference and we can go forward from there. A lot of it can be incremental, like ensuring that the `ParseNode`'s `value` always has a `type` field before `ParseNode`'s own `type` field can be dissolved. E.g. the `"size"` `ParseNode`'s `value` type would become
```javascript
    {|
        type: "size",   // redundantly added
        number: number,
        unit: string,
    |}
```
and things like `ordgroup`s and others would be changed from
```
new ParseNode("ordgroup", expression, this.mode,
                    firstToken, lastToken)
```
to
```
new ParseNode("ordgroup", {type: "ordgroup", args: expression}, this.mode,
                    firstToken, lastToken)
```

WDYT? Is the test suite up to par? Or do you think we should go a different way?

**Comment by kevinbarabash** [comment]
@marcianx thanks for digging deep and providing a detailed writeup.

I was actually thinking we'd combine `ParseNode` and `NodeData` into a single node.  Maybe something like:
```
type Common = {
   loc: SourceLocation | null,
   mode: "math" | "text",
}

type SourceLocation = {
   start: Token,
   end: Token,
   lexer: Lexer,
}

type SqrtNode = BaseNode & {
   type: "sqrt",
   body: ParseNode,
   index: ?ParseNode,
}

type TextNode = BaseNode & {
    type: "text",
    body: ParseNode[],
    font: ?string,
}

type ParseNode = SqrtNode | TextNode | ... ;
```

The main benefit I see in this approach is a shallower tree.  The reason for introducing `loc` is to avoid conflicts between metadata props and node specific props.

I find it weird that `sqrt` nodes use `body: ParseNode` whereas `text` nodes use `body: ParseNode[]` while `color` nodes use `value: ParseNode[]`.  I would like to suggest introducing a new node type called a `GroupNode` which looks like:

```
type GroupNode = BaseNode & {
   type: "ordgroup",
   children: ParseNode[],
}
```

All other nodes would always use `body` and `body` would always be a single node.  I guess `GroupNode` is kind of like `ordgroup`, but we'd use it more consistently.  Also, `ordargument` would become:

```
const ordargument = function(arg: ParseNode) {
    return arg.type === "ordgroup" ? arg : new ParseNode("ordgroup", {children: [arg]});
};
```

As for the lossy nature, one nice benefit of being non-lossy is being able to generate LaTeX code from the AST.  This may be useful for interactive editors or other tools people may develop in the future like codemods for TeX code.  I think we include the name of the function that was used to generate the node.  If it's the same as the type that's okay.

Before doing any major refactor we should get the following PRs reviewed and merged: #871, #875, #885, and #887 (and maybe #884).

**Comment by marcianx** [comment]
Sounds good to me. In the meantime, I'll do some minor refactors that don't seep (too far) outside `Parser`, but allow making it more type-stringent.

**Comment by edemaine** [comment]
It's great that type checking is leading us toward refactoring improvements to the parse tree!  FWIW, I've found the difference between what's returned by a function (a la `defineFunction`) and the actual parse node (wrapping in another `value`, as I recall) to be confusing and unnecessary.  I think that's one of the things you're discussing fixing?

**Comment by marcianx** [comment]
@edemaine Indeed!

@kevinbarabash Actually, isn't it "harder" to construct and pass around
```javascript
type SqrtNode = BaseNode & {
   type: "sqrt",
   body: ParseNode,
   index: ?ParseNode,
}

// Given
type BaseData = {
   loc: SourceLocation | null,
   mode: "math" | "text",
}

type SourceLocation = {
   start: Token,
   end: Token,
   lexer: Lexer,
}
```

than, say,

```javascript
type SqrtNodeData = {
   type: "sqrt",
   body: ParseNode,
   index: ?ParseNode,
}
type Node<Data> = {
   value: Data,
   mode: Mode,
   loc: SourceLocation,
}
```
?

The former seems to require constructing the whole object at once, whereas for the latter, `FunctionHandler` can return `SqrtNodeData` and `Parser` can construct `Node<Data>` with all the metadata. Or did you wish to require updating all the `FunctionHandler`s to set the metadata (`mode`, `loc`) as well?

**Comment by marcianx** [comment]
Or perhaps your suggestion can be modified to
```javascript
type SqrtNodeData = {
   type: "sqrt",
   body: ParseNode,
   index: ?ParseNode,
}
type NodeData = (SqrtNodeData | ...);
type Nodes = NodeData & Common;
```

Then, `FunctionHandler` can return `NodeData`, and `Parser` can add the additional metadata fields in the same object itself.

**Comment by kevinbarabash** [comment]
@marcianx I really like your suggestion of doing `type Nodes = NodeData & Common;`

**Comment by marcianx** [comment]
@kevinbarabash I noticed that #871 and #887 seem to be on a bit of a lull, but they don't obviously seem blocked. Is there anything I can do to help?
I'm not sure I can make any particular progress on refactoring `ParseNode`'s structure that would not touch a lot of code overlapping with those PRs.

**Comment by kevinbarabash** [comment]
@marcianx if you'd like to review them that would definitely help.
