### ISSUE TITLE
remove support for EOT fonts

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#893]
> KaTeX supports all major browsers, including Chrome, Safari, Firefox, Opera, Edge, and IE 9 - IE 11.

WOFF is support of IE9+ and none of the other browsers support EOT so I'd like to suggest getting rid of EOT fonts.  Does anyone have any concerns about removing this font format?

**Comment by ronkok** [comment]
Removal makes sense to me.

**Comment by edemaine** [comment]
Reopening until second PR lands.

**Comment by kevinbarabash** [comment]
Thanks.  I didn't realize that commits to other repos could automatically close issues.
