### ISSUE TITLE
upgrade uses of nomnom to use commander.js

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#900]
In the process of responding to code review comments in #882, it was discovered that nomnom is deprecated.  The suggested replacement is https://github.com/tj/commander.js.  Since we use nomnom in a few places it's probably best to upgrade everything at the same time.

**Comment by raoulb** [comment]
https://npmcompare.com/compare/commander,minimist,nomnom,optimist,yargs

**Comment by kevinbarabash** [comment]
npmcompare.com is awesome!

**Comment by kevinbarabash** [comment]
We're using nomnom now.
