### ISSUE TITLE
please add underbrace  support

### ISSUE THREAD

**Issue by redstoneleo** [Khan/KaTeX#908]
currently KaTeX seems cannot render
`{\lim _{n\to \infty }0.\underbrace {99\ldots 9} _{n}}`
but mathjax can.
please add support for underbrace  ,

**Comment by ronkok** [comment]
@redstoneleo, The current release of KaTeX does support `\underbrace`, as seen in this clip from the [demo page](https://khan.github.io/KaTeX/):
![underbrace](https://user-images.githubusercontent.com/16403058/30974574-d2bf1812-a424-11e7-9d6e-f1c860722b15.PNG)

Check the version of KaTeX that is in use. The current release is 0.8.3. `\underbrace` was addded in 0.8.1

**Comment by edemaine** [comment]
@redstoneleo If you happen to be sanitizing the HTML output from KaTeX, be aware that you need to allow SVG for this feature to work.  (I happened to run into this in my own project.)  Otherwise, you should be all set with `\underbrace` support.
