### ISSUE TITLE
webpack server doesn't support remote connections

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#911]
I just tried out the new `webpackDevServer.js` (via `npm start`) and there's been a regression in functionality compared to the old `server.js`: I can no longer connect to the server from the outside (via `http://hostname:7936`).  I can only connect from the same host.  This is annoying for me, as I like to develop on a remote Linux server and test from a web browser on my local Windows machine.

Is this intentional?  Is there some security hole that this would otherwise open up?  Or can we restore functionality?  [This post](https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a) seems relevant.  We can't reasonably provide the host name (via `--public`), as it depends on the individual user.  Is `disableHostCheck` safe enough for our usage?  We don't need to worry about leaking the source code...

@rrandallcainc

**Comment by rrandallcainc** [comment]
@edemaine Nice catch, I can see how that's a pain. I don't see any concerns with leveraging `disableHostCheck`, but I also don't claim to be a security expert. I'm guessing for local development it should serve just fine.

**Comment by edemaine** [comment]
I read the security issue again and it does seem safe for our purposes, especially given that we're not using proxy features.  Added a PR in #915.

**Comment by edemaine** [comment]
Fixed in #915
