### ISSUE TITLE
Subsript issue : (C{H}_{3})_3 , both 3 are appearing at the same level

### ISSUE THREAD

**Issue by nitishkumarnitc** [Khan/KaTeX#914]
I want outer 3 to be at lower level then inner 3, but it's coming at same level.

**Comment by xymostech** [comment]
You probably want something like `(C{H}_{3})_{{}_3}`:

![image](https://user-images.githubusercontent.com/217900/31061587-c6aeef38-a6d7-11e7-8d72-0aabffcc24fe.png)
