### ISSUE TITLE
linter should complain about tabs in .less files

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#921]
Currently we use eslint for our .js but we don't do any linting of our .less files.

**Comment by edemaine** [comment]
Perhaps [stylelint](https://stylelint.io/)?  See [this css-tricks.com post](https://css-tricks.com/stylelint/).  Looks like you can turn off tab support via the [indentation rule](https://stylelint.io/user-guide/rules/indentation/).
