### ISSUE TITLE
 Outline of formulas containing superscripts is strangely high

### ISSUE THREAD

**Issue by AlbertHilb** [Khan/KaTeX#927]
First of all, thank you for the great work you are doing with KaTeX, it's really awesome. :blush:

With the last releases, on Firefox, the outline of formulas containing superscripts is strangely high.

![screenshot](https://user-images.githubusercontent.com/1220427/31382852-5080bbfa-adb9-11e7-8651-f20edd587590.png)

The problem seems to be in the highlighted `span`:

![screenshot2](https://user-images.githubusercontent.com/1220427/31383229-943f70ba-adba-11e7-9c68-6968c3dc8a2c.png)

This issue was not present in the release 0.7.0.

**Comment by kevinbarabash** [comment]
@AlbertHilb this is due to how we're doing vertical layouts now.  The outline of the of the katex behavior should be the correct size.  Is there a way that a user can actually select inner nodes without using dev tools?

**Comment by edemaine** [comment]
@kevinbarabash I think this is (part of?) what causes the strange highlight behavior during selection (copy/paste). But I don't consider that too big a problem. @AlbertHilb is there another application where this causes a problem?

**Comment by kevinbarabash** [comment]
@edemaine I thought that too, but the highlight rectangle seemed to larger than what would be suggested by these tall spans.

**Comment by AlbertHilb** [comment]
@kevinbarabash, @edemaine 

I use KaTeX to render math formulas in a JavaScript editor.
To show an equation is selected I add `outline: 3px solid dodgerblue` to the inline style of the span containing the math.

On Chrome it works flawlessly, on Firefox the outline is too high.

It's not a big deal because I can overcome it drawing a border around the formula instead , but borders take up some space, thus the math becomes surrounded by more space than needed.

So, if I could, I would prefer to use `outline` property.

**Comment by kevinbarabash** [comment]
I see.  I was confused because you have one of inner nodes selected in the screenshot.  I tried selecting the outermost katex node and applying `outline: solid 2px blue;` on Firefox and it's definitely broken compared to other browsers.

**Comment by kevinbarabash** [comment]
I think this is a browser bug.  If you don't want the border to take up space you could add a negative margin.

**Comment by ronkok** [comment]
The difference in behavior stems from PR #768. In that PR, @kohler fixed a nagging problem in which HTML line box heights were occasionally overiding the vertical position calculated by KaTeX. That code needed a dependable point on which to base things, a point outside the line box. So now it calculates a strut height that is the maximum of any element, then it calculates:
````
pstrutSize += 2;
````
... just to be sure.

All of this is a long winded way of saying that there is a reason for the geometry in that VList. I don't see it going away.

**Comment by kevinbarabash** [comment]
Closing this as won't fix.
