### ISSUE TITLE
webpackDevServer does not reload CSS or main.js

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#929]
When I change `static/katex.css`, the webpack server doesn't notice the change.  I have to manually kill and restart the server to get the CSS to update.  This makes it difficult to develop CSS changes.

The same is true if I change `static/main.js`.

**Comment by rrandallcainc** [comment]
This shouldn't be too hard to integrate for the css. 

Is static/main.js really something that is changed often? Does it need to be watched?

**Comment by edemaine** [comment]
@rrandallcainc FWIW, I was actively development `static/main.js` the other day (for testing of #899). I've seen it change at least twice in the past 6 months, so it does happen, and would be useful.  There is close to zero cost for watching, right?

**Comment by rrandallcainc** [comment]
Nope, was just curious if it get changed frequently :)
