### ISSUE TITLE
katex.renderToString is not a function

### ISSUE THREAD

**Issue by Georg-Git** [Khan/KaTeX#937]
I am trying to combine TinyMCE and this amazing TeX rendering engine.

I am using only the function katex.renderToString() - and was very impressed by Katex version **0.8.3.**
See here my playground:
http://fiddle.tinymce.com/ncgaab/4

But with later versions of Katex I have no luck and receive always an error:
**"katex.renderToString is not a function"** (Browser Debugger).
See here same playground but with higher version of Katex:
http://fiddle.tinymce.com/ncgaab/6

Win 10 / Chrome

**Comment by kevinbarabash** [comment]
There was an issue with v0.9.0-alpha.  I need to publish a new release.

**Comment by kevinbarabash** [comment]
I've just published [v0.9.0-alpha](https://github.com/Khan/KaTeX/releases/tag/v0.9.0-alpha1).  @Georg-Git please let me know if that fixes things for you.

**Comment by kevinbarabash** [comment]
Actually, I'm going to close this issue.  @Georg-Git please re-open if the new release doesn't fix things for you.

**Comment by Georg-Git** [comment]
@kevinbarabash  👍 

I have updated KaTeX version and improve integration in TinyMCE:
http://fiddle.tinymce.com/ncgaab/9
