### ISSUE TITLE
Generate a ES6 module npm package

### ISSUE THREAD

**Issue by justinfagnani** [Khan/KaTeX#954]
See https://unpkg.com/katex@0.9.0-alpha1/src/MacroExpander.js which contains an `import type...` statement.

This prevents using the JS modules published to npm.

**Comment by kevinbarabash** [comment]
@justinfagnani package.json's `main` field points to `"dist/katex.js"` which should not contain any type annotations.

**Comment by justinfagnani** [comment]
`dist/katex.js` isn't a JavaScript module though, and `/katex.js` is. Since browsers are now supporting modules, I'd like to just load a real importable JS module from unpkg without going through any kind of bundling step.

I guess I was confused by the presence of what looked like modules because many of the files don't have Flow annotations. Can you just run them through the flow compiler and publish the raw output, without bundling with WebPack?

**Comment by rrandallcainc** [comment]
@justinfagnani When you say modules, I'm assuming you're referring to ES6 modules? At the moment, the entry point for Katex.js is of CommonJS format.

This is required for backwards compatibility, and an ES6 entry point would be a breaking change.

That being said, perhaps there could be multiple entry points for katex.js, one of them being perhaps katex.es.js (as an ES6 module)?

Babel can be used to strip out the flow annotations, or this library should work: https://github.com/flowtype/flow-remove-types

That would probably be run on each of the files in the dependency tree.

**Comment by kevinbarabash** [comment]
I've changed the title of this issue.  I'm not sure the best way to do this.  This came up in another issue as well.  It sounded like making an ES6 specific npm package wasn't necessary and that there were some package.json fields that might do the trick.

**Comment by rrandallcainc** [comment]
Please refer to the last comment here: https://github.com/Khan/KaTeX/pull/902

Looks like pckg.esnext/pckg.module are options for the ES6 module's entry point. As far as stripping out the flow-type, I'm guessing that could be added to the build script?

**Comment by justinfagnani** [comment]
Thanks a lot for looking into this!

@rrandallcainc yes, I'm referring to ES6 modules. And I'm not suggesting changing `dist/katex.js`* file, but the ones published in `src/`. Since you probably want to keep those around for sourcemaps you could compile them to a `lib/` directory, unbundled, that just mirrors `src/`. That's what I typically do for my TypeScript projects.

On a little tangent, is there an alternate file extension to use with Flow that doesn't lead people to think the files are standard JS?

*yet! I hope the JS ecosystem can move away from CJS as soon as possible :)

**Comment by kevinbarabash** [comment]
I'm curious about the desire have a `lib/` folder over a single ES6 module.

**Comment by justinfagnani** [comment]
I just don't see the need for bundling at the library level anymore, and unbundled files will give a much better developer experience with stack traces, sourcemaps, etc.

Applications can do the bundling, and since the module graph is now easily statically determinable, it's quite trivial for build tools to find all the imported files.

**Comment by kevinbarabash** [comment]
Okay.  Let's start with:
- adding a build step to "compile" files in `src/` to `lib/` by stripping out flow types
- add a pckg.module (or pckg.esnext) entry to our package.json

If other people say they want a precompiled ES6 module that concatenates all the files `lib/` into a single file then we can deal with that as a separate issue.  How does that sound to people?

**Comment by rrandallcainc** [comment]
That sounds good. I think the one other thing we'll need to do is convert the cjs modules -> es for the Katex entry point.

**Comment by kevinbarabash** [comment]
We should probably also move the `katex.js` entry point into `src/` so that we can mirror it in `lib/`.

**Comment by edemaine** [comment]
FWIW, my impression is that the flow types can be "preserved" in the compiled form using comments.  (I ran into this with stylelint in #925.  We might also need to export the types, for build systems using flow, but I guess we can wait for a request about this.)

**Comment by justinfagnani** [comment]
Now that Firefox 60 has shipped with native modules, all major browsers have module support. This would be a great time to get Katex loadable in the browser without additional tools.

**Comment by kevinbarabash** [comment]
I would definitely welcome a PR for this from @justinfagnani or anyone else who's interested in this.
