### ISSUE TITLE
Can I render equations using MathML format?

### ISSUE THREAD

**Issue by nmanumr** [Khan/KaTeX#955]

**Comment by edemaine** [comment]
Could you clarify what you're asking here?  KaTeX already outputs both MathML and HTML.  The MathML is by default hidden visually, but I believe you could change the CSS to make it render, and hide the HTML rendering.

**Comment by marcianx** [comment]
Sorry for the close/open; hit the wrong button on mobile.
@nmanumr Do you mean MathML add input to KaTeX or as output?

**Comment by nmanumr** [comment]
Just found another way
