### ISSUE TITLE
auto-render: Cannot read property 'length' of undefined: childNodes

### ISSUE THREAD

**Issue by arshs** [Khan/KaTeX#956]
I get this error for all formulas on my page: 
it is finding that childNodes is undefined
`for(var n=0;n<t.childNodes.length`

And yet, when I log the element to the console, right before this, childNodes does not seem to be undefined at all (I have 1 span element as a child in all cases).

Any ideas on how to fix this? Thanks!

**Comment by marcianx** [comment]
Could you provide a testable example? I'm happy to try to debug this.

**Comment by arshs** [comment]
Thanks for taking a look.

I am using this in a Meteor project - so I'll post the relevant sections, and hopefully that provides some clarity; not sure if it is easily extricatable from the project. I was using mathjax & it was working (but really slow) so I'm fairly sure the text syntax is not the issue.

**These are literally the only changes I made to my project:** (In the below, `myValidLatexSyntaxText` shows up,  but as the literal text (unformatted).)

Here goes:

My HTML template contains:
`<div data-katex='true'><span>{{{ myValidLatexSyntaxText }}}</span></div>`

Then in the js file for that template:
```
import './myTemplate.html';
Template.myTemplate.onRendered(function(){
	console.log(this.$("[data-katex='true']")); 
	renderMathInElement(this.$("[data-katex='true']"));
});
```

Lastly, my head.html file contains: 
```
<!-- KATEX -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha1/katex.min.css" integrity="sha384-8QOKbPtTFvh/lMY0qPVbXj9hDh+v8US0pD//FcoYFst2lCIf0BmT58+Heqj0IGyx" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha1/katex.min.js" integrity="sha384-GR8SEkOO1rBN/jnOcQDFcFmwXAevSLx7/Io9Ps1rkxWp983ZIuUGfxivlF/5f5eJ" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha1/contrib/auto-render.min.js" integrity="sha384-cXpztMJlr2xFXyDSIfRWYSMVCXZ9HeGXvzyKTYrn03rsMAlOtIQVzjty5ULbaP8L" crossorigin="anonymous"></script>
<!-- END KATEX -->
```

**Comment by arshs** [comment]
Actually I got Katex to start rendering some things... turns out 
`this.$("[data-katex='true']")`
returns  an array, of which the [0] element is the actual html node the renderMathInElement function needs.

(And I was mistaken in my earlier assumption that mathjax syntax translates perfectly...doesn't seem to be the case)

**Comment by edemaine** [comment]
@arshs You'll want to be careful using KaTeX in Meteor's onRendered, because that's only called once even if the template changes/rerenders. In [my own Meteor project](https://github.com/edemaine/coauthor/), I call KaTeX directly in a helper.

**Comment by arshs** [comment]
@edemaine  Thanks for the tip! I'll refactor to do it that way.

Interesting project btw; Have been looking at adding editor collaboration functionality in my project & will be looking at it further...
