### ISSUE TITLE
Aligned not working correctly if first element in last line is empty

### ISSUE THREAD

**Issue by aterenin** [Khan/KaTeX#966]
The following does not work:

```
\begin{aligned}
\hat{\v{y}} = f(\m{X}) = &f^{(1)}\cbr{f^{(2)}\sbr{f^{(3)}\del{\m{X}} + \m{X}} + \sbr{f^{(3)}\del{\m{X}} + \m{X}}}
\\
+& \cbr{f^{(2)}\sbr{f^{(3)}\del{\m{X}} + \m{X}} + \sbr{f^{(3)}\del{\m{X}} + \m{X}}}
.
\end{aligned}
```

whereas the following does:

```
\begin{aligned}
\hat{\v{y}} = f(\m{X}) = &f^{(1)}\cbr{f^{(2)}\sbr{f^{(3)}\del{\m{X}} + \m{X}} + \sbr{f^{(3)}\del{\m{X}} + \m{X}}}
\\
&+ \cbr{f^{(2)}\sbr{f^{(3)}\del{\m{X}} + \m{X}} + \sbr{f^{(3)}\del{\m{X}} + \m{X}}}
.
\end{aligned}
```

The only difference is the plus sign at the start of the last line. Unless it is placed before the &, the last line disappears.

**Comment by ronkok** [comment]
@aterenin Your example has several backslash combinations with which I am unfamiliar. I don't what `\m`, `\cbr`, or `\sbr` are supposed to do.

Putting that aside and concentrating on the `aligned` environment, the problem with an empty cell was reported in issue #946 and a bug fix was merged into master three days ago. That code has not yet made it into a release. Hopefully, the release is not too far off.

**Comment by aterenin** [comment]
Sorry, these are custom macros to make my TeX source more readable. They are all included in a macro definition at the beginning.

Also my apologies if this is a duplicate issue - I searched the repo and did not find that one.

**Comment by edemaine** [comment]
Glad to see macros in use! 

if you'd like, check out the master branch and see if it resolves your issue. Let us know if it's not fixed and we can take a closer look.
