### ISSUE TITLE
Render smart quotes in math as regular quotes

### ISSUE THREAD

**Issue by aterenin** [Khan/KaTeX#967]
Many Markdown preprocessors, such as the one that Jekyll and GitHub Pages use, have a "smart quotes" feature.

This changes quotes such as 
```
'
```
to fancier ones such as
```
’
```
which unfortunately interferes with KaTeX' ability to render prime symbols correctly.

I propose either ignoring smart quotes and rendering them as ordinary quotes (i.e. if KaTeX encounters ```’```, it renders it as if it had encountered ```'```) , or introducing an option to do so.

**Comment by ccorn** [comment]
Just a comment: If such things happen, wouldn't such processors also interfere with usage of `_` and the like?
Or are you referring to (Liquid) filters such as [jekyll-katex-block](https://github.com/drewsberry/jekyll-katex-block)?
In both cases the actual problem is that a language intended for only one parser is interpreted by a second parser. This should be addressed by preventing the wrong parser from trying to fiddle with the output from the first.
(I currently work on a server-side KaTeX implementation that cooperates better with kramdown, so that might fix your issue. The current code works, but I consider factoring out the KaTeX-Ruby interface to a separate gem.)

**Comment by aterenin** [comment]
If they do, the interference is minimal - I have lots of large formulas on my blog with `^_&` and other syntax and it all works correctly. Smart quotes is the only thing that gets through.

My site is built using GitHub pages, and I do not have the kind of control over the environment that would allow me to modify Jekyll or enable 3rd party plugins to work around the issue. Even if I did, I wouldn't use any due to potential security implications.

My current solution is to add a small bit of JavaScript to automatically undo the problematic smart quotes client-side. This works, but I feel that smart quotes in particular are common enough that they shouldn't cause KaTeX to throw an error, especially when there is no valid TeX using them in math mode that I'm aware of.

**Comment by edemaine** [comment]
I believe the "right" way to do KaTeX in Markdown is to extract the math separately, run Markdown processing, then stick the math back in (formatted by KaTeX).  This is what I do [here](https://github.com/edemaine/coauthor/blob/master/lib/formats.coffee), and eventually plan to release as a `contrib` module.

Meanwhile, the behavior of `’` is related to the recent Unicode support that @ronkok is adding.  I'd be all for matching the behavior of LaTeX's [unicode-math.sty](https://github.com/wspr/unicode-math/blob/master/unicode-math-table.tex), but it doesn't seem to define behavior for `U+2019 ’ RIGHT SINGLE QUOTATION MARK`.  So I'm not sure whether there should be a default behavior here...  I observe that `\text{’}` already behaves correctly in KaTeX.

As for the ability to define `’` to map to `'`, I believe the right way to do this would be with the macro system.  Currently the macro system can only define commands starting with `\`, but a one-line change would enable defining single characters as well.  I've created #973 to do this.  There's a test in that PR that corresponds to your exact use-case.

**Comment by aterenin** [comment]
A solution using the macro system would work great for me.

**Comment by kevinbarabash** [comment]
I think a valid resolution to this issue would be to add a section to README.md with common gotchas and include this along with suggestions of how to fix the issue.

**Comment by edemaine** [comment]
@aterenin #973 got merged, so if you clone the master branch of KaTeX you can now pass a macro set of `{"’": "'"}`.  Would you be able to test that this does what you want in your setting before we add it to the README?  Are there other smart quotes, perhaps double quotes, that you'd want to convert?

**Comment by aterenin** [comment]
It works great! In addition, the `&=` bug for the `aligned` environment is also fixed. Thanks very much!

**Comment by edemaine** [comment]
I created #1020 to document this approach in the README.
