### ISSUE TITLE
Dividing lines for array environment sometimes disappear

### ISSUE THREAD

**Issue by akalin** [Khan/KaTeX#970]
Test file for 0.8.3: https://rawgit.com/akalin/cc8023a41d1fc1cd0250bc50d122680f/raw/ed169e5a427382c12543a0b941ae66c34eda0003/test-0.8.3.html

Test file for 0.9.0-alpha1:
https://rawgit.com/akalin/cc8023a41d1fc1cd0250bc50d122680f/raw/e7b2ba03faa7b28b93951dc21402fc5ab443f0eb/test-0.9.0-alpha1.html

Vertical divider isn't visible at 100% zoom with Chrome Version 64.0.3269.3 (Official Build) dev (64-bit) on macOS 10.13.1, but they show up at 110%.

Related to #824, but @ronkok says he wants to fix that one first before doing this one.

Gist: https://gist.github.com/akalin/cc8023a41d1fc1cd0250bc50d122680f

**Comment by ronkok** [comment]
@akalin In PR #976, I went ahead and gave `vertical-separator` the same full-span treatment that I gave to `frac-line`. We have one report in from @trimbonz that the work is effective making frac-lines visible. Hopefully, the same will be true for vertical array separator lines.

**Comment by akalin** [comment]
Not sure if 0.9.0-alpha2 is supposed to fix this too, but https://rawgit.com/akalin/cc8023a41d1fc1cd0250bc50d122680f/raw/e7b2ba03faa7b28b93951dc21402fc5ab443f0eb/test-0.9.0-alpha2.html is a test file that behaves the same way as 0.9.0-alpha1.

**Comment by akalin** [comment]
0.9.0-beta fixes this completely for me: https://rawgit.com/akalin/cc8023a41d1fc1cd0250bc50d122680f/raw/81cbe2e2c359d591b61260c832490c0f1d2c87cc/test-0.9.0-beta.html

Thanks!

**Comment by kevinbarabash** [comment]
@akalin thanks for verify that the new release fixes the issue.
