### ISSUE TITLE
Vertical Layout

### ISSUE THREAD

**Issue by adammaj1** [Khan/KaTeX#972]
I try to make equation in [markdown file on the gitlab](https://gitlab.com/adammajewski/parameter_external_angle).

I f try to follow [this guidelines](https://khan.github.io/KaTeX/function-support.html#environments).

Why this equation

$`\Phi_M(c) \overset{def}{=} \Phi_c(c)`$  

is not rendered ? ( I mean:  \overset{def}{=}  )

TIA

Adam

**Comment by marcianx** [comment]
I ran

    katex.renderToString('\\Phi_M(c) \\overset{def}{=} \\Phi_c(c)')

on the javascript console both on your site and on https://khan.github.io/KaTeX/. It failed on the former as you indicated and it succeeded on the latter.

Are you by any chance running an old version of KaTeX? Per https://github.com/Khan/KaTeX/releases, `\overset` was added in v0.8.0.

**Comment by adammaj1** [comment]
thx.
I have found that [ "Gitlab ships with KaTeX starting from v8.15 "](https://gitlab.com/gitlab-org/gitlab-ce/issues/26079). 
Maye it is a gitlab not KaTex problem so I have also [asked on the gitlab](https://gitlab.com/gitlab-org/gitlab-ce/issues/40393)

**Comment by edemaine** [comment]
Agreed. gitlab seems to include [this version of katex](https://github.com/gitlabhq/gitlabhq/blob/a0715f079c143a362a7f6157db45020b8432003e/vendor/assets/javascripts/katex.js) which clearly doesn't include `\overset`, while the latest versions do.  Hopefully they can upgrade as indicated in the comments there.

**Comment by adammaj1** [comment]
Is KaTex using version number ? I have found only 4fb9445a9 or 2015. How do you check it?

**Comment by edemaine** [comment]
KaTeX uses version numbers, but it doesn't seem to have made its way into Gitlab's code (unfortunately). But from the year, it's clearly an old version.
