### ISSUE TITLE
Superscripts rendered as subscripts

### ISSUE THREAD

**Issue by Reikim** [Khan/KaTeX#978]
I'm aware there are other issues that have been opened on this sort of thing, notably #659, and #183, but having trawled through those issues and attempted a few of the suggestions without any luck, I think it's time to ask for some more hands-on help...

My use case is this: I receive a block of plaintext content from a server that may contain inline [ASCIIMath](http://asciimath.org/), delineated by backticks. I have a script that scans this data for the math, converts the math to TeX, and then feeds that into `katex.renderToString`. The output is slipped into the original data and inserted into the page for display.

The TeX generated by my script is:

```
{x}^{{2}}
```

And the markup generated by KaTeX (version 0.8.3) is:

```
<span class="katex">
	<span class="katex-html">
		<span class="strut"/>
		<span class="strut bottom"/>
		<span class="base">
			<span class="mord">
				<span class="mord">
					<span class="mord mathit">x</span>
				</span>
				<span class="msupsub">
					<span class="vlist-t">
						<span class="vlist-r">
							<span class="vlist">
								<span>
									<span class="pstrut"/>
									<span class="sizing reset-size6 size3 mtight">
										<span class="mord mtight">
											<span class="mord mtight">
												<span class="mord mathrm mtight">2</span>
											</span>
										</span>
									</span>
								</span>
							</span>
						</span>
					</span>
				</span>
			</span>
		</span>
	</span>
</span>
```

This renders as:

![capture](https://user-images.githubusercontent.com/8724794/33093189-4bd9b00c-ceca-11e7-933f-cb1e51cd8de9.PNG)

I've tested this in both Firefox 57 and Chrome 62 and gotten the same result. I've verified that my page has `<!DOCTYPE html>` at the top, and that both the CSS and fonts are loading correctly. I've also tried creating a dummy `<span>` through `document.createElement` and rendering into that using `katex.render`, then dumping the `outerHTML`, but I get the same result. However, it works fine if I render into an _existing_ element on the page.

Am I misusing the library in some way, maybe?

Thanks for all your hard work; this is an excellent library. I appreciate any help you can spare!

**Comment by edemaine** [comment]
I tested that TeX input on the [demo page](https://khan.github.io/KaTeX/) and it works fine. So there must be a problem with how you're using KaTeX in your context.

Maybe try to make a minimal bad example? My guess is that at least  the fonts aren't being loaded properly, as they look wrong. Check for network errors? 

No need to do anything but `renderToString`. That HTML is correct; you just need to get the surrounding HTML to make it render properly.

**Comment by Reikim** [comment]
I already checked that fonts are being loaded correctly over the network (as noted in the original issue). Is there something else I should be checking for? This is being dumped straight into a div.

**Comment by Reikim** [comment]
I also explained that I know it works correctly in the demo page and in one of my own demos. I know it's likely an issue with the way I'm using it; I just have no idea where to look, and I don't know why it works fine using one method but not the other.

**Comment by edemaine** [comment]
@Reikim Without an actual example (even of a generated full webpage), I don't see how we can help debug. Perhaps you have other CSS that generates conflicting rules?

I realize that you said the fonts are loading correctly, but the screenshot indicates that they aren't (or that the KaTeX CSS isn't setting the `font` style to use them, but I imagine you checked for that in Developer Tools).  Look at the 2 in particular, which is lacking the curly cue:

![screenshot from KaTeX demo](https://user-images.githubusercontent.com/2218736/33095722-a74f3d46-ced2-11e7-87d0-5fd366d71f92.png)

(I do not see where you previously mentioned success on the demo page or your own demos. Maybe I'm blind...)

**Comment by edemaine** [comment]
Ah, I saw that it didn't work when `katex.render`ing into a created element, but missed that it works when rendering into an existing element.  That definitely indicates that the fonts and CSS are loading correctly.  Weird indeed...

Can you check that `document.compatMode` is `"CSS1Compat"`, to make sure it's not a quirks-mode issue?

**Comment by Reikim** [comment]
Appears to be. Here's a [fiddle](https://jsfiddle.net/yhvzwLtL/) demonstrating.

**Comment by Reikim** [comment]
One thing I did notice was that, just staring at the generated markup, I can't see any way of distinguishing whether the 2 is a subscript or superscript...and that, when rendering into an existing element, there's some inline style positioning that gets added. Maybe that's the issue?

**Comment by edemaine** [comment]
Thanks for the example!  That is pretty crazy.

I notice now (comparing to the KaTeX demo page) that the `style` attributes are missing on the `span` children of the `<span class="vlist">`.  That's where the vertical positioning happens which in particular distinguishes the subscripts from superscripts.  (Apologies for not realizing this in your original markup.)

Presumably Angular is filtering this out for some reason.  You might check out https://github.com/garciparedes/ng-katex (recently linked to from the README) for using KaTeX within Angular.

**Comment by Reikim** [comment]
Ah, damn, you're right. I didn't think to check the markup before it get run through binding...logging confirms that the styles are present when it gets spit out of renderToString.

Thanks for your patience!

**Comment by edemaine** [comment]
Glad you found a solution!
