### ISSUE TITLE
Unicode rendering inside math environment 

### ISSUE THREAD

**Issue by rah4927** [Khan/KaTeX#979]
The KaTeX library is currently being employed in expii.com and our Bangla users are having trouble using Bangla text inside the math environment. Consider the following code:

(text : $ ঢাল=  \dfrac{\text{অক্ষে}}{\text{শরণ}}$)

If I compile it correctly using XeTeX compiler, this is what the output looks.

![kat1](https://user-images.githubusercontent.com/29117205/33127857-76bf5890-cfb4-11e7-899f-e8cb1f10b9c9.JPG)

Compiling using KaTeX fragments the conjunct letters.

![kat2](https://user-images.githubusercontent.com/29117205/33127909-a5e9fcb0-cfb4-11e7-8def-b205db7f1638.JPG)

**Comment by 07pepa** [comment]
i know that problem is same like here https://github.com/Khan/KaTeX/issues/895

**Comment by edemaine** [comment]
I'm confused how you're getting that to render that at all: I don't think KaTeX supports Bangla characters at all.  When I try `\text{ঢাল}= \dfrac{\text{অক্ষে}}{\text{শরণ}}`, I get `KaTeX parse error: Expected '}', got 'ঢ' at position 7: \text{ঢ̲াল}= \dfrac{\te…`.  Are you getting any messages in console?

The difficulty with supporting Bangla is that we'd need a font with character metrics.  I believe the consensus is that we'd like to do so, but that it should be an extension of some sort.  See #729 (about Persian).

KaTeX supports mostly CJK (and soon, LaTeX-related symbols) right now, because CJK character metrics are all the same so that's relatively easy to do.

**Comment by kevinbarabash** [comment]
@rah4927 did you modify the KaTeX code in anyway?

**Comment by rah4927** [comment]
@kevinbarabash @edemaine sorry for the late response. No I didn't modify the code in any way. I just typed it on the text editor in expii.com and this was the result.

**Comment by edemaine** [comment]
@rah4927 Perhaps expii.com modifies KaTeX, or uses MathJax as a fallback (like KA)? Is there a place where we can try this?  And/or, could you post the raw HTML output (by copy/pasting from an Developer/Inspect view) instead of a screenshot?

**Comment by rah4927** [comment]
@edemaine https://www.expii.com/t/lines-and-slopes-400
Here's a link. If you got to the bottom of the page and change the language to Bangla (it's the second one from the top, right under **English**), you'll find an article that's written in Bangla. Just underneath the picture, you should be able to see some unicode errors inside latex (in the numerator and denominator of a fraction). You can try clicking edit to try it out yourself.(though I'm not sure if you need to sign up).

**Comment by edemaine** [comment]
@rah4927 Thanks for the link. If you inspect the resulting elements, you can confirm that the Bangla rendering is via MathJax. The English version is rendered via KaTeX. Do you know why?

**Comment by davidflanagan** [comment]
Pull request #1060 just landed and adds support for Devangari, Bengali and various other indic scripts, but only in \text{}.

It won't fix the MathJax issue that @rah4927 is having, but KaTeX should now be able to render:

```
\text{ঢাল}= \dfrac{\text{অক্ষে}}{\text{শরণ}}
```

**Comment by davidflanagan** [comment]
<img width="452" alt="screen shot 2018-01-12 at 4 25 37 pm" src="https://user-images.githubusercontent.com/516914/34900479-419cea78-f7b5-11e7-9e81-eed6a3fa2989.png">

**Comment by davidflanagan** [comment]
Note that I had to add \text{} around the left hand side of the equation. We still don't support @rah4927's original source text. But hopefully this is close enough. So I'm going to close the issue.

**Comment by edemaine** [comment]
#1046 captures the "should `\text` be required" aspect of this issue.  Feel free to add discussion there!
