### ISSUE TITLE
Make contrib/auto-render importable

### ISSUE THREAD

**Issue by HarrisonB** [Khan/KaTeX#983]
It appears Webpack >= 2.2.0 [does not support](https://github.com/webpack/webpack/issues/4039) `import` mixed with `module.exports = ...` syntax. Perhaps I have misread that thread or am mistaken? I'm unable to figure out a way to import `renderMathInElement` without getting `TypeError: "exports" is read-only`.

**Comment by edemaine** [comment]
I'm not an expert on this topic, but think this is related to #954. You should be able to `import 'katex'` which should already be translated to vanilla JS; it's just the submodules that aren't importable right now.

**Comment by rrandallcainc** [comment]
Are you able to import Katex?

You should be able to solve this by changing the import to a require. Note: this only needs to be done for the entry point (not anything downstream).

**Comment by HarrisonB** [comment]
Gotcha. I was incorrect to assume that `katex/contrib/auto-render` was `import`/`require`-able. Thanks for clarifying @edemaine.

I am able to `import 'katex'` just fine, @rrandallcainc. Thank you for asking :)

I'm a bit of a JS package novice, but it doesn't that `katex/contrib/auto-render` is too far from being importable (though I imagine maintaining compatibility as a constraint complicates this). I'm going to change the title to reflect this, but I should point out that changing the `import` into a `require` in `contrib/auto-render/auto-render.js` will still be necessary for Webpack >= 2.2.0 compatibility.

Thank you both for your work on this terrific package. Happy holidays 🎁 ✨

**Comment by schober-ch** [comment]
I'm facing the same issue - I'm trying to include katex with auto-render into a project using webpack(2) to bundle all files.

Unfortunately I'm no webpack-guru and can't see how #1068 might help to solve this. I tried to add ` katex_auto_js: './node_modules/katex/contrib/auto-render/auto-render.js',` to my entry-block, but this will result in the same error (`Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`)

The `webpack.common.js` creates separate webpack configs for each target (I guess for publishing/bundling of katex itself), but that's different from using katex via webpack in a project - at least I think. 

Any ideas how to solve this? Or are we doing it the wrong way? Currently the only working solution I see is to include at least the auto-render via a <script>-tag

**Comment by ylemkimon** [comment]
@schober-ch 
(i) The version including PR #1068 has not been released yet, so you have to manually build the source.
(ii) As of #1068, `auto-render` uses only ES6 import/export syntax, so https://github.com/webpack/webpack/issues/4039 will be no longer an issue.
(iii) It's preferable to use `dist` files(built distribution files), i.e., `dist/contrib/auto-render.js`, and it's in UMD(universal module definition).
