### ISSUE TITLE
Aligned environment for split equations

### ISSUE THREAD

**Issue by hagenw** [Khan/KaTeX#985]
As KaTeX has no split environment I tried to achieve the same by using the aligned environment.
I tried the following:
```latex
\begin{alinged}
a &= b + c \\
  &= e + f
\end{aligned}
```
This approach works under LaTeX, but not under KaTeX. For KaTeX I have to add `\\` at the end of the last line as well, otherwise the line is missing in the HTML document (see picture below):
```latex
\begin{alinged}
a &= b + c \\
  &= e + f \\
\end{aligned}
```
![aligned](https://user-images.githubusercontent.com/173624/33214500-805e5364-d12c-11e7-8720-7db29bb2b5ef.png)

Code to produce the picture: https://gist.github.com/hagenw/1260f21203b4095a061ac3da6b01b5e4

**Comment by ronkok** [comment]
@hagenw, PR #949 written to fix a problem with parsing a empty cell at the beginning of the last line in an array. I expect a release this weekend that will include PR #949. Could you try again after that release an tell me if your problem recurs?

**Comment by edemaine** [comment]
0.9.0-alpha2 is out now! Please give a try.

**Comment by kevinbarabash** [comment]
I've also updated the demo to 0.9.0-alpha2 and have verified that it works there.
<img width="894" alt="screen shot 2017-11-26 at 7 58 12 pm" src="https://user-images.githubusercontent.com/1044413/33246573-2a930a24-d2e4-11e7-93ce-9de83c0b2d9d.png">
