### ISSUE TITLE
Consider using Array<T> instead of T[]

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#987]
Reasons why we might want to migrate to using `Array<T>` to specify types of arrays.

**pros**:
- less ambiguous... does `?T[]` mean `Array<T?>` or `?Array<T>`?
- harder to get wrong: flow often accepts `[T]` when really `T[]` is what was meant

**cons**:
- longer to type, may require more wrapping

**Comment by marcianx** [comment]
I've kinda kinda gotten used to `?` binding weakly so that I expect `?string[]` and `(?string)[]` to be different, but YMMV. I've, of course, been spending a lot of time in flow, so this is entirely subjective. Up to you.

**Comment by kevinbarabash** [comment]
I'm okay with either.  If no one feels strongly either way we can keep going with `T[]`.
