### ISSUE TITLE
\vec is not visible in WebKitGTK+

### ISSUE THREAD

**Issue by Jenyay** [Khan/KaTeX#996]
Hello.
I use katex to embed equations using the WebKit engine (WebKitGTK+) under Linux. In this engine, vectors created with \vec are not displayed. \overrightarrow works fine. 

It seems to me that the problem resembles a fixed problem with \fraq (prior to version 0.9-alpha2, there was also a problem with \fraq).

KaTeX version is 0.9-alpha2

**Comment by ronkok** [comment]
@Jenyay , We have an outstanding issue with `\vec` (Issue #735). In that issue, the arrow is placed too far to the right, and we haven't yet found a good way to correct that.

Could your issue possibly be the same as #735?

**Comment by Jenyay** [comment]
No, the arrow is not displayed at all.

**Comment by kevinbarabash** [comment]
@Jenyay `\vec{a}` in https://khan.github.io/KaTeX/ (which is using 0.9.0-alpha2) renders the vector arrow in Chrome version 62.0.3202.94.  Can you provide a link to a page that reproduces the issue?

**Comment by Jenyay** [comment]
@kevinbarabash The page created by the program looks fine in Chrome and Firefox, but in embedded WebKit there is such a problem.

**Comment by kevinbarabash** [comment]
@Jenyay are you loading https://khan.github.io/KaTeX/ in embedded WebKit?  If not try that or verify that the doctype on the page you are loading is correct.

**Comment by edemaine** [comment]
@Jenyay Also, could you upload an actual screenshot?  It's possible that this is still a consequence of #735 if the right shift ends up pushing it outside the rendered rectangle... maybe try `\vec{a}\vec{a}\vec{a}\vec{a}`.

**Comment by Jenyay** [comment]
@kevinbarabash Yes, I load KaTeX in embedded WebKit. I use wxPython 3.0.2 which uses WebKitGTK+ inside.

Here HTML code 
![html](https://user-images.githubusercontent.com/166281/33305939-45dc9064-d421-11e7-8153-1390311741a5.png)

**Comment by Jenyay** [comment]
@edemaine
![vectors](https://user-images.githubusercontent.com/166281/33305977-6fb42ed8-d421-11e7-94c6-c556457174a3.png)

**Comment by ronkok** [comment]
@Jenyay, have you tried `\vec` with the latest release 0.9.0-beta?

**Comment by Jenyay** [comment]
With 0.9.0 beta \vec works fine. Thanks :+1: 

![2018-01-19 09-41-49](https://user-images.githubusercontent.com/166281/35137942-0653d952-fcfd-11e7-8410-2627f1d43776.png)

**Comment by kevinbarabash** [comment]
@Jenyay you mentioned in the original post that there was also an issue with `\frac`.  Is there still an issue with `\frac` in the new version?

**Comment by Jenyay** [comment]
I mentioned that the problem with \frac was observed before version 0.9.0-alpha2. In version 0.9.0-alpha2 \frac already worked well.
